"""Named staging test accounts loaded only from local environment values."""
from staging_env import required

ADMIN_EMAIL = required("PDC_STAGING_ADMIN_EMAIL")
ADMIN_PW = required("PDC_STAGING_ADMIN_PASSWORD")
ADMIN_PASSWORD = ADMIN_PW
ADMIN2_EMAIL = required("PDC_STAGING_ADMIN2_EMAIL")
ADMIN2_PW = required("PDC_STAGING_ADMIN2_PASSWORD")
ADMIN2_PASSWORD = ADMIN2_PW
CTRL_A_EMAIL = required("PDC_STAGING_CONTROLLER_A_EMAIL")
CTRL_A_PW = required("PDC_STAGING_CONTROLLER_A_PASSWORD")
CTRL_B_EMAIL = required("PDC_STAGING_CONTROLLER_B_EMAIL")
CTRL_B_PW = required("PDC_STAGING_CONTROLLER_B_PASSWORD")
VIEWER_EMAIL = required("PDC_STAGING_VIEWER_EMAIL")
VIEWER_PW = required("PDC_STAGING_VIEWER_PASSWORD")
UNAPPROVED_EMAIL = required("PDC_STAGING_UNAPPROVED_EMAIL")
UNAPPROVED_PW = required("PDC_STAGING_UNAPPROVED_PASSWORD")
