// Test-only sample data: 75 vehicles spread across Control Board, PMB stages, Parts statuses, RFT and Completed.
window.VEHICLE_TRACKING_DATA = {
  "vehicles": [
    {
      "source": "Test 75 vehicle dataset",
      "consultant": "BG",
      "stock": "TEST001",
      "batch": "BATCH0001",
      "order": "ORD00001",
      "salesOrder": "SO00001",
      "pdcJobcard": "JC00001",
      "client": "Northwest Plumbing",
      "contact": "0400 000 001",
      "vehicle": "LandCruiser 79",
      "vin": "TESTVIN00000000001",
      "rego": "T00001",
      "prodMth": "Jul 2026",
      "productionMonth": "Jul 2026",
      "navisionKewdaleEta": "26/06/2026",
      "etaAtDealer": "26/06/2026",
      "jitaPartsOrdered": "No",
      "notes": "Test vehicle 1: overseas / production transit with varied work status",
      "navisionDealerComments": "Test dataset row 1 for overseas / production transit",
      "pmbKeyNumber": "K001",
      "toyotaStatus": "Planned for Production",
      "navisionSubLocationDescription": "Planned for Production",
      "pdcRequiresTint": true,
      "pdcRequiresHoist": true,
      "pdcRequiresParts": true,
      "pdcPartsOrdered": true,
      "pdcPartsOrderedAt": "2026-07-07T08:15:00Z",
      "pdcPartsOrderedBy": "Test Parts"
    },
    {
      "source": "Test 75 vehicle dataset",
      "consultant": "AM",
      "stock": "TEST002",
      "batch": "BATCH0002",
      "order": "ORD00002",
      "salesOrder": "SO00002",
      "pdcJobcard": "JC00002",
      "client": "Pilbara Electrical",
      "contact": "0400 000 002",
      "vehicle": "Prado VX",
      "vin": "TESTVIN00000000002",
      "rego": "T00002",
      "prodMth": "Jul 2026",
      "productionMonth": "Jul 2026",
      "navisionKewdaleEta": "27/06/2026",
      "etaAtDealer": "27/06/2026",
      "jitaPartsOrdered": "No",
      "notes": "Test vehicle 2: overseas / production transit with varied work status",
      "navisionDealerComments": "Test dataset row 2 for overseas / production transit",
      "pmbKeyNumber": "K002",
      "toyotaStatus": "Batch Matched",
      "navisionSubLocationDescription": "Batch Matched",
      "pdcRequiresTint": true,
      "pdcRequiresHoist": true,
      "pdcRequiresFitting": true,
      "pdcPartsStoppage": true,
      "pdcPartsStoppageReason": "Supplier ETA pending"
    },
    {
      "source": "Test 75 vehicle dataset",
      "consultant": "JT",
      "stock": "TEST003",
      "batch": "BATCH0003",
      "order": "ORD00003",
      "salesOrder": "SO00003",
      "pdcJobcard": "JC00003",
      "client": "Kewdale Civil",
      "contact": "0400 000 003",
      "vehicle": "HiAce LWB",
      "vin": "TESTVIN00000000003",
      "rego": "T00003",
      "prodMth": "Jul 2026",
      "productionMonth": "Jul 2026",
      "navisionKewdaleEta": "28/06/2026",
      "etaAtDealer": "28/06/2026",
      "jitaPartsOrdered": "Yes",
      "notes": "Test vehicle 3: overseas / production transit with varied work status",
      "navisionDealerComments": "Test dataset row 3 for overseas / production transit",
      "pmbKeyNumber": "K003",
      "toyotaStatus": "Planned for Production",
      "navisionSubLocationDescription": "Planned for Production",
      "pdcRequiresTint": true,
      "pdcRequiresHoist": true,
      "pdcRequiresFitting": true,
      "pdcRequiresFabrication": true,
      "pdcRequiresParts": true
    },
    {
      "source": "Test 75 vehicle dataset",
      "consultant": "LS",
      "stock": "TEST004",
      "batch": "BATCH0004",
      "order": "ORD00004",
      "salesOrder": "SO00004",
      "pdcJobcard": "JC00004",
      "client": "Watson Transport",
      "contact": "0400 000 004",
      "vehicle": "Corolla Cross",
      "vin": "TESTVIN00000000004",
      "rego": "T00004",
      "prodMth": "Jul 2026",
      "productionMonth": "Jul 2026",
      "navisionKewdaleEta": "29/06/2026",
      "etaAtDealer": "29/06/2026",
      "jitaPartsOrdered": "No",
      "notes": "Test vehicle 4: overseas / production transit with varied work status",
      "navisionDealerComments": "Test dataset row 4 for overseas / production transit",
      "pmbKeyNumber": "K004",
      "toyotaStatus": "Batch Matched",
      "navisionSubLocationDescription": "Batch Matched",
      "pdcRequiresTint": true,
      "pdcCompleteParts": true,
      "pdcPartsReceived": true
    },
    {
      "source": "Test 75 vehicle dataset",
      "consultant": "RD",
      "stock": "TEST005",
      "batch": "BATCH0005",
      "order": "ORD00005",
      "salesOrder": "SO00005",
      "pdcJobcard": "JC00005",
      "client": "Coastal Hire",
      "contact": "0400 000 005",
      "vehicle": "RAV4 Cruiser",
      "vin": "TESTVIN00000000005",
      "rego": "T00005",
      "prodMth": "Jul 2026",
      "productionMonth": "Jul 2026",
      "navisionKewdaleEta": "30/06/2026",
      "etaAtDealer": "30/06/2026",
      "jitaPartsOrdered": "No",
      "notes": "Test vehicle 5: overseas / production transit with varied work status",
      "navisionDealerComments": "Test dataset row 5 for overseas / production transit",
      "pmbKeyNumber": "K005",
      "toyotaStatus": "Planned for Production",
      "navisionSubLocationDescription": "Planned for Production",
      "pdcRequiresTint": true,
      "pdcRequiresHoist": true,
      "pdcRequiresParts": true,
      "pdcPartsOrdered": true,
      "pdcPartsOrderedAt": "2026-07-03T08:15:00Z",
      "pdcPartsOrderedBy": "Test Parts"
    },
    {
      "source": "Test 75 vehicle dataset",
      "consultant": "CW",
      "stock": "TEST006",
      "batch": "BATCH0006",
      "order": "ORD00006",
      "salesOrder": "SO00006",
      "pdcJobcard": "JC00006",
      "client": "Red Dirt Contracting",
      "contact": "0400 000 006",
      "vehicle": "Fortuner GXL",
      "vin": "TESTVIN00000000006",
      "rego": "T00006",
      "prodMth": "Jul 2026",
      "productionMonth": "Jul 2026",
      "navisionKewdaleEta": "01/07/2026",
      "etaAtDealer": "01/07/2026",
      "jitaPartsOrdered": "Yes",
      "notes": "Test vehicle 6: overseas / production transit with varied work status",
      "navisionDealerComments": "Test dataset row 6 for overseas / production transit",
      "pmbKeyNumber": "K006",
      "toyotaStatus": "Batch Matched",
      "navisionSubLocationDescription": "Batch Matched",
      "pdcRequiresTint": true,
      "pdcRequiresHoist": true,
      "pdcRequiresFitting": true,
      "pdcPartsStoppage": true,
      "pdcPartsStoppageReason": "Supplier ETA pending"
    },
    {
      "source": "Test 75 vehicle dataset",
      "consultant": "BG",
      "stock": "TEST007",
      "batch": "BATCH0007",
      "order": "ORD00007",
      "salesOrder": "SO00007",
      "pdcJobcard": "JC00007",
      "client": "Metro Maintenance",
      "contact": "0400 000 007",
      "vehicle": "Camry Hybrid",
      "vin": "TESTVIN00000000007",
      "rego": "T00007",
      "prodMth": "Jul 2026",
      "productionMonth": "Jul 2026",
      "navisionKewdaleEta": "02/07/2026",
      "etaAtDealer": "02/07/2026",
      "jitaPartsOrdered": "No",
      "notes": "Test vehicle 7: overseas / production transit with varied work status",
      "navisionDealerComments": "Test dataset row 7 for overseas / production transit",
      "pmbKeyNumber": "K007",
      "toyotaStatus": "Planned for Production",
      "navisionSubLocationDescription": "Planned for Production",
      "pdcRequiresTint": true,
      "pdcRequiresHoist": true,
      "pdcRequiresFitting": true,
      "pdcRequiresFabrication": true,
      "pdcRequiresParts": true
    },
    {
      "source": "Test 75 vehicle dataset",
      "consultant": "AM",
      "stock": "TEST008",
      "batch": "BATCH0008",
      "order": "ORD00008",
      "salesOrder": "SO00008",
      "pdcJobcard": "JC00008",
      "client": "Goldfields Mining",
      "contact": "0400 000 008",
      "vehicle": "Hilux SR5",
      "vin": "TESTVIN00000000008",
      "rego": "T00008",
      "prodMth": "Jul 2026",
      "productionMonth": "Jul 2026",
      "navisionKewdaleEta": "03/07/2026",
      "etaAtDealer": "03/07/2026",
      "jitaPartsOrdered": "No",
      "notes": "Test vehicle 8: overseas / production transit with varied work status",
      "navisionDealerComments": "Test dataset row 8 for overseas / production transit",
      "pmbKeyNumber": "K008",
      "toyotaStatus": "Batch Matched",
      "navisionSubLocationDescription": "Batch Matched",
      "pdcRequiresTint": true,
      "pdcCompleteParts": true,
      "pdcPartsReceived": true
    },
    {
      "source": "Test 75 vehicle dataset",
      "consultant": "JT",
      "stock": "TEST009",
      "batch": "BATCH0009",
      "order": "ORD00009",
      "salesOrder": "SO00009",
      "pdcJobcard": "JC00009",
      "client": "Perth Landscapes",
      "contact": "0400 000 009",
      "vehicle": "LandCruiser 300",
      "vin": "TESTVIN00000000009",
      "rego": "T00009",
      "prodMth": "Jul 2026",
      "productionMonth": "Jul 2026",
      "navisionKewdaleEta": "04/07/2026",
      "etaAtDealer": "04/07/2026",
      "jitaPartsOrdered": "Yes",
      "notes": "Test vehicle 9: overseas / production transit with varied work status",
      "navisionDealerComments": "Test dataset row 9 for overseas / production transit",
      "pmbKeyNumber": "K009",
      "toyotaStatus": "Planned for Production",
      "navisionSubLocationDescription": "Planned for Production",
      "pdcRequiresTint": true,
      "pdcRequiresHoist": true,
      "pdcRequiresParts": true,
      "pdcPartsOrdered": true,
      "pdcPartsOrderedAt": "2026-06-29T08:15:00Z",
      "pdcPartsOrderedBy": "Test Parts"
    },
    {
      "source": "Test 75 vehicle dataset",
      "consultant": "LS",
      "stock": "TEST010",
      "batch": "BATCH0010",
      "order": "ORD00010",
      "salesOrder": "SO00010",
      "pdcJobcard": "JC00010",
      "client": "Swan Valley Electrical",
      "contact": "0400 000 010",
      "vehicle": "Yaris Cross",
      "vin": "TESTVIN00000000010",
      "rego": "T00010",
      "prodMth": "Jul 2026",
      "productionMonth": "Jul 2026",
      "navisionKewdaleEta": "05/07/2026",
      "etaAtDealer": "05/07/2026",
      "jitaPartsOrdered": "No",
      "notes": "Test vehicle 10: overseas / production transit with varied work status",
      "navisionDealerComments": "Test dataset row 10 for overseas / production transit",
      "pmbKeyNumber": "K010",
      "toyotaStatus": "Batch Matched",
      "navisionSubLocationDescription": "Batch Matched",
      "pdcRequiresTint": true,
      "pdcRequiresHoist": true,
      "pdcRequiresFitting": true,
      "pdcPartsStoppage": true,
      "pdcPartsStoppageReason": "Supplier ETA pending"
    },
    {
      "source": "Test 75 vehicle dataset",
      "consultant": "RD",
      "stock": "TEST011",
      "batch": "BATCH0011",
      "order": "ORD00011",
      "salesOrder": "SO00011",
      "pdcJobcard": "JC00011",
      "client": "Outback Energy",
      "contact": "0400 000 011",
      "vehicle": "HiLux Rogue",
      "vin": "TESTVIN00000000011",
      "rego": "T00011",
      "prodMth": "Jul 2026",
      "productionMonth": "Jul 2026",
      "navisionKewdaleEta": "06/07/2026",
      "etaAtDealer": "06/07/2026",
      "jitaPartsOrdered": "No",
      "notes": "Test vehicle 11: in transit with varied work status",
      "navisionDealerComments": "Test dataset row 11 for in transit",
      "pmbKeyNumber": "K011",
      "toyotaStatus": "In Transit to WA",
      "navisionSubLocationDescription": "In Transit to WA",
      "pdcRequiresFitting": true,
      "pdcRequiresElectrical": false,
      "pdcRequiresParts": true
    },
    {
      "source": "Test 75 vehicle dataset",
      "consultant": "CW",
      "stock": "TEST012",
      "batch": "BATCH0012",
      "order": "ORD00012",
      "salesOrder": "SO00012",
      "pdcJobcard": "JC00012",
      "client": "Fremantle Council",
      "contact": "0400 000 012",
      "vehicle": "Coaster Bus",
      "vin": "TESTVIN00000000012",
      "rego": "T00012",
      "prodMth": "Jul 2026",
      "productionMonth": "Jul 2026",
      "navisionKewdaleEta": "07/07/2026",
      "etaAtDealer": "07/07/2026",
      "jitaPartsOrdered": "Yes",
      "notes": "Test vehicle 12: in transit with varied work status",
      "navisionDealerComments": "Test dataset row 12 for in transit",
      "pmbKeyNumber": "K012",
      "toyotaStatus": "In Transit to WA",
      "navisionSubLocationDescription": "In Transit to WA",
      "pdcRequiresFitting": true,
      "pdcRequiresElectrical": true,
      "pdcRequiresParts": false
    },
    {
      "source": "Test 75 vehicle dataset",
      "consultant": "BG",
      "stock": "TEST013",
      "batch": "BATCH0013",
      "order": "ORD00013",
      "salesOrder": "SO00013",
      "pdcJobcard": "JC00013",
      "client": "Western Rescue",
      "contact": "0400 000 013",
      "vehicle": "LandCruiser 79",
      "vin": "TESTVIN00000000013",
      "rego": "T00013",
      "prodMth": "Jul 2026",
      "productionMonth": "Jul 2026",
      "navisionKewdaleEta": "08/07/2026",
      "etaAtDealer": "08/07/2026",
      "jitaPartsOrdered": "No",
      "notes": "Test vehicle 13: in transit with varied work status",
      "navisionDealerComments": "Test dataset row 13 for in transit",
      "pmbKeyNumber": "K013",
      "toyotaStatus": "In Transit to WA",
      "navisionSubLocationDescription": "In Transit to WA",
      "pdcRequiresFitting": true,
      "pdcRequiresElectrical": false,
      "pdcRequiresParts": true,
      "pdcPartsOrdered": true,
      "pdcPartsOrderedAt": "2026-06-25T08:15:00Z"
    },
    {
      "source": "Test 75 vehicle dataset",
      "consultant": "AM",
      "stock": "TEST014",
      "batch": "BATCH0014",
      "order": "ORD00014",
      "salesOrder": "SO00014",
      "pdcJobcard": "JC00014",
      "client": "Horizon Builders",
      "contact": "0400 000 014",
      "vehicle": "Prado VX",
      "vin": "TESTVIN00000000014",
      "rego": "T00014",
      "prodMth": "Jul 2026",
      "productionMonth": "Jul 2026",
      "navisionKewdaleEta": "09/07/2026",
      "etaAtDealer": "09/07/2026",
      "jitaPartsOrdered": "No",
      "notes": "Test vehicle 14: in transit with varied work status",
      "navisionDealerComments": "Test dataset row 14 for in transit",
      "pmbKeyNumber": "K014",
      "toyotaStatus": "In Transit to WA",
      "navisionSubLocationDescription": "In Transit to WA",
      "pdcRequiresFitting": true,
      "pdcRequiresElectrical": true,
      "pdcRequiresParts": true
    },
    {
      "source": "Test 75 vehicle dataset",
      "consultant": "JT",
      "stock": "TEST015",
      "batch": "BATCH0015",
      "order": "ORD00015",
      "salesOrder": "SO00015",
      "pdcJobcard": "JC00015",
      "client": "Kimberley Tours",
      "contact": "0400 000 015",
      "vehicle": "HiAce LWB",
      "vin": "TESTVIN00000000015",
      "rego": "T00015",
      "prodMth": "Jul 2026",
      "productionMonth": "Jul 2026",
      "navisionKewdaleEta": "10/07/2026",
      "etaAtDealer": "10/07/2026",
      "jitaPartsOrdered": "Yes",
      "notes": "Test vehicle 15: in transit with varied work status",
      "navisionDealerComments": "Test dataset row 15 for in transit",
      "pmbKeyNumber": "K015",
      "toyotaStatus": "In Transit to WA",
      "navisionSubLocationDescription": "In Transit to WA",
      "pdcRequiresFitting": true,
      "pdcRequiresElectrical": false,
      "pdcRequiresParts": false,
      "pdcPartsStoppage": true,
      "pdcPartsStoppageReason": "Parts shipment delayed"
    },
    {
      "source": "Test 75 vehicle dataset",
      "consultant": "LS",
      "stock": "TEST016",
      "batch": "BATCH0016",
      "order": "ORD00016",
      "salesOrder": "SO00016",
      "pdcJobcard": "JC00016",
      "client": "Northwest Plumbing",
      "contact": "0400 000 016",
      "vehicle": "Corolla Cross",
      "vin": "TESTVIN00000000016",
      "rego": "T00016",
      "prodMth": "Jul 2026",
      "productionMonth": "Jul 2026",
      "navisionKewdaleEta": "11/07/2026",
      "etaAtDealer": "11/07/2026",
      "jitaPartsOrdered": "No",
      "notes": "Test vehicle 16: in transit with varied work status",
      "navisionDealerComments": "Test dataset row 16 for in transit",
      "pmbKeyNumber": "K016",
      "toyotaStatus": "In Transit to WA",
      "navisionSubLocationDescription": "In Transit to WA",
      "pdcRequiresFitting": true,
      "pdcRequiresElectrical": true,
      "pdcRequiresParts": true,
      "pdcPartsOrdered": true,
      "pdcPartsOrderedAt": "2026-06-22T08:15:00Z"
    },
    {
      "source": "Test 75 vehicle dataset",
      "consultant": "RD",
      "stock": "TEST017",
      "batch": "BATCH0017",
      "order": "ORD00017",
      "salesOrder": "SO00017",
      "pdcJobcard": "JC00017",
      "client": "Pilbara Electrical",
      "contact": "0400 000 017",
      "vehicle": "RAV4 Cruiser",
      "vin": "TESTVIN00000000017",
      "rego": "T00017",
      "prodMth": "Jul 2026",
      "productionMonth": "Jul 2026",
      "navisionKewdaleEta": "12/07/2026",
      "etaAtDealer": "12/07/2026",
      "jitaPartsOrdered": "No",
      "notes": "Test vehicle 17: in transit with varied work status",
      "navisionDealerComments": "Test dataset row 17 for in transit",
      "pmbKeyNumber": "K017",
      "toyotaStatus": "In Transit to WA",
      "navisionSubLocationDescription": "In Transit to WA",
      "pdcRequiresFitting": true,
      "pdcRequiresElectrical": false,
      "pdcRequiresParts": true
    },
    {
      "source": "Test 75 vehicle dataset",
      "consultant": "CW",
      "stock": "TEST018",
      "batch": "BATCH0018",
      "order": "ORD00018",
      "salesOrder": "SO00018",
      "pdcJobcard": "JC00018",
      "client": "Kewdale Civil",
      "contact": "0400 000 018",
      "vehicle": "Fortuner GXL",
      "vin": "TESTVIN00000000018",
      "rego": "T00018",
      "prodMth": "Jul 2026",
      "productionMonth": "Jul 2026",
      "navisionKewdaleEta": "13/07/2026",
      "etaAtDealer": "13/07/2026",
      "jitaPartsOrdered": "Yes",
      "notes": "Test vehicle 18: in transit with varied work status",
      "navisionDealerComments": "Test dataset row 18 for in transit",
      "pmbKeyNumber": "K018",
      "toyotaStatus": "In Transit to WA",
      "navisionSubLocationDescription": "In Transit to WA",
      "pdcRequiresFitting": true,
      "pdcRequiresElectrical": true,
      "pdcRequiresParts": false
    },
    {
      "source": "Test 75 vehicle dataset",
      "consultant": "BG",
      "stock": "TEST019",
      "batch": "BATCH0019",
      "order": "ORD00019",
      "salesOrder": "SO00019",
      "pdcJobcard": "JC00019",
      "client": "Watson Transport",
      "contact": "0400 000 019",
      "vehicle": "Camry Hybrid",
      "vin": "TESTVIN00000000019",
      "rego": "T00019",
      "prodMth": "Jul 2026",
      "productionMonth": "Jul 2026",
      "navisionKewdaleEta": "14/07/2026",
      "etaAtDealer": "14/07/2026",
      "jitaPartsOrdered": "No",
      "notes": "Test vehicle 19: in transit with varied work status",
      "navisionDealerComments": "Test dataset row 19 for in transit",
      "pmbKeyNumber": "K019",
      "toyotaStatus": "In Transit to WA",
      "navisionSubLocationDescription": "In Transit to WA",
      "pdcRequiresFitting": true,
      "pdcRequiresElectrical": false,
      "pdcRequiresParts": true,
      "pdcPartsOrdered": true,
      "pdcPartsOrderedAt": "2026-06-19T08:15:00Z"
    },
    {
      "source": "Test 75 vehicle dataset",
      "consultant": "AM",
      "stock": "TEST020",
      "batch": "BATCH0020",
      "order": "ORD00020",
      "salesOrder": "SO00020",
      "pdcJobcard": "JC00020",
      "client": "Coastal Hire",
      "contact": "0400 000 020",
      "vehicle": "Hilux SR5",
      "vin": "TESTVIN00000000020",
      "rego": "T00020",
      "prodMth": "Jul 2026",
      "productionMonth": "Jul 2026",
      "navisionKewdaleEta": "15/07/2026",
      "etaAtDealer": "15/07/2026",
      "jitaPartsOrdered": "No",
      "notes": "Test vehicle 20: in transit with varied work status",
      "navisionDealerComments": "Test dataset row 20 for in transit",
      "pmbKeyNumber": "K020",
      "toyotaStatus": "In Transit to WA",
      "navisionSubLocationDescription": "In Transit to WA",
      "pdcRequiresFitting": true,
      "pdcRequiresElectrical": true,
      "pdcRequiresParts": true,
      "pdcPartsStoppage": true,
      "pdcPartsStoppageReason": "Parts shipment delayed"
    },
    {
      "source": "Test 75 vehicle dataset",
      "consultant": "JT",
      "stock": "TEST021",
      "batch": "BATCH0021",
      "order": "ORD00021",
      "salesOrder": "SO00021",
      "pdcJobcard": "JC00021",
      "client": "Red Dirt Contracting",
      "contact": "0400 000 021",
      "vehicle": "LandCruiser 300",
      "vin": "TESTVIN00000000021",
      "rego": "T00021",
      "prodMth": "Jul 2026",
      "productionMonth": "Jul 2026",
      "navisionKewdaleEta": "16/07/2026",
      "etaAtDealer": "16/07/2026",
      "jitaPartsOrdered": "Yes",
      "notes": "Test vehicle 21: yard hold with varied work status",
      "navisionDealerComments": "Test dataset row 21 for yard hold",
      "pmbKeyNumber": "K021",
      "toyotaStatus": "Vehicle Yard Hold",
      "navisionSubLocationDescription": "Vehicle Yard Hold",
      "pdcLocation": "YH",
      "pdcLocationUpdatedAt": "2026-06-27T08:15:00Z",
      "pdcRequiresTint": false,
      "pdcRequiresHoist": true,
      "pdcRequiresFitting": true,
      "pdcRequiresFabrication": false,
      "pdcRequiresParts": true,
      "pdcPartsOrdered": true,
      "pdcPartsOrderedAt": "2026-06-17T08:15:00Z"
    },
    {
      "source": "Test 75 vehicle dataset",
      "consultant": "LS",
      "stock": "TEST022",
      "batch": "BATCH0022",
      "order": "ORD00022",
      "salesOrder": "SO00022",
      "pdcJobcard": "JC00022",
      "client": "Metro Maintenance",
      "contact": "0400 000 022",
      "vehicle": "Yaris Cross",
      "vin": "TESTVIN00000000022",
      "rego": "T00022",
      "prodMth": "Jul 2026",
      "productionMonth": "Jul 2026",
      "navisionKewdaleEta": "17/07/2026",
      "etaAtDealer": "17/07/2026",
      "jitaPartsOrdered": "No",
      "notes": "Test vehicle 22: yard hold with varied work status",
      "navisionDealerComments": "Test dataset row 22 for yard hold",
      "pmbKeyNumber": "K022",
      "toyotaStatus": "Vehicle Yard Hold",
      "navisionSubLocationDescription": "Vehicle Yard Hold",
      "pdcLocation": "YH",
      "pdcLocationUpdatedAt": "2026-06-26T08:15:00Z",
      "pdcRequiresTint": true,
      "pdcRequiresHoist": false,
      "pdcRequiresFitting": true,
      "pdcRequiresFabrication": false,
      "pdcRequiresParts": false
    },
    {
      "source": "Test 75 vehicle dataset",
      "consultant": "RD",
      "stock": "TEST023",
      "batch": "BATCH0023",
      "order": "ORD00023",
      "salesOrder": "SO00023",
      "pdcJobcard": "JC00023",
      "client": "Goldfields Mining",
      "contact": "0400 000 023",
      "vehicle": "HiLux Rogue",
      "vin": "TESTVIN00000000023",
      "rego": "T00023",
      "prodMth": "Jul 2026",
      "productionMonth": "Jul 2026",
      "navisionKewdaleEta": "18/07/2026",
      "etaAtDealer": "18/07/2026",
      "jitaPartsOrdered": "No",
      "notes": "Test vehicle 23: yard hold with varied work status",
      "navisionDealerComments": "Test dataset row 23 for yard hold",
      "pmbKeyNumber": "K023",
      "toyotaStatus": "Vehicle Yard Hold",
      "navisionSubLocationDescription": "Vehicle Yard Hold",
      "pdcLocation": "YH",
      "pdcLocationUpdatedAt": "2026-06-25T08:15:00Z",
      "pdcRequiresTint": false,
      "pdcRequiresHoist": false,
      "pdcRequiresFitting": true,
      "pdcRequiresFabrication": false,
      "pdcRequiresParts": true
    },
    {
      "source": "Test 75 vehicle dataset",
      "consultant": "CW",
      "stock": "TEST024",
      "batch": "BATCH0024",
      "order": "ORD00024",
      "salesOrder": "SO00024",
      "pdcJobcard": "JC00024",
      "client": "Perth Landscapes",
      "contact": "0400 000 024",
      "vehicle": "Coaster Bus",
      "vin": "TESTVIN00000000024",
      "rego": "T00024",
      "prodMth": "Jul 2026",
      "productionMonth": "Jul 2026",
      "navisionKewdaleEta": "19/07/2026",
      "etaAtDealer": "19/07/2026",
      "jitaPartsOrdered": "Yes",
      "notes": "Test vehicle 24: yard hold with varied work status",
      "navisionDealerComments": "Test dataset row 24 for yard hold",
      "pmbKeyNumber": "K024",
      "toyotaStatus": "Vehicle Yard Hold",
      "navisionSubLocationDescription": "Vehicle Yard Hold",
      "pdcLocation": "YH",
      "pdcLocationUpdatedAt": "2026-06-24T08:15:00Z",
      "pdcRequiresTint": true,
      "pdcRequiresHoist": true,
      "pdcRequiresFitting": true,
      "pdcRequiresFabrication": true,
      "pdcRequiresParts": false,
      "pdcPartsOrdered": true,
      "pdcPartsOrderedAt": "2026-06-14T08:15:00Z"
    },
    {
      "source": "Test 75 vehicle dataset",
      "consultant": "BG",
      "stock": "TEST025",
      "batch": "BATCH0025",
      "order": "ORD00025",
      "salesOrder": "SO00025",
      "pdcJobcard": "JC00025",
      "client": "Swan Valley Electrical",
      "contact": "0400 000 025",
      "vehicle": "LandCruiser 79",
      "vin": "TESTVIN00000000025",
      "rego": "T00025",
      "prodMth": "Jul 2026",
      "productionMonth": "Jul 2026",
      "navisionKewdaleEta": "20/07/2026",
      "etaAtDealer": "20/07/2026",
      "jitaPartsOrdered": "No",
      "notes": "Test vehicle 25: yard hold with varied work status",
      "navisionDealerComments": "Test dataset row 25 for yard hold",
      "pmbKeyNumber": "K025",
      "toyotaStatus": "Vehicle Yard Hold",
      "navisionSubLocationDescription": "Vehicle Yard Hold",
      "pdcLocation": "YH",
      "pdcLocationUpdatedAt": "2026-06-23T08:15:00Z",
      "pdcRequiresTint": false,
      "pdcRequiresHoist": false,
      "pdcRequiresFitting": true,
      "pdcRequiresFabrication": false,
      "pdcRequiresParts": true
    },
    {
      "source": "Test 75 vehicle dataset",
      "consultant": "AM",
      "stock": "TEST026",
      "batch": "BATCH0026",
      "order": "ORD00026",
      "salesOrder": "SO00026",
      "pdcJobcard": "JC00026",
      "client": "Outback Energy",
      "contact": "0400 000 026",
      "vehicle": "Prado VX",
      "vin": "TESTVIN00000000026",
      "rego": "T00026",
      "prodMth": "Jul 2026",
      "productionMonth": "Jul 2026",
      "navisionKewdaleEta": "25/06/2026",
      "etaAtDealer": "25/06/2026",
      "jitaPartsOrdered": "No",
      "notes": "Test vehicle 26: yard hold with varied work status",
      "navisionDealerComments": "Test dataset row 26 for yard hold",
      "pmbKeyNumber": "K026",
      "toyotaStatus": "Vehicle Yard Hold",
      "navisionSubLocationDescription": "Vehicle Yard Hold",
      "pdcLocation": "YH",
      "pdcLocationUpdatedAt": "2026-06-22T08:15:00Z",
      "pdcRequiresTint": true,
      "pdcRequiresHoist": false,
      "pdcRequiresFitting": true,
      "pdcRequiresFabrication": false,
      "pdcRequiresParts": false
    },
    {
      "source": "Test 75 vehicle dataset",
      "consultant": "JT",
      "stock": "TEST027",
      "batch": "BATCH0027",
      "order": "ORD00027",
      "salesOrder": "SO00027",
      "pdcJobcard": "JC00027",
      "client": "Fremantle Council",
      "contact": "0400 000 027",
      "vehicle": "HiAce LWB",
      "vin": "TESTVIN00000000027",
      "rego": "T00027",
      "prodMth": "Jul 2026",
      "productionMonth": "Jul 2026",
      "navisionKewdaleEta": "26/06/2026",
      "etaAtDealer": "26/06/2026",
      "jitaPartsOrdered": "Yes",
      "notes": "Test vehicle 27: yard hold with varied work status",
      "navisionDealerComments": "Test dataset row 27 for yard hold",
      "pmbKeyNumber": "K027",
      "toyotaStatus": "Vehicle Yard Hold",
      "navisionSubLocationDescription": "Vehicle Yard Hold",
      "pdcLocation": "YH",
      "pdcLocationUpdatedAt": "2026-06-21T08:15:00Z",
      "pdcRequiresTint": false,
      "pdcRequiresHoist": true,
      "pdcRequiresFitting": true,
      "pdcRequiresFabrication": false,
      "pdcRequiresParts": true,
      "pdcPartsOrdered": true,
      "pdcPartsOrderedAt": "2026-06-11T08:15:00Z"
    },
    {
      "source": "Test 75 vehicle dataset",
      "consultant": "LS",
      "stock": "TEST028",
      "batch": "BATCH0028",
      "order": "ORD00028",
      "salesOrder": "SO00028",
      "pdcJobcard": "JC00028",
      "client": "Western Rescue",
      "contact": "0400 000 028",
      "vehicle": "Corolla Cross",
      "vin": "TESTVIN00000000028",
      "rego": "T00028",
      "prodMth": "Jul 2026",
      "productionMonth": "Jul 2026",
      "navisionKewdaleEta": "27/06/2026",
      "etaAtDealer": "27/06/2026",
      "jitaPartsOrdered": "No",
      "notes": "Test vehicle 28: yard hold with varied work status",
      "navisionDealerComments": "Test dataset row 28 for yard hold",
      "pmbKeyNumber": "K028",
      "toyotaStatus": "Vehicle Yard Hold",
      "navisionSubLocationDescription": "Vehicle Yard Hold",
      "pdcLocation": "YH",
      "pdcLocationUpdatedAt": "2026-06-20T08:15:00Z",
      "pdcRequiresTint": true,
      "pdcRequiresHoist": false,
      "pdcRequiresFitting": true,
      "pdcRequiresFabrication": true,
      "pdcRequiresParts": false
    },
    {
      "source": "Test 75 vehicle dataset",
      "consultant": "RD",
      "stock": "TEST029",
      "batch": "BATCH0029",
      "order": "ORD00029",
      "salesOrder": "SO00029",
      "pdcJobcard": "JC00029",
      "client": "Horizon Builders",
      "contact": "0400 000 029",
      "vehicle": "RAV4 Cruiser",
      "vin": "TESTVIN00000000029",
      "rego": "T00029",
      "prodMth": "Jul 2026",
      "productionMonth": "Jul 2026",
      "navisionKewdaleEta": "28/06/2026",
      "etaAtDealer": "28/06/2026",
      "jitaPartsOrdered": "No",
      "notes": "Test vehicle 29: yard hold with varied work status",
      "navisionDealerComments": "Test dataset row 29 for yard hold",
      "pmbKeyNumber": "K029",
      "toyotaStatus": "Vehicle Yard Hold",
      "navisionSubLocationDescription": "Vehicle Yard Hold",
      "pdcLocation": "YH",
      "pdcLocationUpdatedAt": "2026-06-19T08:15:00Z",
      "pdcRequiresTint": false,
      "pdcRequiresHoist": false,
      "pdcRequiresFitting": true,
      "pdcRequiresFabrication": false,
      "pdcRequiresParts": true
    },
    {
      "source": "Test 75 vehicle dataset",
      "consultant": "CW",
      "stock": "TEST030",
      "batch": "BATCH0030",
      "order": "ORD00030",
      "salesOrder": "SO00030",
      "pdcJobcard": "JC00030",
      "client": "Kimberley Tours",
      "contact": "0400 000 030",
      "vehicle": "Fortuner GXL",
      "vin": "TESTVIN00000000030",
      "rego": "T00030",
      "prodMth": "Jul 2026",
      "productionMonth": "Jul 2026",
      "navisionKewdaleEta": "29/06/2026",
      "etaAtDealer": "29/06/2026",
      "jitaPartsOrdered": "Yes",
      "notes": "Test vehicle 30: yard hold with varied work status",
      "navisionDealerComments": "Test dataset row 30 for yard hold",
      "pmbKeyNumber": "K030",
      "toyotaStatus": "Vehicle Yard Hold",
      "navisionSubLocationDescription": "Vehicle Yard Hold",
      "pdcLocation": "YH",
      "pdcLocationUpdatedAt": "2026-06-18T08:15:00Z",
      "pdcRequiresTint": true,
      "pdcRequiresHoist": true,
      "pdcRequiresFitting": true,
      "pdcRequiresFabrication": false,
      "pdcRequiresParts": false,
      "pdcPartsOrdered": true,
      "pdcPartsOrderedAt": "2026-06-08T08:15:00Z"
    },
    {
      "source": "Test 75 vehicle dataset",
      "consultant": "BG",
      "stock": "TEST031",
      "batch": "BATCH0031",
      "order": "ORD00031",
      "salesOrder": "SO00031",
      "pdcJobcard": "JC00031",
      "client": "Northwest Plumbing",
      "contact": "0400 000 031",
      "vehicle": "Camry Hybrid",
      "vin": "TESTVIN00000000031",
      "rego": "T00031",
      "prodMth": "Jul 2026",
      "productionMonth": "Jul 2026",
      "navisionKewdaleEta": "30/06/2026",
      "etaAtDealer": "30/06/2026",
      "jitaPartsOrdered": "No",
      "notes": "Test vehicle 31: PMB workflow with varied work status",
      "navisionDealerComments": "Test dataset row 31 for PMB workflow",
      "pmbKeyNumber": "K031",
      "toyotaStatus": "Vehicle Yard Hold",
      "navisionSubLocationDescription": "Vehicle Yard Hold",
      "pdcLocation": "PMB",
      "pmbEnteredAt": "2026-07-01T08:15:00Z",
      "pdcLocationUpdatedAt": "2026-07-01T08:15:00Z",
      "pmbStage": "",
      "pmbStageUpdatedAt": "2026-07-04T09:15:00Z",
      "pdcRequiresPitInspection": true,
      "pdcRequiresParts": true,
      "pdcCompletePitInspection": true,
      "pdcCompletePitInspectionAt": "2026-07-03T14:15:00Z",
      "pdcCompletePitInspectionBy": "Test Tech"
    },
    {
      "source": "Test 75 vehicle dataset",
      "consultant": "AM",
      "stock": "TEST032",
      "batch": "BATCH0032",
      "order": "ORD00032",
      "salesOrder": "SO00032",
      "pdcJobcard": "JC00032",
      "client": "Pilbara Electrical",
      "contact": "0400 000 032",
      "vehicle": "Hilux SR5",
      "vin": "TESTVIN00000000032",
      "rego": "T00032",
      "prodMth": "Jul 2026",
      "productionMonth": "Jul 2026",
      "navisionKewdaleEta": "01/07/2026",
      "etaAtDealer": "01/07/2026",
      "jitaPartsOrdered": "No",
      "notes": "Test vehicle 32: PMB workflow with varied work status",
      "navisionDealerComments": "Test dataset row 32 for PMB workflow",
      "pmbKeyNumber": "K032",
      "toyotaStatus": "Vehicle Yard Hold",
      "navisionSubLocationDescription": "Vehicle Yard Hold",
      "pdcLocation": "PMB",
      "pmbEnteredAt": "2026-06-30T08:15:00Z",
      "pdcLocationUpdatedAt": "2026-06-30T08:15:00Z",
      "pmbStage": "TINT",
      "pmbStageUpdatedAt": "2026-07-03T09:15:00Z",
      "pdcRequiresTint": true,
      "pmbBayNumber": "02",
      "pdcRequiresFitting": true,
      "pdcRequiresParts": false,
      "pdcCompleteTint": true,
      "pdcCompleteTintAt": "2026-07-02T14:15:00Z",
      "pdcCompleteTintBy": "Test Tech",
      "pdcCompleteFitting": true,
      "pdcCompleteFittingAt": "2026-07-02T14:15:00Z",
      "pdcCompleteFittingBy": "Test Tech"
    },
    {
      "source": "Test 75 vehicle dataset",
      "consultant": "JT",
      "stock": "TEST033",
      "batch": "BATCH0033",
      "order": "ORD00033",
      "salesOrder": "SO00033",
      "pdcJobcard": "JC00033",
      "client": "Kewdale Civil",
      "contact": "0400 000 033",
      "vehicle": "LandCruiser 300",
      "vin": "TESTVIN00000000033",
      "rego": "T00033",
      "prodMth": "Jul 2026",
      "productionMonth": "Jul 2026",
      "navisionKewdaleEta": "02/07/2026",
      "etaAtDealer": "02/07/2026",
      "jitaPartsOrdered": "Yes",
      "notes": "Test vehicle 33: PMB workflow with varied work status",
      "navisionDealerComments": "Test dataset row 33 for PMB workflow",
      "pmbKeyNumber": "K033",
      "toyotaStatus": "Vehicle Yard Hold",
      "navisionSubLocationDescription": "Vehicle Yard Hold",
      "pdcLocation": "PMB",
      "pmbEnteredAt": "2026-06-29T08:15:00Z",
      "pdcLocationUpdatedAt": "2026-06-29T08:15:00Z",
      "pmbStage": "HOIST",
      "pmbStageUpdatedAt": "2026-07-02T09:15:00Z",
      "pdcRequiresHoist": true,
      "pmbBayNumber": "03",
      "pdcRequiresFabrication": true,
      "pdcRequiresParts": true,
      "pdcPartsOrdered": true,
      "pdcPartsOrderedAt": "2026-06-28T08:15:00Z",
      "pdcPartsOrderedBy": "Test Parts"
    },
    {
      "source": "Test 75 vehicle dataset",
      "consultant": "LS",
      "stock": "TEST034",
      "batch": "BATCH0034",
      "order": "ORD00034",
      "salesOrder": "SO00034",
      "pdcJobcard": "JC00034",
      "client": "Watson Transport",
      "contact": "0400 000 034",
      "vehicle": "Yaris Cross",
      "vin": "TESTVIN00000000034",
      "rego": "T00034",
      "prodMth": "Jul 2026",
      "productionMonth": "Jul 2026",
      "navisionKewdaleEta": "03/07/2026",
      "etaAtDealer": "03/07/2026",
      "jitaPartsOrdered": "No",
      "notes": "Test vehicle 34: PMB workflow with varied work status",
      "navisionDealerComments": "Test dataset row 34 for PMB workflow",
      "pmbKeyNumber": "K034",
      "toyotaStatus": "Vehicle Yard Hold",
      "navisionSubLocationDescription": "Vehicle Yard Hold",
      "pdcLocation": "PMB",
      "pmbEnteredAt": "2026-06-28T08:15:00Z",
      "pdcLocationUpdatedAt": "2026-06-28T08:15:00Z",
      "pmbStage": "FITTING",
      "pmbStageUpdatedAt": "2026-07-01T09:15:00Z",
      "pdcRequiresFitting": true,
      "pmbBayNumber": "01",
      "pdcRequiresHoist": true,
      "pdcRequiresElectrical": true,
      "pdcRequiresParts": true,
      "pdcCompleteHoist": true,
      "pdcCompleteHoistAt": "2026-06-30T14:15:00Z",
      "pdcCompleteHoistBy": "Test Tech",
      "pdcCompleteParts": true,
      "pdcCompletePartsAt": "2026-07-01T08:15:00Z",
      "pdcPartsReceived": true,
      "pdcCompletePartsBy": "Test Parts",
      "pdcPartsStoppage": true,
      "pdcPartsStoppageReason": "Backorder awaiting supplier confirmation"
    },
    {
      "source": "Test 75 vehicle dataset",
      "consultant": "RD",
      "stock": "TEST035",
      "batch": "BATCH0035",
      "order": "ORD00035",
      "salesOrder": "SO00035",
      "pdcJobcard": "JC00035",
      "client": "Coastal Hire",
      "contact": "0400 000 035",
      "vehicle": "HiLux Rogue",
      "vin": "TESTVIN00000000035",
      "rego": "T00035",
      "prodMth": "Jul 2026",
      "productionMonth": "Jul 2026",
      "navisionKewdaleEta": "04/07/2026",
      "etaAtDealer": "04/07/2026",
      "jitaPartsOrdered": "No",
      "notes": "Test vehicle 35: PMB workflow with varied work status",
      "navisionDealerComments": "Test dataset row 35 for PMB workflow",
      "pmbKeyNumber": "K035",
      "toyotaStatus": "Vehicle Yard Hold",
      "navisionSubLocationDescription": "Vehicle Yard Hold",
      "pdcLocation": "PMB",
      "pmbEnteredAt": "2026-06-27T08:15:00Z",
      "pdcLocationUpdatedAt": "2026-06-27T08:15:00Z",
      "pmbStage": "FABRICATION",
      "pmbStageUpdatedAt": "2026-06-30T09:15:00Z",
      "pdcRequiresFabrication": true,
      "pdcRequiresTint": true,
      "pdcRequiresTyre": true,
      "pdcRequiresParts": true,
      "pdcCompleteTint": true,
      "pdcCompleteTintAt": "2026-06-29T14:15:00Z",
      "pdcCompleteTintBy": "Test Tech",
      "pdcCompleteTyre": true,
      "pdcCompleteTyreAt": "2026-06-29T14:15:00Z",
      "pdcCompleteTyreBy": "Test Tech"
    },
    {
      "source": "Test 75 vehicle dataset",
      "consultant": "CW",
      "stock": "TEST036",
      "batch": "BATCH0036",
      "order": "ORD00036",
      "salesOrder": "SO00036",
      "pdcJobcard": "JC00036",
      "client": "Red Dirt Contracting",
      "contact": "0400 000 036",
      "vehicle": "Coaster Bus",
      "vin": "TESTVIN00000000036",
      "rego": "T00036",
      "prodMth": "Jul 2026",
      "productionMonth": "Jul 2026",
      "navisionKewdaleEta": "05/07/2026",
      "etaAtDealer": "05/07/2026",
      "jitaPartsOrdered": "Yes",
      "notes": "Test vehicle 36: PMB workflow with varied work status",
      "navisionDealerComments": "Test dataset row 36 for PMB workflow",
      "pmbKeyNumber": "K036",
      "toyotaStatus": "Vehicle Yard Hold",
      "navisionSubLocationDescription": "Vehicle Yard Hold",
      "pdcLocation": "PMB",
      "pmbEnteredAt": "2026-06-26T08:15:00Z",
      "pdcLocationUpdatedAt": "2026-06-26T08:15:00Z",
      "pmbStage": "ELECTRICAL",
      "pmbStageUpdatedAt": "2026-07-07T09:15:00Z",
      "pdcRequiresElectrical": true,
      "pmbBayNumber": "03",
      "pdcRequiresPitInspection": true,
      "pdcRequiresParts": false
    },
    {
      "source": "Test 75 vehicle dataset",
      "consultant": "BG",
      "stock": "TEST037",
      "batch": "BATCH0037",
      "order": "ORD00037",
      "salesOrder": "SO00037",
      "pdcJobcard": "JC00037",
      "client": "Metro Maintenance",
      "contact": "0400 000 037",
      "vehicle": "LandCruiser 79",
      "vin": "TESTVIN00000000037",
      "rego": "T00037",
      "prodMth": "Jul 2026",
      "productionMonth": "Jul 2026",
      "navisionKewdaleEta": "06/07/2026",
      "etaAtDealer": "06/07/2026",
      "jitaPartsOrdered": "No",
      "notes": "Test vehicle 37: PMB workflow with varied work status",
      "navisionDealerComments": "Test dataset row 37 for PMB workflow",
      "pmbKeyNumber": "K037",
      "toyotaStatus": "Vehicle Yard Hold",
      "navisionSubLocationDescription": "Vehicle Yard Hold",
      "pdcLocation": "PMB",
      "pmbEnteredAt": "2026-07-07T08:15:00Z",
      "pdcLocationUpdatedAt": "2026-07-07T08:15:00Z",
      "pmbStage": "TYRE",
      "pmbStageUpdatedAt": "2026-07-06T09:15:00Z",
      "pdcRequiresTyre": true,
      "pmbBayNumber": "01",
      "pdcRequiresFitting": true,
      "pdcRequiresParts": true,
      "pdcPartsOrdered": true,
      "pdcPartsOrderedAt": "2026-07-06T08:15:00Z",
      "pdcPartsOrderedBy": "Test Parts"
    },
    {
      "source": "Test 75 vehicle dataset",
      "consultant": "AM",
      "stock": "TEST038",
      "batch": "BATCH0038",
      "order": "ORD00038",
      "salesOrder": "SO00038",
      "pdcJobcard": "JC00038",
      "client": "Goldfields Mining",
      "contact": "0400 000 038",
      "vehicle": "Prado VX",
      "vin": "TESTVIN00000000038",
      "rego": "T00038",
      "prodMth": "Jul 2026",
      "productionMonth": "Jul 2026",
      "navisionKewdaleEta": "07/07/2026",
      "etaAtDealer": "07/07/2026",
      "jitaPartsOrdered": "No",
      "notes": "Test vehicle 38: PMB workflow with varied work status",
      "navisionDealerComments": "Test dataset row 38 for PMB workflow",
      "pmbKeyNumber": "K038",
      "toyotaStatus": "Vehicle Yard Hold",
      "navisionSubLocationDescription": "Vehicle Yard Hold",
      "pdcLocation": "PMB",
      "pmbEnteredAt": "2026-07-06T08:15:00Z",
      "pdcLocationUpdatedAt": "2026-07-06T08:15:00Z",
      "pmbStage": "PIT_INSPECTION",
      "pmbStageUpdatedAt": "2026-07-05T09:15:00Z",
      "pdcRequiresPitInspection": true,
      "pmbBayNumber": "02",
      "pdcRequiresFabrication": true,
      "pdcRequiresParts": true,
      "pdcCompleteParts": true,
      "pdcCompletePartsAt": "2026-07-04T08:15:00Z",
      "pdcPartsReceived": true,
      "pdcCompletePartsBy": "Test Parts",
      "pmbStoppage": true,
      "pmbStoppageReason": "Workshop stoppage test flag"
    },
    {
      "source": "Test 75 vehicle dataset",
      "consultant": "JT",
      "stock": "TEST039",
      "batch": "BATCH0039",
      "order": "ORD00039",
      "salesOrder": "SO00039",
      "pdcJobcard": "JC00039",
      "client": "Perth Landscapes",
      "contact": "0400 000 039",
      "vehicle": "HiAce LWB",
      "vin": "TESTVIN00000000039",
      "rego": "T00039",
      "prodMth": "Aug 2026",
      "productionMonth": "Aug 2026",
      "navisionKewdaleEta": "08/07/2026",
      "etaAtDealer": "08/07/2026",
      "jitaPartsOrdered": "Yes",
      "notes": "Test vehicle 39: PMB workflow with varied work status",
      "navisionDealerComments": "Test dataset row 39 for PMB workflow",
      "pmbKeyNumber": "K039",
      "toyotaStatus": "Vehicle Yard Hold",
      "navisionSubLocationDescription": "Vehicle Yard Hold",
      "pdcLocation": "PMB",
      "pmbEnteredAt": "2026-07-05T08:15:00Z",
      "pdcLocationUpdatedAt": "2026-07-05T08:15:00Z",
      "pmbStage": "",
      "pmbStageUpdatedAt": "2026-07-04T09:15:00Z",
      "pdcRequiresHoist": true,
      "pdcRequiresElectrical": true,
      "pdcRequiresParts": true
    },
    {
      "source": "Test 75 vehicle dataset",
      "consultant": "LS",
      "stock": "TEST040",
      "batch": "BATCH0040",
      "order": "ORD00040",
      "salesOrder": "SO00040",
      "pdcJobcard": "JC00040",
      "client": "Swan Valley Electrical",
      "contact": "0400 000 040",
      "vehicle": "Corolla Cross",
      "vin": "TESTVIN00000000040",
      "rego": "T00040",
      "prodMth": "Aug 2026",
      "productionMonth": "Aug 2026",
      "navisionKewdaleEta": "09/07/2026",
      "etaAtDealer": "09/07/2026",
      "jitaPartsOrdered": "No",
      "notes": "Test vehicle 40: PMB workflow with varied work status",
      "navisionDealerComments": "Test dataset row 40 for PMB workflow",
      "pmbKeyNumber": "K040",
      "toyotaStatus": "Vehicle Yard Hold",
      "navisionSubLocationDescription": "Vehicle Yard Hold",
      "pdcLocation": "PMB",
      "pmbEnteredAt": "2026-07-04T08:15:00Z",
      "pdcLocationUpdatedAt": "2026-07-04T08:15:00Z",
      "pmbStage": "TINT",
      "pmbStageUpdatedAt": "2026-07-03T09:15:00Z",
      "pdcRequiresTint": true,
      "pmbBayNumber": "01",
      "pdcRequiresTyre": true,
      "pdcRequiresParts": false
    },
    {
      "source": "Test 75 vehicle dataset",
      "consultant": "RD",
      "stock": "TEST041",
      "batch": "BATCH0041",
      "order": "ORD00041",
      "salesOrder": "SO00041",
      "pdcJobcard": "JC00041",
      "client": "Outback Energy",
      "contact": "0400 000 041",
      "vehicle": "RAV4 Cruiser",
      "vin": "TESTVIN00000000041",
      "rego": "T00041",
      "prodMth": "Aug 2026",
      "productionMonth": "Aug 2026",
      "navisionKewdaleEta": "10/07/2026",
      "etaAtDealer": "10/07/2026",
      "jitaPartsOrdered": "No",
      "notes": "Test vehicle 41: PMB workflow with varied work status",
      "navisionDealerComments": "Test dataset row 41 for PMB workflow",
      "pmbKeyNumber": "K041",
      "toyotaStatus": "Vehicle Yard Hold",
      "navisionSubLocationDescription": "Vehicle Yard Hold",
      "pdcLocation": "PMB",
      "pmbEnteredAt": "2026-07-03T08:15:00Z",
      "pdcLocationUpdatedAt": "2026-07-03T08:15:00Z",
      "pmbStage": "HOIST",
      "pmbStageUpdatedAt": "2026-07-02T09:15:00Z",
      "pdcRequiresHoist": true,
      "pmbBayNumber": "02",
      "pdcRequiresPitInspection": true,
      "pdcRequiresParts": true,
      "pdcPartsOrdered": true,
      "pdcPartsOrderedAt": "2026-07-02T08:15:00Z",
      "pdcPartsOrderedBy": "Test Parts"
    },
    {
      "source": "Test 75 vehicle dataset",
      "consultant": "CW",
      "stock": "TEST042",
      "batch": "BATCH0042",
      "order": "ORD00042",
      "salesOrder": "SO00042",
      "pdcJobcard": "JC00042",
      "client": "Fremantle Council",
      "contact": "0400 000 042",
      "vehicle": "Fortuner GXL",
      "vin": "TESTVIN00000000042",
      "rego": "T00042",
      "prodMth": "Aug 2026",
      "productionMonth": "Aug 2026",
      "navisionKewdaleEta": "11/07/2026",
      "etaAtDealer": "11/07/2026",
      "jitaPartsOrdered": "Yes",
      "notes": "Test vehicle 42: PMB workflow with varied work status",
      "navisionDealerComments": "Test dataset row 42 for PMB workflow",
      "pmbKeyNumber": "K042",
      "toyotaStatus": "Vehicle Yard Hold",
      "navisionSubLocationDescription": "Vehicle Yard Hold",
      "pdcLocation": "PMB",
      "pmbEnteredAt": "2026-07-02T08:15:00Z",
      "pdcLocationUpdatedAt": "2026-07-02T08:15:00Z",
      "pmbStage": "FITTING",
      "pmbStageUpdatedAt": "2026-07-01T09:15:00Z",
      "pdcRequiresFitting": true,
      "pmbBayNumber": "03",
      "pdcRequiresParts": true,
      "pdcCompleteParts": true,
      "pdcCompletePartsAt": "2026-07-07T08:15:00Z",
      "pdcPartsReceived": true,
      "pdcCompletePartsBy": "Test Parts",
      "pdcPartsStoppage": true,
      "pdcPartsStoppageReason": "Backorder awaiting supplier confirmation"
    },
    {
      "source": "Test 75 vehicle dataset",
      "consultant": "BG",
      "stock": "TEST043",
      "batch": "BATCH0043",
      "order": "ORD00043",
      "salesOrder": "SO00043",
      "pdcJobcard": "JC00043",
      "client": "Western Rescue",
      "contact": "0400 000 043",
      "vehicle": "Camry Hybrid",
      "vin": "TESTVIN00000000043",
      "rego": "T00043",
      "prodMth": "Aug 2026",
      "productionMonth": "Aug 2026",
      "navisionKewdaleEta": "12/07/2026",
      "etaAtDealer": "12/07/2026",
      "jitaPartsOrdered": "No",
      "notes": "Test vehicle 43: PMB workflow with varied work status",
      "navisionDealerComments": "Test dataset row 43 for PMB workflow",
      "pmbKeyNumber": "K043",
      "toyotaStatus": "Vehicle Yard Hold",
      "navisionSubLocationDescription": "Vehicle Yard Hold",
      "pdcLocation": "PMB",
      "pmbEnteredAt": "2026-07-01T08:15:00Z",
      "pdcLocationUpdatedAt": "2026-07-01T08:15:00Z",
      "pmbStage": "FABRICATION",
      "pmbStageUpdatedAt": "2026-06-30T09:15:00Z",
      "pdcRequiresFabrication": true,
      "pdcRequiresParts": true,
      "pdcCompleteFabrication": true,
      "pdcCompleteFabricationAt": "2026-06-30T14:15:00Z",
      "pdcCompleteFabricationBy": "Test Tech"
    },
    {
      "source": "Test 75 vehicle dataset",
      "consultant": "AM",
      "stock": "TEST044",
      "batch": "BATCH0044",
      "order": "ORD00044",
      "salesOrder": "SO00044",
      "pdcJobcard": "JC00044",
      "client": "Horizon Builders",
      "contact": "0400 000 044",
      "vehicle": "Hilux SR5",
      "vin": "TESTVIN00000000044",
      "rego": "T00044",
      "prodMth": "Aug 2026",
      "productionMonth": "Aug 2026",
      "navisionKewdaleEta": "13/07/2026",
      "etaAtDealer": "13/07/2026",
      "jitaPartsOrdered": "No",
      "notes": "Test vehicle 44: PMB workflow with varied work status",
      "navisionDealerComments": "Test dataset row 44 for PMB workflow",
      "pmbKeyNumber": "K044",
      "toyotaStatus": "Vehicle Yard Hold",
      "navisionSubLocationDescription": "Vehicle Yard Hold",
      "pdcLocation": "PMB",
      "pmbEnteredAt": "2026-06-30T08:15:00Z",
      "pdcLocationUpdatedAt": "2026-06-30T08:15:00Z",
      "pmbStage": "ELECTRICAL",
      "pmbStageUpdatedAt": "2026-07-07T09:15:00Z",
      "pdcRequiresElectrical": true,
      "pmbBayNumber": "02",
      "pdcRequiresHoist": true,
      "pdcRequiresParts": false,
      "pdcCompleteElectrical": true,
      "pdcCompleteElectricalAt": "2026-06-29T14:15:00Z",
      "pdcCompleteElectricalBy": "Test Tech"
    },
    {
      "source": "Test 75 vehicle dataset",
      "consultant": "JT",
      "stock": "TEST045",
      "batch": "BATCH0045",
      "order": "ORD00045",
      "salesOrder": "SO00045",
      "pdcJobcard": "JC00045",
      "client": "Kimberley Tours",
      "contact": "0400 000 045",
      "vehicle": "LandCruiser 300",
      "vin": "TESTVIN00000000045",
      "rego": "T00045",
      "prodMth": "Aug 2026",
      "productionMonth": "Aug 2026",
      "navisionKewdaleEta": "14/07/2026",
      "etaAtDealer": "14/07/2026",
      "jitaPartsOrdered": "Yes",
      "notes": "Test vehicle 45: PMB workflow with varied work status",
      "navisionDealerComments": "Test dataset row 45 for PMB workflow",
      "pmbKeyNumber": "K045",
      "toyotaStatus": "Vehicle Yard Hold",
      "navisionSubLocationDescription": "Vehicle Yard Hold",
      "pdcLocation": "PMB",
      "pmbEnteredAt": "2026-06-29T08:15:00Z",
      "pdcLocationUpdatedAt": "2026-06-29T08:15:00Z",
      "pmbStage": "TYRE",
      "pmbStageUpdatedAt": "2026-07-06T09:15:00Z",
      "pdcRequiresTyre": true,
      "pmbBayNumber": "03",
      "pdcRequiresTint": true,
      "pdcRequiresParts": true,
      "pdcPartsOrdered": true,
      "pdcPartsOrderedAt": "2026-06-28T08:15:00Z",
      "pdcPartsOrderedBy": "Test Parts"
    },
    {
      "source": "Test 75 vehicle dataset",
      "consultant": "LS",
      "stock": "TEST046",
      "batch": "BATCH0046",
      "order": "ORD00046",
      "salesOrder": "SO00046",
      "pdcJobcard": "JC00046",
      "client": "Northwest Plumbing",
      "contact": "0400 000 046",
      "vehicle": "Yaris Cross",
      "vin": "TESTVIN00000000046",
      "rego": "T00046",
      "prodMth": "Aug 2026",
      "productionMonth": "Aug 2026",
      "navisionKewdaleEta": "15/07/2026",
      "etaAtDealer": "15/07/2026",
      "jitaPartsOrdered": "No",
      "notes": "Test vehicle 46: PMB workflow with varied work status",
      "navisionDealerComments": "Test dataset row 46 for PMB workflow",
      "pmbKeyNumber": "K046",
      "toyotaStatus": "Vehicle Yard Hold",
      "navisionSubLocationDescription": "Vehicle Yard Hold",
      "pdcLocation": "PMB",
      "pmbEnteredAt": "2026-06-28T08:15:00Z",
      "pdcLocationUpdatedAt": "2026-06-28T08:15:00Z",
      "pmbStage": "PIT_INSPECTION",
      "pmbStageUpdatedAt": "2026-07-05T09:15:00Z",
      "pdcRequiresPitInspection": true,
      "pmbBayNumber": "01",
      "pdcRequiresParts": true,
      "pdcCompletePitInspection": true,
      "pdcCompletePitInspectionAt": "2026-07-06T14:15:00Z",
      "pdcCompletePitInspectionBy": "Test Tech",
      "pdcCompleteParts": true,
      "pdcCompletePartsAt": "2026-07-03T08:15:00Z",
      "pdcPartsReceived": true,
      "pdcCompletePartsBy": "Test Parts"
    },
    {
      "source": "Test 75 vehicle dataset",
      "consultant": "RD",
      "stock": "TEST047",
      "batch": "BATCH0047",
      "order": "ORD00047",
      "salesOrder": "SO00047",
      "pdcJobcard": "JC00047",
      "client": "Pilbara Electrical",
      "contact": "0400 000 047",
      "vehicle": "HiLux Rogue",
      "vin": "TESTVIN00000000047",
      "rego": "T00047",
      "prodMth": "Aug 2026",
      "productionMonth": "Aug 2026",
      "navisionKewdaleEta": "16/07/2026",
      "etaAtDealer": "16/07/2026",
      "jitaPartsOrdered": "No",
      "notes": "Test vehicle 47: PMB workflow with varied work status",
      "navisionDealerComments": "Test dataset row 47 for PMB workflow",
      "pmbKeyNumber": "K047",
      "toyotaStatus": "Vehicle Yard Hold",
      "navisionSubLocationDescription": "Vehicle Yard Hold",
      "pdcLocation": "PMB",
      "pmbEnteredAt": "2026-06-27T08:15:00Z",
      "pdcLocationUpdatedAt": "2026-06-27T08:15:00Z",
      "pmbStage": "",
      "pmbStageUpdatedAt": "2026-07-04T09:15:00Z",
      "pdcRequiresFitting": true,
      "pdcRequiresParts": true,
      "pdcCompleteFitting": true,
      "pdcCompleteFittingAt": "2026-07-05T14:15:00Z",
      "pdcCompleteFittingBy": "Test Tech",
      "pmbStoppage": true,
      "pmbStoppageReason": "Workshop stoppage test flag"
    },
    {
      "source": "Test 75 vehicle dataset",
      "consultant": "CW",
      "stock": "TEST048",
      "batch": "BATCH0048",
      "order": "ORD00048",
      "salesOrder": "SO00048",
      "pdcJobcard": "JC00048",
      "client": "Kewdale Civil",
      "contact": "0400 000 048",
      "vehicle": "Coaster Bus",
      "vin": "TESTVIN00000000048",
      "rego": "T00048",
      "prodMth": "Aug 2026",
      "productionMonth": "Aug 2026",
      "navisionKewdaleEta": "17/07/2026",
      "etaAtDealer": "17/07/2026",
      "jitaPartsOrdered": "Yes",
      "notes": "Test vehicle 48: PMB workflow with varied work status",
      "navisionDealerComments": "Test dataset row 48 for PMB workflow",
      "pmbKeyNumber": "K048",
      "toyotaStatus": "Vehicle Yard Hold",
      "navisionSubLocationDescription": "Vehicle Yard Hold",
      "pdcLocation": "PMB",
      "pmbEnteredAt": "2026-06-26T08:15:00Z",
      "pdcLocationUpdatedAt": "2026-06-26T08:15:00Z",
      "pmbStage": "TINT",
      "pmbStageUpdatedAt": "2026-07-03T09:15:00Z",
      "pdcRequiresTint": true,
      "pmbBayNumber": "03",
      "pdcRequiresFabrication": true,
      "pdcRequiresParts": false
    },
    {
      "source": "Test 75 vehicle dataset",
      "consultant": "BG",
      "stock": "TEST049",
      "batch": "BATCH0049",
      "order": "ORD00049",
      "salesOrder": "SO00049",
      "pdcJobcard": "JC00049",
      "client": "Watson Transport",
      "contact": "0400 000 049",
      "vehicle": "LandCruiser 79",
      "vin": "TESTVIN00000000049",
      "rego": "T00049",
      "prodMth": "Aug 2026",
      "productionMonth": "Aug 2026",
      "navisionKewdaleEta": "18/07/2026",
      "etaAtDealer": "18/07/2026",
      "jitaPartsOrdered": "No",
      "notes": "Test vehicle 49: PMB workflow with varied work status",
      "navisionDealerComments": "Test dataset row 49 for PMB workflow",
      "pmbKeyNumber": "K049",
      "toyotaStatus": "Vehicle Yard Hold",
      "navisionSubLocationDescription": "Vehicle Yard Hold",
      "pdcLocation": "PMB",
      "pmbEnteredAt": "2026-07-07T08:15:00Z",
      "pdcLocationUpdatedAt": "2026-07-07T08:15:00Z",
      "pmbStage": "HOIST",
      "pmbStageUpdatedAt": "2026-07-02T09:15:00Z",
      "pdcRequiresHoist": true,
      "pmbBayNumber": "01",
      "pdcRequiresElectrical": true,
      "pdcRequiresParts": true,
      "pdcCompleteHoist": true,
      "pdcCompleteHoistAt": "2026-07-03T14:15:00Z",
      "pdcCompleteHoistBy": "Test Tech",
      "pdcPartsOrdered": true,
      "pdcPartsOrderedAt": "2026-07-06T08:15:00Z",
      "pdcPartsOrderedBy": "Test Parts"
    },
    {
      "source": "Test 75 vehicle dataset",
      "consultant": "AM",
      "stock": "TEST050",
      "batch": "BATCH0050",
      "order": "ORD00050",
      "salesOrder": "SO00050",
      "pdcJobcard": "JC00050",
      "client": "Coastal Hire",
      "contact": "0400 000 050",
      "vehicle": "Prado VX",
      "vin": "TESTVIN00000000050",
      "rego": "T00050",
      "prodMth": "Aug 2026",
      "productionMonth": "Aug 2026",
      "navisionKewdaleEta": "19/07/2026",
      "etaAtDealer": "19/07/2026",
      "jitaPartsOrdered": "No",
      "notes": "Test vehicle 50: PMB workflow with varied work status",
      "navisionDealerComments": "Test dataset row 50 for PMB workflow",
      "pmbKeyNumber": "K050",
      "toyotaStatus": "Vehicle Yard Hold",
      "navisionSubLocationDescription": "Vehicle Yard Hold",
      "pdcLocation": "PMB",
      "pmbEnteredAt": "2026-07-06T08:15:00Z",
      "pdcLocationUpdatedAt": "2026-07-06T08:15:00Z",
      "pmbStage": "FITTING",
      "pmbStageUpdatedAt": "2026-07-01T09:15:00Z",
      "pdcRequiresFitting": true,
      "pmbBayNumber": "02",
      "pdcRequiresTint": true,
      "pdcRequiresTyre": true,
      "pdcRequiresParts": true,
      "pdcCompleteTint": true,
      "pdcCompleteTintAt": "2026-07-02T14:15:00Z",
      "pdcCompleteTintBy": "Test Tech",
      "pdcCompleteFitting": true,
      "pdcCompleteFittingAt": "2026-07-02T14:15:00Z",
      "pdcCompleteFittingBy": "Test Tech",
      "pdcCompleteTyre": true,
      "pdcCompleteTyreAt": "2026-07-02T14:15:00Z",
      "pdcCompleteTyreBy": "Test Tech",
      "pdcCompleteParts": true,
      "pdcCompletePartsAt": "2026-07-06T08:15:00Z",
      "pdcPartsReceived": true,
      "pdcCompletePartsBy": "Test Parts"
    },
    {
      "source": "Test 75 vehicle dataset",
      "consultant": "JT",
      "stock": "TEST051",
      "batch": "BATCH0051",
      "order": "ORD00051",
      "salesOrder": "SO00051",
      "pdcJobcard": "JC00051",
      "client": "Red Dirt Contracting",
      "contact": "0400 000 051",
      "vehicle": "HiAce LWB",
      "vin": "TESTVIN00000000051",
      "rego": "T00051",
      "prodMth": "Aug 2026",
      "productionMonth": "Aug 2026",
      "navisionKewdaleEta": "20/07/2026",
      "etaAtDealer": "20/07/2026",
      "jitaPartsOrdered": "Yes",
      "notes": "Test vehicle 51: PMB workflow with varied work status",
      "navisionDealerComments": "Test dataset row 51 for PMB workflow",
      "pmbKeyNumber": "K051",
      "toyotaStatus": "Vehicle Yard Hold",
      "navisionSubLocationDescription": "Vehicle Yard Hold",
      "pdcLocation": "PMB",
      "pmbEnteredAt": "2026-07-05T08:15:00Z",
      "pdcLocationUpdatedAt": "2026-07-05T08:15:00Z",
      "pmbStage": "FABRICATION",
      "pmbStageUpdatedAt": "2026-06-30T09:15:00Z",
      "pdcRequiresFabrication": true,
      "pdcRequiresPitInspection": true,
      "pdcRequiresParts": true
    },
    {
      "source": "Test 75 vehicle dataset",
      "consultant": "LS",
      "stock": "TEST052",
      "batch": "BATCH0052",
      "order": "ORD00052",
      "salesOrder": "SO00052",
      "pdcJobcard": "JC00052",
      "client": "Metro Maintenance",
      "contact": "0400 000 052",
      "vehicle": "Corolla Cross",
      "vin": "TESTVIN00000000052",
      "rego": "T00052",
      "prodMth": "Aug 2026",
      "productionMonth": "Aug 2026",
      "navisionKewdaleEta": "25/06/2026",
      "etaAtDealer": "25/06/2026",
      "jitaPartsOrdered": "No",
      "notes": "Test vehicle 52: PMB workflow with varied work status",
      "navisionDealerComments": "Test dataset row 52 for PMB workflow",
      "pmbKeyNumber": "K052",
      "toyotaStatus": "Vehicle Yard Hold",
      "navisionSubLocationDescription": "Vehicle Yard Hold",
      "pdcLocation": "PMB",
      "pmbEnteredAt": "2026-07-04T08:15:00Z",
      "pdcLocationUpdatedAt": "2026-07-04T08:15:00Z",
      "pmbStage": "ELECTRICAL",
      "pmbStageUpdatedAt": "2026-07-07T09:15:00Z",
      "pdcRequiresElectrical": true,
      "pmbBayNumber": "01",
      "pdcRequiresFitting": true,
      "pdcRequiresParts": false
    },
    {
      "source": "Test 75 vehicle dataset",
      "consultant": "RD",
      "stock": "TEST053",
      "batch": "BATCH0053",
      "order": "ORD00053",
      "salesOrder": "SO00053",
      "pdcJobcard": "JC00053",
      "client": "Goldfields Mining",
      "contact": "0400 000 053",
      "vehicle": "RAV4 Cruiser",
      "vin": "TESTVIN00000000053",
      "rego": "T00053",
      "prodMth": "Aug 2026",
      "productionMonth": "Aug 2026",
      "navisionKewdaleEta": "26/06/2026",
      "etaAtDealer": "26/06/2026",
      "jitaPartsOrdered": "No",
      "notes": "Test vehicle 53: PMB workflow with varied work status",
      "navisionDealerComments": "Test dataset row 53 for PMB workflow",
      "pmbKeyNumber": "K053",
      "toyotaStatus": "Vehicle Yard Hold",
      "navisionSubLocationDescription": "Vehicle Yard Hold",
      "pdcLocation": "PMB",
      "pmbEnteredAt": "2026-07-03T08:15:00Z",
      "pdcLocationUpdatedAt": "2026-07-03T08:15:00Z",
      "pmbStage": "TYRE",
      "pmbStageUpdatedAt": "2026-07-06T09:15:00Z",
      "pdcRequiresTyre": true,
      "pmbBayNumber": "02",
      "pdcRequiresFabrication": true,
      "pdcRequiresParts": true,
      "pdcCompleteTyre": true,
      "pdcCompleteTyreAt": "2026-06-29T14:15:00Z",
      "pdcCompleteTyreBy": "Test Tech",
      "pdcPartsOrdered": true,
      "pdcPartsOrderedAt": "2026-07-02T08:15:00Z",
      "pdcPartsOrderedBy": "Test Parts"
    },
    {
      "source": "Test 75 vehicle dataset",
      "consultant": "CW",
      "stock": "TEST054",
      "batch": "BATCH0054",
      "order": "ORD00054",
      "salesOrder": "SO00054",
      "pdcJobcard": "JC00054",
      "client": "Perth Landscapes",
      "contact": "0400 000 054",
      "vehicle": "Fortuner GXL",
      "vin": "TESTVIN00000000054",
      "rego": "T00054",
      "prodMth": "Aug 2026",
      "productionMonth": "Aug 2026",
      "navisionKewdaleEta": "27/06/2026",
      "etaAtDealer": "27/06/2026",
      "jitaPartsOrdered": "Yes",
      "notes": "Test vehicle 54: PMB workflow with varied work status",
      "navisionDealerComments": "Test dataset row 54 for PMB workflow",
      "pmbKeyNumber": "K054",
      "toyotaStatus": "Vehicle Yard Hold",
      "navisionSubLocationDescription": "Vehicle Yard Hold",
      "pdcLocation": "PMB",
      "pmbEnteredAt": "2026-07-02T08:15:00Z",
      "pdcLocationUpdatedAt": "2026-07-02T08:15:00Z",
      "pmbStage": "PIT_INSPECTION",
      "pmbStageUpdatedAt": "2026-07-05T09:15:00Z",
      "pdcRequiresPitInspection": true,
      "pmbBayNumber": "03",
      "pdcRequiresHoist": true,
      "pdcRequiresElectrical": true,
      "pdcRequiresParts": true,
      "pdcCompleteParts": true,
      "pdcCompletePartsAt": "2026-07-02T08:15:00Z",
      "pdcPartsReceived": true,
      "pdcCompletePartsBy": "Test Parts"
    },
    {
      "source": "Test 75 vehicle dataset",
      "consultant": "BG",
      "stock": "TEST055",
      "batch": "BATCH0055",
      "order": "ORD00055",
      "salesOrder": "SO00055",
      "pdcJobcard": "JC00055",
      "client": "Swan Valley Electrical",
      "contact": "0400 000 055",
      "vehicle": "Camry Hybrid",
      "vin": "TESTVIN00000000055",
      "rego": "T00055",
      "prodMth": "Aug 2026",
      "productionMonth": "Aug 2026",
      "navisionKewdaleEta": "28/06/2026",
      "etaAtDealer": "28/06/2026",
      "jitaPartsOrdered": "No",
      "notes": "Test vehicle 55: PMB workflow with varied work status",
      "navisionDealerComments": "Test dataset row 55 for PMB workflow",
      "pmbKeyNumber": "K055",
      "toyotaStatus": "Vehicle Yard Hold",
      "navisionSubLocationDescription": "Vehicle Yard Hold",
      "pdcLocation": "PMB",
      "pmbEnteredAt": "2026-07-01T08:15:00Z",
      "pdcLocationUpdatedAt": "2026-07-01T08:15:00Z",
      "pmbStage": "",
      "pmbStageUpdatedAt": "2026-07-04T09:15:00Z",
      "pdcRequiresTint": true,
      "pdcRequiresTyre": true,
      "pdcRequiresParts": true,
      "pdcPartsStoppage": true,
      "pdcPartsStoppageReason": "Backorder awaiting supplier confirmation"
    },
    {
      "source": "Test 75 vehicle dataset",
      "consultant": "AM",
      "stock": "TEST056",
      "batch": "BATCH0056",
      "order": "ORD00056",
      "salesOrder": "SO00056",
      "pdcJobcard": "JC00056",
      "client": "Outback Energy",
      "contact": "0400 000 056",
      "vehicle": "Hilux SR5",
      "vin": "TESTVIN00000000056",
      "rego": "T00056",
      "prodMth": "Aug 2026",
      "productionMonth": "Aug 2026",
      "navisionKewdaleEta": "29/06/2026",
      "etaAtDealer": "29/06/2026",
      "jitaPartsOrdered": "No",
      "notes": "Test vehicle 56: PMB workflow with varied work status",
      "navisionDealerComments": "Test dataset row 56 for PMB workflow",
      "pmbKeyNumber": "K056",
      "toyotaStatus": "Vehicle Yard Hold",
      "navisionSubLocationDescription": "Vehicle Yard Hold",
      "pdcLocation": "PMB",
      "pmbEnteredAt": "2026-06-30T08:15:00Z",
      "pdcLocationUpdatedAt": "2026-06-30T08:15:00Z",
      "pmbStage": "TINT",
      "pmbStageUpdatedAt": "2026-07-03T09:15:00Z",
      "pdcRequiresTint": true,
      "pmbBayNumber": "02",
      "pdcRequiresPitInspection": true,
      "pdcRequiresParts": false,
      "pdcCompleteTint": true,
      "pdcCompleteTintAt": "2026-07-05T14:15:00Z",
      "pdcCompleteTintBy": "Test Tech"
    },
    {
      "source": "Test 75 vehicle dataset",
      "consultant": "JT",
      "stock": "TEST057",
      "batch": "BATCH0057",
      "order": "ORD00057",
      "salesOrder": "SO00057",
      "pdcJobcard": "JC00057",
      "client": "Fremantle Council",
      "contact": "0400 000 057",
      "vehicle": "LandCruiser 300",
      "vin": "TESTVIN00000000057",
      "rego": "T00057",
      "prodMth": "Aug 2026",
      "productionMonth": "Aug 2026",
      "navisionKewdaleEta": "30/06/2026",
      "etaAtDealer": "30/06/2026",
      "jitaPartsOrdered": "Yes",
      "notes": "Test vehicle 57: PMB workflow with varied work status",
      "navisionDealerComments": "Test dataset row 57 for PMB workflow",
      "pmbKeyNumber": "K057",
      "toyotaStatus": "Vehicle Yard Hold",
      "navisionSubLocationDescription": "Vehicle Yard Hold",
      "pdcLocation": "PMB",
      "pmbEnteredAt": "2026-06-29T08:15:00Z",
      "pdcLocationUpdatedAt": "2026-06-29T08:15:00Z",
      "pmbStage": "HOIST",
      "pmbStageUpdatedAt": "2026-07-02T09:15:00Z",
      "pdcRequiresHoist": true,
      "pmbBayNumber": "03",
      "pdcRequiresFitting": true,
      "pdcRequiresParts": true,
      "pdcPartsOrdered": true,
      "pdcPartsOrderedAt": "2026-06-28T08:15:00Z",
      "pdcPartsOrderedBy": "Test Parts"
    },
    {
      "source": "Test 75 vehicle dataset",
      "consultant": "LS",
      "stock": "TEST058",
      "batch": "BATCH0058",
      "order": "ORD00058",
      "salesOrder": "SO00058",
      "pdcJobcard": "JC00058",
      "client": "Western Rescue",
      "contact": "0400 000 058",
      "vehicle": "Yaris Cross",
      "vin": "TESTVIN00000000058",
      "rego": "T00058",
      "prodMth": "Aug 2026",
      "productionMonth": "Aug 2026",
      "navisionKewdaleEta": "01/07/2026",
      "etaAtDealer": "01/07/2026",
      "jitaPartsOrdered": "No",
      "notes": "Test vehicle 58: PMB workflow with varied work status",
      "navisionDealerComments": "Test dataset row 58 for PMB workflow",
      "pmbKeyNumber": "K058",
      "toyotaStatus": "Vehicle Yard Hold",
      "navisionSubLocationDescription": "Vehicle Yard Hold",
      "pdcLocation": "PMB",
      "pmbEnteredAt": "2026-06-28T08:15:00Z",
      "pdcLocationUpdatedAt": "2026-06-28T08:15:00Z",
      "pmbStage": "FITTING",
      "pmbStageUpdatedAt": "2026-07-01T09:15:00Z",
      "pdcRequiresFitting": true,
      "pmbBayNumber": "01",
      "pdcRequiresFabrication": true,
      "pdcRequiresParts": true,
      "pdcCompleteFabrication": true,
      "pdcCompleteFabricationAt": "2026-07-03T14:15:00Z",
      "pdcCompleteFabricationBy": "Test Tech",
      "pdcCompleteParts": true,
      "pdcCompletePartsAt": "2026-07-05T08:15:00Z",
      "pdcPartsReceived": true,
      "pdcCompletePartsBy": "Test Parts"
    },
    {
      "source": "Test 75 vehicle dataset",
      "consultant": "RD",
      "stock": "TEST059",
      "batch": "BATCH0059",
      "order": "ORD00059",
      "salesOrder": "SO00059",
      "pdcJobcard": "JC00059",
      "client": "Horizon Builders",
      "contact": "0400 000 059",
      "vehicle": "HiLux Rogue",
      "vin": "TESTVIN00000000059",
      "rego": "T00059",
      "prodMth": "Aug 2026",
      "productionMonth": "Aug 2026",
      "navisionKewdaleEta": "02/07/2026",
      "etaAtDealer": "02/07/2026",
      "jitaPartsOrdered": "No",
      "notes": "Test vehicle 59: PMB workflow with varied work status",
      "navisionDealerComments": "Test dataset row 59 for PMB workflow",
      "pmbKeyNumber": "K059",
      "toyotaStatus": "Vehicle Yard Hold",
      "navisionSubLocationDescription": "Vehicle Yard Hold",
      "pdcLocation": "PMB",
      "pmbEnteredAt": "2026-06-27T08:15:00Z",
      "pdcLocationUpdatedAt": "2026-06-27T08:15:00Z",
      "pmbStage": "FABRICATION",
      "pmbStageUpdatedAt": "2026-06-30T09:15:00Z",
      "pdcRequiresFabrication": true,
      "pdcRequiresHoist": true,
      "pdcRequiresElectrical": true,
      "pdcRequiresParts": true,
      "pdcCompleteElectrical": true,
      "pdcCompleteElectricalAt": "2026-07-02T14:15:00Z",
      "pdcCompleteElectricalBy": "Test Tech",
      "pmbStoppage": true,
      "pmbStoppageReason": "Workshop stoppage test flag"
    },
    {
      "source": "Test 75 vehicle dataset",
      "consultant": "CW",
      "stock": "TEST060",
      "batch": "BATCH0060",
      "order": "ORD00060",
      "salesOrder": "SO00060",
      "pdcJobcard": "JC00060",
      "client": "Kimberley Tours",
      "contact": "0400 000 060",
      "vehicle": "Coaster Bus",
      "vin": "TESTVIN00000000060",
      "rego": "T00060",
      "prodMth": "Aug 2026",
      "productionMonth": "Aug 2026",
      "navisionKewdaleEta": "03/07/2026",
      "etaAtDealer": "03/07/2026",
      "jitaPartsOrdered": "Yes",
      "notes": "Test vehicle 60: PMB workflow with varied work status",
      "navisionDealerComments": "Test dataset row 60 for PMB workflow",
      "pmbKeyNumber": "K060",
      "toyotaStatus": "Vehicle Yard Hold",
      "navisionSubLocationDescription": "Vehicle Yard Hold",
      "pdcLocation": "PMB",
      "pmbEnteredAt": "2026-06-26T08:15:00Z",
      "pdcLocationUpdatedAt": "2026-06-26T08:15:00Z",
      "pmbStage": "ELECTRICAL",
      "pmbStageUpdatedAt": "2026-07-07T09:15:00Z",
      "pdcRequiresElectrical": true,
      "pmbBayNumber": "03",
      "pdcRequiresTint": true,
      "pdcRequiresTyre": true,
      "pdcRequiresParts": false
    },
    {
      "source": "Test 75 vehicle dataset",
      "consultant": "BG",
      "stock": "TEST061",
      "batch": "BATCH0061",
      "order": "ORD00061",
      "salesOrder": "SO00061",
      "pdcJobcard": "JC00061",
      "client": "Northwest Plumbing",
      "contact": "0400 000 061",
      "vehicle": "LandCruiser 79",
      "vin": "TESTVIN00000000061",
      "rego": "T00061",
      "prodMth": "Aug 2026",
      "productionMonth": "Aug 2026",
      "navisionKewdaleEta": "04/07/2026",
      "etaAtDealer": "04/07/2026",
      "jitaPartsOrdered": "No",
      "notes": "Test vehicle 61: RFT with varied work status",
      "navisionDealerComments": "Test dataset row 61 for RFT",
      "pmbKeyNumber": "K061",
      "toyotaStatus": "Vehicle Yard Hold",
      "navisionSubLocationDescription": "Vehicle Yard Hold",
      "pdcLocation": "RFT",
      "pmbEnteredAt": "2026-07-02T08:15:00Z",
      "rftTransferredAt": "2026-07-06T08:15:00Z",
      "pdcRequiresTint": true,
      "pdcCompleteTint": true,
      "pdcCompleteTintAt": "2026-07-06T08:15:00Z",
      "pdcCompleteTintBy": "Test Tech",
      "pdcRequiresFitting": true,
      "pdcCompleteFitting": true,
      "pdcCompleteFittingAt": "2026-07-06T08:15:00Z",
      "pdcCompleteFittingBy": "Test Tech",
      "pdcRequiresParts": true,
      "pdcCompleteParts": true,
      "pdcCompletePartsAt": "2026-07-06T08:15:00Z",
      "pdcCompletePartsBy": "Test Tech",
      "pdcRequiresPitInspection": true,
      "pdcCompletePitInspection": true,
      "pdcCompletePitInspectionAt": "2026-07-06T08:15:00Z",
      "pdcCompletePitInspectionBy": "Test Tech",
      "pdcPartsReceived": true
    },
    {
      "source": "Test 75 vehicle dataset",
      "consultant": "AM",
      "stock": "TEST062",
      "batch": "BATCH0062",
      "order": "ORD00062",
      "salesOrder": "SO00062",
      "pdcJobcard": "JC00062",
      "client": "Pilbara Electrical",
      "contact": "0400 000 062",
      "vehicle": "Prado VX",
      "vin": "TESTVIN00000000062",
      "rego": "T00062",
      "prodMth": "Aug 2026",
      "productionMonth": "Aug 2026",
      "navisionKewdaleEta": "05/07/2026",
      "etaAtDealer": "05/07/2026",
      "jitaPartsOrdered": "No",
      "notes": "Test vehicle 62: RFT with varied work status",
      "navisionDealerComments": "Test dataset row 62 for RFT",
      "pmbKeyNumber": "K062",
      "toyotaStatus": "Vehicle Yard Hold",
      "navisionSubLocationDescription": "Vehicle Yard Hold",
      "pdcLocation": "RFT",
      "pmbEnteredAt": "2026-07-01T08:15:00Z",
      "rftTransferredAt": "2026-07-05T08:15:00Z",
      "pdcRequiresTint": true,
      "pdcCompleteTint": true,
      "pdcCompleteTintAt": "2026-07-05T08:15:00Z",
      "pdcCompleteTintBy": "Test Tech",
      "pdcRequiresFitting": true,
      "pdcCompleteFitting": true,
      "pdcCompleteFittingAt": "2026-07-05T08:15:00Z",
      "pdcCompleteFittingBy": "Test Tech",
      "pdcRequiresParts": true,
      "pdcCompleteParts": true,
      "pdcCompletePartsAt": "2026-07-05T08:15:00Z",
      "pdcCompletePartsBy": "Test Tech",
      "pdcRequiresPitInspection": true,
      "pdcCompletePitInspection": true,
      "pdcCompletePitInspectionAt": "2026-07-05T08:15:00Z",
      "pdcCompletePitInspectionBy": "Test Tech",
      "pdcPartsReceived": true
    },
    {
      "source": "Test 75 vehicle dataset",
      "consultant": "JT",
      "stock": "TEST063",
      "batch": "BATCH0063",
      "order": "ORD00063",
      "salesOrder": "SO00063",
      "pdcJobcard": "JC00063",
      "client": "Kewdale Civil",
      "contact": "0400 000 063",
      "vehicle": "HiAce LWB",
      "vin": "TESTVIN00000000063",
      "rego": "T00063",
      "prodMth": "Aug 2026",
      "productionMonth": "Aug 2026",
      "navisionKewdaleEta": "06/07/2026",
      "etaAtDealer": "06/07/2026",
      "jitaPartsOrdered": "Yes",
      "notes": "Test vehicle 63: RFT with varied work status",
      "navisionDealerComments": "Test dataset row 63 for RFT",
      "pmbKeyNumber": "K063",
      "toyotaStatus": "Vehicle Yard Hold",
      "navisionSubLocationDescription": "Vehicle Yard Hold",
      "pdcLocation": "RFT",
      "pmbEnteredAt": "2026-06-30T08:15:00Z",
      "rftTransferredAt": "2026-07-04T08:15:00Z",
      "pdcRequiresTint": true,
      "pdcCompleteTint": true,
      "pdcCompleteTintAt": "2026-07-04T08:15:00Z",
      "pdcCompleteTintBy": "Test Tech",
      "pdcRequiresFitting": true,
      "pdcCompleteFitting": true,
      "pdcCompleteFittingAt": "2026-07-04T08:15:00Z",
      "pdcCompleteFittingBy": "Test Tech",
      "pdcRequiresParts": true,
      "pdcCompleteParts": true,
      "pdcCompletePartsAt": "2026-07-04T08:15:00Z",
      "pdcCompletePartsBy": "Test Tech",
      "pdcRequiresPitInspection": true,
      "pdcCompletePitInspection": true,
      "pdcCompletePitInspectionAt": "2026-07-04T08:15:00Z",
      "pdcCompletePitInspectionBy": "Test Tech",
      "pdcPartsReceived": true
    },
    {
      "source": "Test 75 vehicle dataset",
      "consultant": "LS",
      "stock": "TEST064",
      "batch": "BATCH0064",
      "order": "ORD00064",
      "salesOrder": "SO00064",
      "pdcJobcard": "JC00064",
      "client": "Watson Transport",
      "contact": "0400 000 064",
      "vehicle": "Corolla Cross",
      "vin": "TESTVIN00000000064",
      "rego": "T00064",
      "prodMth": "Aug 2026",
      "productionMonth": "Aug 2026",
      "navisionKewdaleEta": "07/07/2026",
      "etaAtDealer": "07/07/2026",
      "jitaPartsOrdered": "No",
      "notes": "Test vehicle 64: RFT with varied work status",
      "navisionDealerComments": "Test dataset row 64 for RFT",
      "pmbKeyNumber": "K064",
      "toyotaStatus": "Vehicle Yard Hold",
      "navisionSubLocationDescription": "Vehicle Yard Hold",
      "pdcLocation": "RFT",
      "pmbEnteredAt": "2026-06-29T08:15:00Z",
      "rftTransferredAt": "2026-07-03T08:15:00Z",
      "pdcRequiresTint": true,
      "pdcCompleteTint": true,
      "pdcCompleteTintAt": "2026-07-03T08:15:00Z",
      "pdcCompleteTintBy": "Test Tech",
      "pdcRequiresFitting": true,
      "pdcCompleteFitting": true,
      "pdcCompleteFittingAt": "2026-07-03T08:15:00Z",
      "pdcCompleteFittingBy": "Test Tech",
      "pdcRequiresParts": true,
      "pdcCompleteParts": true,
      "pdcCompletePartsAt": "2026-07-03T08:15:00Z",
      "pdcCompletePartsBy": "Test Tech",
      "pdcRequiresPitInspection": true,
      "pdcCompletePitInspection": true,
      "pdcCompletePitInspectionAt": "2026-07-03T08:15:00Z",
      "pdcCompletePitInspectionBy": "Test Tech",
      "pdcPartsReceived": true
    },
    {
      "source": "Test 75 vehicle dataset",
      "consultant": "RD",
      "stock": "TEST065",
      "batch": "BATCH0065",
      "order": "ORD00065",
      "salesOrder": "SO00065",
      "pdcJobcard": "JC00065",
      "client": "Coastal Hire",
      "contact": "0400 000 065",
      "vehicle": "RAV4 Cruiser",
      "vin": "TESTVIN00000000065",
      "rego": "T00065",
      "prodMth": "Aug 2026",
      "productionMonth": "Aug 2026",
      "navisionKewdaleEta": "08/07/2026",
      "etaAtDealer": "08/07/2026",
      "jitaPartsOrdered": "No",
      "notes": "Test vehicle 65: RFT with varied work status",
      "navisionDealerComments": "Test dataset row 65 for RFT",
      "pmbKeyNumber": "K065",
      "toyotaStatus": "Vehicle Yard Hold",
      "navisionSubLocationDescription": "Vehicle Yard Hold",
      "pdcLocation": "RFT",
      "pmbEnteredAt": "2026-06-28T08:15:00Z",
      "rftTransferredAt": "2026-07-02T08:15:00Z",
      "pdcRequiresTint": true,
      "pdcCompleteTint": true,
      "pdcCompleteTintAt": "2026-07-02T08:15:00Z",
      "pdcCompleteTintBy": "Test Tech",
      "pdcRequiresFitting": true,
      "pdcCompleteFitting": true,
      "pdcCompleteFittingAt": "2026-07-02T08:15:00Z",
      "pdcCompleteFittingBy": "Test Tech",
      "pdcRequiresParts": true,
      "pdcCompleteParts": true,
      "pdcCompletePartsAt": "2026-07-02T08:15:00Z",
      "pdcCompletePartsBy": "Test Tech",
      "pdcRequiresPitInspection": true,
      "pdcCompletePitInspection": true,
      "pdcCompletePitInspectionAt": "2026-07-02T08:15:00Z",
      "pdcCompletePitInspectionBy": "Test Tech",
      "pdcPartsReceived": true
    },
    {
      "source": "Test 75 vehicle dataset",
      "consultant": "CW",
      "stock": "TEST066",
      "batch": "BATCH0066",
      "order": "ORD00066",
      "salesOrder": "SO00066",
      "pdcJobcard": "JC00066",
      "client": "Red Dirt Contracting",
      "contact": "0400 000 066",
      "vehicle": "Fortuner GXL",
      "vin": "TESTVIN00000000066",
      "rego": "T00066",
      "prodMth": "Aug 2026",
      "productionMonth": "Aug 2026",
      "navisionKewdaleEta": "09/07/2026",
      "etaAtDealer": "09/07/2026",
      "jitaPartsOrdered": "Yes",
      "notes": "Test vehicle 66: RFT with varied work status",
      "navisionDealerComments": "Test dataset row 66 for RFT",
      "pmbKeyNumber": "K066",
      "toyotaStatus": "Vehicle Yard Hold",
      "navisionSubLocationDescription": "Vehicle Yard Hold",
      "pdcLocation": "RFT",
      "pmbEnteredAt": "2026-06-27T08:15:00Z",
      "rftTransferredAt": "2026-07-01T08:15:00Z",
      "pdcRequiresTint": true,
      "pdcCompleteTint": true,
      "pdcCompleteTintAt": "2026-07-07T08:15:00Z",
      "pdcCompleteTintBy": "Test Tech",
      "pdcRequiresFitting": true,
      "pdcCompleteFitting": true,
      "pdcCompleteFittingAt": "2026-07-07T08:15:00Z",
      "pdcCompleteFittingBy": "Test Tech",
      "pdcRequiresParts": true,
      "pdcCompleteParts": true,
      "pdcCompletePartsAt": "2026-07-07T08:15:00Z",
      "pdcCompletePartsBy": "Test Tech",
      "pdcRequiresPitInspection": true,
      "pdcCompletePitInspection": true,
      "pdcCompletePitInspectionAt": "2026-07-07T08:15:00Z",
      "pdcCompletePitInspectionBy": "Test Tech",
      "pdcPartsReceived": true
    },
    {
      "source": "Test 75 vehicle dataset",
      "consultant": "BG",
      "stock": "TEST067",
      "batch": "BATCH0067",
      "order": "ORD00067",
      "salesOrder": "SO00067",
      "pdcJobcard": "JC00067",
      "client": "Metro Maintenance",
      "contact": "0400 000 067",
      "vehicle": "Camry Hybrid",
      "vin": "TESTVIN00000000067",
      "rego": "T00067",
      "prodMth": "Aug 2026",
      "productionMonth": "Aug 2026",
      "navisionKewdaleEta": "10/07/2026",
      "etaAtDealer": "10/07/2026",
      "jitaPartsOrdered": "No",
      "notes": "Test vehicle 67: RFT with varied work status",
      "navisionDealerComments": "Test dataset row 67 for RFT",
      "pmbKeyNumber": "K067",
      "toyotaStatus": "Vehicle Yard Hold",
      "navisionSubLocationDescription": "Vehicle Yard Hold",
      "pdcLocation": "RFT",
      "pmbEnteredAt": "2026-06-26T08:15:00Z",
      "rftTransferredAt": "2026-06-30T08:15:00Z",
      "pdcRequiresTint": true,
      "pdcCompleteTint": true,
      "pdcCompleteTintAt": "2026-07-06T08:15:00Z",
      "pdcCompleteTintBy": "Test Tech",
      "pdcRequiresFitting": true,
      "pdcCompleteFitting": true,
      "pdcCompleteFittingAt": "2026-07-06T08:15:00Z",
      "pdcCompleteFittingBy": "Test Tech",
      "pdcRequiresParts": true,
      "pdcCompleteParts": true,
      "pdcCompletePartsAt": "2026-07-06T08:15:00Z",
      "pdcCompletePartsBy": "Test Tech",
      "pdcRequiresPitInspection": true,
      "pdcCompletePitInspection": true,
      "pdcCompletePitInspectionAt": "2026-07-06T08:15:00Z",
      "pdcCompletePitInspectionBy": "Test Tech",
      "pdcPartsReceived": true
    },
    {
      "source": "Test 75 vehicle dataset",
      "consultant": "AM",
      "stock": "TEST068",
      "batch": "BATCH0068",
      "order": "ORD00068",
      "salesOrder": "SO00068",
      "pdcJobcard": "JC00068",
      "client": "Goldfields Mining",
      "contact": "0400 000 068",
      "vehicle": "Hilux SR5",
      "vin": "TESTVIN00000000068",
      "rego": "T00068",
      "prodMth": "Aug 2026",
      "productionMonth": "Aug 2026",
      "navisionKewdaleEta": "11/07/2026",
      "etaAtDealer": "11/07/2026",
      "jitaPartsOrdered": "No",
      "notes": "Test vehicle 68: RFT with varied work status",
      "navisionDealerComments": "Test dataset row 68 for RFT",
      "pmbKeyNumber": "K068",
      "toyotaStatus": "Vehicle Yard Hold",
      "navisionSubLocationDescription": "Vehicle Yard Hold",
      "pdcLocation": "RFT",
      "pmbEnteredAt": "2026-06-25T08:15:00Z",
      "rftTransferredAt": "2026-06-29T08:15:00Z",
      "pdcRequiresTint": true,
      "pdcCompleteTint": true,
      "pdcCompleteTintAt": "2026-07-05T08:15:00Z",
      "pdcCompleteTintBy": "Test Tech",
      "pdcRequiresFitting": true,
      "pdcCompleteFitting": true,
      "pdcCompleteFittingAt": "2026-07-05T08:15:00Z",
      "pdcCompleteFittingBy": "Test Tech",
      "pdcRequiresParts": true,
      "pdcCompleteParts": true,
      "pdcCompletePartsAt": "2026-07-05T08:15:00Z",
      "pdcCompletePartsBy": "Test Tech",
      "pdcRequiresPitInspection": true,
      "pdcCompletePitInspection": true,
      "pdcCompletePitInspectionAt": "2026-07-05T08:15:00Z",
      "pdcCompletePitInspectionBy": "Test Tech",
      "pdcPartsReceived": true
    },
    {
      "source": "Test 75 vehicle dataset",
      "consultant": "JT",
      "stock": "TEST069",
      "batch": "BATCH0069",
      "order": "ORD00069",
      "salesOrder": "SO00069",
      "pdcJobcard": "JC00069",
      "client": "Perth Landscapes",
      "contact": "0400 000 069",
      "vehicle": "LandCruiser 300",
      "vin": "TESTVIN00000000069",
      "rego": "T00069",
      "prodMth": "Aug 2026",
      "productionMonth": "Aug 2026",
      "navisionKewdaleEta": "12/07/2026",
      "etaAtDealer": "12/07/2026",
      "jitaPartsOrdered": "Yes",
      "notes": "Test vehicle 69: completed / collected with varied work status",
      "navisionDealerComments": "Test dataset row 69 for completed / collected",
      "pmbKeyNumber": "K069",
      "toyotaStatus": "Vehicle Yard Hold",
      "navisionSubLocationDescription": "Vehicle Yard Hold",
      "pdcLocation": "RFT",
      "pmbEnteredAt": "2026-06-29T08:15:00Z",
      "rftTransferredAt": "2026-07-04T08:15:00Z",
      "rftCollected": true,
      "completedVehicle": true,
      "rftCollectedAt": "2026-07-07T16:15:00Z",
      "rftCollectedBy": "Test Dispatch",
      "pdcRequiresTint": true,
      "pdcCompleteTint": true,
      "pdcCompleteTintAt": "2026-07-02T08:15:00Z",
      "pdcCompleteTintBy": "Test Tech",
      "pdcRequiresFitting": true,
      "pdcCompleteFitting": true,
      "pdcCompleteFittingAt": "2026-07-02T08:15:00Z",
      "pdcCompleteFittingBy": "Test Tech",
      "pdcRequiresElectrical": true,
      "pdcCompleteElectrical": true,
      "pdcCompleteElectricalAt": "2026-07-02T08:15:00Z",
      "pdcCompleteElectricalBy": "Test Tech",
      "pdcRequiresParts": true,
      "pdcCompleteParts": true,
      "pdcCompletePartsAt": "2026-07-02T08:15:00Z",
      "pdcCompletePartsBy": "Test Tech",
      "pdcRequiresPitInspection": true,
      "pdcCompletePitInspection": true,
      "pdcCompletePitInspectionAt": "2026-07-02T08:15:00Z",
      "pdcCompletePitInspectionBy": "Test Tech",
      "pdcPartsReceived": true
    },
    {
      "source": "Test 75 vehicle dataset",
      "consultant": "LS",
      "stock": "TEST070",
      "batch": "BATCH0070",
      "order": "ORD00070",
      "salesOrder": "SO00070",
      "pdcJobcard": "JC00070",
      "client": "Swan Valley Electrical",
      "contact": "0400 000 070",
      "vehicle": "Yaris Cross",
      "vin": "TESTVIN00000000070",
      "rego": "T00070",
      "prodMth": "Aug 2026",
      "productionMonth": "Aug 2026",
      "navisionKewdaleEta": "13/07/2026",
      "etaAtDealer": "13/07/2026",
      "jitaPartsOrdered": "No",
      "notes": "Test vehicle 70: completed / collected with varied work status",
      "navisionDealerComments": "Test dataset row 70 for completed / collected",
      "pmbKeyNumber": "K070",
      "toyotaStatus": "Vehicle Yard Hold",
      "navisionSubLocationDescription": "Vehicle Yard Hold",
      "pdcLocation": "RFT",
      "pmbEnteredAt": "2026-06-28T08:15:00Z",
      "rftTransferredAt": "2026-07-03T08:15:00Z",
      "rftCollected": true,
      "completedVehicle": true,
      "rftCollectedAt": "2026-07-06T16:15:00Z",
      "rftCollectedBy": "Test Dispatch",
      "pdcRequiresHoist": true,
      "pdcCompleteHoist": true,
      "pdcCompleteHoistAt": "2026-07-01T08:15:00Z",
      "pdcCompleteHoistBy": "Test Tech",
      "pdcRequiresFitting": true,
      "pdcCompleteFitting": true,
      "pdcCompleteFittingAt": "2026-07-01T08:15:00Z",
      "pdcCompleteFittingBy": "Test Tech",
      "pdcRequiresParts": true,
      "pdcCompleteParts": true,
      "pdcCompletePartsAt": "2026-07-01T08:15:00Z",
      "pdcCompletePartsBy": "Test Tech",
      "pdcRequiresPitInspection": true,
      "pdcCompletePitInspection": true,
      "pdcCompletePitInspectionAt": "2026-07-01T08:15:00Z",
      "pdcCompletePitInspectionBy": "Test Tech",
      "pdcPartsReceived": true
    },
    {
      "source": "Test 75 vehicle dataset",
      "consultant": "RD",
      "stock": "TEST071",
      "batch": "BATCH0071",
      "order": "ORD00071",
      "salesOrder": "SO00071",
      "pdcJobcard": "JC00071",
      "client": "Outback Energy",
      "contact": "0400 000 071",
      "vehicle": "HiLux Rogue",
      "vin": "TESTVIN00000000071",
      "rego": "T00071",
      "prodMth": "Aug 2026",
      "productionMonth": "Aug 2026",
      "navisionKewdaleEta": "14/07/2026",
      "etaAtDealer": "14/07/2026",
      "jitaPartsOrdered": "No",
      "notes": "Test vehicle 71: completed / collected with varied work status",
      "navisionDealerComments": "Test dataset row 71 for completed / collected",
      "pmbKeyNumber": "K071",
      "toyotaStatus": "Vehicle Yard Hold",
      "navisionSubLocationDescription": "Vehicle Yard Hold",
      "pdcLocation": "RFT",
      "pmbEnteredAt": "2026-06-27T08:15:00Z",
      "rftTransferredAt": "2026-07-02T08:15:00Z",
      "rftCollected": true,
      "completedVehicle": true,
      "rftCollectedAt": "2026-07-05T16:15:00Z",
      "rftCollectedBy": "Test Dispatch",
      "pdcRequiresTint": true,
      "pdcCompleteTint": true,
      "pdcCompleteTintAt": "2026-06-30T08:15:00Z",
      "pdcCompleteTintBy": "Test Tech",
      "pdcRequiresFitting": true,
      "pdcCompleteFitting": true,
      "pdcCompleteFittingAt": "2026-06-30T08:15:00Z",
      "pdcCompleteFittingBy": "Test Tech",
      "pdcRequiresElectrical": true,
      "pdcCompleteElectrical": true,
      "pdcCompleteElectricalAt": "2026-06-30T08:15:00Z",
      "pdcCompleteElectricalBy": "Test Tech",
      "pdcRequiresParts": true,
      "pdcCompleteParts": true,
      "pdcCompletePartsAt": "2026-06-30T08:15:00Z",
      "pdcCompletePartsBy": "Test Tech",
      "pdcRequiresPitInspection": true,
      "pdcCompletePitInspection": true,
      "pdcCompletePitInspectionAt": "2026-06-30T08:15:00Z",
      "pdcCompletePitInspectionBy": "Test Tech",
      "pdcPartsReceived": true
    },
    {
      "source": "Test 75 vehicle dataset",
      "consultant": "CW",
      "stock": "TEST072",
      "batch": "BATCH0072",
      "order": "ORD00072",
      "salesOrder": "SO00072",
      "pdcJobcard": "JC00072",
      "client": "Fremantle Council",
      "contact": "0400 000 072",
      "vehicle": "Coaster Bus",
      "vin": "TESTVIN00000000072",
      "rego": "T00072",
      "prodMth": "Aug 2026",
      "productionMonth": "Aug 2026",
      "navisionKewdaleEta": "15/07/2026",
      "etaAtDealer": "15/07/2026",
      "jitaPartsOrdered": "Yes",
      "notes": "Test vehicle 72: completed / collected with varied work status",
      "navisionDealerComments": "Test dataset row 72 for completed / collected",
      "pmbKeyNumber": "K072",
      "toyotaStatus": "Vehicle Yard Hold",
      "navisionSubLocationDescription": "Vehicle Yard Hold",
      "pdcLocation": "RFT",
      "pmbEnteredAt": "2026-06-26T08:15:00Z",
      "rftTransferredAt": "2026-07-01T08:15:00Z",
      "rftCollected": true,
      "completedVehicle": true,
      "rftCollectedAt": "2026-07-04T16:15:00Z",
      "rftCollectedBy": "Test Dispatch",
      "pdcRequiresHoist": true,
      "pdcCompleteHoist": true,
      "pdcCompleteHoistAt": "2026-07-07T08:15:00Z",
      "pdcCompleteHoistBy": "Test Tech",
      "pdcRequiresFitting": true,
      "pdcCompleteFitting": true,
      "pdcCompleteFittingAt": "2026-07-07T08:15:00Z",
      "pdcCompleteFittingBy": "Test Tech",
      "pdcRequiresParts": true,
      "pdcCompleteParts": true,
      "pdcCompletePartsAt": "2026-07-07T08:15:00Z",
      "pdcCompletePartsBy": "Test Tech",
      "pdcRequiresPitInspection": true,
      "pdcCompletePitInspection": true,
      "pdcCompletePitInspectionAt": "2026-07-07T08:15:00Z",
      "pdcCompletePitInspectionBy": "Test Tech",
      "pdcPartsReceived": true
    },
    {
      "source": "Test 75 vehicle dataset",
      "consultant": "BG",
      "stock": "TEST073",
      "batch": "BATCH0073",
      "order": "ORD00073",
      "salesOrder": "SO00073",
      "pdcJobcard": "JC00073",
      "client": "Western Rescue",
      "contact": "0400 000 073",
      "vehicle": "LandCruiser 79",
      "vin": "TESTVIN00000000073",
      "rego": "T00073",
      "prodMth": "Aug 2026",
      "productionMonth": "Aug 2026",
      "navisionKewdaleEta": "16/07/2026",
      "etaAtDealer": "16/07/2026",
      "jitaPartsOrdered": "No",
      "notes": "Test vehicle 73: completed / collected with varied work status",
      "navisionDealerComments": "Test dataset row 73 for completed / collected",
      "pmbKeyNumber": "K073",
      "toyotaStatus": "Vehicle Yard Hold",
      "navisionSubLocationDescription": "Vehicle Yard Hold",
      "pdcLocation": "RFT",
      "pmbEnteredAt": "2026-06-25T08:15:00Z",
      "rftTransferredAt": "2026-06-30T08:15:00Z",
      "rftCollected": true,
      "completedVehicle": true,
      "rftCollectedAt": "2026-07-03T16:15:00Z",
      "rftCollectedBy": "Test Dispatch",
      "pdcRequiresTint": true,
      "pdcCompleteTint": true,
      "pdcCompleteTintAt": "2026-07-06T08:15:00Z",
      "pdcCompleteTintBy": "Test Tech",
      "pdcRequiresFitting": true,
      "pdcCompleteFitting": true,
      "pdcCompleteFittingAt": "2026-07-06T08:15:00Z",
      "pdcCompleteFittingBy": "Test Tech",
      "pdcRequiresElectrical": true,
      "pdcCompleteElectrical": true,
      "pdcCompleteElectricalAt": "2026-07-06T08:15:00Z",
      "pdcCompleteElectricalBy": "Test Tech",
      "pdcRequiresParts": true,
      "pdcCompleteParts": true,
      "pdcCompletePartsAt": "2026-07-06T08:15:00Z",
      "pdcCompletePartsBy": "Test Tech",
      "pdcRequiresPitInspection": true,
      "pdcCompletePitInspection": true,
      "pdcCompletePitInspectionAt": "2026-07-06T08:15:00Z",
      "pdcCompletePitInspectionBy": "Test Tech",
      "pdcPartsReceived": true
    },
    {
      "source": "Test 75 vehicle dataset",
      "consultant": "AM",
      "stock": "TEST074",
      "batch": "BATCH0074",
      "order": "ORD00074",
      "salesOrder": "SO00074",
      "pdcJobcard": "JC00074",
      "client": "Horizon Builders",
      "contact": "0400 000 074",
      "vehicle": "Prado VX",
      "vin": "TESTVIN00000000074",
      "rego": "T00074",
      "prodMth": "Aug 2026",
      "productionMonth": "Aug 2026",
      "navisionKewdaleEta": "17/07/2026",
      "etaAtDealer": "17/07/2026",
      "jitaPartsOrdered": "No",
      "notes": "Test vehicle 74: completed / collected with varied work status",
      "navisionDealerComments": "Test dataset row 74 for completed / collected",
      "pmbKeyNumber": "K074",
      "toyotaStatus": "Vehicle Yard Hold",
      "navisionSubLocationDescription": "Vehicle Yard Hold",
      "pdcLocation": "RFT",
      "pmbEnteredAt": "2026-06-24T08:15:00Z",
      "rftTransferredAt": "2026-06-29T08:15:00Z",
      "rftCollected": true,
      "completedVehicle": true,
      "rftCollectedAt": "2026-07-02T16:15:00Z",
      "rftCollectedBy": "Test Dispatch",
      "pdcRequiresHoist": true,
      "pdcCompleteHoist": true,
      "pdcCompleteHoistAt": "2026-07-05T08:15:00Z",
      "pdcCompleteHoistBy": "Test Tech",
      "pdcRequiresFitting": true,
      "pdcCompleteFitting": true,
      "pdcCompleteFittingAt": "2026-07-05T08:15:00Z",
      "pdcCompleteFittingBy": "Test Tech",
      "pdcRequiresParts": true,
      "pdcCompleteParts": true,
      "pdcCompletePartsAt": "2026-07-05T08:15:00Z",
      "pdcCompletePartsBy": "Test Tech",
      "pdcRequiresPitInspection": true,
      "pdcCompletePitInspection": true,
      "pdcCompletePitInspectionAt": "2026-07-05T08:15:00Z",
      "pdcCompletePitInspectionBy": "Test Tech",
      "pdcPartsReceived": true
    },
    {
      "source": "Test 75 vehicle dataset",
      "consultant": "JT",
      "stock": "TEST075",
      "batch": "BATCH0075",
      "order": "ORD00075",
      "salesOrder": "SO00075",
      "pdcJobcard": "JC00075",
      "client": "Kimberley Tours",
      "contact": "0400 000 075",
      "vehicle": "HiAce LWB",
      "vin": "TESTVIN00000000075",
      "rego": "T00075",
      "prodMth": "Aug 2026",
      "productionMonth": "Aug 2026",
      "navisionKewdaleEta": "18/07/2026",
      "etaAtDealer": "18/07/2026",
      "jitaPartsOrdered": "Yes",
      "notes": "Test vehicle 75: completed / collected with varied work status",
      "navisionDealerComments": "Test dataset row 75 for completed / collected",
      "pmbKeyNumber": "K075",
      "toyotaStatus": "Vehicle Yard Hold",
      "navisionSubLocationDescription": "Vehicle Yard Hold",
      "pdcLocation": "RFT",
      "pmbEnteredAt": "2026-06-23T08:15:00Z",
      "rftTransferredAt": "2026-06-28T08:15:00Z",
      "rftCollected": true,
      "completedVehicle": true,
      "rftCollectedAt": "2026-07-01T16:15:00Z",
      "rftCollectedBy": "Test Dispatch",
      "pdcRequiresTint": true,
      "pdcCompleteTint": true,
      "pdcCompleteTintAt": "2026-07-04T08:15:00Z",
      "pdcCompleteTintBy": "Test Tech",
      "pdcRequiresFitting": true,
      "pdcCompleteFitting": true,
      "pdcCompleteFittingAt": "2026-07-04T08:15:00Z",
      "pdcCompleteFittingBy": "Test Tech",
      "pdcRequiresElectrical": true,
      "pdcCompleteElectrical": true,
      "pdcCompleteElectricalAt": "2026-07-04T08:15:00Z",
      "pdcCompleteElectricalBy": "Test Tech",
      "pdcRequiresParts": true,
      "pdcCompleteParts": true,
      "pdcCompletePartsAt": "2026-07-04T08:15:00Z",
      "pdcCompletePartsBy": "Test Tech",
      "pdcRequiresPitInspection": true,
      "pdcCompletePitInspection": true,
      "pdcCompletePitInspectionAt": "2026-07-04T08:15:00Z",
      "pdcCompletePitInspectionBy": "Test Tech",
      "pdcPartsReceived": true
    }
  ]
};
