'use strict';
const assert = require('assert');
const fs = require('fs');
const { reconcileVehicleRows } = require('./pdc-email-vehicle-location-service.js');
const sql = fs.readFileSync('supabase/staging_only/20260826203000_428_collected_vehicle_authoritative_snapshot.sql','utf8');
const service = fs.readFileSync('pdc-email-vehicle-location-service.js','utf8');
const app = fs.readFileSync('app.js','utf8');
assert.match(sql,/8e214bde7a1fc8706452526d34abadada708696386bed0c3cb4602466c62ec19/);
assert.match(sql,/v\.lifecycle_state=''completed'' AND v\.rft_collected_at IS NOT NULL/);
assert.match(sql,/pdc_rft_transport_action_receipts_412 handover/);
assert.match(sql,/handover\.action=''collected''/);
assert.match(service,/visible_on_board !== false[\s\S]*Boolean\(row\.rft_collected_at\)/);
const completed={id:'00000000-0000-4000-8000-000000000428',permanent_vehicle_id:'PERM-428',stock_number:'HERMES-TEST-428',version:9,lifecycle_state:'completed',current_location:'Completed',visible_on_board:false,rft_collected_at:'2026-08-25T10:00:00Z'};
const hiddenActive={id:'00000000-0000-4000-8000-000000000429',permanent_vehicle_id:'PERM-429',stock_number:'HERMES-TEST-429',version:1,lifecycle_state:'active',current_location:'PMB',visible_on_board:false};
const result=reconcileVehicleRows([], [completed,hiddenActive], {authoritative:true});
assert.strictEqual(result.rows.length,1);
assert.strictEqual(result.rows[0].stock,'HERMES-TEST-428');
assert.strictEqual(result.rows[0].rftCollectedAt,'2026-08-25T10:00:00Z');
assert.strictEqual(result.rows[0].lifecycleState,'completed');
assert.match(app,/function isHermesSyntheticVehicle/);
assert.match(app,/if \(isHermesSyntheticVehicle\(vehicle\)\) return/);
assert.match(app,/vehicleCollectedFromRft\(vehicle\) && !isHermesSyntheticVehicle\(vehicle\)/);
console.log('receipt-backed collected vehicle survives authoritative reconciliation: PASS');
