'use strict';

const assert = require('assert');
const fs = require('fs');
const app = fs.readFileSync('app.js', 'utf8');
const planner = fs.readFileSync('workshop-planner.js', 'utf8');
const css = fs.readFileSync('styles.css', 'utf8');
const auditorCss = fs.readFileSync('ai-auditor.css', 'utf8');
const sql = fs.readFileSync('supabase/staging_only/088_vehicle_workshop_detail_page.sql', 'utf8');

assert(app.includes('role="tablist"') && app.includes('data-vehicle-detail-tab="details"') && app.includes('data-vehicle-detail-tab="work"'), 'Vehicle detail header must expose two accessible pages');
assert(app.includes('Vehicle details') && app.includes('Work & bookings'), 'Both vehicle-detail page names must be visible');
assert(app.includes('data-vehicle-workshop-booking-id'), 'Booked work rows must expose a selectable booking target');
assert(app.includes('openVehicleWorkshopBooking'), 'Booking selection must route through the dedicated planner-link handler');
assert(app.includes('app.pendingWorkshopBookingLink'), 'Planner deep link must retain exact booking, station and date through lazy route loading');
assert(planner.includes('pendingWorkshopBookingLink') && planner.includes('searchHighlightPlanId'), 'Planner render must consume the exact pending booking and highlight it');
assert(app.includes('Booking data unavailable') && app.includes('Not booked'), 'Every required line must have a truthful booking-time state');
assert(app.includes('Estimated hours') && app.includes('Estimate not set'), 'Every required line must have an explicit estimate state without guessing');
assert(app.includes('vehicleWorkshopLineDescription'), 'Every required line must render a non-empty description');
const selectedVehicleBody = app.match(/function selectedVehicle\([^]*?\r?\n}\r?\n\r?\nfunction saveVehicleEdits/)?.[0] || '';
assert(selectedVehicleBody.indexOf('if (canonicalMatches.length > 1)') < selectedVehicleBody.indexOf('const boardMatches'), 'Ambiguous raw canonical identity must fail closed before reconciliation');
assert(selectedVehicleBody.includes('if (boardVehicle) return boardVehicle;'), 'Vehicle detail must preserve the unique non-conflicting authoritative board snapshot and canonical UUID');
assert(selectedVehicleBody.indexOf("if (boardVehicle?.__emailVehicleIdentityConflict === true || boardVehicle?.__locationIdentityReadOnly === true)") < selectedVehicleBody.indexOf('if (boardVehicle) return boardVehicle;'), 'Identity conflicts must fail closed before authoritative board selection');
assert(selectedVehicleBody.includes("__emailVehicleIdentityConflict") && selectedVehicleBody.includes("__locationIdentityReadOnly"), 'Conflicting reconciled identity must fail closed');
const workshopGroupsBody = app.match(/function vehicleWorkshopGroups\([^]*?\r?\n}\r?\n\r?\nfunction vehicleWorkshopJobCardValue/)?.[0] || '';
assert(workshopGroupsBody.includes('pdcEmailOperationLines'), 'Vehicle Work & bookings must consume authenticated job-card operation lines');
assert(workshopGroupsBody.includes('operation_no'), 'Authenticated operation numbers must remain available to the detail renderer');
assert(workshopGroupsBody.includes('groups.get(stage).lines.push'), 'Authenticated operation lines must be placed into their canonical station group');
assert(css.includes('.vehicle-workshop-station') && css.includes('--station-colour'), 'Station groups must be colour coded through a shared station colour token');
assert(css.includes('.vehicle-detail-tabs') && css.includes('@media (max-width: 760px)'), 'Tabs and work rows must have responsive treatment');
const stationHtmlStart = app.indexOf('function vehicleWorkshopCompactLinesHtml');
const stationHtmlEnd = app.indexOf('function renderVehicleWorkshopWorkPage', stationHtmlStart);
const stationHtmlBody = stationHtmlStart >= 0 && stationHtmlEnd > stationHtmlStart ? app.slice(stationHtmlStart, stationHtmlEnd) : '';
assert(stationHtmlBody.includes('data-vehicle-workshop-hours-input'), 'Editable rows must expose a direct estimated-hours input');
assert(stationHtmlBody.includes('data-vehicle-workshop-hours-save'), 'Direct estimated-hours editing must have an explicit save action');
assert(stationHtmlBody.includes('data-vehicle-workshop-line-handle') && stationHtmlBody.includes('draggable="true"'), 'Visible operation numbers must be draggable Workshop bay handles');
assert(stationHtmlBody.includes('data-vehicle-workshop-schedule-next') && stationHtmlBody.includes('Schedule next available'), 'Every unbooked editable Workshop row must expose Schedule next available');
assert(stationHtmlBody.includes('vehicle-workshop-line-actions') && stationHtmlBody.includes('vehicle-workshop-line-booking'), 'Scheduling/edit controls and booking state must remain on each compact work row');
assert(stationHtmlBody.includes('<div class="vehicle-workshop-lines">') && !stationHtmlBody.includes('<table class="vehicle-workshop-job-card">'), 'Work & bookings must use compact rows, never the wide audit table');
assert(!stationHtmlBody.includes('<th scope="col">Department</th>') && !stationHtmlBody.includes('<th scope="col">Provenance</th>') && !stationHtmlBody.includes('<th scope="col">Parts dependency / status</th>') && !stationHtmlBody.includes('<th scope="col">Sublet provider</th>'), 'Operational detail must not expose audit-only columns');
assert(!/(^|\n)\.vehicle-workshop-job-card\s*\{/m.test(auditorCss), 'AI Auditor CSS must not globally override Vehicle Detail work rows');
assert(app.includes('saveVehicleWorkshopLineHours'), 'Direct estimated-hours changes must use a dedicated authoritative save handler');
const bulkHoursStart = app.indexOf('async function saveVehicleWorkshopLineHours');
const bulkHoursEnd = app.indexOf('async function scheduleVehicleWorkshopNextAvailable', bulkHoursStart);
const bulkHoursBody = bulkHoursStart >= 0 && bulkHoursEnd > bulkHoursStart ? app.slice(bulkHoursStart, bulkHoursEnd) : '';
assert(bulkHoursBody.includes("closest?.('.vehicle-workshop-line')") && bulkHoursBody.includes("row?.querySelector?.('[data-vehicle-workshop-hours-input]')"), 'Saving a row must resolve only the clicked row and its hours input');
assert(!bulkHoursBody.includes("querySelectorAll('.vehicle-workshop-line')") && !bulkHoursBody.includes('Promise.all'), 'A row Save must not validate or update unrelated populated rows');
assert(app.includes("addEventListener('dragstart', event => beginVehicleWorkshopLineDrag(event, handle))"), 'Operation handles must wire dragstart to the Planner handoff');
assert(app.includes('workshopScheduleVehicleNextAvailable(payload)'), 'Schedule next available must delegate to the established Workshop Planner authority');
assert(planner.includes('async function workshopScheduleVehicleNextAvailable'), 'Planner must own next-available slot selection and authoritative scheduling');
assert(planner.includes('etaConstraint.earliestDateKey') && planner.includes('workshopBestStageSlot'), 'Next-available scheduling must obey the ETA floor and operational bay/calendar rules');
const nextAvailableStart = planner.indexOf('async function workshopScheduleVehicleNextAvailable');
const nextAvailableEnd = planner.indexOf('async function scheduleWorkshopVehicle', nextAvailableStart);
const nextAvailableBody = nextAvailableStart >= 0 && nextAvailableEnd > nextAvailableStart ? planner.slice(nextAvailableStart, nextAvailableEnd) : '';
assert(nextAvailableBody.includes("await service.setScope({ stageCode: normalizedStage, dateFrom: slot.dateKey, dateTo: slot.dateKey })"), 'Next-available booking must switch the authoritative snapshot to the selected future date before mutation so the created chip is visible immediately');
assert(nextAvailableBody.indexOf('await service.setScope({ stageCode: normalizedStage, dateFrom: slot.dateKey') < nextAvailableBody.indexOf('return scheduleWorkshopVehicle({'), 'Future-date scope reconciliation must complete before booking creation');
assert(/\.vehicle-workshop-line\s*\{[^}]*grid-template-columns:[^;]*auto/i.test(css), 'Desktop work rows must reserve a compact final action column');
assert(/\.vehicle-workshop-line\s*>\s*span\s*\{[^}]*padding:\s*(?:[0-6](?:px)?\s+){1,3}[0-8]px/i.test(css), 'Vehicle workshop row cell padding must stay slim');

assert(/create or replace function public\.get_vehicle_workshop_detail\(p_vehicle_id uuid\)/i.test(sql), 'Migration must add one narrow viewer-readable vehicle workshop detail RPC');
assert(/perform public\.require_pdc_role\('viewer'\)/i.test(sql), 'Vehicle workshop detail RPC must enforce authenticated viewer authority');
assert(/from public\.vehicle_work_items/i.test(sql) && /from public\.workshop_bookings/i.test(sql), 'RPC must source canonical requirements and bookings');
assert(/default_duration_minutes/i.test(sql) && /scheduled_start_at/i.test(sql) && /bay_number/i.test(sql), 'RPC must return authoritative duration, booking time and bay');
assert(/revoke all on function public\.get_vehicle_workshop_detail\(uuid\) from public, anon/i.test(sql), 'Anonymous callers must not execute the detail RPC');
assert(!/['\"]customer_name['\"]|['\"]notes['\"]|wi\.notes/i.test(sql), 'Narrow workshop detail RPC must not leak customer or free-text notes');

console.log('Vehicle detail work-and-bookings contract passed');
