'use strict';
const assert = require('assert');
const fs = require('fs');
const crypto = require('crypto');
const raw = fs.readFileSync('supabase/staging_only/253_ai_auditor_typed_operation_control.sql','utf8').replace(/\r\n/g,'\n');
const sql = raw.toLowerCase();
function body(name, tag) { const m=sql.match(new RegExp(`create function public\\.${name}\\([\\s\\S]*?as \\$${tag}\\$([\\s\\S]*?)\\$${tag}\\$;`)); assert(m,`${name} missing`); return m[1]; }
function has(h, xs, label) { for (const x of xs) assert(h.includes(x),`${label}: ${x}`); }
const verify=body('pdc_auditor_verify_envelope_253','verify');
const bytes=body('pdc_auditor_signing_bytes_253','bytes');
const plan=body('plan_pdc_auditor_typed_instruction_253','plan');
const apply=body('apply_pdc_auditor_typed_plan_253','apply');
const undo=body('undo_last_pdc_auditor_typed_run_253','undo');

// Literal source vector generated by backend.pdc_auditor_telegram_runtime.gateway_signing_bytes.
const VECTOR_BYTES = 'pdc-auditor-envelope-253-v1\n'+
'gateway_instance_id:12:gw-staging-1\n'+
'delivery_uuid:36:11111111-2222-4333-8444-555555555555\n'+
'key_id:11:key-2026-08\n'+
'nonce:22:nonce-abcdefghijklmnop\n'+
'issued_at:27:2026-08-13T10:11:12.123456Z\n'+
'expires_at:27:2026-08-13T10:16:12.123456Z\n'+
'instruction_sha256:64:dbfbe4a5ab6d4f9342414f0c18dacc5d0ef7e0a4856201faaf9e0347f21f02ff\n'+
'selected_scope:129:{"plan_hash":"aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa","plan_id":"aaaaaaaa-bbbb-4ccc-8ddd-eeeeeeeeeeee"}\n'+
'telegram_evidence:288:{"bot_identity":"pdc-auditor-staging","instruction_sha256":"dbfbe4a5ab6d4f9342414f0c18dacc5d0ef7e0a4856201faaf9e0347f21f02ff","original_instruction":"Apply these corrections","telegram_chat_id":7828138290,"telegram_message_id":321,"telegram_sender_id":7828138290,"telegram_update_id":654}';
const VECTOR_HEX='7064632d61756469746f722d656e76656c6f70652d3235332d76310a676174657761795f696e7374616e63655f69643a31323a67772d73746167696e672d310a64656c69766572795f757569643a33363a31313131313131312d323232322d343333332d383434342d3535353535353535353535350a6b65795f69643a31313a6b65792d323032362d30380a6e6f6e63653a32323a6e6f6e63652d6162636465666768696a6b6c6d6e6f700a6973737565645f61743a32373a323032362d30382d31335431303a31313a31322e3132333435365a0a657870697265735f61743a32373a323032362d30382d31335431303a31363a31322e3132333435365a0a696e737472756374696f6e5f7368613235363a36343a646266626534613561623664346639333432343134663063313864616363356430656637653061343835363230316661616639653033343766323166303266660a73656c65637465645f73636f70653a3132393a7b22706c616e5f68617368223a2261616161616161616161616161616161616161616161616161616161616161616161616161616161616161616161616161616161616161616161616161616161222c22706c616e5f6964223a2261616161616161612d626262622d346363632d386464642d656565656565656565656565227d0a74656c656772616d5f65766964656e63653a3238383a7b22626f745f6964656e74697479223a227064632d61756469746f722d73746167696e67222c22696e737472756374696f6e5f736861323536223a2264626662653461356162366434663933343234313466306331386461636335643065663765306134383536323031666161663965303334376632316630326666222c226f726967696e616c5f696e737472756374696f6e223a224170706c7920746865736520636f7272656374696f6e73222c2274656c656772616d5f636861745f6964223a373832383133383239302c2274656c656772616d5f6d6573736167655f6964223a3332312c2274656c656772616d5f73656e6465725f6964223a373832383133383239302c2274656c656772616d5f7570646174655f6964223a3635347d';
const VECTOR_SIGNATURE='73c2c888f720edfc8d5142d2369df63aab54bb06e51b38cc91d7b1754afec745';
assert.strictEqual(Buffer.from(VECTOR_BYTES).toString('hex'),VECTOR_HEX);
assert.strictEqual(crypto.createHmac('sha256',Buffer.from('00112233445566778899aabbccddeeff00112233445566778899aabbccddeeff','hex')).update(Buffer.from(VECTOR_HEX,'hex')).digest('hex'),VECTOR_SIGNATURE);
has(bytes,["e'pdc-auditor-envelope-253-v1\\n'","array['gateway_instance_id','delivery_uuid','key_id','nonce','issued_at','expires_at','instruction_sha256','selected_scope','telegram_evidence']","octet_length(raw)","f||':'||octet_length(raw)::text||':'"],'exact signing bytes');
has(verify,["jsonb_typeof(p_envelope->'issued_at')<>'string'","(\\.\\d{1,6})?z$","expires-issued>interval '300 seconds'",'pdc_auditor_signing_bytes_253(p_envelope)','extensions.hmac(signing'],'runtime envelope');
has(verify,['pdc_auditor_telegram_deliveries_230',"'pdc_auditor_signed_deliveries_253'",'pdc_253_telegram_delivery_already_consumed',"'pdc-230-message:'","'pdc-230-update:'"],'global Telegram replay reservation');
assert(!verify.includes("p_envelope-'signature'"),'must not sign compact whole envelope');

// Planner contract: immutable candidates are server-expanded from bounded selector/desire.
has(plan,["array['action','apply_unambiguous','contract','desire','selector']","pdc-auditor-bounded-intent-253-v1","?| array['items','candidates','old_value','old_effective_value','proof','disposition']",'derived_items',"selector->>'category'='long_range_fuel_tank'","selector->>'category'='gvm_upgrade'",'pdc_253_clarification_required'],'bounded server intent');
has(plan,['pdc_auditor_normalized_operation_lines_253','pdc_253_exact_namespaced_ref_required'],'namespaced refs');
has(sql,["'source:'||e.operation_line_id::text","'auditor:'||e.adjustment_id::text"],'normalized namespace projection');
has(plan,['source_uid','operation_fingerprint','a.source_hash=b.source_hash','kit|left|right|front|rear|stage|qty|quantity|pair','source_uid_fingerprint_distinct_hash_exact_variant_228'],'228 duplicate proof');
assert(!plan.includes("jsonb_array_elements(p_selected_scope->'items')"),'caller item arrays forbidden');

// Apply is a separately signed exact immutable selection and exact confirmation instruction.
has(apply,["'pdc-auditor-apply-selection-253-v1'","<>'apply these corrections'",'pdc_253_exact_craig_apply_required'],'distinct apply confirmation');
assert(!apply.includes("p_gateway_envelope->'selected_scope'<>plan.selected_scope"),'apply must not reuse planner scope');
assert(!/operation_identifier::uuid|ref::uuid/.test(apply),'unqualified refs must never be UUID-cast');
has(apply,["i.operation_identifier like 'source:%'","i.operation_identifier like 'auditor:%'",'source_operation_identifiers'],'both origins');
assert(!apply.includes('where wi.vehicle_id=i.vehicle_id and wi.completed)'),'unrelated completed work must not blanket-block');
has(apply,['pdc_253_affected_completed_work_protected',"wi.work_key in(select distinct x"],'affected work protection');

// Logical snapshots omit inactive/tombstoned generated overlays and non-effective false work rows.
has(sql,["coalesce(e.job_card_number,'')=p_job_card and e.active","from public.vehicle_work_items wi where wi.vehicle_id=p_vehicle and (wi.required or wi.completed)"],'logical snapshot semantics');
has(undo,['pdc_253_strict_undo_scope_conflict','order by mutation_sequence desc','pdc_253_undo_before_state_not_restored',"correction_origin='ai_auditor_rolled_back'",'set undo_state=\'undone\''],'strict append-only undo');
assert(undo.indexOf('pdc_253_undo_before_state_not_restored')<undo.indexOf("set undo_state='undone'"));

// Realtime policy is human approved Administrator + exact UUID/email/dealer/environment only.
has(sql,['create policy pdc_auditor_workshop_revisions_admin_read_253','from public.pdc_user_roles r','join auth.users au','join public.pdc_auditor_user_dealer_scopes s',"r.account_status='approved'","r.role::text='administrator'","s.environment='staging' and s.active"],'administrator realtime RLS');
for (const denied of ['viewer','monitor','importer','operator','pdc_auditor_service_identities_225']) assert(!sql.includes(`r.role::text='${denied}'`) && !sql.includes(`role::text in ('${denied}'`),`${denied} must not be admitted`);

console.log('Migration 253 source contract passed: literal runtime envelope vector, bounded server intent, namespaces, exact Apply/Undo and Administrator-only RLS');
