const assert=require('node:assert/strict');
const fs=require('node:fs');
const vm=require('node:vm');
const handover=require('./pdc-vehicle-handover.js');
const at=h=>new Date(Date.UTC(2026,8,14,h));
const busy=[{start_at:at(7),end_at:at(9)}];
assert.equal(handover.fits(at(13),at(15),busy),false);
assert.equal(handover.fits(at(14),at(16),busy),true);
assert.equal(handover.fits(at(0),at(2),busy),true);
assert.equal(handover.fits(at(0),at(3),busy),false);
assert.equal(handover.fits(at(7),at(8),busy),false);
assert.equal(handover.fits(at(14),at(22),[...busy,{start_at:at(25),end_at:at(27)}]),false,'whole duration must fit before a later booking');
assert.equal(handover.fits(at(31),at(33),[{start_at:at(15),end_at:at(17)}]),true,'overnight counts toward elapsed buffer');
assert.equal(handover.fits(at(14),at(16),[{start_at:'invalid',end_at:at(9)}]),false);
const source=fs.readFileSync('workshop-planner.js','utf8');
const start=source.indexOf('function workshopFirstAvailableStartMinutes(');
const end=source.indexOf('\nfunction workshopFirstAvailableStartSlot(',start);
const context={window:{PDC_VEHICLE_HANDOVER:handover},WORKSHOP_PLANNER_CONFIG:{schedulingIncrementMinutes:15,dayLengthMinutes:600},normalizePmbStage:s=>s,workshopExactDurationHours:n=>n,workshopDateAtOffset:(_,m)=>new Date(+at(7)+m*60000),workshopNewBookingValidation:()=>({ok:true}),workshopHasConflict:c=>c.bay===2&&+new Date(c.startAt)<+at(15),workshopLoadAdminBlocks:()=>[],workshopAdminBlockConflict:()=>null,workshopEntryStart:c=>new Date(c.startAt),workshopEntryEnd:c=>new Date(+new Date(c.startAt)+c.hours*3600000)};
vm.createContext(context);vm.runInContext(source.slice(start,end),context);
assert.equal(context.workshopFirstAvailableStartMinutes('ELEC',1,'2026-09-14',2,[],0,busy),420,'next slot starts at 14:00 after 09:00 finish + five hours');
assert.equal(context.workshopFirstAvailableStartMinutes('ELEC',2,'2026-09-14',2,[],0,busy),480,'bay occupancy still applies');
assert.equal(context.workshopFirstAvailableStartMinutes('ELEC',1,'2026-09-14',2,[],0,[{start_at:at(7),end_at:at(17)}]),null,'continue to a later workday if buffer exceeds closing');
console.log('Cross-station five-hour buffer and actual slot search: PASS');
