'use strict';
const assert = require('assert');
const fs = require('fs');

const app = fs.readFileSync('app.js', 'utf8');
const css = fs.readFileSync('styles.css', 'utf8');
const start = app.indexOf('function partsQueueActionsHtml');
const end = app.indexOf('function bindPartsQueueActionButtons', start);
assert.ok(start >= 0 && end > start, 'Parts action renderer exists');
const actions = app.slice(start, end);
assert.match(actions, /class="small-button parts-ordered-button"[^>]+data-parts-ordered=/, 'Mark ordered has a dedicated class');
assert.doesNotMatch(actions, /class="[^"]*primary[^"]*"[^>]+data-parts-ordered=/, 'Mark ordered no longer inherits primary styling');
assert.match(actions, /const orderEtaReady = Boolean\(partsWorstEtaDate\(vehicle\)\);/, 'Mark ordered derives readiness from a valid Parts ETA date');
assert.match(actions, /disabled aria-disabled="true" title="Set Parts ETA before marking ordered"/, 'Mark ordered is disabled with a clear explanation when ETA is missing');
assert.match(css, /\.parts-ordered-button\[data-parts-ordered\]\s*\{[^}]*background:\s*#dcfce7;[^}]*color:\s*#14532d;/s, 'light-green accessible base style exists');
assert.match(css, /\.parts-ordered-button\[data-parts-ordered\]:hover:not\(:disabled\)/, 'hover state exists');
assert.match(css, /\.parts-ordered-button\[data-parts-ordered\]:focus-visible/, 'focus-visible state exists');
assert.match(css, /\.parts-ordered-button\[data-parts-ordered\]:disabled/, 'disabled state exists');
const orderedStart = app.indexOf('async function markVehiclePartsOrdered');
const orderedEnd = app.indexOf('async function markVehiclePartsComplete', orderedStart);
assert.ok(orderedStart >= 0 && orderedEnd > orderedStart, 'Mark ordered handler exists');
const orderedHandler = app.slice(orderedStart, orderedEnd);
assert.match(orderedHandler, /if \(!partsWorstEtaDate\(vehicle\)\)/, 'handler rejects a missing or invalid Parts ETA');
assert.match(orderedHandler, /if \(!partsWorstEtaDate\(sharedVehicle\)\)/, 'handler rechecks the authoritative shared ETA');
console.log('Parts Mark ordered dedicated presentation: PASS');
