'use strict';
const assert=require('assert'); const fs=require('fs');
const load=n=>fs.readFileSync(`supabase/staging_only/${n}`,'utf8').replace(/\r\n/g,'\n').toLowerCase();
const files={225:load('225_ai_auditor_telegram_plans.sql'),226:load('226_ai_auditor_atomic_apply_undo.sql'),227:load('227_ai_auditor_versioned_rules.sql'),228:load('228_proven_duplicate_source_evidence.sql'),229:load('229_auditor_realtime_publication.sql'),230:load('230_auditor_authorization_hardening.sql'),231:load('231_auditor_delivery_registry_reconciliation.sql')};
function all(n,need,label){for(const x of need)assert(files[n].includes(x),`${n} ${label}: ${x}`)}
function guarded(n,pre){all(n,["project_ref='cdsmnqxtyyoeoznmbidd'",'pdc_production_environment_sentinel',`version='${pre}'`,`version::integer>${pre}`,`version='${n}'`,`pdc_${n}_staging_or_ledger_mismatch`],'guard')}
for(const [n,p] of [[225,224],[226,225],[227,226],[228,227],[229,228],[230,229],[231,230]]) guarded(n,p);
all(225,['pdc_auditor_service_identities_225','pdc_auditor_telegram_instructions_225','pdc_auditor_plans_225','pdc_auditor_plan_items_225','pdc_auditor_review_queue_225','enable row level security','revoke all on table public.%i from public,anon,authenticated,service_role','before update or delete','pdc_auditor_telegram_actor_scope_225','service_role','review_only','operational_revision','plan_hash','item_count between 0 and 250','grant execute on function public.plan_pdc_auditor_telegram_instruction_225(text,text,jsonb,jsonb) to authenticated','legacy_acl'],'planning/ACL');
assert(!/grant execute on function public\.(review_pdc_auditor_operation_batch|apply_pdc_auditor_operation_batch|rollback_pdc_auditor_operation_run)/.test(files[225]),'225 restores generic mutation');
all(226,['pdc_auditor_telegram_runs_226','pdc_auditor_telegram_changes_226','pdc_auditor_telegram_apply_receipts_226','pdc_auditor_telegram_rollback_receipts_226','pdc_auditor_workshop_revisions','enable row level security','revoke all on table public.%i from public,anon,authenticated,service_role','preflight all proposed rows','for update','operational_revision_stale','vehicle_workshop_line_adjustments','vehicle_work_items','audit_events','telegram_plan_applied_226','telegram_run_rolled_back_226','grant execute on function public.apply_pdc_auditor_telegram_plan_226(uuid,text,jsonb) to authenticated'],'Apply/revision');
assert((files[226].match(/insert into public\.pdc_auditor_workshop_revisions/g)||[]).length===2,'226 must contain one Apply and one Undo revision insert');
all(227,['pdc_auditor_rule_families_227','pdc_auditor_rule_commands_227','pdc_auditor_rule_versions_227','pdc_auditor_rule_examples_227','predecessor_rule_version_id','supersedes_rule_version_id','canonical_request_sha256','exact_command_replay','before update or delete','enable row level security','revoke all on table public.%i from public,anon,authenticated,service_role','grant execute on function public.rule_pdc_auditor_telegram_227(text,jsonb,jsonb) to authenticated'],'immutable evidence/versioning');
all(228,['rename to pdc_auditor_plan_candidates_base_225','same immutable source uid and operation fingerprint','distinct source hashes','remaining_exclusions','quantity','manual','completed','revoke all on function public.pdc_auditor_plan_candidates_225(text,text,jsonb)'],'duplicate hardening');
all(229,['pg_publication_tables',"pubname='supabase_realtime'",'alter publication supabase_realtime add table public.vehicle_workshop_line_adjustments','alter publication supabase_realtime add table public.pdc_auditor_workshop_revisions','publication changes no rls grants'],'Realtime');
assert(!/grant\s/.test(files[229]),'229 must not alter authority grants');
all(230,['pdc_auditor_telegram_deliveries_230','unique(telegram_chat_id,telegram_message_id)','unique(bot_identity,telegram_update_id)','existing_cross_domain_delivery_conflict','before insert on public.pdc_auditor_telegram_instructions_225','before insert on public.pdc_auditor_rule_commands_227','enable row level security','revoke all on public.pdc_auditor_telegram_deliveries_230 from public,anon,authenticated,service_role','rename to pdc_auditor_telegram_actor_scope_base_225','pdc_230_telegram_administrator_required','rename to rule_pdc_auditor_telegram_base_227','pdc_230_rule_action_not_exposed','grant execute on function public.rule_pdc_auditor_telegram_227(text,jsonb,jsonb) to authenticated'],'authorization hardening');
all(231,['lock table public.pdc_auditor_telegram_instructions_225 in share row exclusive mode','lock table public.pdc_auditor_rule_commands_227 in share row exclusive mode','lock table public.pdc_auditor_telegram_deliveries_230 in share row exclusive mode','pdc_231_cross_domain_delivery_conflict','where not exists','exact bidirectional coverage and evidence equality','pdc_231_delivery_registry_coverage_mismatch','d.original_instruction<>o.original_instruction','d.original_instruction<>r.original_instruction'],'registry reconciliation');
for(const n of Object.keys(files)) assert(files[n].trim().endsWith('commit;'),`${n} not transactional`);
console.log('AI Auditor migrations 225-231 focused source contracts passed: guards, ACL/RLS, immutable evidence, Apply/revision, Realtime, hardening and reconciliation');
