'use strict';
const assert = require('assert');
const fs = require('fs');

const app = fs.readFileSync('app.js', 'utf8');
const actions = fs.readFileSync('vehicle-lifecycle-actions.js', 'utf8');
const remove = app.slice(app.indexOf('async function removeVehicle('), app.indexOf('function renderDetail('));
const detail = app.slice(app.indexOf('function renderDetail('), app.indexOf('function renderNavisionDetailSection('));

assert(remove.includes('vehicleLifecycleAdministratorActive()'), 'Delete must require Administrator role');
assert(remove.includes('vehicleLifecycleSharedModeActive()'), 'Delete must require shared lifecycle mode');
assert(remove.includes('return false; // Fail closed: destructive shared-mode actions never use localStorage.'), 'Delete must fail closed without a localStorage fallback');
assert(remove.includes('Stock Number: ${stockNumber}'), 'Confirmation must display exact Stock Number');
assert(remove.includes('Customer: ${customer}'), 'Confirmation must display customer');
assert(remove.includes('Vehicle UUID: ${vehicleUuid}'), 'Confirmation must display vehicle UUID');
assert(remove.includes('Type the exact Stock Number (${stockNumber}) to confirm:'), 'Delete must require typed Stock Number');
assert(remove.includes('stockConfirmation !== stockNumber'), 'Typed Stock Number must match exactly');
assert(remove.includes('window.__vehicleLifecycleActions.adminArchiveVehicle({'), 'Delete must use migration 205 archive RPC bridge');
assert(remove.includes('expectedVersion: ref.version'), 'Delete must send fresh expected version');
assert(remove.includes('resetTest'), 'Delete bridge must carry reset-test flag');
assert(remove.includes('await refreshVehicleLifecycleLocationsAndRender()'), 'Lifecycle action must refresh shared Email Vehicle locations and render');
assert(!remove.includes('removeVehiclesFromTracker'), 'Shared lifecycle delete must not fall back to browser-local destruction');
assert(!remove.toLowerCase().includes('permanently remove'), 'UI must not describe archive as permanent deletion');
assert(detail.includes('vehicleLifecycleAdministratorActive() && vehicleLifecycleSharedModeActive()'), 'Lifecycle controls must be hidden from non-admin users');
assert(detail.includes('>Delete Vehicle</button>'), 'Active detail must show Delete Vehicle');
assert(detail.includes('vehicleLifecycleStagingResetAllowed()'), 'Reset control must use staging guard');
assert(detail.includes('>Reset Staging Test Vehicle</button>'), 'Staging detail must offer reset control');
assert(actions.includes("'pdc_admin_archive_vehicle'"), 'Lifecycle bridge must call pdc_admin_archive_vehicle');
assert(actions.includes("'pdc_admin_reset_staging_test_vehicle'"), 'Lifecycle bridge must call the staging reset RPC');
console.log('Vehicle Detail shared Administrator delete/reset contracts passed');
