'use strict';
const assert = require('assert');
const fs = require('fs');

const app = fs.readFileSync('app.js', 'utf8');
const actions = fs.readFileSync('vehicle-lifecycle-actions.js', 'utf8');
const stagingConfig = fs.readFileSync('pdc-supabase-config.staging.js', 'utf8');
const remove = app.slice(app.indexOf('async function removeVehicle('), app.indexOf('function renderDetail('));
const detail = app.slice(app.indexOf('function renderDetail('), app.indexOf('function renderNavisionDetailSection('));
const allowed = app.slice(app.indexOf('function vehicleLocationActionAllowed('), app.indexOf('function renderSharedNavisionVisibilityState('));
const resetGuard = app.slice(app.indexOf('function vehicleLifecycleStagingResetAllowed('), app.indexOf('function vehicleLifecycleActionErrorMessage('));

assert(remove.includes('vehicleLifecycleAdministratorActive()'), 'Delete must require Administrator role');
assert(remove.includes('vehicleLifecycleSharedModeActive()'), 'Delete must require shared lifecycle mode');
assert(remove.includes('return false; // Fail closed: destructive shared-mode actions never use localStorage.'), 'Delete must fail closed without a localStorage fallback');
assert(remove.includes('Stock Number: ${stockNumber}'), 'Confirmation must display exact Stock Number');
assert(remove.includes('Customer: ${customer}'), 'Confirmation must display customer');
assert(remove.includes('Vehicle UUID: ${vehicleUuid}'), 'Confirmation must display vehicle UUID');
assert(remove.includes('Type the exact Stock Number (${stockNumber}) to confirm:'), 'Delete must require typed Stock Number');
assert(remove.includes('stockConfirmation !== stockNumber'), 'Typed Stock Number must match exactly');
assert(remove.includes('window.__vehicleLifecycleActions.adminArchiveVehicle({'), 'Delete must use migration 205 archive RPC bridge');
assert(remove.includes('expectedVersion: ref.version'), 'Delete must send fresh expected version');
assert(remove.includes('resetTest'), 'Delete bridge must carry reset-test flag');
assert(remove.includes('await refreshVehicleLifecycleLocationsAndRender()'), 'Lifecycle action must refresh shared Email Vehicle locations and render');
assert(!remove.includes('removeVehiclesFromTracker'), 'Shared lifecycle delete must not fall back to browser-local destruction');
assert(!remove.toLowerCase().includes('permanently remove'), 'UI must not describe archive as permanent deletion');
assert(detail.includes('vehicleLifecycleAdministratorActive() && vehicleLifecycleSharedModeActive()'), 'Lifecycle controls must be hidden from non-admin users');
assert(detail.includes('>Delete Vehicle</button>'), 'Active detail must show Delete Vehicle');
assert(detail.includes('vehicleLifecycleStagingResetAllowed()'), 'Reset control must use staging guard');
assert(detail.includes('>Reset Staging Test Vehicle</button>'), 'Staging detail must offer reset control');
assert(resetGuard.includes('vehicleLifecycleResolverRollbackEnabled(config, location)'), 'Reset guard must delegate to the staging-only config contract');
assert(stagingConfig.includes("origin: 'https://btnew.github.io'"), 'Staging config must require the approved Pages origin');
assert(stagingConfig.includes("'/pdc-control-board-staging/'"), 'Staging config must require the approved Pages root path');
assert(stagingConfig.includes("'/pdc-control-board-staging/index.html'"), 'Staging config must permit only the approved explicit index path');
assert(actions.includes("'pdc_admin_archive_vehicle'"), 'Lifecycle bridge must call pdc_admin_archive_vehicle');
assert(actions.includes("'pdc_admin_reset_staging_test_vehicle'"), 'Lifecycle bridge must call the staging reset RPC');
assert(allowed.includes("operation === 'delete'"), 'Read-only canonical rows must have an explicit Delete authority path');
assert(allowed.includes('vehicleLifecycleAdministratorActive()'), 'Read-only canonical Delete must require Administrator authority');
assert(allowed.includes("typeof window.__vehicleLifecycleActions?.adminArchiveVehicle === 'function'"), 'Read-only canonical Delete must require the current archive bridge');
assert(!allowed.includes('vehicleRequiresCanonicalSharedDelete'), 'Read-only Delete must not call the retired helper');
assert(!allowed.includes('markVehicleDeleted'), 'Read-only Delete must not require the retired bridge');
assert(app.includes("onStatus: status => { if (status === 'SUBSCRIBED') onChange({ reconnect: true }); }"), 'Email Vehicle Realtime must reconcile authoritatively on subscribe/reconnect');
console.log('Vehicle Detail shared Administrator delete/reset contracts passed');
