'use strict';
const assert=require('assert');const fs=require('fs');
const sql=fs.readFileSync('supabase/staging_only/20260826204000_429_rft_email_intercept_receipts.sql','utf8');
const acceptance=fs.readFileSync('supabase/staging_only/20260826205000_430_admin_email_intercept_acceptance.sql','utf8');
const storageRepair=fs.readFileSync('supabase/staging_only/20260826210000_431_intercept_storage_security_definer_predicate.sql','utf8');
for(const marker of ['pdc_rft_transport_email_intercept_claims_429','pdc_rft_transport_email_intercept_receipts_429','claim_pdc_rft_transport_email_intercept_429','ack_pdc_rft_transport_email_intercept_429','pdc_rft_transport_interceptor_read_429','pmbcontroller@gmail.com','69846ef4-a74c-4569-9e35-376cf0837888','delivery_enabled','HERMES-TEST-%','intercepted','payload_sha256','mime_sha256','attachment_sha256','artifact_sha256'])assert.ok(sql.includes(marker),marker);
assert.match(sql,/REVOKE ALL ON TABLE public\.pdc_rft_transport_email_intercept_claims_429,public\.pdc_rft_transport_email_intercept_receipts_429 FROM public,anon,authenticated,service_role/);
assert.match(sql,/o\.delivery_status='pending' AND o\.sent_at IS NULL AND o\.delivered_at IS NULL/);
assert.match(sql,/NOT coalesce\(\(x\.payload->>'delivery_enabled'\)::boolean,false\)/);
assert.match(sql,/monitored_mailboxes.*m\.active.*outbound_email_enabled/s);
assert.match(sql,/pdc_monitor_stage_activation_writers.*w\.active.*w\.revoked_at IS NULL/s);
assert.match(sql,/pdc_rft_transport_email_intercept_receipts_429_append_only/);
assert.match(sql,/storage\.objects FOR SELECT TO authenticated/);
assert.match(sql,/intercept_receipt_id/);
assert.match(acceptance,/claim_pdc_rft_transport_email_intercept_acceptance_430/);
assert.match(acceptance,/ack_pdc_rft_transport_email_intercept_acceptance_430/);
assert.match(acceptance,/557dba7f-fd70-4b9e-aa7b-b83b717682a7/);
assert.match(acceptance,/administrator2@staging\.pdc-workshop\.example\.com/);
assert.match(acceptance,/No real recipient, outbound provider, real vehicle, Production target/);
assert.match(storageRepair,/pdc_rft_transport_intercept_object_allowed_431/);
assert.match(storageRepair,/SECURITY DEFINER/);
assert.match(storageRepair,/DROP POLICY pdc_rft_transport_interceptor_read_429/);
assert.match(storageRepair,/real and Production objects remain inaccessible/);
console.log('sealed RFT salesperson email interception contract passed');
