'use strict';
const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('fs'),vm=require('vm');
const source=fs.readFileSync('app.js','utf8');
function extract(name){const start=source.search(new RegExp('(?:async )?function '+name+'\\('));assert(start>=0);const rest=source.slice(start);const end=rest.slice(1).search(/\n(?:async )?function /);return end<0?rest:rest.slice(0,end+1);}
function setup(){const records=[{id:'one',name:'Provider One',email:'one@example.com',version:7,active:true},{id:'two',name:'Provider Two',email:'two@example.com',version:3,active:true}];let vehicle={__emailVehicleServerAuthoritative:true,__subletProviderId:'one',pmbSubletProvider:'Old name'};const alerts=[],calls=[],nodes={};const c={loadSubletProviderRecords:()=>records,cleanNavisionText:s=>String(s||'').trim(),pmbBaySubletProvider:v=>v.pmbSubletProvider||'',subletVehicleByKey:()=>vehicle,displayStockNumber:()=> '123',vehicleEmailLines:()=>['Vehicle: Test'],vehicleJobcardNumber:()=> 'JC123',plainDateValue:s=>s||'',window:{location:{href:''},alert:s=>alerts.push(s)},$:s=>nodes[s],workshopTechnicianAdminCanMutate:()=>true,initWorkshopReferenceDataServiceIfAvailable:()=>({editSubletProvider:async(...a)=>{calls.push(a);return {ok:true}}}),renderAdminLists:()=>calls.push('render')};vm.createContext(c);for(const name of ['subletProviderEmailValid','subletProviderContact','draftSubletProviderEmail','fillSubletCreateProviderEmail','saveSubletProviderEmail'])vm.runInContext(extract(name),c);return {c,records,vehicle,alerts,calls,nodes};}
test('draft uses canonical provider name/email and opens only a reviewable mailto',()=>{const {c}=setup();c.draftSubletProviderEmail('booking');const url=new URL(c.window.location.href);assert.equal(decodeURIComponent(url.pathname),'one@example.com');assert.match(url.searchParams.get('body'),/^Hello Provider One,/);assert.equal(url.searchParams.get('subject'),'Sublet booking - 123');});
test('booking recipient override is preserved; missing and malformed addresses do not open drafts',()=>{const {c,vehicle,records,alerts}=setup();vehicle.pmbSubletProviderEmail='specific@example.com';c.draftSubletProviderEmail();assert(c.window.location.href.startsWith('mailto:specific%40example.com'));vehicle.pmbSubletProviderEmail='';records[0].email='';c.window.location.href='';c.draftSubletProviderEmail();assert.equal(c.window.location.href,'');records[0].email='one@example.com\nBcc: other@example.com';c.draftSubletProviderEmail();assert.equal(c.window.location.href,'');assert.equal(alerts.length,2);});
test('legacy match must be unique and active; canonical identity never falls back to another matching name',()=>{const {c,vehicle,records}=setup();delete vehicle.__subletProviderId;vehicle.pmbSubletProvider='Provider Two';assert.equal(c.subletProviderContact(vehicle).email,'two@example.com');records.push({...records[1],id:'duplicate'});assert.equal(c.subletProviderContact(vehicle).email,'');vehicle.__subletProviderId='missing';assert.equal(c.subletProviderContact(vehicle).email,'');});
test('provider selection replaces the previous email including blank or unassigned providers',()=>{const {c,nodes,records}=setup();nodes['#sublet-create-provider']={value:'one'};nodes['#sublet-create-provider-email']={value:'old@example.com'};c.fillSubletCreateProviderEmail();assert.equal(nodes['#sublet-create-provider-email'].value,'one@example.com');records[1].email=null;nodes['#sublet-create-provider'].value='two';c.fillSubletCreateProviderEmail();assert.equal(nodes['#sublet-create-provider-email'].value,'');nodes['#sublet-create-provider'].value='';c.fillSubletCreateProviderEmail();assert.equal(nodes['#sublet-create-provider-email'].value,'');});
test('save uses displayed provider version and only email; permits clearing and blocks invalid/non-admin writes',async()=>{const {c,calls}=setup();const input={value:' new@example.com ',reportValidity:()=>true};const button={dataset:{saveProviderEmail:'one',providerVersion:'7'},closest:()=>({querySelector:()=>input})};assert.equal(await c.saveSubletProviderEmail(button),true);assert.equal(JSON.stringify(calls[0]),JSON.stringify(['one',7,{email:'new@example.com'}]));calls.length=0;input.value='';await c.saveSubletProviderEmail(button);assert.equal(calls[0][2].email,'');calls.length=0;input.value='invalid';assert.equal(await c.saveSubletProviderEmail(button),false);assert.equal(calls.length,0);c.workshopTechnicianAdminCanMutate=()=>false;input.value='new@example.com';await c.saveSubletProviderEmail(button);assert.equal(calls.length,0);});
test('conflict or network error never reports a successful save and releases the button',async()=>{const {c,calls}=setup();const button={dataset:{saveProviderEmail:'one',providerVersion:'7'},closest:()=>({querySelector:()=>({value:'new@example.com',reportValidity:()=>true})})};c.initWorkshopReferenceDataServiceIfAvailable=()=>({editSubletProvider:async()=>({ok:false,error:'version_conflict'})});assert.equal(await c.saveSubletProviderEmail(button),false);assert.equal(button.disabled,false);assert.equal(calls.length,0);c.initWorkshopReferenceDataServiceIfAvailable=()=>({editSubletProvider:async()=>{throw Error('offline')}});assert.equal(await c.saveSubletProviderEmail(button),false);assert.equal(button.disabled,false);});
