'use strict';
const {test}=require('node:test');
const assert=require('node:assert/strict');
const fs=require('node:fs');
const vm=require('node:vm');
const api=require('./pdc-new-vehicles.js');
function fixture(){return {vehicle_id:'00000000-0000-4000-8000-000000000001',vehicle_version:3,stock_number:'TEST-NEW',status:'pending',snapshot_hash:'a'.repeat(64),operations:[
 {line_identity:'source:00000000-0000-4000-8000-000000000002',source_line_id:'00000000-0000-4000-8000-000000000002',description:'Test kit',stage_code:'UNALLOCATED_MAPPING_REVIEW',estimated_hours:0.5,completed:false,active:true},
 {line_identity:'source:00000000-0000-4000-8000-000000000003',source_line_id:'00000000-0000-4000-8000-000000000003',description:'Test light',stage_code:'ELECTRICAL',estimated_hours:1.25,completed:false,active:true}
]};}
function choices(row){return {[row.operations[0].line_identity]:'FITTING'};}
test('review does not guess a station; approved source proposals are preselected',()=>{const row=fixture();assert.deepEqual(api.assignmentsFor(row).map(x=>x.stage_code),['','ELECTRICAL']);assert.deepEqual(api.problems(row),['Choose a station for every operation.']);});
test('all positive-hour lines are assigned without source mutation',()=>{const row=fixture(),before=JSON.stringify(row);assert.deepEqual(api.problems(row,choices(row)),[]);assert.equal(JSON.stringify(row),before);assert.equal(row.operations[0].estimated_hours,0.5);});
test('operation tiles can move between any supported station, not just Review',()=>{const row=fixture();for(const [station] of api.STATIONS){const choice={...choices(row),[row.operations[1].line_identity]:station};assert.equal(api.assignmentsFor(row,choice)[1].stage_code,station);assert.equal(api.problems(row,choice).length,0);}assert.match(api.problems(row,{...choices(row),[row.operations[1].line_identity]:'ADMIN'}).join(' '),/station/);});
test('station totals use only the actual assigned source lines',()=>{const row=fixture();const groups=api.stationGroups(row,choices(row));assert.equal(groups.find(x=>x.code==='FITTING').hours,0.5);assert.equal(groups.find(x=>x.code==='ELECTRICAL').hours,1.25);assert.equal(groups.find(x=>x.code==='HOIST').lines.length,0);});
test('unknown hours, completed lines, duplicate identity and missing job card stay blocked',()=>{let row=fixture();row.operations[0].estimated_hours=null;assert.match(api.problems(row,choices(row)).join(' '),/hours/);assert.equal(api.stationGroups(row,choices(row)).find(x=>x.code==='FITTING').hours,null);row=fixture();row.operations[0].completed=true;assert.match(api.problems(row,choices(row)).join(' '),/completed/);row=fixture();row.operations.push({...row.operations[0]});assert.match(api.problems(row,choices(row)).join(' '),/Duplicate/);assert.ok(api.problems(null).length);});
test('approval verification checks every saved station, identity, hours, description and unchecked state',()=>{const row=fixture(),choice=choices(row);const result={ok:true,data:{vehicle_id:row.vehicle_id,visible_on_board:true,bookings_created:0,operations:row.operations.map((l,i)=>({...l,stage_code:i?'ELECTRICAL':'FITTING'}))}};assert.equal(api.verifyApproval(result,row,choice),true);for(const patch of [{completed:true},{estimated_hours:1},{source_line_id:'wrong'},{description:'rewritten'},{stage_code:'TINT'}]){const bad=structuredClone(result);Object.assign(bad.data.operations[0],patch);assert.equal(api.verifyApproval(bad,row,choice),false);}assert.equal(api.verifyApproval({...result,data:{...result.data,bookings_created:1}},row,choice),false);});
test('new module compiles; boot loads assets, navigation moves existing buttons without changing authority',()=>{const js=fs.readFileSync('pdc-new-vehicles.js','utf8');new vm.Script(js);const boot=fs.readFileSync('canonical-entry.js','utf8');assert.match(boot,/pdc-new-vehicles\.js\?v=/);assert.match(boot,/pdc-new-vehicles\.css\?v=/);assert.match(boot,/requestedIntake = !phone && location.hash === '#\/newvehicles'/);assert.match(boot,/intakeScript.onload/);assert.match(js,/adminMenu\.appendChild\(button\)/);assert.doesNotMatch(js,/localStorage|service_role|\.from\(['"]vehicles/);assert.match(js,/approve_pdc_new_vehicle_review/);assert.match(js,/Promise\.allSettled\(\[refreshEmailVehicleLocations\(\),loadSharedNavisionVisibleRows\(\)\]/);});
test('user-controlled source text is escaped in cards and controls',()=>{assert.equal(api.esc('<img onerror="x">&'), '&lt;img onerror=&quot;x&quot;&gt;&amp;');});
