'use strict';
const assert = require('assert');
const fs = require('fs');
const planner = fs.readFileSync('workshop-planner.js', 'utf8');
const css = fs.readFileSync('workshop-planner.css', 'utf8');
const index = fs.readFileSync('index.html', 'utf8');
const start = planner.indexOf('function workshopEnsureDedicatedShell');
const end = planner.indexOf('\nfunction workshopSelectedDateBookingCount', start);
assert.ok(start >= 0 && end > start, 'dedicated planner shell function exists');
const shell = planner.slice(start, end);
assert.match(shell, /data-workshop-station-content/);
assert.doesNotMatch(shell, /Back to Control Board|data-workshop-back-control/);
assert.doesNotMatch(shell, /workshop-station-shell-header|data-workshop-station-title/);
assert.doesNotMatch(shell, /workshop-station-tabs|data-workshop-open-stage|workshopDedicatedStageTabsHtml/);
assert.doesNotMatch(planner, /function workshopDedicatedStageTabsHtml/);
assert.match(css, /\.workshop-planner-dedicated\s*\{\s*grid-template-rows:\s*minmax\(0, 1fr\)/);
assert.doesNotMatch(css, /\.workshop-back-control|\.workshop-station-tabs/);
assert.match(index, /workshop-planner\.css\?v=2026\.08\.30\.771-admin-block-continuations/);
console.log('Dedicated Workshop planner opens directly on its schedule: PASS');
