'use strict';
const assert=require('assert');
const fs=require('fs');
const path=require('path');
const sql=fs.readFileSync(path.join(__dirname,'supabase','staging_only','100_workshop_future_planning_without_parts_override.sql'),'utf8');
assert.match(sql,/create or replace function public\.schedule_vehicle_work/i);
assert.match(sql,/workshop_candidate_schedule_gate\(p_vehicle_id,v_code,p_scheduled_start_at\)/i);
assert.match(sql,/workshop_create_booking\(/i);
const schedule=sql.match(/create or replace function public\.schedule_vehicle_work[\s\S]*?end \$\$;/i)?.[0]||'';
assert.ok(schedule,'schedule function missing');
assert.doesNotMatch(schedule,/workshop_parts_overrides/i,'future planning must not create a Parts override');
assert.doesNotMatch(schedule,/require_pdc_role\('administrator'\)/i,'future planning must remain available to Controller');
assert.match(schedule,/parts_reserved',false/i,'response must state that Parts were not reserved');
assert.match(sql,/__future_planning_does_not_reserve_parts__/i,'atomic legacy inner call must bypass only its obsolete planning gate');
assert.match(sql,/create or replace function public\.cascade_workshop_schedule/i);
assert.match(sql,/grant execute[\s\S]*cascade_workshop_schedule[\s\S]*to authenticated/i);
assert.match(sql,/revoke all[\s\S]*cascade_workshop_schedule[\s\S]*from public,anon,authenticated/i);
assert.doesNotMatch(sql,/create or replace function public\.start_workshop_work/i,'physical Start authority must remain unchanged');
const planner=fs.readFileSync(path.join(__dirname,'workshop-planner.js'),'utf8');
assert.match(planner,/workshopSchedulableBayNumbers/);
assert.match(planner,/workshopBayAvailabilityStatus\(normalizedStage, bay\) === 'active'/);
console.log('PASS migration 100 future-planning and active-bay authority contract');
