'use strict';
const assert = require('assert');
const fs = require('fs');
const vm = require('vm');
const planner = fs.readFileSync('workshop-planner.js', 'utf8');
const app = fs.readFileSync('app.js', 'utf8');
const css = fs.readFileSync('styles.css', 'utf8');
assert.doesNotMatch(planner, /Configured hours \$\{workshopTimeLabelFromMinutes/);
assert.doesNotMatch(planner, /Long jobs carry into the next configured workday/);
assert.doesNotMatch(planner, /overlapping bay bookings are blocked/);
const start = app.indexOf('function vehicleRftTransportBooked');
const end = app.indexOf('\nfunction vehicleCollectedFromRft', start);
const context = {};
vm.createContext(context);
vm.runInContext(`${app.slice(start, end)}\nthis.label=rftTransportEmailStatusLabel;`, context);
assert.strictEqual(context.label({}), '');
assert.strictEqual(context.label({ rftTransportBookedAt: '2026-08-26T00:00:00Z' }), 'Mandatory salesperson email queued');
assert.strictEqual(context.label({ rftTransportBookedAt: '2026-08-26T00:00:00Z', rftTransportOutbox: { intercept_receipt_id: 'x' } }), 'Mandatory salesperson email captured in staging');
assert.strictEqual(context.label({ rftTransportOutbox: { delivery_status: 'sent' } }), 'Mandatory salesperson email sent');
assert.match(app, /Booked on trucking website/);
assert.match(app, /data-rft-collected-key/);
assert.match(app, /rftTransportEmailStatusLabel\(vehicle\)/);
assert.match(css, /\.rft-email-status/);
console.log('Planner compact header and RFT email status: PASS');
