'use strict';
const {test}=require('node:test');const assert=require('node:assert/strict');const fs=require('node:fs');const {createFixture}=require('./qa/dashboard-render-fixture.cjs');const {createNavisionBackendService,NAVISION_STAGING_PROJECT_REF}=require('./navision-backend-service.js');
function fixture(){const f=createFixture({vehicleCount:0});f.loadHelper('navision-vin.js');return f;}
const exportText='Order\tBatch\tCOSI\tDealer\tSalesperson\tModel Description\tETA At Kewdale Yard\tWMI\tVDS Number\tFrame\n000123\t\tYes\t037047\tBG 19751217\tHiLux\t15/11/2026\tMR0\tREBHVX\t00541949\n000124\t13000002\tYes\t001234\tBG\tHiAce\t16/11/2026\t\t\t\n000125\t\tYes\t002345\tBG\tPrado\t17/11/2026\t\t\t\n000126\t13000004\tYes\t090000\tBG\tCorolla\t\t\t\t';
test('Broome and Pilbara profiles retain stockless Toyota identity and original evidence without affecting legacy parsing',()=>{const f=fixture();for(const profile of ['broome','pilbara']){const parsed=f.context.parseNavisionInput(exportText,{uploadProfile:profile});assert.equal(parsed.vehicles.length,4);assert.equal(parsed.rejectedRows.length,0);assert.equal(parsed.vehicles[0].id,'TOYOTA-ORDER-000123');assert.equal(parsed.vehicles[0].stock,'');assert.equal(parsed.vehicles[0].order,'000123');assert.equal(parsed.vehicles[0].cosi,'Yes');assert.equal(parsed.vehicles[0].vin,'MR0REBHVX00541949');assert.equal(parsed.vehicles[0].navisionRawEvidence.columns.find(c=>c.header==='Dealer').value,'037047');}assert.equal(f.context.parseNavisionInput(exportText).rejectedRows.length,2);});
test('column position does not change Toyota orders or dealer partitioning',()=>{const f=fixture();const rearranged='COSI\tDealer\tModel Description\tBatch\tOrder\tSalesperson\nYes\t014450\tHiLux\t\t000001\tSP';const parsed=f.context.parseNavisionInput(rearranged,{uploadProfile:'pilbara'});assert.equal(parsed.vehicles[0].order,'000001');assert.equal(parsed.vehicles[0].dealer_code,'014450');assert.equal(parsed.vehicles[0].id,'TOYOTA-ORDER-000001');});
test('each profile calls one scoped preview and one atomic apply with exact hashes and revision',async()=>{for(const profile of ['broome','pilbara']){const calls=[];const service=createNavisionBackendService({projectRef:NAVISION_STAGING_PROJECT_REF,getAccessToken:()=> 'fixture',client:{rpc:async(token,name,params)=>{calls.push({name,params});return {ok:true,status:200,body:{ok:true}};}}});const rows=[{id:'test'}],metadata={dealerCode:profile,sourceName:'example.tsv'};await service.preview(rows,metadata);await service.approveInitialScope(rows,metadata);const p={data:{source_hash:'source',preview_hash:'preview',base_revision:5,counts:{total:1},blocking:false}};await service.apply(rows,p,{...metadata,confirmed:true,idempotencyKey:'same-request'});assert.deepEqual(calls.map(c=>c.name),['preview_navision_upload_profile','approve_navision_upload_profile','apply_navision_upload_profile']);for(const c of calls){assert.equal(c.params.p_profile,profile);assert.equal(c.params.p_rows,rows);}assert.equal(calls[2].params.p_preview_hash,'preview');assert.equal(calls[2].params.p_expected_revision,5);assert.equal((await service.apply(rows,p,metadata)).error,'explicit_confirmation_required');}});
test('profile preflight checks only included dealers, and still rejects duplicates',()=>{const f=fixture();const rows=f.context.parseNavisionInput(exportText,{uploadProfile:'broome'}).vehicles;assert.equal(f.context.navisionClientPreflight(rows,'broome').blocking,false);assert.equal(f.context.navisionClientPreflight(rows,'pilbara').blocking,false);rows[2].order=rows[1].order;assert.equal(f.context.navisionClientPreflight(rows,'broome').blocking,true);});
test('PMB tabs replace dealer picker and cancel previews when switching',()=>{const html=fs.readFileSync('index.html','utf8'),app=fs.readFileSync('app.js','utf8');assert.match(html,/role="tab"[^>]*data-navision-profile="broome"/);assert.match(html,/role="tab"[^>]*data-navision-profile="pilbara"/);assert.match(html,/id="navision-dealer-code" hidden/);assert.doesNotMatch(html,/<option value="combined"/);assert.match(app,/clearNavisionImport\(\);\$\('#navision-dealer-code'\).value=profile/);assert.match(app,/if\(app.navisionPreviewInFlight\|\|app.navisionSharedApplyInFlight\)return/);});
test('sales table has no fixed vertical height and retains horizontal column resizing',()=>{const css=fs.readFileSync('sales/sales.css','utf8');assert.match(css,/\.tracker-panel>\.table-wrap\{max-height:none;overflow-x:auto;overflow-y:visible/);assert.match(fs.readFileSync('sales/index.html','utf8'),/id="sales-reset-widths"/);});
