'use strict';
const fs=require('fs'); const assert=require('assert');
const app=fs.readFileSync('app.js','utf8'); const html=fs.readFileSync('index.html','utf8'); const stagingHtml=fs.readFileSync('staging.html','utf8');
const service=fs.readFileSync('navision-backend-service.js','utf8'); const sql=fs.readFileSync('supabase/migrations/038_combined_staging_dealer_scope_eta_planning.sql','utf8');
const start=app.indexOf('async function importNavisionVehicles()'); const end=app.indexOf('\nasync function applySharedNavisionImport()',start); const previewFn=app.slice(start,end);
const applyEnd=app.indexOf('\nfunction ',end+2); const applyFn=app.slice(end,applyEnd);
let n=0; const ok=(v,m)=>{assert.ok(v,m);n++;};
ok(!html.includes('Daily Navision import · shared backend')&&!html.includes('id="navision-dealer-code"'),'production shell does not expose the staging-only shared flow');
ok(html.includes('id="navision-remove-missing"')&&html.includes('Import vehicle updates'),'production shell retains its browser-local upload flow');
ok(!html.includes('navision-backend-service.js'),'production shell does not load the staging-only service');
ok(html.includes('Export current local Navision data'),'recovery export retained');
ok(stagingHtml.includes('Daily Navision import · shared backend')&&stagingHtml.includes('Pilbara Toyota · 14450')&&stagingHtml.includes('Broome Toyota · 37047'),'deployed staging shell carries the same scoped shared UI');
ok(stagingHtml.includes('id="export-local-navision"')&&stagingHtml.includes('id="apply-navision-shared"')&&!stagingHtml.includes('id="navision-remove-missing"'),'deployed staging shell retains recovery export and removes local retirement apply');
ok(previewFn.includes('.preview(rows, metadata)'),'normal preview uses shared service');
ok(previewFn.includes("if (!$('#navision-dealer-code')) return importNavisionVehiclesLocal(text)"),'non-staging shell retains the browser-local import path');
ok(app.includes('vehicle.navisionRawEvidence = rawEvidence')&&app.includes('columns: rawHeaders.map'),'accepted shared rows retain every parsed source heading and value');
ok(app.includes('parsed.rejectedRows?.length')&&!previewFn.includes('__browser_parse_error'),'shared preview blocks skipped identity rows rather than manufacturing or discarding evidence');
ok(previewFn.includes('sourceTimestamp: null')&&!previewFn.includes('new Date().toISOString()'),'same source and revision produce deterministic preview metadata');
ok(!previewFn.includes('saveNavisionImport('),'preview has no localStorage apply fallback');
ok(applyFn.includes('confirmed: true'),'apply contract carries explicit confirmation');
ok(applyFn.includes('browserLocalSha256: afterSha256'),'browser authority hash is reported');
ok(applyFn.includes('navisionBrowserAuthoritySha256()'),'browser authority is verified after shared apply');
ok(!applyFn.includes('saveJson(')&&!applyFn.includes('localStorage.setItem'),'shared apply does not write browser authority');
ok(service.includes("Object.freeze(['14450', '37047'])"),'service allowlists exact dealer codes');
ok(service.includes("error: 'invalid_dealer_code'"),'missing/malformed dealer fails closed');
ok(service.includes('p_source_system: sourceSystem')&&service.includes('p_dealer_code: dealerCode'),'RPC carries exact scope');
ok(service.includes("explicit_confirmation_required"),'service requires confirmation');
ok(service.includes('options.confirmed !== true'),'service accepts only explicit boolean confirmation');
ok(service.includes('p_preview_hash')&&service.includes('p_expected_revision'),'preview/apply parity enforced');
ok(sql.includes("dealer_code in ('14450','37047','LEGACY_UNSCOPED')"),'database dealer constraint');
ok(sql.includes("record_status = 'not_in_latest_batch'"),'missing records are status-marked, not deleted');
ok(!sql.slice(sql.indexOf('create or replace function public.apply_navision_backend_import('),sql.indexOf('create or replace function public.rollback_navision_backend_import(')).includes('delete from public.vehicles'),'apply never deletes vehicles');
ok(sql.includes("b.dealer_code = v_dealer_code")||sql.includes("dealer_code = v_dealer_code"),'missing scope is dealer-local');
ok(sql.includes('LEGACY_UNSCOPED'),'legacy evidence retained for controlled claim');
ok(sql.includes('legacy_claim_requires_administrator'),'legacy adoption requires an explicit administrator-scoped preview/apply');
ok(sql.includes('raw_evidence = v_row'),'source evidence retained');
ok(sql.includes('p_after_record_id uuid')&&sql.includes('r.source_system=v_source_system and r.dealer_code=v_dealer_code'),'snapshot/export use exact scope and a composite cursor');
ok(sql.includes("v_role = any(array['importer','administrator'])"),'snapshot data is limited to importer/administrator roles');
ok(sql.includes('navision_backend_audit'),'audit retained');
ok(sql.includes('revoke all on function public.preview_navision_backend_import(jsonb,text,timestamptz)'),'unscoped preview revoked');
ok(sql.includes('revoke all on function public.apply_navision_backend_import(text,jsonb,text,timestamptz,text,text,bigint)'),'unscoped apply revoked');
console.log(`Navision shared UI/dealer-scope regression: ${n} assertions passed.`);
