-- STAGING ONLY 718: remove the final JSONB path-operator coercion from the
-- acceptance marker check in the strict 502 execute wrapper.
BEGIN;
SET LOCAL lock_timeout='10s'; SET LOCAL statement_timeout='90s';
SELECT pg_advisory_xact_lock(hashtextextended('pdc-staging-718-agentic-acceptance-marker-check',0));
LOCK TABLE supabase_migrations.schema_migrations IN EXCLUSIVE MODE;
DO $guard$
DECLARE h text;
BEGIN SELECT encode(extensions.digest(convert_to(p.prosrc,'UTF8'),'sha256'),'hex') INTO h FROM pg_proc p WHERE p.oid='public.execute_pdc_agentic_email_action_502(jsonb)'::regprocedure;
 IF current_user<>'postgres' OR session_user<>'postgres' OR (SELECT count(*) FROM public.pdc_staging_environment_sentinel WHERE singleton AND project_ref='cdsmnqxtyyoeoznmbidd')<>1 OR to_regclass('public.pdc_production_environment_sentinel') IS NOT NULL OR lower(coalesce(current_setting('app.environment',true),''))='production' OR (SELECT max(version) FROM supabase_migrations.schema_migrations WHERE version~'^[0-9]{14}$')<>'20260828390000' OR h<>'1aaa5858a67dd66fa04ac20d0d27dca2e44052bfc00389088b600508a1412c67' OR to_regclass('public.pdc_authenticated_agentic_acceptance_marker_history_718') IS NOT NULL THEN RAISE EXCEPTION 'PDC_718_EXACT_717_EXECUTE_PREDECESSOR_MISMATCH' USING errcode='55000'; END IF; END $guard$;
CREATE TABLE public.pdc_authenticated_agentic_acceptance_marker_history_718(history_id uuid PRIMARY KEY DEFAULT gen_random_uuid(),event_key text NOT NULL UNIQUE,event_kind text NOT NULL CHECK(event_kind='agentic_acceptance_marker_check'),predecessor_head text NOT NULL CHECK(predecessor_head='20260828390000'),successor_head text NOT NULL CHECK(successor_head='20260828400000'),predecessor_function_sha256 text NOT NULL CHECK(predecessor_function_sha256='1aaa5858a67dd66fa04ac20d0d27dca2e44052bfc00389088b600508a1412c67'),successor_function_sha256 text NOT NULL,repair_contract text NOT NULL,production_writes boolean NOT NULL CHECK(NOT production_writes),task_enabled boolean NOT NULL CHECK(NOT task_enabled),mailbox_contacted boolean NOT NULL CHECK(NOT mailbox_contacted),uid514_processed boolean NOT NULL CHECK(NOT uid514_processed),created_at timestamptz NOT NULL DEFAULT clock_timestamp());
ALTER TABLE public.pdc_authenticated_agentic_acceptance_marker_history_718 ENABLE ROW LEVEL SECURITY; ALTER TABLE public.pdc_authenticated_agentic_acceptance_marker_history_718 FORCE ROW LEVEL SECURITY; REVOKE ALL ON public.pdc_authenticated_agentic_acceptance_marker_history_718 FROM public,anon,authenticated,service_role,pdc_email_monitor;
CREATE FUNCTION public.pdc_authenticated_agentic_acceptance_marker_history_immutable_718() RETURNS trigger LANGUAGE plpgsql SECURITY DEFINER SET search_path=pg_catalog,public AS $$ BEGIN RAISE EXCEPTION 'PDC_718_ACCEPTANCE_MARKER_HISTORY_IMMUTABLE' USING errcode='55000'; END $$;
REVOKE ALL ON FUNCTION public.pdc_authenticated_agentic_acceptance_marker_history_immutable_718() FROM public,anon,authenticated,service_role,pdc_email_monitor;
CREATE TRIGGER pdc_authenticated_agentic_acceptance_marker_history_immutable_718 BEFORE UPDATE OR DELETE ON public.pdc_authenticated_agentic_acceptance_marker_history_718 FOR EACH ROW EXECUTE FUNCTION public.pdc_authenticated_agentic_acceptance_marker_history_immutable_718();
DO $repair$
DECLARE d text;before_sha text;after_sha text;old text;new text;
BEGIN
 SELECT pg_get_functiondef('public.execute_pdc_agentic_email_action_502(jsonb)'::regprocedure),encode(extensions.digest(convert_to(p.prosrc,'UTF8'),'sha256'),'hex') INTO d,before_sha FROM pg_proc p WHERE p.oid='public.execute_pdc_agentic_email_action_502(jsonb)'::regprocedure;
 old:=$old$q.canonical_evidence#>>'{acceptance_context_projection,contract_version}'$old$; new:=$new$q.canonical_evidence->'acceptance_context_projection'->>'contract_version'$new$;
 IF before_sha<>'1aaa5858a67dd66fa04ac20d0d27dca2e44052bfc00389088b600508a1412c67' OR position(old IN d)=0 THEN RAISE EXCEPTION 'PDC_718_MARKER_ANCHOR_MISMATCH' USING errcode='55000'; END IF;
 EXECUTE replace(d,old,new);
 SELECT encode(extensions.digest(convert_to(p.prosrc,'UTF8'),'sha256'),'hex') INTO after_sha FROM pg_proc p WHERE p.oid='public.execute_pdc_agentic_email_action_502(jsonb)'::regprocedure;
 INSERT INTO public.pdc_authenticated_agentic_acceptance_marker_history_718(event_key,event_kind,predecessor_head,successor_head,predecessor_function_sha256,successor_function_sha256,repair_contract,production_writes,task_enabled,mailbox_contacted,uid514_processed) VALUES(encode(extensions.digest(convert_to('pdc-staging-718-agentic-acceptance-marker-check|forward','UTF8'),'sha256'),'hex'),'agentic_acceptance_marker_check','20260828390000','20260828400000',before_sha,after_sha,'Use direct JSONB field traversal for the stored exact acceptance marker; do not change the marker values or any normal action path',false,false,false,false);
END $repair$;
DO $post$ BEGIN IF (SELECT count(*) FROM public.pdc_authenticated_agentic_acceptance_marker_history_718)<>1 OR position($needle$q.canonical_evidence->'acceptance_context_projection'->>'contract_version'$needle$ IN (SELECT p.prosrc FROM pg_proc p WHERE p.oid='public.execute_pdc_agentic_email_action_502(jsonb)'::regprocedure))=0 OR to_regclass('public.pdc_production_environment_sentinel') IS NOT NULL THEN RAISE EXCEPTION 'PDC_718_POSTCONDITION_FAILED' USING errcode='55000'; END IF; END $post$;
INSERT INTO supabase_migrations.schema_migrations(version,name,statements) VALUES('20260828400000','718_agentic_acceptance_marker_check',ARRAY['Exact 717 predecessor and strict execute hash guard','Acceptance marker check uses direct JSONB traversal only','Normal Board/read filters, action semantics, idempotency, UID514/task/mailbox/outbound and Production untouched']);
NOTIFY pgrST,'reload schema'; COMMIT;
