-- Applied to STAGING after the classifier-v2 migration to remove PL/pgSQL response-column ambiguity.
-- The canonical 20260910032452 source in this repository already includes the corrected v_response variable.
