-- STAGING ONLY 685: bind the exact retained seven/four attachment arrays.
-- Append-only hardening after 684. No UID514 processing or evidence mutation.
BEGIN;
SET LOCAL lock_timeout='10s';
SET LOCAL statement_timeout='90s';
SELECT pg_advisory_xact_lock(hashtextextended('pdc-staging-685-uid514-exact-attachment-array-guard',0));
LOCK TABLE supabase_migrations.schema_migrations IN EXCLUSIVE MODE;
DO $guard$
DECLARE h text;
BEGIN
 SELECT encode(extensions.digest(convert_to(p.prosrc,'UTF8'),'sha256'),'hex') INTO h FROM pg_proc p WHERE p.oid='public.pdc_monitor_authenticated_uid514_claim_scope_684(text,uuid,uuid,uuid,text,text)'::regprocedure;
 IF current_user<>'postgres' OR session_user<>'postgres' OR (SELECT count(*) FROM public.pdc_staging_environment_sentinel WHERE singleton AND project_ref='cdsmnqxtyyoeoznmbidd')<>1 OR to_regclass('public.pdc_production_environment_sentinel') IS NOT NULL OR lower(coalesce(current_setting('app.environment',true),''))='production' OR (SELECT count(*) FROM supabase_migrations.schema_migrations WHERE version='20260828050000' AND name='684_authenticated_provider_import_agentic_compatibility')<>1 OR (SELECT max(version) FROM supabase_migrations.schema_migrations WHERE version~'^[0-9]{14}$')<>'20260828050000' OR to_regclass('public.pdc_authenticated_provider_import_agentic_inventory_guard_history_685') IS NOT NULL OR h<>'7626fd496feaea6c90bd254dffefd0c36ab18e69403f2b3c7aff38d104e7682b' OR (SELECT count(*) FROM public.pdc_authenticated_provider_import_agentic_compatibility_controls_684 WHERE singleton AND enabled AND observed_mime_part_count=7 AND retained_authenticated_attachment_count=4 AND parent_source_hash='440d174b6e1994fbb1afb9c285f068cb62b130f541ebaa834d590f44bdbec280' AND job_card_sha256='9a8f412ec5c9e108817da26b20993fa0a5e61a54f7ac983673c1ef9e2d8af8f4' AND NOT task_enabled AND NOT mailbox_contacted AND NOT uid514_processed AND NOT production_writes)<>1 OR (SELECT count(*) FROM public.ai_email_intake WHERE id='102e286d-1799-4c97-8e45-e0da9fb31c63'::uuid AND status='failed' AND queue_attempts=8)<>1 OR (SELECT count(*) FROM public.pdc_provider_email_observations WHERE intake_id='102e286d-1799-4c97-8e45-e0da9fb31c63'::uuid)<>0 THEN RAISE EXCEPTION 'PDC_685_EXACT_684_PREDECESSOR_OR_UID514_STATE_MISMATCH' USING errcode='55000'; END IF;
END
$guard$;
CREATE TABLE public.pdc_authenticated_provider_import_agentic_inventory_guard_history_685(
 history_id uuid PRIMARY KEY DEFAULT gen_random_uuid(), event_key text NOT NULL UNIQUE, event_kind text NOT NULL CHECK(event_kind='forward_inventory_guard'), predecessor_head text NOT NULL CHECK(predecessor_head='20260828050000'), successor_head text NOT NULL CHECK(successor_head='20260828060000'), predecessor_helper_sha256 text NOT NULL, successor_helper_sha256 text NOT NULL, actor_id uuid NOT NULL CHECK(actor_id='df7c55d9-6ba0-47f6-ba16-44d6ae2c2a4b'), actor_email text NOT NULL CHECK(actor_email='sales@broometoyota.com.au'), jwt_role text NOT NULL CHECK(jwt_role='authenticated'), server_application_role text NOT NULL CHECK(server_application_role='importer'), gateway_instance_id text NOT NULL CHECK(gateway_instance_id='pdc-monitor-staging-sales-uid509-v1'), release_name text NOT NULL CHECK(release_name='pdc-monitor-staging-m502-2026.08.44'), source_sha text NOT NULL CHECK(source_sha='e850c319989d98b45b95a28aa815d78e2c2e3a4b'), manifest_sha256 text NOT NULL CHECK(manifest_sha256='d48b49f6598a99fbef99fc4f0d0ab36b8b47576b8ff7cd8ecd2cb64d6cfed58d'), planner_sha256 text NOT NULL CHECK(planner_sha256='7e08a00bc099610aa919bb7c3089ef84b91a74bafd69f95fab06bfccfdf67348'), trust_receipt_sha256 text NOT NULL CHECK(trust_receipt_sha256='e3e30ace04e676e34f271b161283b9e4764d462f76428d63826fa3cb153d7227'), recovery_event_id integer NOT NULL CHECK(recovery_event_id=25751401), parent_source_hash text NOT NULL CHECK(parent_source_hash='440d174b6e1994fbb1afb9c285f068cb62b130f541ebaa834d590f44bdbec280'), observed_mime_part_count integer NOT NULL CHECK(observed_mime_part_count=7), retained_authenticated_attachment_count integer NOT NULL CHECK(retained_authenticated_attachment_count=4), before_state jsonb NOT NULL, after_state jsonb NOT NULL, task_enabled boolean NOT NULL CHECK(NOT task_enabled), mailbox_contacted boolean NOT NULL CHECK(NOT mailbox_contacted), uid514_processed boolean NOT NULL CHECK(NOT uid514_processed), production_writes boolean NOT NULL CHECK(NOT production_writes), created_at timestamptz NOT NULL DEFAULT clock_timestamp()
);
CREATE FUNCTION public.pdc_authenticated_provider_import_agentic_inventory_guard_history_immutable_685() RETURNS trigger LANGUAGE plpgsql SECURITY DEFINER SET search_path=pg_catalog,public AS $immutable$ BEGIN RAISE EXCEPTION 'PDC_685_INVENTORY_GUARD_HISTORY_IMMUTABLE' USING errcode='55000'; END $immutable$;
CREATE TRIGGER pdc_authenticated_provider_import_agentic_inventory_guard_history_immutable_685 BEFORE UPDATE OR DELETE ON public.pdc_authenticated_provider_import_agentic_inventory_guard_history_685 FOR EACH ROW EXECUTE FUNCTION public.pdc_authenticated_provider_import_agentic_inventory_guard_history_immutable_685();
ALTER TABLE public.pdc_authenticated_provider_import_agentic_inventory_guard_history_685 ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.pdc_authenticated_provider_import_agentic_inventory_guard_history_685 FORCE ROW LEVEL SECURITY;
REVOKE ALL ON public.pdc_authenticated_provider_import_agentic_inventory_guard_history_685 FROM public,anon,authenticated,service_role,pdc_email_monitor;
DO $repair$
DECLARE d text; n text; before_sha text; after_sha text; old text:='ok:=i.id IS NOT NULL AND m.id IS NOT NULL AND z.recovery_event_id IS NOT NULL AND s.selection_id IS NOT NULL AND a.id IS NOT NULL AND p_parent_hash=c.parent_source_hash AND p_gateway=c.gateway_instance_id AND p_intake_id=z.intake_id AND p_attachment_id=s.job_card_attachment_id AND NOT c.task_enabled AND NOT c.mailbox_contacted AND NOT c.uid514_processed AND NOT c.production_writes;'; new text:='ok:=i.id IS NOT NULL AND m.id IS NOT NULL AND z.recovery_event_id IS NOT NULL AND s.selection_id IS NOT NULL AND a.id IS NOT NULL AND p_parent_hash=c.parent_source_hash AND p_gateway=c.gateway_instance_id AND p_intake_id=z.intake_id AND p_attachment_id=s.job_card_attachment_id AND c.all_attachment_hashes=(SELECT array_agg(lower(x.source_hash) ORDER BY x.created_at,x.id) FROM public.ai_email_attachments x WHERE x.intake_id=i.id) AND c.pdf_hashes=(SELECT array_agg(lower(x.source_hash) ORDER BY x.created_at,x.id) FILTER (WHERE lower(x.content_type)=''application/pdf'') FROM public.ai_email_attachments x WHERE x.intake_id=i.id) AND s.all_attachment_ids=(SELECT array_agg(x.id ORDER BY x.created_at,x.id) FROM public.ai_email_attachments x WHERE x.intake_id=i.id) AND s.qualifying_attachment_ids=(SELECT array_agg(x.id ORDER BY x.created_at,x.id) FILTER (WHERE lower(x.content_type)=''application/pdf'') FROM public.ai_email_attachments x WHERE x.intake_id=i.id) AND NOT c.task_enabled AND NOT c.mailbox_contacted AND NOT c.uid514_processed AND NOT c.production_writes;';
BEGIN
 SELECT pg_get_functiondef('public.pdc_monitor_authenticated_uid514_claim_scope_684(text,uuid,uuid,uuid,text,text)'::regprocedure) INTO d; before_sha:=encode(extensions.digest(convert_to((SELECT prosrc FROM pg_proc WHERE oid='public.pdc_monitor_authenticated_uid514_claim_scope_684(text,uuid,uuid,uuid,text,text)'::regprocedure),'UTF8'),'sha256'),'hex'); IF position(old IN d)=0 THEN RAISE EXCEPTION 'PDC_685_HELPER_SOURCE_DRIFT' USING errcode='55000'; END IF; n:=replace(d,old,new); EXECUTE n; SELECT encode(extensions.digest(convert_to((SELECT prosrc FROM pg_proc WHERE oid='public.pdc_monitor_authenticated_uid514_claim_scope_684(text,uuid,uuid,uuid,text,text)'::regprocedure),'UTF8'),'sha256'),'hex') INTO after_sha;
 INSERT INTO public.pdc_authenticated_provider_import_agentic_inventory_guard_history_685(event_key,event_kind,predecessor_head,successor_head,predecessor_helper_sha256,successor_helper_sha256,actor_id,actor_email,jwt_role,server_application_role,gateway_instance_id,release_name,source_sha,manifest_sha256,planner_sha256,trust_receipt_sha256,recovery_event_id,parent_source_hash,observed_mime_part_count,retained_authenticated_attachment_count,before_state,after_state,task_enabled,mailbox_contacted,uid514_processed,production_writes) VALUES(encode(extensions.digest(convert_to('pdc-staging-685-forward|20260828060000','UTF8'),'sha256'),'hex'),'forward_inventory_guard','20260828050000','20260828060000',before_sha,after_sha,'df7c55d9-6ba0-47f6-ba16-44d6ae2c2a4b','sales@broometoyota.com.au','authenticated','importer','pdc-monitor-staging-sales-uid509-v1','pdc-monitor-staging-m502-2026.08.44','e850c319989d98b45b95a28aa815d78e2c2e3a4b','d48b49f6598a99fbef99fc4f0d0ab36b8b47576b8ff7cd8ecd2cb64d6cfed58d','7e08a00bc099610aa919bb7c3089ef84b91a74bafd69f95fab06bfccfdf67348','e3e30ace04e676e34f271b161283b9e4764d462f76428d63826fa3cb153d7227',25751401,'440d174b6e1994fbb1afb9c285f068cb62b130f541ebaa834d590f44bdbec280',7,4,jsonb_build_object('helper_sha256',before_sha,'ordered_hash_guard',false),jsonb_build_object('helper_sha256',after_sha,'ordered_hash_guard',true,'all_attachment_hashes_verified',true,'pdf_hashes_verified',true),false,false,false,false);
END
$repair$;
DO $post$
BEGIN
 IF (SELECT count(*) FROM public.pdc_authenticated_provider_import_agentic_inventory_guard_history_685 WHERE event_kind='forward_inventory_guard')<>1 OR position('c.all_attachment_hashes' IN pg_get_functiondef('public.pdc_monitor_authenticated_uid514_claim_scope_684(text,uuid,uuid,uuid,text,text)'::regprocedure))=0 OR position('s.qualifying_attachment_ids' IN pg_get_functiondef('public.pdc_monitor_authenticated_uid514_claim_scope_684(text,uuid,uuid,uuid,text,text)'::regprocedure))=0 OR (SELECT count(*) FROM public.pdc_provider_email_observations WHERE intake_id='102e286d-1799-4c97-8e45-e0da9fb31c63'::uuid)<>0 OR (SELECT status FROM public.ai_email_intake WHERE id='102e286d-1799-4c97-8e45-e0da9fb31c63'::uuid)<>'failed' OR (SELECT queue_attempts FROM public.ai_email_intake WHERE id='102e286d-1799-4c97-8e45-e0da9fb31c63'::uuid)<>8 OR to_regclass('public.pdc_production_environment_sentinel') IS NOT NULL THEN RAISE EXCEPTION 'PDC_685_POSTCONDITION_FAILED' USING errcode='55000'; END IF;
END $post$;
INSERT INTO supabase_migrations.schema_migrations(version,name,statements) VALUES('20260828060000','685_uid514_exact_attachment_array_guard',ARRAY['Exact 684 predecessor and helper hash guard','Bind every authenticated claim to the ordered seven retained attachment hashes, ordered four PDF hashes, and immutable 673 selection arrays','Preserve failed UID514 intake and eight prior attempts; no observation, vehicle, task, mailbox or Production mutation']);
NOTIFY pgrst,'reload schema';
COMMIT;
