-- STAGING ONLY 469: bind the paused email runtime to the direct Inbox cutoff before any future reactivation.
BEGIN;SET LOCAL lock_timeout='10s';SET LOCAL statement_timeout='120s';
SELECT pg_advisory_xact_lock(hashtextextended('pdc-staging-469-bind-paused-email-runtime-cutoff',0));
DO $guard$ BEGIN
 IF current_user<>'postgres' OR session_user<>'postgres'
 OR (SELECT count(*) FROM public.pdc_staging_environment_sentinel WHERE singleton AND project_ref='cdsmnqxtyyoeoznmbidd')<>1
 OR to_regclass('public.pdc_production_environment_sentinel') IS NOT NULL
 OR NOT EXISTS(SELECT 1 FROM supabase_migrations.schema_migrations WHERE version='20260827018000' AND name='468_bind_reset_scope_review_correction')
 OR EXISTS(SELECT 1 FROM supabase_migrations.schema_migrations WHERE version~'^[0-9]{14}$' AND version>'20260827018000')
 OR NOT EXISTS(SELECT 1 FROM public.pdc_staging_replay_fences_466 WHERE fence_key='email:Inbox' AND uidvalidity=1 AND denied_through=631 AND first_eligible=632)
 OR EXISTS(SELECT 1 FROM public.pdc_email_monitor_pilot WHERE enabled OR outbound_email_enabled OR automatic_rule_application OR automatic_authenticated_jobcards)
 OR EXISTS(SELECT 1 FROM public.monitored_mailboxes WHERE active)
 OR EXISTS(SELECT 1 FROM public.pdc_monitor_stage_activation_writers WHERE active AND revoked_at IS NULL)
 THEN RAISE EXCEPTION 'PDC_469_TARGET_HEAD_FENCE_OR_CONTAINMENT_MISMATCH' USING errcode='55000';END IF;
END $guard$;
UPDATE public.monitored_mailboxes SET config=config||jsonb_build_object('paused_scheduler_sha256','2738643248f097c13fef188150a41a8483ce782744c403b3a2951033473e94b9','paused_scheduler_uidvalidity',1,'paused_scheduler_activation_high_water_uid',631,'paused_scheduler_minimum_uid',632,'reactivation_requires_successor',true),updated_at=clock_timestamp() WHERE mailbox_key='pdc_pmb_email';
CREATE TABLE public.pdc_staging_paused_email_runtime_receipts_469(receipt_id uuid PRIMARY KEY DEFAULT gen_random_uuid(),project_ref text NOT NULL CHECK(project_ref='cdsmnqxtyyoeoznmbidd'),scheduler_sha256 text NOT NULL CHECK(scheduler_sha256='2738643248f097c13fef188150a41a8483ce782744c403b3a2951033473e94b9'),uidvalidity bigint NOT NULL CHECK(uidvalidity=1),activation_high_water_uid bigint NOT NULL CHECK(activation_high_water_uid=631),minimum_uid bigint NOT NULL CHECK(minimum_uid=632),cron_state text NOT NULL CHECK(cron_state='paused'),reactivation_requires_successor boolean NOT NULL CHECK(reactivation_requires_successor),created_at timestamptz NOT NULL DEFAULT clock_timestamp());ALTER TABLE public.pdc_staging_paused_email_runtime_receipts_469 ENABLE ROW LEVEL SECURITY;REVOKE ALL ON public.pdc_staging_paused_email_runtime_receipts_469 FROM public,anon,authenticated,service_role;
CREATE FUNCTION public.pdc_staging_paused_email_runtime_receipt_immutable_469() RETURNS trigger LANGUAGE plpgsql SECURITY DEFINER SET search_path=pg_catalog,public AS $$BEGIN RAISE EXCEPTION 'PDC_469_RUNTIME_RECEIPT_IMMUTABLE' USING errcode='55000';END$$;REVOKE ALL ON FUNCTION public.pdc_staging_paused_email_runtime_receipt_immutable_469() FROM public,anon,authenticated,service_role;CREATE TRIGGER pdc_staging_paused_email_runtime_receipt_immutable_469 BEFORE UPDATE OR DELETE ON public.pdc_staging_paused_email_runtime_receipts_469 FOR EACH ROW EXECUTE FUNCTION public.pdc_staging_paused_email_runtime_receipt_immutable_469();
INSERT INTO public.pdc_staging_paused_email_runtime_receipts_469(project_ref,scheduler_sha256,uidvalidity,activation_high_water_uid,minimum_uid,cron_state,reactivation_requires_successor) VALUES('cdsmnqxtyyoeoznmbidd','2738643248f097c13fef188150a41a8483ce782744c403b3a2951033473e94b9',1,631,632,'paused',true);
INSERT INTO supabase_migrations.schema_migrations(version,name,statements) VALUES('20260827019000','469_bind_paused_email_runtime_cutoff',ARRAY['Bind the installed paused scheduler bytes to direct Inbox UIDVALIDITY 1 cutoff UID 631 and minimum UID 632','Require a separate append-only activation successor before the email cron mailbox writer or automatic actions can resume','Keep old mail fenced automatic recovery revoked outbound email false and Production untouched']);NOTIFY pgrst,'reload schema';COMMIT;
