-- STAGING ONLY 699: deny direct Parts operator RPC use by the exact importer actor.
-- Narrow transaction-local capability is consumed only by the authenticated AI
-- action wrapper; operator and administrator website paths remain unchanged.
BEGIN;
SET LOCAL lock_timeout='10s'; SET LOCAL statement_timeout='90s';
SELECT pg_advisory_xact_lock(hashtextextended('pdc-staging-699-monitor-operator-rpc-boundary',0));
LOCK TABLE supabase_migrations.schema_migrations IN EXCLUSIVE MODE;
DO $guard$ BEGIN IF current_user<>'postgres' OR session_user<>'postgres' OR (SELECT count(*) FROM public.pdc_staging_environment_sentinel WHERE singleton AND project_ref='cdsmnqxtyyoeoznmbidd')<>1 OR to_regclass('public.pdc_production_environment_sentinel') IS NOT NULL OR (SELECT max(version) FROM supabase_migrations.schema_migrations WHERE version~'^[0-9]{14}$')<>'20260828190000' OR to_regprocedure('public.mark_pdc_parts_complete(uuid,integer)') IS NULL OR to_regprocedure('public.update_pdc_parts_eta(uuid,integer,date)') IS NULL OR to_regprocedure('public.execute_pdc_email_ai_acceptance_action_693(uuid,text,uuid,text,text)') IS NULL OR to_regclass('public.pdc_monitor_operator_boundary_history_699') IS NOT NULL THEN RAISE EXCEPTION 'PDC_699_EXACT_698_PRESTATE_REQUIRED' USING errcode='55000'; END IF; END $guard$;
CREATE TABLE public.pdc_monitor_operator_boundary_history_699(history_id uuid PRIMARY KEY DEFAULT gen_random_uuid(),event_key text NOT NULL UNIQUE,predecessor_head text NOT NULL CHECK(predecessor_head='20260828190000'),successor_head text NOT NULL CHECK(successor_head='20260828200000'),before_hashes jsonb NOT NULL,after_hashes jsonb NOT NULL,repair_contract text NOT NULL,production_writes boolean NOT NULL CHECK(NOT production_writes),created_at timestamptz NOT NULL DEFAULT clock_timestamp());
ALTER TABLE public.pdc_monitor_operator_boundary_history_699 ENABLE ROW LEVEL SECURITY; ALTER TABLE public.pdc_monitor_operator_boundary_history_699 FORCE ROW LEVEL SECURITY; REVOKE ALL ON public.pdc_monitor_operator_boundary_history_699 FROM public,anon,authenticated,service_role,pdc_email_monitor;
CREATE FUNCTION public.pdc_monitor_operator_boundary_history_immutable_699() RETURNS trigger LANGUAGE plpgsql SECURITY DEFINER SET search_path=pg_catalog,public AS $$ BEGIN RAISE EXCEPTION 'PDC_699_OPERATOR_BOUNDARY_HISTORY_IMMUTABLE' USING errcode='55000'; END $$;
CREATE TRIGGER pdc_monitor_operator_boundary_history_immutable_699 BEFORE UPDATE OR DELETE ON public.pdc_monitor_operator_boundary_history_699 FOR EACH ROW EXECUTE FUNCTION public.pdc_monitor_operator_boundary_history_immutable_699();
DO $repair$ DECLARE m text;u text;e text;d text;bh text;uh text;after_hashes jsonb;BEGIN
 SELECT pg_get_functiondef('public.mark_pdc_parts_complete(uuid,integer)'::regprocedure),pg_get_functiondef('public.update_pdc_parts_eta(uuid,integer,date)'::regprocedure),pg_get_functiondef('public.execute_pdc_email_ai_acceptance_action_693(uuid,text,uuid,text,text)'::regprocedure) INTO m,u,e;
 SELECT jsonb_build_object('mark',encode(extensions.digest(convert_to(m,'UTF8'),'sha256'),'hex'),'eta',encode(extensions.digest(convert_to(u,'UTF8'),'sha256'),'hex'),'wrapper',encode(extensions.digest(convert_to(e,'UTF8'),'sha256'),'hex'))::text INTO bh;
 m:=replace(m,'perform public.require_pdc_role(''operator'');','IF public.current_pdc_user_role()::text=''importer'' AND current_setting(''pdc_monitor_canonical_action'',true)<>''pdc-email-ai-693'' THEN RAISE EXCEPTION ''PDC_MONITOR_DIRECT_OPERATOR_RPC_DENIED'' USING errcode=''42501''; END IF; perform public.require_pdc_role(''operator'');');
 u:=replace(u,'perform public.require_pdc_role(''operator'');','IF public.current_pdc_user_role()::text=''importer'' AND current_setting(''pdc_monitor_canonical_action'',true)<>''pdc-email-ai-693'' THEN RAISE EXCEPTION ''PDC_MONITOR_DIRECT_OPERATOR_RPC_DENIED'' USING errcode=''42501''; END IF; perform public.require_pdc_role(''operator'');');
 e:=replace(e,'r:=public.update_pdc_parts_eta(v.id,v.version,d);','PERFORM set_config(''pdc_monitor_canonical_action'',''pdc-email-ai-693'',true); r:=public.update_pdc_parts_eta(v.id,v.version,d); PERFORM set_config(''pdc_monitor_canonical_action'','''',true);');
 e:=replace(e,'r:=public.mark_pdc_parts_complete(v.id,v.version);','PERFORM set_config(''pdc_monitor_canonical_action'',''pdc-email-ai-693'',true); r:=public.mark_pdc_parts_complete(v.id,v.version); PERFORM set_config(''pdc_monitor_canonical_action'','''',true);');
 IF position('PDC_MONITOR_DIRECT_OPERATOR_RPC_DENIED' IN m)=0 OR position('PDC_MONITOR_DIRECT_OPERATOR_RPC_DENIED' IN u)=0 OR position('pdc_monitor_canonical_action' IN e)=0 THEN RAISE EXCEPTION 'PDC_699_SOURCE_ANCHOR_MISSING' USING errcode='55000'; END IF;
 EXECUTE m; EXECUTE u; EXECUTE e;
 SELECT jsonb_build_object('mark',encode(extensions.digest(convert_to(p.prosrc,'UTF8'),'sha256'),'hex'))::text INTO d FROM pg_proc p WHERE p.oid='public.mark_pdc_parts_complete(uuid,integer)'::regprocedure;
 SELECT jsonb_build_object('mark',encode(extensions.digest(convert_to(p.prosrc,'UTF8'),'sha256'),'hex'),'eta',encode(extensions.digest(convert_to(q.prosrc,'UTF8'),'sha256'),'hex'),'wrapper',encode(extensions.digest(convert_to(r.prosrc,'UTF8'),'sha256'),'hex')) INTO after_hashes FROM pg_proc p,pg_proc q,pg_proc r WHERE p.oid='public.mark_pdc_parts_complete(uuid,integer)'::regprocedure AND q.oid='public.update_pdc_parts_eta(uuid,integer,date)'::regprocedure AND r.oid='public.execute_pdc_email_ai_acceptance_action_693(uuid,text,uuid,text,text)'::regprocedure;
 INSERT INTO public.pdc_monitor_operator_boundary_history_699(event_key,before_hashes,after_hashes,repair_contract,production_writes) VALUES(encode(extensions.digest(convert_to('pdc-staging-699-operator-boundary|forward','UTF8'),'sha256'),'hex'),bh::jsonb,after_hashes,'Importer direct execution is rejected; only the exact transaction-local authenticated AI wrapper capability reaches canonical Parts RPCs; no grant/RLS weakening',false);
END $repair$;
INSERT INTO supabase_migrations.schema_migrations(version,name,statements) VALUES('20260828200000','699_monitor_direct_operator_parts_boundary',ARRAY['Exact 698 predecessor and staging guards','Deny direct importer calls to mark_pdc_parts_complete and update_pdc_parts_eta with stable PDC_MONITOR_DIRECT_OPERATOR_RPC_DENIED','Wrapper consumes a transaction-local pdc_monitor_canonical_action capability while preserving canonical Parts RPCs and operator/admin paths','Immutable forced-RLS source hash history; UID514, task, mailbox, outbound and Production untouched']);
NOTIFY pgrST,'reload schema'; COMMIT;
