-- STAGING ONLY 470: Craig-authorised one-shot fresh Inbox check after full reset.
BEGIN;SET LOCAL lock_timeout='10s';SET LOCAL statement_timeout='120s';
SELECT pg_advisory_xact_lock(hashtextextended('pdc-staging-470-one-shot-fresh-inbox-check',0));
DO $guard$ BEGIN
 IF current_user<>'postgres' OR session_user<>'postgres'
 OR (SELECT count(*) FROM public.pdc_staging_environment_sentinel WHERE singleton AND project_ref='cdsmnqxtyyoeoznmbidd')<>1
 OR to_regclass('public.pdc_production_environment_sentinel') IS NOT NULL
 OR NOT EXISTS(SELECT 1 FROM supabase_migrations.schema_migrations WHERE version='20260827019000' AND name='469_bind_paused_email_runtime_cutoff')
 OR EXISTS(SELECT 1 FROM supabase_migrations.schema_migrations WHERE version~'^[0-9]{14}$' AND version>'20260827019000')
 OR NOT EXISTS(SELECT 1 FROM public.pdc_staging_replay_fences_466 WHERE fence_key='email:Inbox' AND uidvalidity=1 AND denied_through=631 AND first_eligible=632)
 OR NOT EXISTS(SELECT 1 FROM public.pdc_staging_paused_email_runtime_receipts_469 WHERE scheduler_sha256='2738643248f097c13fef188150a41a8483ce782744c403b3a2951033473e94b9' AND activation_high_water_uid=631 AND minimum_uid=632 AND cron_state='paused' AND reactivation_requires_successor)
 OR NOT EXISTS(SELECT 1 FROM auth.users u JOIN public.pdc_user_roles r ON r.auth_user_id=u.id WHERE u.id='69846ef4-a74c-4569-9e35-376cf0837888'::uuid AND lower(u.email)='pmbcontroller@gmail.com' AND u.raw_app_meta_data->>'pdc_identity_type'='non_human_monitor' AND r.active AND r.account_status='approved' AND r.role::text='importer')
 OR EXISTS(SELECT 1 FROM public.pdc_email_monitor_pilot WHERE enabled OR outbound_email_enabled OR automatic_rule_application OR automatic_authenticated_jobcards)
 OR EXISTS(SELECT 1 FROM public.monitored_mailboxes WHERE active)
 OR EXISTS(SELECT 1 FROM public.pdc_monitor_stage_activation_writers WHERE active AND revoked_at IS NULL)
 THEN RAISE EXCEPTION 'PDC_470_TARGET_HEAD_RUNTIME_OR_CONTAINMENT_MISMATCH' USING errcode='55000';END IF;
END $guard$;
UPDATE public.pdc_monitor_stage_activation_writers SET active=true,reason='Craig authorised one-shot fresh Inbox check after reset; no recurring cron activation',granted_by='8a83b715-8d79-4b0e-95b2-02b55da6e8d7'::uuid,granted_at=clock_timestamp(),revoked_at=null WHERE user_id='69846ef4-a74c-4569-9e35-376cf0837888'::uuid;
UPDATE public.monitored_mailboxes SET active=true,test_mode=true,updated_by='8a83b715-8d79-4b0e-95b2-02b55da6e8d7'::uuid,updated_at=clock_timestamp() WHERE mailbox_key='pdc_pmb_email' AND lower(mailbox_address)='pmbcontroller@gmail.com';
UPDATE public.pdc_email_monitor_pilot SET enabled=true,minimum_uid=632,automatic_rule_application=true,automatic_authenticated_jobcards=true,outbound_email_enabled=false,ambiguous_to_review=true,exactly_once_required=true,authorized_by='8a83b715-8d79-4b0e-95b2-02b55da6e8d7'::uuid,authorized_by_email='craig.watson@broometoyota.com.au',authorized_at=clock_timestamp(),updated_at=clock_timestamp() WHERE singleton AND project_ref='cdsmnqxtyyoeoznmbidd' AND mailbox_key='pdc_pmb_email';
UPDATE public.pdc_email_monitor_status SET running_status='running',gateway_instance_id='pdc-monitor-staging-pmbcontroller-one-shot-20260826',last_started_at=clock_timestamp(),last_error=null,last_error_code=null,updated_at=clock_timestamp() WHERE singleton;
CREATE TABLE public.pdc_staging_one_shot_email_check_receipts_470(receipt_id uuid PRIMARY KEY DEFAULT gen_random_uuid(),project_ref text NOT NULL CHECK(project_ref='cdsmnqxtyyoeoznmbidd'),actor_id uuid NOT NULL CHECK(actor_id='69846ef4-a74c-4569-9e35-376cf0837888'::uuid),scheduler_sha256 text NOT NULL CHECK(scheduler_sha256='2738643248f097c13fef188150a41a8483ce782744c403b3a2951033473e94b9'),uidvalidity bigint NOT NULL CHECK(uidvalidity=1),minimum_uid bigint NOT NULL CHECK(minimum_uid=632),mode text NOT NULL CHECK(mode='one_shot_direct_run_no_cron_resume'),outbound_email_enabled boolean NOT NULL CHECK(NOT outbound_email_enabled),created_at timestamptz NOT NULL DEFAULT clock_timestamp());ALTER TABLE public.pdc_staging_one_shot_email_check_receipts_470 ENABLE ROW LEVEL SECURITY;REVOKE ALL ON public.pdc_staging_one_shot_email_check_receipts_470 FROM public,anon,authenticated,service_role;
INSERT INTO public.pdc_staging_one_shot_email_check_receipts_470(project_ref,actor_id,scheduler_sha256,uidvalidity,minimum_uid,mode,outbound_email_enabled) VALUES('cdsmnqxtyyoeoznmbidd','69846ef4-a74c-4569-9e35-376cf0837888','2738643248f097c13fef188150a41a8483ce782744c403b3a2951033473e94b9',1,632,'one_shot_direct_run_no_cron_resume',false);
DO $post$ BEGIN IF (SELECT count(*) FROM public.pdc_monitor_stage_activation_writers WHERE user_id='69846ef4-a74c-4569-9e35-376cf0837888'::uuid AND active AND revoked_at IS NULL)<>1 OR (SELECT count(*) FROM public.monitored_mailboxes WHERE mailbox_key='pdc_pmb_email' AND active AND test_mode)<>1 OR (SELECT count(*) FROM public.pdc_email_monitor_pilot WHERE singleton AND enabled AND minimum_uid=632 AND automatic_rule_application AND automatic_authenticated_jobcards AND NOT outbound_email_enabled)<>1 OR (SELECT count(*) FROM public.pdc_staging_one_shot_email_check_receipts_470)<>1 THEN RAISE EXCEPTION 'PDC_470_POSTCONDITION_FAILED' USING errcode='55000';END IF;END $post$;
INSERT INTO supabase_migrations.schema_migrations(version,name,statements) VALUES('20260827020000','470_activate_one_shot_fresh_inbox_check',ARRAY['Activate exact pmbcontroller staging Importer mailbox and receipt-bound mutations for one direct cycle at UID 632','Do not resume recurring cron and keep outbound email false review fail-closed and Production untouched','Require immediate post-cycle containment successor regardless of success review or failure']);NOTIFY pgrst,'reload schema';COMMIT;
