-- STAGING ONLY 713: route the strict 502 execute pre-read through the
-- exact acceptance projection only when the stored context receipt carries the
-- 703 synthetic marker. Every other action keeps the original snapshot read.
BEGIN;
SET LOCAL lock_timeout='10s'; SET LOCAL statement_timeout='90s';
SELECT pg_advisory_xact_lock(hashtextextended('pdc-staging-713-agentic-acceptance-preread',0));
LOCK TABLE supabase_migrations.schema_migrations IN EXCLUSIVE MODE;
DO $guard$
DECLARE h text;
BEGIN SELECT encode(extensions.digest(convert_to(p.prosrc,'UTF8'),'sha256'),'hex') INTO h FROM pg_proc p WHERE p.oid='public.execute_pdc_agentic_email_action_502(jsonb)'::regprocedure;
 IF current_user<>'postgres' OR session_user<>'postgres' OR (SELECT count(*) FROM public.pdc_staging_environment_sentinel WHERE singleton AND project_ref='cdsmnqxtyyoeoznmbidd')<>1 OR to_regclass('public.pdc_production_environment_sentinel') IS NOT NULL OR lower(coalesce(current_setting('app.environment',true),''))='production' OR (SELECT max(version) FROM supabase_migrations.schema_migrations WHERE version~'^[0-9]{14}$')<>'20260828340000' OR h<>'5e1dccd8af4998b4f467c96bee47418b2535f07dc6ac0c3e62b3d5c75485126f' OR to_regclass('public.pdc_authenticated_agentic_acceptance_preread_history_713') IS NOT NULL THEN RAISE EXCEPTION 'PDC_713_EXACT_712_EXECUTE_PREDECESSOR_MISMATCH' USING errcode='55000'; END IF; END $guard$;
CREATE TABLE public.pdc_authenticated_agentic_acceptance_preread_history_713(history_id uuid PRIMARY KEY DEFAULT gen_random_uuid(),event_key text NOT NULL UNIQUE,event_kind text NOT NULL CHECK(event_kind='agentic_acceptance_authoritative_preread'),predecessor_head text NOT NULL CHECK(predecessor_head='20260828340000'),successor_head text NOT NULL CHECK(successor_head='20260828350000'),predecessor_function_sha256 text NOT NULL CHECK(predecessor_function_sha256='5e1dccd8af4998b4f467c96bee47418b2535f07dc6ac0c3e62b3d5c75485126f'),successor_function_sha256 text NOT NULL,repair_contract text NOT NULL,production_writes boolean NOT NULL CHECK(NOT production_writes),task_enabled boolean NOT NULL CHECK(NOT task_enabled),mailbox_contacted boolean NOT NULL CHECK(NOT mailbox_contacted),uid514_processed boolean NOT NULL CHECK(NOT uid514_processed),created_at timestamptz NOT NULL DEFAULT clock_timestamp());
ALTER TABLE public.pdc_authenticated_agentic_acceptance_preread_history_713 ENABLE ROW LEVEL SECURITY; ALTER TABLE public.pdc_authenticated_agentic_acceptance_preread_history_713 FORCE ROW LEVEL SECURITY; REVOKE ALL ON public.pdc_authenticated_agentic_acceptance_preread_history_713 FROM public,anon,authenticated,service_role,pdc_email_monitor;
CREATE FUNCTION public.pdc_authenticated_agentic_acceptance_preread_history_immutable_713() RETURNS trigger LANGUAGE plpgsql SECURITY DEFINER SET search_path=pg_catalog,public AS $$ BEGIN RAISE EXCEPTION 'PDC_713_ACCEPTANCE_PREREAD_HISTORY_IMMUTABLE' USING errcode='55000'; END $$;
REVOKE ALL ON FUNCTION public.pdc_authenticated_agentic_acceptance_preread_history_immutable_713() FROM public,anon,authenticated,service_role,pdc_email_monitor;
CREATE TRIGGER pdc_authenticated_agentic_acceptance_preread_history_immutable_713 BEFORE UPDATE OR DELETE ON public.pdc_authenticated_agentic_acceptance_preread_history_713 FOR EACH ROW EXECUTE FUNCTION public.pdc_authenticated_agentic_acceptance_preread_history_immutable_713();
DO $repair$
DECLARE d text;before_sha text;after_sha text;old text;new text;
BEGIN
 SELECT pg_get_functiondef('public.execute_pdc_agentic_email_action_502(jsonb)'::regprocedure),encode(extensions.digest(convert_to(p.prosrc,'UTF8'),'sha256'),'hex') INTO d,before_sha FROM pg_proc p WHERE p.oid='public.execute_pdc_agentic_email_action_502(jsonb)'::regprocedure;
 old:=$old$v_before:=public.read_pdc_agentic_email_vehicle_502((p_action->>'vehicle_id')::uuid);$old$;
 new:=$new$v_before:=case when exists(select 1 from public.pdc_agentic_email_context_receipts_502 q where q.context_receipt_id=v_plan.context_receipt_id and q.actor_id=auth.uid() and q.canonical_evidence#>>'{acceptance_context_projection,contract_version}'='pdc-acceptance-context-projection-703.1') then public.pdc_monitor_authenticated_acceptance_vehicle_projection_703((p_action->>'vehicle_id')::uuid,v_plan.context_receipt_id) else public.read_pdc_agentic_email_vehicle_502((p_action->>'vehicle_id')::uuid) end;$new$;
 IF before_sha<>'5e1dccd8af4998b4f467c96bee47418b2535f07dc6ac0c3e62b3d5c75485126f' OR position(old IN d)=0 THEN RAISE EXCEPTION 'PDC_713_PREREAD_ANCHOR_MISMATCH' USING errcode='55000'; END IF;
 EXECUTE replace(d,old,new);
 SELECT encode(extensions.digest(convert_to(p.prosrc,'UTF8'),'sha256'),'hex') INTO after_sha FROM pg_proc p WHERE p.oid='public.execute_pdc_agentic_email_action_502(jsonb)'::regprocedure;
 INSERT INTO public.pdc_authenticated_agentic_acceptance_preread_history_713(event_key,event_kind,predecessor_head,successor_head,predecessor_function_sha256,successor_function_sha256,repair_contract,production_writes,task_enabled,mailbox_contacted,uid514_processed) VALUES(encode(extensions.digest(convert_to('pdc-staging-713-agentic-acceptance-preread|forward','UTF8'),'sha256'),'hex'),'agentic_acceptance_authoritative_preread','20260828340000','20260828350000',before_sha,after_sha,'Use the direct server-side acceptance vehicle projection only for an actor-bound 703 context receipt; all normal 502 actions continue through the unchanged Board-backed vehicle read',false,false,false,false);
END $repair$;
DO $post$ BEGIN IF (SELECT count(*) FROM public.pdc_authenticated_agentic_acceptance_preread_history_713)<>1 OR position('pdc_monitor_authenticated_acceptance_vehicle_projection_703' IN (SELECT p.prosrc FROM pg_proc p WHERE p.oid='public.execute_pdc_agentic_email_action_502(jsonb)'::regprocedure))=0 OR to_regclass('public.pdc_production_environment_sentinel') IS NOT NULL THEN RAISE EXCEPTION 'PDC_713_POSTCONDITION_FAILED' USING errcode='55000'; END IF; END $post$;
INSERT INTO supabase_migrations.schema_migrations(version,name,statements) VALUES('20260828350000','713_agentic_acceptance_authoritative_preread',ARRAY['Exact 712 predecessor and strict execute hash guard','Acceptance projection is selected only by the stored exact synthetic context receipt marker; normal 502 reads unchanged','Immutable forced-RLS history; UID514/task/mailbox/outbound/Production untouched']);
NOTIFY pgrST,'reload schema'; COMMIT;
