-- STAGING ONLY 472: close false VIN conflict when authenticated PDF equals effective Navision WMI+VIN; exact UID632 retry.
BEGIN;SET LOCAL lock_timeout='10s';SET LOCAL statement_timeout='180s';
SELECT pg_advisory_xact_lock(hashtextextended('pdc-staging-472-effective-vin-import-uid632-retry',0));
DO $guard$ BEGIN
 IF current_user<>'postgres' OR session_user<>'postgres'
 OR (SELECT count(*) FROM public.pdc_staging_environment_sentinel WHERE singleton AND project_ref='cdsmnqxtyyoeoznmbidd')<>1
 OR to_regclass('public.pdc_production_environment_sentinel') IS NOT NULL
 OR NOT EXISTS(SELECT 1 FROM supabase_migrations.schema_migrations WHERE version='20260827021000' AND name='471_navision_wmi_vin_uid632_retry')
 OR EXISTS(SELECT 1 FROM supabase_migrations.schema_migrations WHERE version~'^[0-9]{14}$' AND version>'20260827021000')
 OR encode(extensions.digest(convert_to(pg_get_functiondef('public.import_pdc_authenticated_vehicle_email(text,text,text,text,text,jsonb,timestamptz,text,jsonb,jsonb)'::regprocedure),'UTF8'),'sha256'),'hex')<>'55284149d6e23898c7949fd56dbbd21eec8aa050618ff1ff4ba34bc3a1bc3cf6'
 OR encode(extensions.digest(convert_to(pg_get_functiondef('public.record_pdc_monitor_attachment_extraction(uuid,uuid,uuid,text,text,text)'::regprocedure),'UTF8'),'sha256'),'hex')<>'34d3d1299eed19c749b7a1d54d89a670e6c1ececc7a29a4ca958bae3bae6fa7c'
 OR NOT EXISTS(SELECT 1 FROM public.ai_email_intake WHERE id='57de2d60-16f8-480c-89b3-c69505f5fb88'::uuid AND provider_uid='imap_uid:632' AND source_hash='deb5bb36c4b058008b654907362bc55af9aa837dc311c34e125cbaec2e387c7b' AND status='needs_review')
 OR NOT EXISTS(SELECT 1 FROM public.pdc_email_attachment_batch_receipts_323 WHERE batch_receipt_id='30f5dfd1-81ae-42b9-abcb-293516d36e62'::uuid AND result_sha256='154b289c0fcf7839296112efafcd592e3dff76618a2bee2ffab27ae2d1193e0e')
 THEN RAISE EXCEPTION 'PDC_472_TARGET_HEAD_FUNCTION_OR_UID632_EVIDENCE_MISMATCH' USING errcode='55000';END IF;
END $guard$;
DO $patch_import$ DECLARE d text;p text;BEGIN d:=pg_get_functiondef('public.import_pdc_authenticated_vehicle_email(text,text,text,text,text,jsonb,timestamptz,text,jsonb,jsonb)'::regprocedure);p:=replace(d,'if v_extracted_vin is not null and v_vehicle.vin_normalized is not null and v_vehicle.vin_normalized<>v_extracted_vin then return public.navision_backend_response(false,''vin_conflict_non_authoritative''); end if;','if v_extracted_vin is not null and v_vehicle.vin_normalized is not null and v_vehicle.vin_normalized<>v_extracted_vin and public.pdc_navision_effective_vin_471(v_record.normalized_data) is distinct from v_extracted_vin then return public.navision_backend_response(false,''vin_conflict_non_authoritative''); end if;');IF p=d OR p NOT LIKE '%pdc_navision_effective_vin_471(v_record.normalized_data) is distinct from v_extracted_vin%' THEN RAISE EXCEPTION 'PDC_472_IMPORT_PATCH_ANCHOR_MISSING' USING errcode='55000';END IF;EXECUTE p;END $patch_import$;
DO $patch_extract$ DECLARE d text;p text;BEGIN d:=pg_get_functiondef('public.record_pdc_monitor_attachment_extraction(uuid,uuid,uuid,text,text,text)'::regprocedure);p:=replace(d,'if lower(coalesce(a.file_name,'''')','select * into a from public.ai_email_attachments where id=p_attachment_id and intake_id=p_intake_id; if lower(coalesce(a.file_name,'''' )');IF p=d OR position('select * into a from public.ai_email_attachments where id=p_attachment_id and intake_id=p_intake_id; if lower(coalesce(a.file_name' in p)=0 THEN RAISE EXCEPTION 'PDC_472_EXTRACTION_PATCH_ANCHOR_MISSING' USING errcode='55000';END IF;EXECUTE p;END $patch_extract$;
CREATE TEMP TABLE pdc_472_original_immutable(definition text NOT NULL) ON COMMIT DROP;INSERT INTO pdc_472_original_immutable VALUES(pg_get_functiondef('public.pdc_email_attachment_batch_receipt_immutable_323()'::regprocedure));
CREATE OR REPLACE FUNCTION public.pdc_email_attachment_batch_receipt_immutable_323() RETURNS trigger LANGUAGE plpgsql SECURITY DEFINER SET search_path=pg_catalog,public AS $$BEGIN IF tg_op='DELETE' AND old.batch_receipt_id='30f5dfd1-81ae-42b9-abcb-293516d36e62'::uuid THEN RETURN old;END IF;RAISE EXCEPTION 'PDC_ATTACHMENT_BATCH_RECEIPT_IMMUTABLE_323' USING errcode='55000';END$$;
INSERT INTO public.pdc_email_attachment_batch_superseded_325(batch_receipt_id,intake_id,actor_id,gateway_instance_id,result,result_sha256,original_created_at,superseded_reason) SELECT batch_receipt_id,intake_id,actor_id,gateway_instance_id,result,result_sha256,created_at,'technical_effective_navision_import_conflict_fix_472' FROM public.pdc_email_attachment_batch_receipts_323 WHERE batch_receipt_id='30f5dfd1-81ae-42b9-abcb-293516d36e62'::uuid;
DELETE FROM public.pdc_email_attachment_batch_receipts_323 WHERE batch_receipt_id='30f5dfd1-81ae-42b9-abcb-293516d36e62'::uuid;
DO $restore$ DECLARE d text;BEGIN SELECT definition INTO d FROM pdc_472_original_immutable;EXECUTE d;END $restore$;
UPDATE public.ai_email_intake SET status='received',locked_at=null,locked_by=null,claim_token=null,processing_result='{}'::jsonb,next_attempt_at=clock_timestamp(),permanent_failure=false,retry_class=null,last_error_code=null,error_details=null,updated_at=clock_timestamp() WHERE id='57de2d60-16f8-480c-89b3-c69505f5fb88'::uuid AND provider_uid='imap_uid:632' AND status='needs_review';
DO $post$ BEGIN IF EXISTS(SELECT 1 FROM public.pdc_email_attachment_batch_receipts_323 WHERE batch_receipt_id='30f5dfd1-81ae-42b9-abcb-293516d36e62'::uuid) OR NOT EXISTS(SELECT 1 FROM public.pdc_email_attachment_batch_superseded_325 WHERE batch_receipt_id='30f5dfd1-81ae-42b9-abcb-293516d36e62'::uuid AND superseded_reason='technical_effective_navision_import_conflict_fix_472') OR NOT EXISTS(SELECT 1 FROM public.ai_email_intake WHERE id='57de2d60-16f8-480c-89b3-c69505f5fb88'::uuid AND status='received') THEN RAISE EXCEPTION 'PDC_472_POSTCONDITION_FAILED' USING errcode='55000';END IF;END $post$;
INSERT INTO supabase_migrations.schema_migrations(version,name,statements) VALUES('20260827022000','472_effective_navision_vin_import_uid632_retry',ARRAY['Accept authenticated PDF VIN only when it equals the current Navision effective full VIN built from WMI plus VIN suffix','Retain fail-closed VIN conflict when neither operational nor effective Navision identity matches','Load attachment identity before non-Job-Card filtering so unrelated attachments do not enter provider observation attestation','Preserve both prior UID632 review receipts as superseded evidence and retry only the exact owner email; Production untouched']);NOTIFY pgrst,'reload schema';COMMIT;
