-- STAGING ONLY 720: explicitly group the nested source_binding JSONB
-- traversal in the acceptance UID parity branch. This closes the final
-- text-to-JSON coercion without changing the 684 authority or normal reads.
BEGIN;
SET LOCAL lock_timeout='10s'; SET LOCAL statement_timeout='90s';
SELECT pg_advisory_xact_lock(hashtextextended('pdc-staging-720-agentic-acceptance-uid-traversal',0));
LOCK TABLE supabase_migrations.schema_migrations IN EXCLUSIVE MODE;
DO $guard$
DECLARE h text;
BEGIN SELECT encode(extensions.digest(convert_to(p.prosrc,'UTF8'),'sha256'),'hex') INTO h FROM pg_proc p WHERE p.oid='public.execute_pdc_agentic_email_action_502(jsonb)'::regprocedure;
 IF current_user<>'postgres' OR session_user<>'postgres' OR (SELECT count(*) FROM public.pdc_staging_environment_sentinel WHERE singleton AND project_ref='cdsmnqxtyyoeoznmbidd')<>1 OR to_regclass('public.pdc_production_environment_sentinel') IS NOT NULL OR lower(coalesce(current_setting('app.environment',true),''))='production' OR (SELECT max(version) FROM supabase_migrations.schema_migrations WHERE version~'^[0-9]{14}$')<>'20260828410000' OR h<>'b3855874fb8cce643367d44755b0cd49a15fe05274d5fbaba3a57ceb4be901e7' OR to_regclass('public.pdc_authenticated_agentic_acceptance_uid_traversal_history_720') IS NOT NULL THEN RAISE EXCEPTION 'PDC_720_EXACT_719_EXECUTE_PREDECESSOR_MISMATCH' USING errcode='55000'; END IF; END $guard$;
CREATE TABLE public.pdc_authenticated_agentic_acceptance_uid_traversal_history_720(history_id uuid PRIMARY KEY DEFAULT gen_random_uuid(),event_key text NOT NULL UNIQUE,event_kind text NOT NULL CHECK(event_kind='agentic_acceptance_uid_traversal'),predecessor_head text NOT NULL CHECK(predecessor_head='20260828410000'),successor_head text NOT NULL CHECK(successor_head='20260828420000'),predecessor_function_sha256 text NOT NULL CHECK(predecessor_function_sha256='b3855874fb8cce643367d44755b0cd49a15fe05274d5fbaba3a57ceb4be901e7'),successor_function_sha256 text NOT NULL,repair_contract text NOT NULL,production_writes boolean NOT NULL CHECK(NOT production_writes),task_enabled boolean NOT NULL CHECK(NOT task_enabled),mailbox_contacted boolean NOT NULL CHECK(NOT mailbox_contacted),uid514_processed boolean NOT NULL CHECK(NOT uid514_processed),created_at timestamptz NOT NULL DEFAULT clock_timestamp());
ALTER TABLE public.pdc_authenticated_agentic_acceptance_uid_traversal_history_720 ENABLE ROW LEVEL SECURITY; ALTER TABLE public.pdc_authenticated_agentic_acceptance_uid_traversal_history_720 FORCE ROW LEVEL SECURITY; REVOKE ALL ON public.pdc_authenticated_agentic_acceptance_uid_traversal_history_720 FROM public,anon,authenticated,service_role,pdc_email_monitor;
CREATE FUNCTION public.pdc_authenticated_agentic_acceptance_uid_traversal_history_immutable_720() RETURNS trigger LANGUAGE plpgsql SECURITY DEFINER SET search_path=pg_catalog,public AS $$ BEGIN RAISE EXCEPTION 'PDC_720_ACCEPTANCE_UID_TRAVERSAL_HISTORY_IMMUTABLE' USING errcode='55000'; END $$;
REVOKE ALL ON FUNCTION public.pdc_authenticated_agentic_acceptance_uid_traversal_history_immutable_720() FROM public,anon,authenticated,service_role,pdc_email_monitor;
CREATE TRIGGER pdc_authenticated_agentic_acceptance_uid_traversal_history_immutable_720 BEFORE UPDATE OR DELETE ON public.pdc_authenticated_agentic_acceptance_uid_traversal_history_720 FOR EACH ROW EXECUTE FUNCTION public.pdc_authenticated_agentic_acceptance_uid_traversal_history_immutable_720();
DO $repair$
DECLARE d text;before_sha text;after_sha text;old text;new text;
BEGIN
 SELECT pg_get_functiondef('public.execute_pdc_agentic_email_action_502(jsonb)'::regprocedure),encode(extensions.digest(convert_to(p.prosrc,'UTF8'),'sha256'),'hex') INTO d,before_sha FROM pg_proc p WHERE p.oid='public.execute_pdc_agentic_email_action_502(jsonb)'::regprocedure;
 old:=$old$p_action->'source_binding'->>'provider_uid'$old$; new:=$new$(p_action->'source_binding')->>'provider_uid'$new$;
 IF before_sha<>'b3855874fb8cce643367d44755b0cd49a15fe05274d5fbaba3a57ceb4be901e7' OR position(old IN d)=0 THEN RAISE EXCEPTION 'PDC_720_UID_TRAVERSAL_ANCHOR_MISMATCH' USING errcode='55000'; END IF;
 d:=replace(d,old,new); EXECUTE d;
 SELECT encode(extensions.digest(convert_to(p.prosrc,'UTF8'),'sha256'),'hex') INTO after_sha FROM pg_proc p WHERE p.oid='public.execute_pdc_agentic_email_action_502(jsonb)'::regprocedure;
 INSERT INTO public.pdc_authenticated_agentic_acceptance_uid_traversal_history_720(event_key,event_kind,predecessor_head,successor_head,predecessor_function_sha256,successor_function_sha256,repair_contract,production_writes,task_enabled,mailbox_contacted,uid514_processed) VALUES(encode(extensions.digest(convert_to('pdc-staging-720-agentic-acceptance-uid-traversal|forward','UTF8'),'sha256'),'hex'),'agentic_acceptance_uid_traversal','20260828410000','20260828420000',before_sha,after_sha,'Parenthesize only the nested source_binding field traversal used by the exact synthetic UID>=515 acceptance branch; retain strict actor/fixture wrapper authority and normal 502 behavior',false,false,false,false);
END $repair$;
DO $post$ BEGIN IF (SELECT count(*) FROM public.pdc_authenticated_agentic_acceptance_uid_traversal_history_720)<>1 OR position($needle$(p_action->'source_binding')->>'provider_uid'$needle$ IN (SELECT p.prosrc FROM pg_proc p WHERE p.oid='public.execute_pdc_agentic_email_action_502(jsonb)'::regprocedure))=0 OR to_regclass('public.pdc_production_environment_sentinel') IS NOT NULL THEN RAISE EXCEPTION 'PDC_720_POSTCONDITION_FAILED' USING errcode='55000'; END IF; END $post$;
INSERT INTO supabase_migrations.schema_migrations(version,name,statements) VALUES('20260828420000','720_agentic_acceptance_uid_traversal',ARRAY['Exact 719 predecessor and strict execute hash guard','Parenthesize nested source_binding provider UID traversal in the exact acceptance branch','Normal Board/read filters, UID514/task/mailbox/outbound and Production untouched']);
NOTIFY pgrST,'reload schema'; COMMIT;
