-- STAGING ONLY 684: exact authenticated provider/import/agentic compatibility.
-- Append-only successor. It does not process UID514, create vehicles, enable the
-- task, contact a mailbox, send email, delete evidence, or write Production.
BEGIN;
SET LOCAL lock_timeout='10s';
SET LOCAL statement_timeout='180s';
SELECT pg_advisory_xact_lock(hashtextextended('pdc-staging-684-authenticated-provider-import-agentic-compatibility',0));
LOCK TABLE supabase_migrations.schema_migrations IN EXCLUSIVE MODE;

DO $guard$
DECLARE h text; x integer;
BEGIN
  SELECT encode(extensions.digest(convert_to(p.prosrc,'UTF8'),'sha256'),'hex') INTO h FROM pg_proc p WHERE p.oid='public.pdc_monitor_actor_scope()'::regprocedure;
  IF current_user<>'postgres' OR session_user<>'postgres'
     OR (SELECT count(*) FROM public.pdc_staging_environment_sentinel WHERE singleton AND project_ref='cdsmnqxtyyoeoznmbidd')<>1
     OR to_regclass('public.pdc_production_environment_sentinel') IS NOT NULL
     OR lower(coalesce(current_setting('app.environment',true),''))='production'
     OR (SELECT count(*) FROM supabase_migrations.schema_migrations WHERE version='20260828010000' AND name='683_uid514_capability_mint_replay_repair')<>1
     OR (SELECT count(*) FROM supabase_migrations.schema_migrations WHERE version='20260828020000' AND name='714_fail_closed_navision_family_catalog_hardening')<>1
     OR (SELECT count(*) FROM supabase_migrations.schema_migrations WHERE version='20260828030000' AND name='715_remove_leaked_navision_714_test_probes')<>1
     OR (SELECT count(*) FROM supabase_migrations.schema_migrations WHERE version='20260828040000' AND name='716_close_all_raw_navision_acl_grantees')<>1
     OR (SELECT max(version) FROM supabase_migrations.schema_migrations WHERE version~'^[0-9]{14}$')<>'20260828040000'
     OR to_regclass('public.pdc_authenticated_provider_import_agentic_compatibility_controls_684') IS NOT NULL
     OR to_regclass('public.pdc_authenticated_provider_import_agentic_compatibility_history_684') IS NOT NULL
     OR to_regprocedure('public.pdc_monitor_authenticated_uid514_claim_scope_684(text,uuid,uuid,uuid,text,text)') IS NOT NULL
     OR to_regprocedure('public.pdc_monitor_authenticated_uid514_source_scope_684(jsonb)') IS NOT NULL
     OR to_regprocedure('public.attest_pdc_monitor_provider_email_observation_684(text,uuid,uuid,uuid,text,text,text,text,jsonb)') IS NOT NULL
     OR to_regprocedure('public.import_pdc_monitor_jobcard_attachment_authenticated_684(text,uuid,uuid,uuid,text,text,jsonb,jsonb,jsonb,jsonb)') IS NOT NULL
     OR to_regprocedure('public.read_pdc_monitor_jobcard_attachment_receipt_authenticated_684(text,uuid,uuid,uuid,text,text,uuid)') IS NOT NULL
     OR to_regprocedure('public.read_pdc_agentic_email_context_authenticated_684(jsonb)') IS NOT NULL
     OR to_regprocedure('public.record_pdc_agentic_email_plan_authenticated_684(jsonb)') IS NOT NULL
     OR to_regprocedure('public.execute_pdc_agentic_email_action_authenticated_684(jsonb)') IS NOT NULL
     OR to_regprocedure('public.pdc_agentic_apply_action_authenticated_684(uuid)') IS NOT NULL
     OR to_regprocedure('public.finalize_pdc_agentic_email_plan_authenticated_684(jsonb)') IS NOT NULL
     OR h<>'fbdada6560ea401c0ba4f721eada6353225398df24e851be041fad58c4699b08'
     OR (SELECT encode(extensions.digest(convert_to(p.prosrc,'UTF8'),'sha256'),'hex') FROM pg_proc p WHERE p.oid='public.attest_pdc_provider_email_observation(uuid,uuid,text,text,text,text,jsonb)'::regprocedure)<>'7be3241ac65da67024907c2afd1f47d3d82ca429960d3f1464dc56d489c8e0dd'
     OR (SELECT encode(extensions.digest(convert_to(p.prosrc,'UTF8'),'sha256'),'hex') FROM pg_proc p WHERE p.oid='public.import_pdc_monitor_jobcard_attachment_279(text,uuid,uuid,text,text,jsonb,jsonb,jsonb,jsonb)'::regprocedure)<>'ac656b019e863fba781e2280655cba2a9f8a00ae432939699839a1d902508266'
     OR (SELECT encode(extensions.digest(convert_to(p.prosrc,'UTF8'),'sha256'),'hex') FROM pg_proc p WHERE p.oid='public.read_pdc_monitor_jobcard_attachment_receipt_279(text,uuid)'::regprocedure)<>'695bb6dedcad700ac81c221f14cf9607707417691f27df58a0a5fbb42c10c1fa'
     OR (SELECT encode(extensions.digest(convert_to(p.prosrc,'UTF8'),'sha256'),'hex') FROM pg_proc p WHERE p.oid='public.pdc_agentic_email_source_authorized_502(jsonb)'::regprocedure)<>'55161035e5ec36c10d2df3b84ec85f937d9287c55163f87d7f4d2335d24b3f79'
     OR (SELECT encode(extensions.digest(convert_to(p.prosrc,'UTF8'),'sha256'),'hex') FROM pg_proc p WHERE p.oid='public.pdc_agentic_email_authorized_502()'::regprocedure)<>'23b7447ff343f51e1dcc19916316db89920b627a85002ce0d6433251f11e1621'
     OR (SELECT count(*) FROM public.ai_email_intake WHERE id='102e286d-1799-4c97-8e45-e0da9fb31c63'::uuid AND provider_uid='imap_uid:514' AND source_hash='440d174b6e1994fbb1afb9c285f068cb62b130f541ebaa834d590f44bdbec280' AND status='failed')<>1
     OR (SELECT count(*) FROM public.pdc_uid514_recovery_authorizations_257 WHERE recovery_event_id=25751401 AND intake_id='102e286d-1799-4c97-8e45-e0da9fb31c63'::uuid AND attachment_count=7 AND parent_source_hash='440d174b6e1994fbb1afb9c285f068cb62b130f541ebaa834d590f44bdbec280')<>1
     OR (SELECT count(*) FROM public.pdc_uid514_attachment_selection_673 WHERE recovery_event_id=25751401 AND intake_id='102e286d-1799-4c97-8e45-e0da9fb31c63'::uuid AND observed_mime_part_count=7 AND retained_authenticated_attachment_count=4 AND all_mime_parts_retained AND qualifying_attachment_sha256='9a8f412ec5c9e108817da26b20993fa0a5e61a54f7ac983673c1ef9e2d8af8f4')<>1
     OR (SELECT count(*) FROM public.ai_email_attachments WHERE intake_id='102e286d-1799-4c97-8e45-e0da9fb31c63'::uuid)<>7
     OR (SELECT count(*) FROM public.ai_email_attachments WHERE intake_id='102e286d-1799-4c97-8e45-e0da9fb31c63'::uuid AND text_extraction_status='extracted')<>4
     OR (SELECT count(*) FROM public.pdc_provider_email_observations WHERE intake_id='102e286d-1799-4c97-8e45-e0da9fb31c63'::uuid)<>0
     OR (SELECT count(*) FROM public.vehicles WHERE public.normalize_vehicle_stock_number(stock_number)='13016925')<>0
     OR (SELECT count(*) FROM public.pdc_email_monitor_pilot WHERE singleton AND (enabled OR automatic_rule_application OR automatic_authenticated_jobcards OR outbound_email_enabled))<>0
     OR (SELECT count(*) FROM public.monitored_mailboxes WHERE active)<>1
  THEN RAISE EXCEPTION 'PDC_684_EXACT_683_716_PREDECESSOR_OR_RETAINED_UID514_MISMATCH' USING errcode='55000'; END IF;
END
$guard$;

CREATE TABLE public.pdc_authenticated_provider_import_agentic_compatibility_controls_684(
  singleton boolean PRIMARY KEY DEFAULT true CHECK(singleton), enabled boolean NOT NULL DEFAULT true,
  actor_id uuid NOT NULL CHECK(actor_id='df7c55d9-6ba0-47f6-ba16-44d6ae2c2a4b'),
  actor_email text NOT NULL CHECK(actor_email='sales@broometoyota.com.au'), jwt_role text NOT NULL CHECK(jwt_role='authenticated'),
  server_application_role text NOT NULL CHECK(server_application_role='importer'),
  gateway_instance_id text NOT NULL CHECK(gateway_instance_id='pdc-monitor-staging-sales-uid509-v1'),
  release_name text NOT NULL CHECK(release_name='pdc-monitor-staging-m502-2026.08.44'),
  source_sha text NOT NULL CHECK(source_sha='e850c319989d98b45b95a28aa815d78e2c2e3a4b'),
  manifest_sha256 text NOT NULL CHECK(manifest_sha256='d48b49f6598a99fbef99fc4f0d0ab36b8b47576b8ff7cd8ecd2cb64d6cfed58d'),
  planner_sha256 text NOT NULL CHECK(planner_sha256='7e08a00bc099610aa919bb7c3089ef84b91a74bafd69f95fab06bfccfdf67348'),
  trust_receipt_sha256 text NOT NULL CHECK(trust_receipt_sha256='e3e30ace04e676e34f271b161283b9e4764d462f76428d63826fa3cb153d7227'),
  mailbox_id uuid NOT NULL CHECK(mailbox_id='12fe383d-5c1e-5801-96e4-f67cf3e3bb57'), mailbox_key text NOT NULL CHECK(mailbox_key='pdc_pmb_email'),
  mailbox_address text NOT NULL CHECK(mailbox_address='pmbcontroller@gmail.com'), provider text NOT NULL CHECK(provider='gmail'),
  mailbox_folder text NOT NULL CHECK(mailbox_folder='Inbox'), mailbox_uidvalidity bigint NOT NULL CHECK(mailbox_uidvalidity=1), mailbox_uid bigint NOT NULL CHECK(mailbox_uid=514),
  recovery_event_id integer NOT NULL CHECK(recovery_event_id=25751401), parent_source_hash text NOT NULL CHECK(parent_source_hash='440d174b6e1994fbb1afb9c285f068cb62b130f541ebaa834d590f44bdbec280'),
  all_attachment_hashes text[] NOT NULL, pdf_hashes text[] NOT NULL, job_card_sha256 text NOT NULL CHECK(job_card_sha256='9a8f412ec5c9e108817da26b20993fa0a5e61a54f7ac983673c1ef9e2d8af8f4'),
  observed_mime_part_count integer NOT NULL CHECK(observed_mime_part_count=7), retained_authenticated_attachment_count integer NOT NULL CHECK(retained_authenticated_attachment_count=4),
  source_total_hours numeric(10,2) NOT NULL CHECK(source_total_hours=7.46), stale_expected_hours numeric(10,2) NOT NULL CHECK(stale_expected_hours=13.10),
  task_enabled boolean NOT NULL DEFAULT false CHECK(NOT task_enabled), mailbox_contacted boolean NOT NULL DEFAULT false CHECK(NOT mailbox_contacted), uid514_processed boolean NOT NULL DEFAULT false CHECK(NOT uid514_processed), production_writes boolean NOT NULL DEFAULT false CHECK(NOT production_writes),
  changed_at timestamptz NOT NULL DEFAULT clock_timestamp()
);
ALTER TABLE public.pdc_authenticated_provider_import_agentic_compatibility_controls_684 ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.pdc_authenticated_provider_import_agentic_compatibility_controls_684 FORCE ROW LEVEL SECURITY;
REVOKE ALL ON public.pdc_authenticated_provider_import_agentic_compatibility_controls_684 FROM public,anon,authenticated,service_role,pdc_email_monitor;
INSERT INTO public.pdc_authenticated_provider_import_agentic_compatibility_controls_684(
 actor_id,actor_email,jwt_role,server_application_role,gateway_instance_id,release_name,source_sha,manifest_sha256,planner_sha256,trust_receipt_sha256,
 mailbox_id,mailbox_key,mailbox_address,provider,mailbox_folder,mailbox_uidvalidity,mailbox_uid,recovery_event_id,parent_source_hash,all_attachment_hashes,pdf_hashes,job_card_sha256,observed_mime_part_count,retained_authenticated_attachment_count,source_total_hours,stale_expected_hours)
VALUES('df7c55d9-6ba0-47f6-ba16-44d6ae2c2a4b','sales@broometoyota.com.au','authenticated','importer','pdc-monitor-staging-sales-uid509-v1','pdc-monitor-staging-m502-2026.08.44','e850c319989d98b45b95a28aa815d78e2c2e3a4b','d48b49f6598a99fbef99fc4f0d0ab36b8b47576b8ff7cd8ecd2cb64d6cfed58d','7e08a00bc099610aa919bb7c3089ef84b91a74bafd69f95fab06bfccfdf67348','e3e30ace04e676e34f271b161283b9e4764d462f76428d63826fa3cb153d7227','12fe383d-5c1e-5801-96e4-f67cf3e3bb57','pdc_pmb_email','pmbcontroller@gmail.com','gmail','Inbox',1,514,25751401,'440d174b6e1994fbb1afb9c285f068cb62b130f541ebaa834d590f44bdbec280',
 ARRAY['7bc4e2dec9b1c405098f1ca7b4c646bf3262158e328f9f548abb855b8ef2f21a','ffaa2bfbca036f9dbcbe10de9a43f8a141fd2a84f9fea75c0e114b96b87b4cf3','c60dae99a28cdccdee51f5bdffa43382d9b7eb31af690c31caedcc8d4f66cf40','9a8f412ec5c9e108817da26b20993fa0a5e61a54f7ac983673c1ef9e2d8af8f4','66b790ba3a72760e00a034bf7f5cf5a7e1defe5d6947373216f8c8dc4ed8acff','b297f4f9070f6c78c88aae099630b78bb5157c3094c45a30b5cfef0f263ac3b1','ea248634b8610f757907c519ea2f7ba243fb1602c8114cbde947707aff8407ae'],
 ARRAY['9a8f412ec5c9e108817da26b20993fa0a5e61a54f7ac983673c1ef9e2d8af8f4','66b790ba3a72760e00a034bf7f5cf5a7e1defe5d6947373216f8c8dc4ed8acff','b297f4f9070f6c78c88aae099630b78bb5157c3094c45a30b5cfef0f263ac3b1','ea248634b8610f757907c519ea2f7ba243fb1602c8114cbde947707aff8407ae'], '9a8f412ec5c9e108817da26b20993fa0a5e61a54f7ac983673c1ef9e2d8af8f4',7,4,7.46,13.10);

CREATE TABLE public.pdc_authenticated_provider_import_agentic_compatibility_history_684(
 history_id uuid PRIMARY KEY DEFAULT gen_random_uuid(), event_key text NOT NULL UNIQUE,
 event_kind text NOT NULL CHECK(event_kind IN('forward_compatibility','rollback')), predecessor_head text NOT NULL CHECK(predecessor_head='20260828040000'), successor_head text NOT NULL CHECK(successor_head='20260828050000'),
 actor_id uuid NOT NULL CHECK(actor_id='df7c55d9-6ba0-47f6-ba16-44d6ae2c2a4b'), actor_email text NOT NULL CHECK(actor_email='sales@broometoyota.com.au'), jwt_role text NOT NULL CHECK(jwt_role='authenticated'), server_application_role text NOT NULL CHECK(server_application_role='importer'),
 gateway_instance_id text NOT NULL CHECK(gateway_instance_id='pdc-monitor-staging-sales-uid509-v1'), release_name text NOT NULL CHECK(release_name='pdc-monitor-staging-m502-2026.08.44'), source_sha text NOT NULL CHECK(source_sha='e850c319989d98b45b95a28aa815d78e2c2e3a4b'), manifest_sha256 text NOT NULL CHECK(manifest_sha256='d48b49f6598a99fbef99fc4f0d0ab36b8b47576b8ff7cd8ecd2cb64d6cfed58d'), planner_sha256 text NOT NULL CHECK(planner_sha256='7e08a00bc099610aa919bb7c3089ef84b91a74bafd69f95fab06bfccfdf67348'), trust_receipt_sha256 text NOT NULL CHECK(trust_receipt_sha256='e3e30ace04e676e34f271b161283b9e4764d462f76428d63826fa3cb153d7227'), recovery_event_id integer NOT NULL CHECK(recovery_event_id=25751401), parent_source_hash text NOT NULL CHECK(parent_source_hash='440d174b6e1994fbb1afb9c285f068cb62b130f541ebaa834d590f44bdbec280'),
 before_state jsonb NOT NULL, after_state jsonb NOT NULL, predecessor_function_hashes jsonb NOT NULL, successor_function_hashes jsonb NOT NULL, source_total_hours numeric(10,2) NOT NULL CHECK(source_total_hours=7.46), stale_expected_hours numeric(10,2) NOT NULL CHECK(stale_expected_hours=13.10), task_enabled boolean NOT NULL CHECK(NOT task_enabled), mailbox_contacted boolean NOT NULL CHECK(NOT mailbox_contacted), uid514_processed boolean NOT NULL CHECK(NOT uid514_processed), production_writes boolean NOT NULL CHECK(NOT production_writes), rollback_contract text NOT NULL, created_at timestamptz NOT NULL DEFAULT clock_timestamp()
);
CREATE FUNCTION public.pdc_authenticated_provider_import_agentic_compatibility_history_immutable_684() RETURNS trigger LANGUAGE plpgsql SECURITY DEFINER SET search_path=pg_catalog,public AS $immutable$ BEGIN RAISE EXCEPTION 'PDC_684_COMPATIBILITY_HISTORY_IMMUTABLE' USING errcode='55000'; END $immutable$;
CREATE TRIGGER pdc_authenticated_provider_import_agentic_compatibility_history_immutable_684 BEFORE UPDATE OR DELETE ON public.pdc_authenticated_provider_import_agentic_compatibility_history_684 FOR EACH ROW EXECUTE FUNCTION public.pdc_authenticated_provider_import_agentic_compatibility_history_immutable_684();
ALTER TABLE public.pdc_authenticated_provider_import_agentic_compatibility_history_684 ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.pdc_authenticated_provider_import_agentic_compatibility_history_684 FORCE ROW LEVEL SECURITY;
REVOKE ALL ON public.pdc_authenticated_provider_import_agentic_compatibility_history_684 FROM public,anon,authenticated,service_role,pdc_email_monitor;

CREATE FUNCTION public.pdc_monitor_authenticated_uid514_claim_scope_684(p_gateway text,p_claim_token uuid,p_intake_id uuid,p_attachment_id uuid,p_parent_hash text,p_attachment_hash text)
RETURNS jsonb LANGUAGE plpgsql STABLE SECURITY DEFINER SET search_path=pg_catalog,public,auth,extensions AS $scope$
DECLARE i public.ai_email_intake%rowtype; m public.monitored_mailboxes%rowtype; a public.ai_email_attachments%rowtype; z public.pdc_uid514_recovery_authorizations_257%rowtype; s public.pdc_uid514_attachment_selection_673%rowtype; c public.pdc_authenticated_provider_import_agentic_compatibility_controls_684%rowtype; ok boolean:=false;
BEGIN
 IF NOT public.pdc_authenticated_provider_import_agentic_compatibility_enabled_684() OR NOT public.pdc_monitor_authenticated_active_scope_674(p_gateway) THEN RETURN jsonb_build_object('ok',false,'code','authenticated_uid514_scope_required'); END IF;
 SELECT * INTO c FROM public.pdc_authenticated_provider_import_agentic_compatibility_controls_684 WHERE singleton AND enabled;
 SELECT * INTO i FROM public.ai_email_intake WHERE id=p_intake_id AND provider_uid='imap_uid:514' AND source_hash='440d174b6e1994fbb1afb9c285f068cb62b130f541ebaa834d590f44bdbec280' AND status='processing' AND locked_by=auth.uid() AND claim_token=p_claim_token AND gateway_instance_id=p_gateway AND locked_at>=clock_timestamp()-interval '10 minutes';
 SELECT * INTO m FROM public.monitored_mailboxes WHERE id=i.monitored_mailbox_id AND id=c.mailbox_id AND active AND mailbox_key=c.mailbox_key AND lower(mailbox_address)=c.mailbox_address AND lower(provider)=c.provider AND test_mode;
 SELECT * INTO z FROM public.pdc_uid514_recovery_authorizations_257 WHERE recovery_event_id=25751401 AND intake_id=p_intake_id AND parent_source_hash=p_parent_hash AND mailbox_uidvalidity=1 AND mailbox_uid=514 AND qualifying_attachment_sha256=c.job_card_sha256 AND attachment_count=7;
 SELECT * INTO s FROM public.pdc_uid514_attachment_selection_673 WHERE recovery_event_id=25751401 AND intake_id=p_intake_id AND parent_source_hash=p_parent_hash AND observed_mime_part_count=7 AND retained_authenticated_attachment_count=4 AND all_mime_parts_retained AND qualifying_attachment_sha256=c.job_card_sha256;
 SELECT * INTO a FROM public.ai_email_attachments WHERE id=p_attachment_id AND intake_id=p_intake_id AND source_hash=p_attachment_hash AND source_hash=c.job_card_sha256 AND content_type='application/pdf' AND file_name='J139125482 - _13016925.pdf' AND size_bytes=72551 AND storage_path='pdc-email-intake-private/9a8f412ec5c9e108817da26b20993fa0a5e61a54f7ac983673c1ef9e2d8af8f4/J139125482 - _13016925.pdf';
 ok:=i.id IS NOT NULL AND m.id IS NOT NULL AND z.recovery_event_id IS NOT NULL AND s.selection_id IS NOT NULL AND a.id IS NOT NULL AND p_parent_hash=c.parent_source_hash AND p_gateway=c.gateway_instance_id AND p_intake_id=z.intake_id AND p_attachment_id=s.job_card_attachment_id AND NOT c.task_enabled AND NOT c.mailbox_contacted AND NOT c.uid514_processed AND NOT c.production_writes;
 IF NOT ok THEN RETURN jsonb_build_object('ok',false,'code','authenticated_uid514_scope_required'); END IF;
 RETURN jsonb_build_object('ok',true,'code','authenticated_uid514_scope_verified','actor_id',auth.uid(),'actor_email',c.actor_email,'jwt_role',c.jwt_role,'server_application_role',c.server_application_role,'gateway_instance_id',c.gateway_instance_id,'release_name',c.release_name,'source_sha',c.source_sha,'manifest_sha256',c.manifest_sha256,'planner_sha256',c.planner_sha256,'trust_receipt_sha256',c.trust_receipt_sha256,'mailbox_id',c.mailbox_id,'recovery_event_id',c.recovery_event_id,'intake_id',i.id,'attachment_id',a.id,'parent_source_hash',c.parent_source_hash,'attachment_source_hash',a.source_hash,'observed_mime_part_count',7,'retained_authenticated_attachment_count',4,'all_mime_parts_retained',true,'task_enabled',false,'mailbox_contacted',false,'uid514_processed',false,'production_writes',false);
EXCEPTION WHEN others THEN RETURN jsonb_build_object('ok',false,'code','authenticated_uid514_scope_required');
END $scope$;

CREATE FUNCTION public.pdc_authenticated_provider_import_agentic_compatibility_enabled_684() RETURNS boolean LANGUAGE sql STABLE SECURITY DEFINER SET search_path=pg_catalog,public AS $$ SELECT EXISTS(SELECT 1 FROM public.pdc_authenticated_provider_import_agentic_compatibility_controls_684 WHERE singleton AND enabled AND NOT task_enabled AND NOT mailbox_contacted AND NOT uid514_processed AND NOT production_writes) $$;
CREATE FUNCTION public.pdc_monitor_authenticated_uid514_source_scope_684(p_evidence jsonb)
RETURNS boolean LANGUAGE plpgsql STABLE SECURITY DEFINER SET search_path=pg_catalog,public,auth,extensions AS $source$
DECLARE i public.ai_email_intake%rowtype; o public.pdc_provider_email_observations%rowtype; s public.pdc_uid514_attachment_selection_673%rowtype; c public.pdc_authenticated_provider_import_agentic_compatibility_controls_684%rowtype; q uuid; ok boolean:=false;
BEGIN
 IF jsonb_typeof(p_evidence)<>'object' OR p_evidence->>'intake_id' IS DISTINCT FROM '102e286d-1799-4c97-8e45-e0da9fb31c63' OR NOT public.pdc_authenticated_provider_import_agentic_compatibility_enabled_684() OR NOT public.pdc_monitor_authenticated_active_scope_674(p_evidence->>'gateway_instance_id') THEN RETURN false; END IF;
 q:=nullif(p_evidence->>'claim_token','')::uuid;
 SELECT * INTO c FROM public.pdc_authenticated_provider_import_agentic_compatibility_controls_684 WHERE singleton AND enabled;
 SELECT * INTO i FROM public.ai_email_intake WHERE id='102e286d-1799-4c97-8e45-e0da9fb31c63'::uuid AND provider_uid='imap_uid:514' AND status='processing' AND locked_by=auth.uid() AND claim_token=q AND gateway_instance_id=c.gateway_instance_id AND locked_at>=clock_timestamp()-interval '10 minutes' AND lower(source_hash)=lower(p_evidence->>'source_hash') AND coalesce(nullif(btrim(internet_message_id),''),graph_message_id)=p_evidence->>'message_id' AND lower(btrim(sender_email))=lower(btrim(p_evidence->>'sender')) AND received_at=nullif(p_evidence->>'received_at','')::timestamptz AND lower(btrim(recipient_mailbox))=lower(btrim(p_evidence->>'recipient_mailbox')) AND provider_uid=p_evidence->>'provider_uid' AND lower(provider_authserv_id)=lower(p_evidence->>'provider_authserv_id') AND provider_authentication=p_evidence->'provider_authentication';
 SELECT * INTO o FROM public.pdc_provider_email_observations WHERE intake_id=i.id AND attachment_id=(SELECT job_card_attachment_id FROM public.pdc_uid514_attachment_selection_673 WHERE recovery_event_id=25751401 AND intake_id=i.id) AND parent_source_hash=c.parent_source_hash AND provider_message_id=p_evidence->>'message_id' AND provider_authserv_id='mx.google.com' AND authentication=jsonb_build_object('dkim_aligned',false,'dmarc_aligned',true,'gmail_authentication_results',true,'sender_domain','pmgwa.com.au','spf_aligned',true);
 SELECT * INTO s FROM public.pdc_uid514_attachment_selection_673 WHERE recovery_event_id=25751401 AND intake_id=i.id AND parent_source_hash=c.parent_source_hash AND observed_mime_part_count=7 AND retained_authenticated_attachment_count=4 AND all_mime_parts_retained;
 ok:=i.id IS NOT NULL AND o.observation_id IS NOT NULL AND s.selection_id IS NOT NULL AND lower(p_evidence->>'source_hash')=c.parent_source_hash AND p_evidence->>'provider_uid'='imap_uid:514' AND p_evidence->>'recipient_mailbox'=c.mailbox_address AND lower(p_evidence->>'provider_authserv_id')='mx.google.com';
 RETURN ok;
EXCEPTION WHEN others THEN RETURN false;
END $source$;
REVOKE ALL ON FUNCTION public.pdc_authenticated_provider_import_agentic_compatibility_enabled_684() FROM public,anon,authenticated,service_role,pdc_email_monitor;
REVOKE ALL ON FUNCTION public.pdc_monitor_authenticated_uid514_claim_scope_684(text,uuid,uuid,uuid,text,text) FROM public,anon,authenticated,service_role,pdc_email_monitor;
REVOKE ALL ON FUNCTION public.pdc_monitor_authenticated_uid514_source_scope_684(jsonb) FROM public,anon,authenticated,service_role,pdc_email_monitor;

CREATE FUNCTION public.attest_pdc_monitor_provider_email_observation_684(p_gateway text,p_claim_token uuid,p_intake_id uuid,p_attachment_id uuid,p_expected_parent_hash text,p_expected_attachment_hash text,p_provider_message_id text,p_provider_authserv_id text,p_authentication jsonb)
RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path=pg_catalog,public,auth,extensions AS $attest$
DECLARE v jsonb; i public.ai_email_intake%rowtype; a public.ai_email_attachments%rowtype; e public.pdc_provider_email_observations%rowtype; h text;
BEGIN
 v:=public.pdc_monitor_authenticated_uid514_claim_scope_684(p_gateway,p_claim_token,p_intake_id,p_attachment_id,p_expected_parent_hash,p_expected_attachment_hash); IF v->>'ok'<>'true' THEN RETURN public.navision_backend_response(false,'authenticated_uid514_scope_required'); END IF;
 SELECT * INTO i FROM public.ai_email_intake WHERE id=p_intake_id; SELECT * INTO a FROM public.ai_email_attachments WHERE id=p_attachment_id AND intake_id=p_intake_id;
 IF p_expected_parent_hash<>'440d174b6e1994fbb1afb9c285f068cb62b130f541ebaa834d590f44bdbec280' OR p_expected_attachment_hash<>'9a8f412ec5c9e108817da26b20993fa0a5e61a54f7ac983673c1ef9e2d8af8f4' OR p_provider_authserv_id<>'mx.google.com' OR p_provider_message_id IS DISTINCT FROM coalesce(nullif(btrim(i.internet_message_id),''),i.graph_message_id) OR p_authentication IS DISTINCT FROM i.provider_authentication OR jsonb_typeof(p_authentication)<>'object' OR (SELECT array_agg(k order by k) FROM jsonb_object_keys(p_authentication) k) IS DISTINCT FROM ARRAY['dkim_aligned','dmarc_aligned','gmail_authentication_results','sender_domain','spf_aligned']::text[] OR p_authentication<>jsonb_build_object('dkim_aligned',false,'dmarc_aligned',true,'gmail_authentication_results',true,'sender_domain','pmgwa.com.au','spf_aligned',true) THEN RETURN public.navision_backend_response(false,'provider_observation_binding_mismatch'); END IF;
 h:=encode(extensions.digest(convert_to(jsonb_build_object('contract_version','684.1','intake_id',p_intake_id,'attachment_id',p_attachment_id,'parent_source_hash',p_expected_parent_hash,'attachment_source_hash',p_expected_attachment_hash,'provider_message_id',p_provider_message_id,'provider_authserv_id',p_provider_authserv_id,'authentication',p_authentication)::text,'UTF8'),'sha256'),'hex');
 PERFORM pg_advisory_xact_lock(hashtextextended('pdc-provider-email-observation-684:'||p_intake_id::text||':'||p_attachment_id::text,0));
 SELECT * INTO e FROM public.pdc_provider_email_observations WHERE intake_id=p_intake_id AND attachment_id=p_attachment_id;
 IF FOUND THEN IF e.request_sha256<>h THEN RETURN public.navision_backend_response(false,'provider_observation_replay_conflict'); END IF; RETURN public.navision_backend_response(true,'provider_observation_already_attested',jsonb_build_object('observation_id',e.observation_id,'request_sha256',e.request_sha256)); END IF;
 INSERT INTO public.pdc_provider_email_observations(contract_version,intake_id,attachment_id,parent_source_hash,attachment_source_hash,provider_message_id,provider_authserv_id,authentication,request_sha256,attested_by,attested_authority) VALUES('159.2',p_intake_id,p_attachment_id,p_expected_parent_hash,p_expected_attachment_hash,p_provider_message_id,p_provider_authserv_id,p_authentication,h,auth.uid(),'authenticated_provider_684') RETURNING * INTO e;
 RETURN public.navision_backend_response(true,'provider_observation_attested',jsonb_build_object('observation_id',e.observation_id,'request_sha256',e.request_sha256));
END $attest$;
REVOKE ALL ON FUNCTION public.attest_pdc_monitor_provider_email_observation_684(text,uuid,uuid,uuid,text,text,text,text,jsonb) FROM public,anon,service_role,pdc_email_monitor;
GRANT EXECUTE ON FUNCTION public.attest_pdc_monitor_provider_email_observation_684(text,uuid,uuid,uuid,text,text,text,text,jsonb) TO authenticated;
REVOKE ALL ON FUNCTION public.attest_pdc_provider_email_observation(uuid,uuid,text,text,text,text,jsonb) FROM public,anon,authenticated,service_role,pdc_email_monitor;
REVOKE ALL ON FUNCTION public.import_pdc_monitor_jobcard_attachment_279(text,uuid,uuid,text,text,jsonb,jsonb,jsonb,jsonb) FROM public,anon,authenticated,service_role,pdc_email_monitor;
REVOKE ALL ON FUNCTION public.read_pdc_monitor_jobcard_attachment_receipt_279(text,uuid) FROM public,anon,authenticated,service_role,pdc_email_monitor;
REVOKE ALL ON FUNCTION public.import_pdc_jobcard_attachment_canonical(uuid,uuid,text,text,jsonb,jsonb,jsonb,jsonb) FROM public,anon,authenticated,service_role,pdc_email_monitor;
REVOKE ALL ON FUNCTION public.read_pdc_jobcard_attachment_import_receipt(uuid) FROM public,anon,authenticated,service_role,pdc_email_monitor;

CREATE FUNCTION public.import_pdc_monitor_jobcard_attachment_authenticated_684(p_gateway text,p_claim_token uuid,p_intake_id uuid,p_attachment_id uuid,p_expected_parent_hash text,p_expected_attachment_hash text,p_authentication jsonb,p_email_vehicle jsonb,p_required_work jsonb,p_operation_lines jsonb)
RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path=pg_catalog,public,auth,extensions AS $import$
DECLARE v jsonb; e jsonb; o jsonb; a jsonb; r jsonb;
BEGIN
 v:=public.pdc_monitor_authenticated_uid514_claim_scope_684(p_gateway,p_claim_token,p_intake_id,p_attachment_id,p_expected_parent_hash,p_expected_attachment_hash); IF v->>'ok'<>'true' THEN RETURN public.navision_backend_response(false,'authenticated_uid514_scope_required'); END IF;
 IF p_authentication IS DISTINCT FROM jsonb_build_object('dkim_aligned',false,'dmarc_aligned',true,'gmail_authentication_results',true,'sender_domain','pmgwa.com.au','spf_aligned',true) OR p_email_vehicle->'stock_numbers' IS DISTINCT FROM '["13016925"]'::jsonb OR p_email_vehicle->>'job_card_number' IS DISTINCT FROM 'J139125482' OR p_email_vehicle->'conflicts' IS DISTINCT FROM '[]'::jsonb OR p_email_vehicle->'cancelled' IS DISTINCT FROM 'false'::jsonb OR p_required_work IS DISTINCT FROM '["fabrication","fitting"]'::jsonb OR p_operation_lines IS DISTINCT FROM '[{"source_row_no":1,"operation_no":"OP1","work_key":"owner_supplied_document","description":"Fill Fuel","estimated_hours":0},{"source_row_no":2,"operation_no":"OP2","work_key":"owner_supplied_document","description":"PDI","estimated_hours":0.70},{"source_row_no":3,"operation_no":"OP3","work_key":"fabrication","description":"HDA Tray","estimated_hours":0},{"source_row_no":4,"operation_no":"OP4","work_key":"fitting","description":"Steel Bull Bar","estimated_hours":5.18},{"source_row_no":5,"operation_no":"OP5","work_key":"fitting","description":"Tow Bar long tongue","estimated_hours":1.58}]'::jsonb THEN RETURN public.navision_backend_response(false,'source_layout_or_hours_mismatch',jsonb_build_object('source_total_hours',7.46,'stale_expected_hours_rejected',13.10,'zero_hours_preserved',true,'tow_bar_work_key','fitting')); END IF;
 IF NOT EXISTS(SELECT 1 FROM public.pdc_provider_email_observations WHERE intake_id=p_intake_id AND attachment_id=p_attachment_id AND parent_source_hash=p_expected_parent_hash AND attachment_source_hash=p_expected_attachment_hash AND authentication=p_authentication) THEN RETURN public.navision_backend_response(false,'provider_observation_required_or_mismatch'); END IF;
 e:=jsonb_build_object('authentication',p_authentication,'canonical_attachment_id',p_attachment_id::text,'canonical_document_hash',p_expected_attachment_hash,'contract_version','pmb-email-work-v2','email_vehicle',p_email_vehicle,'operation_lines',p_operation_lines,'required_work',p_required_work);
 r:=public.process_claimed_pdc_email_intake_work(p_intake_id,p_claim_token,p_gateway,p_expected_parent_hash,encode(extensions.digest(convert_to(e::text,'UTF8'),'sha256'),'hex'),e);
 RETURN r;
EXCEPTION WHEN invalid_text_representation THEN RETURN public.navision_backend_response(false,'invalid_authenticated_uid514_payload');
END $import$;
REVOKE ALL ON FUNCTION public.import_pdc_monitor_jobcard_attachment_authenticated_684(text,uuid,uuid,uuid,text,text,jsonb,jsonb,jsonb,jsonb) FROM public,anon,service_role,pdc_email_monitor;
GRANT EXECUTE ON FUNCTION public.import_pdc_monitor_jobcard_attachment_authenticated_684(text,uuid,uuid,uuid,text,text,jsonb,jsonb,jsonb,jsonb) TO authenticated;

CREATE FUNCTION public.read_pdc_monitor_jobcard_attachment_receipt_authenticated_684(p_gateway text,p_claim_token uuid,p_intake_id uuid,p_attachment_id uuid,p_expected_parent_hash text,p_expected_attachment_hash text,p_receipt_id uuid)
RETURNS jsonb LANGUAGE plpgsql STABLE SECURITY DEFINER SET search_path=pg_catalog,public,auth,extensions AS $read$
DECLARE v jsonb; r jsonb;
BEGIN
 v:=public.pdc_monitor_authenticated_uid514_claim_scope_684(p_gateway,p_claim_token,p_intake_id,p_attachment_id,p_expected_parent_hash,p_expected_attachment_hash); IF v->>'ok'<>'true' THEN RETURN public.navision_backend_response(false,'authenticated_uid514_scope_required'); END IF;
 r:=public.read_pdc_jobcard_attachment_import_receipt(p_receipt_id);
 IF r->>'ok'<>'true' OR r#>>'{data,intake_id}' IS DISTINCT FROM p_intake_id::text OR r#>>'{data,attachment_id}' IS DISTINCT FROM p_attachment_id::text OR r#>>'{data,parent_source_hash}' IS DISTINCT FROM p_expected_parent_hash OR r#>>'{data,attachment_source_hash}' IS DISTINCT FROM p_expected_attachment_hash THEN RETURN public.navision_backend_response(false,'canonical_receipt_binding_mismatch'); END IF;
 RETURN r;
END $read$;
REVOKE ALL ON FUNCTION public.read_pdc_monitor_jobcard_attachment_receipt_authenticated_684(text,uuid,uuid,uuid,text,text,uuid) FROM public,anon,service_role,pdc_email_monitor;
GRANT EXECUTE ON FUNCTION public.read_pdc_monitor_jobcard_attachment_receipt_authenticated_684(text,uuid,uuid,uuid,text,text,uuid) TO authenticated;

CREATE FUNCTION public.read_pdc_agentic_email_context_authenticated_684(p_evidence jsonb) RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path=pg_catalog,public,auth,extensions AS $$ BEGIN IF NOT public.pdc_monitor_authenticated_uid514_source_scope_684(p_evidence) THEN RETURN jsonb_build_object('ok',false,'code','authenticated_uid514_source_required','ambiguous',true,'vehicles','[]'::jsonb); END IF; RETURN public.read_pdc_agentic_email_context_502(p_evidence); END $$;
CREATE FUNCTION public.record_pdc_agentic_email_plan_authenticated_684(p_plan jsonb) RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path=pg_catalog,public,auth,extensions AS $$ BEGIN IF NOT public.pdc_monitor_authenticated_uid514_source_scope_684(p_plan->'source_binding') THEN RETURN jsonb_build_object('ok',false,'code','authenticated_uid514_source_required'); END IF; RETURN public.record_pdc_agentic_email_plan_502(p_plan); END $$;
CREATE FUNCTION public.execute_pdc_agentic_email_action_authenticated_684(p_action jsonb) RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path=pg_catalog,public,auth,extensions AS $$ BEGIN IF NOT public.pdc_monitor_authenticated_uid514_source_scope_684(p_action->'source_binding') THEN RETURN jsonb_build_object('ok',false,'code','authenticated_uid514_source_required'); END IF; RETURN public.execute_pdc_agentic_email_action_502(p_action); END $$;
CREATE FUNCTION public.pdc_agentic_apply_action_authenticated_684(p_action_receipt_id uuid) RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path=pg_catalog,public,auth,extensions AS $$ DECLARE b jsonb; BEGIN SELECT request->'source_binding' INTO b FROM public.pdc_agentic_email_action_receipts_502 WHERE action_receipt_id=p_action_receipt_id AND actor_id=auth.uid(); IF NOT public.pdc_monitor_authenticated_uid514_source_scope_684(b) THEN RETURN jsonb_build_object('ok',false,'code','authenticated_uid514_source_required'); END IF; RETURN public.pdc_agentic_apply_action_502(p_action_receipt_id); END $$;
CREATE FUNCTION public.finalize_pdc_agentic_email_plan_authenticated_684(p_result jsonb) RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path=pg_catalog,public,auth,extensions AS $$ BEGIN IF NOT public.pdc_monitor_authenticated_uid514_source_scope_684(p_result->'source_binding') THEN RETURN jsonb_build_object('ok',false,'code','authenticated_uid514_source_required'); END IF; RETURN public.finalize_pdc_agentic_email_plan_502(p_result); END $$;
REVOKE ALL ON FUNCTION public.read_pdc_agentic_email_context_authenticated_684(jsonb),public.record_pdc_agentic_email_plan_authenticated_684(jsonb),public.execute_pdc_agentic_email_action_authenticated_684(jsonb),public.pdc_agentic_apply_action_authenticated_684(uuid),public.finalize_pdc_agentic_email_plan_authenticated_684(jsonb) FROM public,anon,service_role,pdc_email_monitor;
GRANT EXECUTE ON FUNCTION public.read_pdc_agentic_email_context_authenticated_684(jsonb),public.record_pdc_agentic_email_plan_authenticated_684(jsonb),public.execute_pdc_agentic_email_action_authenticated_684(jsonb),public.pdc_agentic_apply_action_authenticated_684(uuid),public.finalize_pdc_agentic_email_plan_authenticated_684(jsonb) TO authenticated;

CREATE OR REPLACE FUNCTION public.pdc_agentic_email_source_authorized_502(p_evidence jsonb) RETURNS boolean LANGUAGE plpgsql STABLE SECURITY DEFINER SET search_path=pg_catalog,public,extensions AS $source_compat$
BEGIN
 IF p_evidence->>'intake_id'='102e286d-1799-4c97-8e45-e0da9fb31c63' THEN RETURN public.pdc_monitor_authenticated_uid514_source_scope_684(p_evidence); END IF;
 RETURN (SELECT public.pdc_email_monitor_runtime_authorized_502(p_evidence->>'gateway_instance_id') AND jsonb_typeof(p_evidence)='object' AND EXISTS(SELECT 1 FROM public.ai_email_intake i JOIN public.monitored_mailboxes m ON m.id=i.monitored_mailbox_id AND m.active JOIN public.pdc_provider_email_observations o ON o.intake_id=i.id WHERE i.id=nullif(p_evidence->>'intake_id','')::uuid AND i.status='processing' AND i.locked_by=auth.uid() AND i.claim_token=nullif(p_evidence->>'claim_token','')::uuid AND i.gateway_instance_id=p_evidence->>'gateway_instance_id' AND i.locked_at>=clock_timestamp()-interval '10 minutes' AND lower(i.source_hash)=lower(p_evidence->>'source_hash') AND coalesce(nullif(btrim(i.internet_message_id),''),i.graph_message_id)=p_evidence->>'message_id' AND lower(btrim(i.sender_email))=lower(btrim(p_evidence->>'sender')) AND i.received_at=nullif(p_evidence->>'received_at','')::timestamptz AND lower(btrim(i.recipient_mailbox))=lower(btrim(m.mailbox_address)) AND lower(btrim(i.recipient_mailbox))=lower(btrim(p_evidence->>'recipient_mailbox')) AND coalesce(i.provider_uid,'')=coalesce(p_evidence->>'provider_uid','') AND lower(coalesce(i.provider_authserv_id,''))=lower(coalesce(p_evidence->>'provider_authserv_id','')) AND coalesce(i.provider_authentication,'{}'::jsonb)=coalesce(p_evidence->'provider_authentication','{}'::jsonb) AND o.parent_source_hash=lower(p_evidence->>'source_hash') AND o.provider_message_id=p_evidence->>'message_id' AND lower(o.provider_authserv_id)='mx.google.com' AND o.authentication->'gmail_authentication_results'='true'::jsonb AND (o.authentication->'spf_aligned'='true'::jsonb OR o.authentication->'dkim_aligned'='true'::jsonb OR o.authentication->'dmarc_aligned'='true'::jsonb) AND lower(o.authentication->>'sender_domain')=split_part(lower(btrim(i.sender_email)),'@',2) AND EXISTS(SELECT 1 FROM public.pdc_monitor_exact_sender_enrollments e WHERE e.active AND e.sender_sha256=encode(extensions.digest(convert_to(lower(btrim(i.sender_email)),'UTF8'),'sha256'),'hex'))));
EXCEPTION WHEN others THEN RETURN false;
END $source_compat$;
REVOKE ALL ON FUNCTION public.pdc_agentic_email_source_authorized_502(jsonb) FROM public,anon,service_role,pdc_email_monitor;
GRANT EXECUTE ON FUNCTION public.pdc_agentic_email_source_authorized_502(jsonb) TO authenticated;

CREATE FUNCTION public.admin_rollback_pdc_authenticated_provider_import_agentic_compatibility_684(p_reason text) RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path=pg_catalog,public,auth AS $rollback$
DECLARE r public.pdc_authenticated_provider_import_agentic_compatibility_controls_684%rowtype; k text:=encode(extensions.digest(convert_to('pdc-staging-684-rollback|'||btrim(coalesce(p_reason,'')),'UTF8'),'sha256'),'hex');
BEGIN
 IF NOT public.pdc_monitor_staging_guard() OR auth.role()<>'authenticated' OR NOT EXISTS(SELECT 1 FROM public.pdc_user_roles u WHERE u.auth_user_id=auth.uid() AND u.active AND u.account_status='approved' AND u.role::text='administrator') THEN RAISE EXCEPTION 'PDC_684_ADMIN_ROLLBACK_REQUIRED' USING errcode='42501'; END IF;
 SELECT * INTO r FROM public.pdc_authenticated_provider_import_agentic_compatibility_controls_684 WHERE singleton FOR UPDATE; IF NOT FOUND THEN RAISE EXCEPTION 'PDC_684_CONTROL_MISSING' USING errcode='55000'; END IF;
 IF NOT r.enabled THEN RETURN jsonb_build_object('ok',true,'code','compatibility_rollback_replayed'); END IF;
 UPDATE public.pdc_authenticated_provider_import_agentic_compatibility_controls_684 SET enabled=false WHERE singleton;
 INSERT INTO public.pdc_authenticated_provider_import_agentic_compatibility_history_684(event_key,event_kind,predecessor_head,successor_head,actor_id,actor_email,jwt_role,server_application_role,gateway_instance_id,release_name,source_sha,manifest_sha256,planner_sha256,trust_receipt_sha256,recovery_event_id,parent_source_hash,before_state,after_state,predecessor_function_hashes,successor_function_hashes,source_total_hours,stale_expected_hours,task_enabled,mailbox_contacted,uid514_processed,production_writes,rollback_contract) VALUES(k,'rollback','20260828040000','20260828050000',r.actor_id,r.actor_email,r.jwt_role,r.server_application_role,r.gateway_instance_id,r.release_name,r.source_sha,r.manifest_sha256,r.planner_sha256,r.trust_receipt_sha256,r.recovery_event_id,r.parent_source_hash,to_jsonb(r),to_jsonb((SELECT c FROM public.pdc_authenticated_provider_import_agentic_compatibility_controls_684 c WHERE singleton)),jsonb_build_object('reason',p_reason),jsonb_build_object('reason',p_reason),7.46,13.10,false,false,false,false,'Administrator-only disable; no history or evidence deletion');
 RETURN jsonb_build_object('ok',true,'code','compatibility_rollback_applied');
END $rollback$;
REVOKE ALL ON FUNCTION public.admin_rollback_pdc_authenticated_provider_import_agentic_compatibility_684(text) FROM public,anon,authenticated,service_role,pdc_email_monitor;
GRANT EXECUTE ON FUNCTION public.admin_rollback_pdc_authenticated_provider_import_agentic_compatibility_684(text) TO authenticated;

INSERT INTO public.pdc_authenticated_provider_import_agentic_compatibility_history_684(event_key,event_kind,predecessor_head,successor_head,actor_id,actor_email,jwt_role,server_application_role,gateway_instance_id,release_name,source_sha,manifest_sha256,planner_sha256,trust_receipt_sha256,recovery_event_id,parent_source_hash,before_state,after_state,predecessor_function_hashes,successor_function_hashes,source_total_hours,stale_expected_hours,task_enabled,mailbox_contacted,uid514_processed,production_writes,rollback_contract)
SELECT encode(extensions.digest(convert_to('pdc-staging-684-forward|20260828050000','UTF8'),'sha256'),'hex'),'forward_compatibility','20260828040000','20260828050000',c.actor_id,c.actor_email,c.jwt_role,c.server_application_role,c.gateway_instance_id,c.release_name,c.source_sha,c.manifest_sha256,c.planner_sha256,c.trust_receipt_sha256,c.recovery_event_id,c.parent_source_hash,jsonb_build_object('provider_observations',0,'uid514_status','failed','queue_attempts',8,'stale_import_wrapper','monitor_scope_required','agentic_dkim_requirement','true'),jsonb_build_object('claim_bound_provider_observation','authenticated_provider_684','source_total_hours',7.46,'stale_expected_hours_rejected',13.10,'zero_hours_preserved',true,'tow_bar_work_key','fitting','task_enabled',false,'mailbox_contacted',false,'uid514_processed',false,'production_writes',false),jsonb_build_object('pdc_monitor_actor_scope','fbdada6560ea401c0ba4f721eada6353225398df24e851be041fad58c4699b08','attest_provider','7be3241ac65da67024907c2afd1f47d3d82ca429960d3f1464dc56d489c8e0dd','import_wrapper','ac656b019e863fba781e2280655cba2a9f8a00ae432939699839a1d902508266','read_wrapper','695bb6dedcad700ac81c221f14cf9607707417691f27df58a0a5fbb42c10c1fa','agentic_source','55161035e5ec36c10d2df3b84ec85f937d9287c55163f87d7f4d2335d24b3f79'),jsonb_build_object('successor','computed_after_install'),7.46,13.10,false,false,false,false,'Administrator-only disable; immutable history; no destructive rollback'
FROM public.pdc_authenticated_provider_import_agentic_compatibility_controls_684 c WHERE c.singleton AND c.enabled;

DO $post$
BEGIN
 IF (SELECT count(*) FROM public.pdc_authenticated_provider_import_agentic_compatibility_history_684 WHERE event_kind='forward_compatibility')<>1 OR (SELECT count(*) FROM public.pdc_provider_email_observations WHERE intake_id='102e286d-1799-4c97-8e45-e0da9fb31c63'::uuid)<>0 OR (SELECT status FROM public.ai_email_intake WHERE id='102e286d-1799-4c97-8e45-e0da9fb31c63'::uuid)<>'failed' OR (SELECT queue_attempts FROM public.ai_email_intake WHERE id='102e286d-1799-4c97-8e45-e0da9fb31c63'::uuid)<>8 OR (SELECT count(*) FROM public.vehicles WHERE public.normalize_vehicle_stock_number(stock_number)='13016925')<>0 OR to_regclass('public.pdc_production_environment_sentinel') IS NOT NULL THEN RAISE EXCEPTION 'PDC_684_FORWARD_POSTCONDITION_FAILED' USING errcode='55000'; END IF;
END $post$;
INSERT INTO supabase_migrations.schema_migrations(version,name,statements) VALUES('20260828050000','684_authenticated_provider_import_agentic_compatibility',ARRAY['Exact 683 and unrelated 714-716 predecessor/source guards with staging-only sentinel and Production absence','Claim-bound exact authenticated actor provider observation for retained UID514 Job Card attachment only; no generic observation creation','Authenticated canonical import/readback wrappers prove actor, importer, writer, gateway, release, source, manifest, planner, trust, mailbox, claim and source hashes server-side','Agentic context, plan, action, apply and finalize wrappers use the exact retained source proof and accept the genuine SPF/DMARC-aligned five-key Gmail object with DKIM=false','Preserve UID514 intake, authorization, selection, seven attachments, four extractions and all prior claim attempts; idempotent observation/import replay','Use exact PDF layout rows OP1 Fill Fuel 0.00, OP2 PDI 0.70, OP3 HDA Tray 0.00, OP4 Steel Bull Bar 5.18, OP5 Tow Bar long tongue 1.58; source total 7.46; reject stale 13.10; map Tow Bar to fitting','Immutable forced-RLS history and Administrator-only disable; no task enablement, mailbox contact, UID514 processing, evidence deletion or Production action']);
NOTIFY pgrst,'reload schema';
COMMIT;
