-- STAGING ONLY 722: parenthesize the two source-binding JSONB
-- subtractions in the canonical apply function used by the real 684 chain.
BEGIN;
SET LOCAL lock_timeout='10s'; SET LOCAL statement_timeout='90s';
SELECT pg_advisory_xact_lock(hashtextextended('pdc-staging-722-agentic-apply-precedence',0));
LOCK TABLE supabase_migrations.schema_migrations IN EXCLUSIVE MODE;
DO $guard$
DECLARE h text;
BEGIN SELECT encode(extensions.digest(convert_to(p.prosrc,'UTF8'),'sha256'),'hex') INTO h FROM pg_proc p WHERE p.oid='public.pdc_agentic_apply_action_502(uuid)'::regprocedure;
 IF current_user<>'postgres' OR session_user<>'postgres' OR (SELECT count(*) FROM public.pdc_staging_environment_sentinel WHERE singleton AND project_ref='cdsmnqxtyyoeoznmbidd')<>1 OR to_regclass('public.pdc_production_environment_sentinel') IS NOT NULL OR lower(coalesce(current_setting('app.environment',true),''))='production' OR (SELECT max(version) FROM supabase_migrations.schema_migrations WHERE version~'^[0-9]{14}$')<>'20260828430000' OR h<>'cdb1998b46884a798c7bc77ff858442ab24a0771e5157298712a2eb917cc49a2' OR to_regclass('public.pdc_authenticated_agentic_apply_precedence_history_722') IS NOT NULL THEN RAISE EXCEPTION 'PDC_722_EXACT_721_APPLY_PREDECESSOR_MISMATCH' USING errcode='55000'; END IF; END $guard$;
CREATE TABLE public.pdc_authenticated_agentic_apply_precedence_history_722(history_id uuid PRIMARY KEY DEFAULT gen_random_uuid(),event_key text NOT NULL UNIQUE,event_kind text NOT NULL CHECK(event_kind='agentic_apply_jsonb_precedence'),predecessor_head text NOT NULL CHECK(predecessor_head='20260828430000'),successor_head text NOT NULL CHECK(successor_head='20260828440000'),predecessor_function_sha256 text NOT NULL CHECK(predecessor_function_sha256='cdb1998b46884a798c7bc77ff858442ab24a0771e5157298712a2eb917cc49a2'),successor_function_sha256 text NOT NULL,repair_contract text NOT NULL,production_writes boolean NOT NULL CHECK(NOT production_writes),task_enabled boolean NOT NULL CHECK(NOT task_enabled),mailbox_contacted boolean NOT NULL CHECK(NOT mailbox_contacted),uid514_processed boolean NOT NULL CHECK(NOT uid514_processed),created_at timestamptz NOT NULL DEFAULT clock_timestamp());
ALTER TABLE public.pdc_authenticated_agentic_apply_precedence_history_722 ENABLE ROW LEVEL SECURITY; ALTER TABLE public.pdc_authenticated_agentic_apply_precedence_history_722 FORCE ROW LEVEL SECURITY; REVOKE ALL ON public.pdc_authenticated_agentic_apply_precedence_history_722 FROM public,anon,authenticated,service_role,pdc_email_monitor;
CREATE FUNCTION public.pdc_authenticated_agentic_apply_precedence_history_immutable_722() RETURNS trigger LANGUAGE plpgsql SECURITY DEFINER SET search_path=pg_catalog,public AS $$ BEGIN RAISE EXCEPTION 'PDC_722_APPLY_PRECEDENCE_HISTORY_IMMUTABLE' USING errcode='55000'; END $$;
REVOKE ALL ON FUNCTION public.pdc_authenticated_agentic_apply_precedence_history_immutable_722() FROM public,anon,authenticated,service_role,pdc_email_monitor;
CREATE TRIGGER pdc_authenticated_agentic_apply_precedence_history_immutable_722 BEFORE UPDATE OR DELETE ON public.pdc_authenticated_agentic_apply_precedence_history_722 FOR EACH ROW EXECUTE FUNCTION public.pdc_authenticated_agentic_apply_precedence_history_immutable_722();
DO $repair$
DECLARE d text;before_sha text;after_sha text;old1 text;new1 text;old2 text;new2 text;
BEGIN
 SELECT pg_get_functiondef('public.pdc_agentic_apply_action_502(uuid)'::regprocedure),encode(extensions.digest(convert_to(p.prosrc,'UTF8'),'sha256'),'hex') INTO d,before_sha FROM pg_proc p WHERE p.oid='public.pdc_agentic_apply_action_502(uuid)'::regprocedure;
 old1:=$old$(a.request->'source_binding'-array['claim_token','gateway_instance_id']::text[])$old$; new1:=$new$((a.request->'source_binding')-array['claim_token','gateway_instance_id']::text[])$new$; old2:=$old$(p.plan->'source_binding'-array['claim_token','gateway_instance_id']::text[])$old$; new2:=$new$((p.plan->'source_binding')-array['claim_token','gateway_instance_id']::text[])$new$;
 IF before_sha<>'cdb1998b46884a798c7bc77ff858442ab24a0771e5157298712a2eb917cc49a2' OR position(old1 IN d)=0 OR position(old2 IN d)=0 THEN RAISE EXCEPTION 'PDC_722_APPLY_ANCHOR_MISMATCH' USING errcode='55000'; END IF;
 EXECUTE replace(replace(d,old1,new1),old2,new2);
 SELECT encode(extensions.digest(convert_to(p.prosrc,'UTF8'),'sha256'),'hex') INTO after_sha FROM pg_proc p WHERE p.oid='public.pdc_agentic_apply_action_502(uuid)'::regprocedure;
 INSERT INTO public.pdc_authenticated_agentic_apply_precedence_history_722(event_key,event_kind,predecessor_head,successor_head,predecessor_function_sha256,successor_function_sha256,repair_contract,production_writes,task_enabled,mailbox_contacted,uid514_processed) VALUES(encode(extensions.digest(convert_to('pdc-staging-722-agentic-apply-precedence|forward','UTF8'),'sha256'),'hex'),'agentic_apply_jsonb_precedence','20260828430000','20260828440000',before_sha,after_sha,'Parenthesize only the two canonical apply source-binding subtractions so the real action chain accepts the exact projected receipt; preserve all canonical action, expected-state and replay guards',false,false,false,false);
END $repair$;
DO $post$ BEGIN IF (SELECT count(*) FROM public.pdc_authenticated_agentic_apply_precedence_history_722)<>1 OR position('(a.request->''source_binding'')-array' IN (SELECT p.prosrc FROM pg_proc p WHERE p.oid='public.pdc_agentic_apply_action_502(uuid)'::regprocedure))=0 OR to_regclass('public.pdc_production_environment_sentinel') IS NOT NULL THEN RAISE EXCEPTION 'PDC_722_POSTCONDITION_FAILED' USING errcode='55000'; END IF; END $post$;
INSERT INTO supabase_migrations.schema_migrations(version,name,statements) VALUES('20260828440000','722_agentic_apply_jsonb_precedence',ARRAY['Exact 721 predecessor and canonical apply hash guard','Parenthesize the two apply source-binding JSONB subtractions','UID514/task/mailbox/outbound/Production untouched']);
NOTIFY pgrST,'reload schema'; COMMIT;
