-- STAGING ONLY 782/1740: reviewed atomic wrapper successor.
-- The 1730 schema predecessor is already applied in staging. This successor
-- privatizes its body and exposes only the verified boundary wrapper.
BEGIN;
SET LOCAL lock_timeout='15s';
SET LOCAL statement_timeout='300s';
SELECT pg_advisory_xact_lock(hashtextextended('pdc-staging-782-historical-reconciliation-wrapper-1740',0));
LOCK TABLE supabase_migrations.schema_migrations IN EXCLUSIVE MODE;

DO $guard$
DECLARE v_body text; v_owner text; v_config text; v_acl text; v_secdef boolean; v_trigger_text text; v_trigger_hash text; v_trigger_executor_text text; v_trigger_executor_hash text; r record;
BEGIN
 IF current_user<>'postgres' OR session_user<>'postgres' OR NOT public.pdc_monitor_staging_guard()
    OR (SELECT count(*) FROM public.pdc_staging_environment_sentinel WHERE singleton AND project_ref='cdsmnqxtyyoeoznmbidd')<>1
    OR to_regclass('public.pdc_production_environment_sentinel') IS NOT NULL
    OR (SELECT (version,name)::text FROM supabase_migrations.schema_migrations WHERE version~'^[0-9]{14}$' ORDER BY version::bigint DESC LIMIT 1) IS DISTINCT FROM '(20260830173000,782_historical_reconciliation_current_head_security_successor)'
    OR NOT EXISTS(SELECT 1 FROM supabase_migrations.schema_migrations WHERE version='20260830173000' AND name='782_historical_reconciliation_current_head_security_successor' AND statements=ARRAY[
      'Lock and equality-bind the exact live 20260830172000/778 predecessor serialization before replacement',
      'Pin delegated child, parent, enqueue and authorization bodies by owner, SECURITY DEFINER, config, ACL, body hash, callee marker and protected trigger fingerprint',
      'Bind every frozen Job Card by immutable parent/provider/ordinal/kind/hash/MIME/filename/size/extraction/job-card/Stock evidence and reject sibling substitution',
      'Atomically enqueue, observe, parent-process and canonical-child-process; reread authoritative vehicle/operations and protected boundaries before deriving flags or writing the immutable receipt',
      'Preserve frozen manifest/runtime/sender/Stock/UID/24-hour/replay/old-mail/RLS/authenticated-only/Production/outbound/task boundaries'
    ])
    OR EXISTS(SELECT 1 FROM supabase_migrations.schema_migrations WHERE version='20260830174000')
 THEN RAISE EXCEPTION 'PDC_782_1740_CURRENT_HEAD_GUARD_FAILED' USING errcode='55000'; END IF;
 FOR r IN SELECT * FROM (VALUES
   ('public.pdc_monitor_staging_guard()','596f9c1c46c405b245b7aca9e21e33a1232a0cae01a596a61d3f11168328edba','search_path=pg_catalog, public','postgres:EXECUTE:false|service_role:EXECUTE:false','pdc_monitor_staging_guard'),
   ('public.pdc_monitor_authenticated_active_scope_674(text)','cdf74a6b90abd0839a7226c881830844e5d0dcc20f8652141395662e9853f5ba','search_path=pg_catalog, public, auth','postgres:EXECUTE:false','pdc_monitor_authenticated_active_scope_674'),
   ('public.verify_pdc_monitor_runtime_binding_authenticated_766(text,text,text,text,text,text,text)','ac5d8baa2adbda0c078b3da5fa721ff262301ab6402954a92603ccc57d1c6086','search_path=pg_catalog, public, auth, extensions','authenticated:EXECUTE:false|postgres:EXECUTE:false','verify_pdc_monitor_runtime_binding_authenticated_766'),
   ('public.pdc_historical_writer_authorized_773(text,text,text,jsonb,text)','9bd5a567213e77dd4fb3ff45fa7031443444707505e576a3c17ace1c7c6699dd','search_path=pg_catalog, public, auth, extensions','postgres:EXECUTE:false','pdc_historical_reconciliation_writer_authorizations_773'),
   ('public.enqueue_pdc_email_intake(jsonb,jsonb)','f4f6f14d094afc04c110c72ca6d6d2c642bf6bf2fa8a96f59d3115793a6accd8','search_path=pg_catalog, public, extensions','authenticated:EXECUTE:false|postgres:EXECUTE:false','pdc_historical_writer_authorized_773'),
   ('public.submit_pdc_ai_intake_observation_pre135(text,text,text,text,jsonb,timestamptz,text,text,text,text,jsonb)','f73dd525e5dc6caccde4d5658bea8a2cabd95ec7f55898b792e5984568de5950','search_path=pg_catalog, public, extensions','postgres:EXECUTE:false','pdc_monitor_staging_guard'),
   ('public.import_pdc_jobcard_attachment_canonical(uuid,uuid,text,text,jsonb,jsonb,jsonb,jsonb)','6497f2ba7ad244ea414f26d80400a3fa4bff2bf090746fdaa4cad800cbe53cfb','search_path=pg_catalog, public, extensions,statement_timeout=180s','postgres:EXECUTE:false','pdc_historical_provider_observations_778'),
   ('public.read_pdc_historical_reconciliation_778_receipt(uuid)','f6a954d162f3b9d7ae53a6fa073f4195b6a1067f51fc8ba7346217a95f518bb8','search_path=pg_catalog, public, auth, extensions','authenticated:EXECUTE:false|postgres:EXECUTE:false','pdc_historical_reconciliation_778_receipts'),
   ('public.pdc_historical_782_boundary_snapshot()','5540e514e14cc883bb7fcfa9d302118b32d03160f707f4094624711d7dcd4ab6','search_path=pg_catalog, public','postgres:EXECUTE:false','vehicle_parts_updates'),
   ('public.pdc_historical_782_unrelated_snapshot(uuid)','e2fc3356fb65cef9b3ae4f42864c08091997e7397e2ab09a7d6e0a93c6b64c8e','search_path=pg_catalog, public','postgres:EXECUTE:false','vehicles'),
   ('public.pdc_historical_job_card_attachments_immutable_782()','fa3c8b3fdef6daa59362e20ef54f1597199ab61acae087dd40c0d562bd852355','search_path=pg_catalog, public','postgres:EXECUTE:false','pdc_782_jobcard_evidence_immutable'),
   ('public.submit_pdc_historical_reconciliation_778(jsonb)','6d091224653234e662601e494bcc7af4aa1f65e659b3798c39b2bcafd1990bbf','search_path=pg_catalog, public, auth, extensions,statement_timeout=300s','authenticated:EXECUTE:false|postgres:EXECUTE:false','enqueue_pdc_email_intake')
 ) AS x(sig,body_hash,config,acl,callee) LOOP
   SELECT pg_get_userbyid(p.proowner),p.prosecdef,coalesce(array_to_string(p.proconfig,','),''),encode(extensions.digest(convert_to(pg_get_functiondef(p.oid),'UTF8'),'sha256'),'hex'),coalesce((SELECT string_agg(coalesce(pg_get_userbyid(a.grantee),'PUBLIC')||':'||a.privilege_type||':'||a.is_grantable,'|' ORDER BY coalesce(pg_get_userbyid(a.grantee),'PUBLIC'),a.privilege_type,a.is_grantable) FROM aclexplode(coalesce(p.proacl,acldefault('f',p.proowner))) a),'') INTO v_owner,v_secdef,v_config,v_body,v_acl FROM pg_proc p WHERE p.oid=r.sig::regprocedure;
   IF to_regprocedure(r.sig) IS NULL OR v_owner IS DISTINCT FROM 'postgres' OR v_secdef IS DISTINCT FROM true OR v_config IS DISTINCT FROM r.config OR v_body IS DISTINCT FROM r.body_hash OR v_acl IS DISTINCT FROM r.acl THEN RAISE EXCEPTION 'PDC_782_1740_DEPENDENCY_CONTRACT_DRIFT:%',r.sig USING errcode='55000'; END IF;
   IF position(lower(r.callee) in lower(pg_get_functiondef(r.sig::regprocedure)))=0 THEN RAISE EXCEPTION 'PDC_782_1740_CALLEE_CONTRACT_DRIFT:%',r.sig USING errcode='55000'; END IF;
 END LOOP;
 SELECT coalesce(string_agg(event_object_table||'|'||trigger_name||'|'||event_manipulation||'|'||action_timing||'|'||action_statement,'|' ORDER BY event_object_table,trigger_name,event_manipulation),'') INTO v_trigger_text FROM information_schema.triggers WHERE event_object_schema='public' AND event_object_table IN ('ai_email_intake','ai_email_attachments','vehicles','vehicle_work_items','pdc_authenticated_email_operation_lines','vehicle_workshop_line_adjustments','vehicle_parts_updates','workshop_bookings','workshop_booking_assignments','pdc_sublet_bookings','pdc_sublet_booking_instances','pdc_qc_operation_completions_379','pdc_pmb_stoppage_receipts_422','pdc_email_monitor_current_head_compatibility_controls_766','pdc_email_monitor_pilot','pdc_email_monitor_status','pdc_qc_salesperson_update_outbox_399','pdc_rft_transport_email_outbox_734','pdc_sublet_email_update_receipts','pdc_historical_provider_observations_778','pdc_historical_reconciliation_778_receipts');
 v_trigger_hash:=encode(extensions.digest(convert_to(v_trigger_text,'UTF8'),'sha256'),'hex');
 IF v_trigger_hash IS DISTINCT FROM 'ff68e5580c8a77701eb5f92ef6a0b6ad99a44f0036185e60900a4292775870f1' THEN RAISE EXCEPTION 'PDC_782_1740_TRIGGER_CONTRACT_DRIFT' USING errcode='55000'; END IF;
 SELECT coalesce(string_agg(x.event_object_table||'|'||x.trigger_name||'|'||x.event_manipulation||'|'||x.action_timing||'|'||x.action_statement||'|'||coalesce(encode(extensions.digest(convert_to(pg_get_functiondef(t.tgfoid),'UTF8'),'sha256'),'hex'),'')||'|'||coalesce(pg_get_userbyid(p.proowner),'')||'|'||coalesce(array_to_string(p.proconfig,','),'')||'|'||coalesce((SELECT string_agg(coalesce(pg_get_userbyid(a.grantee),'PUBLIC')||':'||a.privilege_type||':'||a.is_grantable,'|' ORDER BY coalesce(pg_get_userbyid(a.grantee),'PUBLIC'),a.privilege_type,a.is_grantable) FROM aclexplode(coalesce(p.proacl,acldefault('f',p.proowner))) a),'') ,'|' ORDER BY x.event_object_table,x.trigger_name,x.event_manipulation),'') INTO v_trigger_executor_text FROM information_schema.triggers x JOIN pg_class c ON c.relname=x.event_object_table JOIN pg_namespace n ON n.oid=c.relnamespace AND n.nspname=x.event_object_schema JOIN pg_trigger t ON t.tgrelid=c.oid AND t.tgname=x.trigger_name JOIN pg_proc p ON p.oid=t.tgfoid WHERE x.event_object_schema='public' AND x.event_object_table IN ('ai_email_intake','ai_email_attachments','vehicles','vehicle_work_items','pdc_authenticated_email_operation_lines','vehicle_workshop_line_adjustments','vehicle_parts_updates','workshop_bookings','workshop_booking_assignments','pdc_sublet_bookings','pdc_sublet_booking_instances','pdc_qc_operation_completions_379','pdc_pmb_stoppage_receipts_422','pdc_email_monitor_current_head_compatibility_controls_766','pdc_email_monitor_pilot','pdc_email_monitor_status','pdc_qc_salesperson_update_outbox_399','pdc_rft_transport_email_outbox_734','pdc_sublet_email_update_receipts','pdc_historical_provider_observations_778','pdc_historical_reconciliation_778_receipts');
 v_trigger_executor_hash:=encode(extensions.digest(convert_to(v_trigger_executor_text,'UTF8'),'sha256'),'hex');
 IF v_trigger_executor_hash IS DISTINCT FROM '59f828545fd10c6928ccf38d0e8d8d1e25841fd9af75d591ee96f4219ea82fac' THEN RAISE EXCEPTION 'PDC_782_1740_TRIGGER_EXECUTOR_CONTRACT_DRIFT' USING errcode='55000'; END IF;
END
$guard$;

ALTER FUNCTION public.submit_pdc_historical_reconciliation_778(jsonb) RENAME TO submit_pdc_historical_reconciliation_782_base;
REVOKE ALL ON FUNCTION public.submit_pdc_historical_reconciliation_782_base(jsonb) FROM public,anon,authenticated,service_role,pdc_email_monitor;
GRANT EXECUTE ON FUNCTION public.submit_pdc_historical_reconciliation_782_base(jsonb) TO postgres;

CREATE OR REPLACE FUNCTION public.submit_pdc_historical_reconciliation_778(p_request jsonb)
RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER
SET search_path=pg_catalog,public,auth,extensions
SET statement_timeout='300s'
AS $wrapper$
DECLARE
 v_before jsonb; v_after jsonb; v_location_before text; v_location_after text; v_result jsonb; v_booking_created boolean:=false; v_completion_created boolean:=false; v_location_scheduled boolean:=false; v_parts_changed boolean:=false;
 v_vehicle_id uuid; v_vehicle public.vehicles%rowtype; v_existing public.pdc_historical_reconciliation_778_receipts%rowtype; v_child_receipt public.pdc_jobcard_attachment_import_receipts%rowtype; v_request_hash text; v_uid text; v_parent text; v_sender text; v_stock text; v_source jsonb; v_items jsonb; v_auth jsonb; v_runtime jsonb; v_authz public.pdc_historical_reconciliation_writer_authorizations_773%rowtype; v_authz_count integer; v_intake public.ai_email_intake%rowtype; v_intake_id uuid; v_attachment_id uuid; v_child jsonb; v_item jsonb; v_required jsonb; v_work_key text; v_booking_count integer:=0; v_completion_count integer:=0; v_parts_count integer:=0; v_receipt_count integer:=0;
BEGIN
 IF NOT public.pdc_monitor_staging_guard() OR to_regclass('public.pdc_production_environment_sentinel') IS NOT NULL OR auth.uid()<>'df7c55d9-6ba0-47f6-ba16-44d6ae2c2a4b'::uuid OR lower(btrim(coalesce(auth.jwt()->>'email','')))<>'sales@broometoyota.com.au' OR NOT public.pdc_monitor_authenticated_active_scope_674('pdc-monitor-staging-sales-uid509-v1') OR jsonb_typeof(p_request) IS DISTINCT FROM 'object' OR (SELECT array_agg(k ORDER BY k) FROM jsonb_object_keys(p_request) k) IS DISTINCT FROM ARRAY['action_type','attachment_manifest','authentication','evidence_hash','gateway_instance_id','job_card_children','manifest_high_water_uid','manifest_sha256','manifest_uid_count','manifest_uidvalidity','observations','parent_source_hash','provider_uid','release_manifest_sha256','release_name','release_source_sha','sender_email','source_metadata','stock_number','subject','summary']::text[] THEN RETURN jsonb_build_object('ok',false,'code','unauthorized'); END IF;
 v_uid:=btrim(coalesce(p_request->>'provider_uid','')); v_parent:=lower(btrim(coalesce(p_request->>'parent_source_hash',''))); v_sender:=lower(btrim(coalesce(p_request->>'sender_email',''))); v_stock:=public.normalize_vehicle_stock_number(p_request->>'stock_number'); v_source:=coalesce(p_request->'source_metadata','null'::jsonb); v_items:=coalesce(p_request->'attachment_manifest','null'::jsonb); v_auth:=coalesce(p_request->'authentication','null'::jsonb); v_request_hash:=encode(extensions.digest(convert_to(p_request::text,'UTF8'),'sha256'),'hex');
 IF p_request->>'gateway_instance_id' IS DISTINCT FROM 'pdc-monitor-staging-sales-uid509-v1' OR p_request->>'release_name' IS DISTINCT FROM 'pdc-monitor-staging-m502-2026.08.44' OR lower(p_request->>'release_source_sha') IS DISTINCT FROM 'e850c319989d98b45b95a28aa815d78e2c2e3a4b' OR lower(p_request->>'release_manifest_sha256') IS DISTINCT FROM 'd48b49f6598a99fbef99fc4f0d0ab36b8b47576b8ff7cd8ecd2cb64d6cfed58d' OR p_request->>'manifest_sha256' IS DISTINCT FROM 'aa9e2451645b3fc51eba68c422b5eaf6f146ed18596a94ce8560c55b80729018' OR p_request->>'manifest_uidvalidity' IS DISTINCT FROM '1' OR p_request->>'manifest_high_water_uid' IS DISTINCT FROM '685' OR p_request->>'manifest_uid_count' IS DISTINCT FROM '669' OR v_request_hash!~'^[a-f0-9]{64}$' OR v_uid!~'^1:[1-9][0-9]{0,5}$' OR v_uid='1:197' OR v_parent!~'^[a-f0-9]{64}$' OR v_sender!~'^[a-z0-9.!#$%&''*+/=?^_`{|}~-]+@[a-z0-9](?:[a-z0-9.-]{0,251}[a-z0-9])?$' OR v_stock='13056899' OR NOT public.is_real_vehicle_stock_number(v_stock) OR v_request->>'evidence_hash'!~'^[a-f0-9]{64}$' OR p_request->>'action_type' NOT IN ('board_activate_only','review_only') OR jsonb_typeof(v_auth) IS DISTINCT FROM 'object' OR (SELECT array_agg(k ORDER BY k) FROM jsonb_object_keys(v_auth) k) IS DISTINCT FROM ARRAY['dkim_aligned','dmarc_aligned','gmail_authentication_results','sender_domain','spf_aligned']::text[] OR v_auth->>'sender_domain' IS DISTINCT FROM split_part(v_sender,'@',2) OR v_auth->'gmail_authentication_results' IS DISTINCT FROM 'true'::jsonb OR NOT(v_auth->'spf_aligned'='true'::jsonb OR v_auth->'dkim_aligned'='true'::jsonb OR v_auth->'dmarc_aligned'='true'::jsonb) OR jsonb_typeof(v_items) IS DISTINCT FROM 'array' OR jsonb_array_length(v_items) NOT BETWEEN 1 AND 25 OR jsonb_typeof(p_request->'job_card_children') IS DISTINCT FROM 'array' OR jsonb_array_length(p_request->'job_card_children')>25 OR jsonb_typeof(v_source) IS DISTINCT FROM 'object' OR (SELECT array_agg(k ORDER BY k) FROM jsonb_object_keys(v_source) k) IS DISTINCT FROM ARRAY['attachment_names','graph_message_id','internet_message_id','parsed_text','provider_authserv_id','raw_body','received_at','recipient_mailbox','sender_name','uid','uidvalidity']::text[] OR v_source->>'uidvalidity' IS DISTINCT FROM '1' OR v_source->>'uid' IS DISTINCT FROM substring(v_uid FROM '^1:([0-9]+)$') OR v_source->>'provider_authserv_id' IS DISTINCT FROM 'mx.google.com' OR lower(v_source->>'recipient_mailbox') IS DISTINCT FROM 'pmbcontroller@gmail.com' OR v_source->>'received_at' IS NULL OR (v_source->>'received_at')::timestamptz > clock_timestamp()+interval '5 minutes' OR (v_source->>'received_at')::timestamptz < clock_timestamp()-interval '120 days' OR v_source->'attachment_names' IS DISTINCT FROM (SELECT jsonb_agg(m->>'filename' ORDER BY ordinality) FROM jsonb_array_elements(v_items) WITH ORDINALITY x(m,ordinality)) THEN RETURN jsonb_build_object('ok',false,'code','historical_wrapper_preflight_failed'); END IF;
 v_runtime:=public.verify_pdc_monitor_runtime_binding_authenticated_766('active','pdc-monitor-staging-sales-uid509-v1','pdc-monitor-staging-m502-2026.08.44','e850c319989d98b45b95a28aa815d78e2c2e3a4b','d48b49f6598a99fbef99fc4f0d0ab36b8b47576b8ff7cd8ecd2cb64d6cfed58d','7e08a00bc099610aa919bb7c3089ef84b91a74bafd69f95fab06bfccfdf67348','e3e30ace04e676e34f271b161283b9e4764d462f76428d63826fa3cb153d7227');
 IF v_runtime->>'ok' IS DISTINCT FROM 'true' OR v_runtime->>'actor_id' IS DISTINCT FROM auth.uid()::text OR v_runtime->>'actor_email' IS DISTINCT FROM lower(auth.jwt()->>'email') OR v_runtime->>'task_enabled' IS DISTINCT FROM 'false' OR v_runtime->>'mailbox_contacted' IS DISTINCT FROM 'false' OR v_runtime->>'production_writes' IS DISTINCT FROM 'false' THEN RETURN jsonb_build_object('ok',false,'code','historical_wrapper_preflight_failed'); END IF;
 IF EXISTS(SELECT 1 FROM jsonb_array_elements(v_items) WITH ORDINALITY x(m,ordinality) WHERE jsonb_typeof(x.m) IS DISTINCT FROM 'object' OR (SELECT array_agg(k ORDER BY k) FROM jsonb_object_keys(x.m) k) IS DISTINCT FROM ARRAY['attachment_kind','content_type','filename','ordinal','sha256','size']::text[] OR x.m->>'attachment_kind' NOT IN ('job_card','ambiguous_job_card','non_job_card_sibling') OR x.m->>'sha256'!~'^[a-f0-9]{64}$' OR x.m->>'ordinal'!~'^[1-9][0-9]{0,2}$' OR (x.m->>'ordinal')::integer<>x.ordinality OR x.m->>'size'!~'^[1-9][0-9]{0,7}$' OR x.m->>'content_type' IS NULL OR x.m->>'filename' IS NULL) THEN RETURN jsonb_build_object('ok',false,'code','historical_wrapper_preflight_failed'); END IF;
 SELECT count(*) INTO v_authz_count FROM public.pdc_historical_reconciliation_writer_authorizations_773 e WHERE e.active AND e.manifest_sha256=p_request->>'manifest_sha256' AND e.provider_uid=v_uid AND e.parent_source_hash=v_parent AND e.sender_email=v_sender AND e.sender_sha256=encode(extensions.digest(convert_to(v_sender,'UTF8'),'sha256'),'hex') AND e.provider_authentication IS NOT DISTINCT FROM v_auth AND public.normalize_vehicle_stock_number(e.stock_number)=v_stock AND e.authorized_actor_id=auth.uid() AND e.authorized_actor_email=lower(auth.jwt()->>'email') AND e.authorized_gateway_instance_id='pdc-monitor-staging-sales-uid509-v1' AND public.pdc_historical_writer_authorized_773(v_parent,v_uid,v_sender,v_auth,v_stock);
 IF v_authz_count<>1 THEN RETURN jsonb_build_object('ok',false,'code','pdc_778_exact_authorization_failed'); END IF;
 SELECT * INTO v_authz FROM public.pdc_historical_reconciliation_writer_authorizations_773 e WHERE e.active AND e.manifest_sha256=p_request->>'manifest_sha256' AND e.provider_uid=v_uid AND e.parent_source_hash=v_parent AND e.sender_email=v_sender AND e.authorized_actor_id=auth.uid() AND e.authorized_actor_email=lower(auth.jwt()->>'email') AND e.authorized_gateway_instance_id='pdc-monitor-staging-sales-uid509-v1';
 SELECT * INTO v_existing FROM public.pdc_historical_reconciliation_778_receipts WHERE actor_id=auth.uid() AND provider_uid=v_uid AND parent_source_hash=v_parent;
 IF FOUND THEN IF v_existing.request_sha256<>v_request_hash THEN RETURN jsonb_build_object('ok',false,'code','historical_replay_conflict'); END IF; RETURN v_existing.canonical_response; END IF;
 SELECT * INTO v_intake FROM public.ai_email_intake WHERE source_hash=v_parent ORDER BY created_at DESC LIMIT 1;
 IF FOUND AND (v_intake.duplicate_of IS NOT NULL OR v_intake.status::text NOT IN ('received','processing') OR v_intake.received_at IS NULL OR v_intake.received_at>clock_timestamp()+interval '5 minutes' OR v_intake.received_at<clock_timestamp()-interval '120 days') THEN RETURN jsonb_build_object('ok',false,'code','pdc_782_old_mail_completed'); END IF;
 IF clock_timestamp()>v_authz.authorized_at+interval '24 hours' THEN RETURN jsonb_build_object('ok',false,'code','historical_authorization_expired'); END IF;
 v_before:=public.pdc_historical_782_boundary_snapshot();
 SELECT md5(coalesce((SELECT string_agg(to_jsonb(x)::text,'|' ORDER BY to_jsonb(x)::text) FROM public.vehicle_movements x),'')||'|'||coalesce((SELECT string_agg(to_jsonb(x)::text,'|' ORDER BY to_jsonb(x)::text) FROM public.vehicle_aliases x),'')) INTO v_location_before;
 v_result:=public.submit_pdc_historical_reconciliation_782_base(p_request);
 v_after:=public.pdc_historical_782_boundary_snapshot();
 SELECT md5(coalesce((SELECT string_agg(to_jsonb(x)::text,'|' ORDER BY to_jsonb(x)::text) FROM public.vehicle_movements x),'')||'|'||coalesce((SELECT string_agg(to_jsonb(x)::text,'|' ORDER BY to_jsonb(x)::text) FROM public.vehicle_aliases x),'')) INTO v_location_after;
 v_booking_created:=v_after->>'workshop_bookings' IS DISTINCT FROM v_before->>'workshop_bookings' OR v_after->>'workshop_booking_assignments' IS DISTINCT FROM v_before->>'workshop_booking_assignments';
 v_completion_created:=v_after->>'pdc_qc_operation_completions_379' IS DISTINCT FROM v_before->>'pdc_qc_operation_completions_379';
 v_location_scheduled:=v_booking_created;
 v_parts_changed:=v_after->>'vehicle_parts_updates' IS DISTINCT FROM v_before->>'vehicle_parts_updates';
 v_location_scheduled:=v_location_scheduled OR v_location_after IS DISTINCT FROM v_location_before;
 IF v_booking_created OR v_completion_created OR v_location_scheduled OR v_parts_changed THEN RAISE EXCEPTION 'PDC_782_1740_PROTECTED_BOUNDARY_DRIFT' USING errcode='55000'; END IF;
 IF v_result->>'ok'='true' THEN
   IF v_result->'data'->>'booking_created' IS DISTINCT FROM v_booking_created::text OR v_result->'data'->>'completion_created' IS DISTINCT FROM v_completion_created::text OR v_result->'data'->>'location_scheduled' IS DISTINCT FROM v_location_scheduled::text OR v_result->'data'->>'parts_changed' IS DISTINCT FROM v_parts_changed::text THEN RAISE EXCEPTION 'PDC_782_1740_FLAG_READBACK_FAILED' USING errcode='55000'; END IF;
   IF jsonb_typeof(v_result->'data'->'authoritative_state') IS DISTINCT FROM 'object' THEN RAISE EXCEPTION 'PDC_782_1740_AUTHORITATIVE_STATE_MISSING' USING errcode='55000'; END IF;
   IF v_result->'data'->'authoritative_state'->>'vehicle_id' IS NOT NULL THEN
     IF v_result->'data'->'authoritative_state'->>'vehicle_id' !~ '^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-5][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}$' THEN RAISE EXCEPTION 'PDC_782_1740_VEHICLE_ID_READBACK_FAILED' USING errcode='55000'; END IF;
     v_vehicle_id:=(v_result->'data'->'authoritative_state'->>'vehicle_id')::uuid;
     SELECT * INTO v_vehicle FROM public.vehicles WHERE id=v_vehicle_id;
     IF NOT FOUND OR v_vehicle.deleted_at IS NOT NULL OR v_vehicle.lifecycle_state::text<>'active' OR v_vehicle.board_purged_at IS NOT NULL OR NOT coalesce(v_vehicle.visible_on_board,false) THEN RAISE EXCEPTION 'PDC_782_1740_AUTHORITATIVE_VEHICLE_FAILED' USING errcode='55000'; END IF;
     select count(*) into v_booking_count from public.workshop_bookings where vehicle_id=v_vehicle_id;
     select count(*) into v_completion_count from public.pdc_qc_operation_completions_379 where vehicle_id=v_vehicle_id;
     select count(*) into v_parts_count from public.vehicle_parts_updates where vehicle_id=v_vehicle_id;
     IF v_booking_count<>0 OR v_completion_count<>0 OR v_parts_count<>0 THEN RAISE EXCEPTION 'PDC_782_1740_AUTHORITATIVE_PROTECTED_STATE_FAILED' USING errcode='55000'; END IF;
     FOR v_child IN SELECT value FROM jsonb_array_elements(p_request->'job_card_children') LOOP
       IF v_child->>'attachment_kind'='job_card' THEN
         v_intake_id:=NULLIF(v_result->'data'->>'intake_id','')::uuid;
         SELECT count(*) INTO v_receipt_count FROM public.ai_email_attachments a WHERE a.intake_id=v_intake_id AND a.graph_attachment_id=p_request->>'provider_uid'||':historical-782-'||lpad((v_child->>'attachment_ordinal')::integer::text,3,'0')||'-'||lower(v_child->>'attachment_hash') AND lower(a.source_hash)=lower(v_child->>'attachment_hash');
         IF v_receipt_count<>1 THEN RAISE EXCEPTION 'PDC_782_1740_CHILD_ATTACHMENT_READBACK_FAILED' USING errcode='55000'; END IF;
         SELECT a.id INTO v_attachment_id FROM public.ai_email_attachments a WHERE a.intake_id=v_intake_id AND a.graph_attachment_id=p_request->>'provider_uid'||':historical-782-'||lpad((v_child->>'attachment_ordinal')::integer::text,3,'0')||'-'||lower(v_child->>'attachment_hash');
         SELECT count(*) INTO v_receipt_count FROM public.pdc_jobcard_attachment_import_receipts r WHERE r.intake_id=v_intake_id AND r.attachment_id=v_attachment_id AND r.parent_source_hash=p_request->>'parent_source_hash' AND r.attachment_source_hash=lower(v_child->>'attachment_hash') AND r.attachment_content_type='application/pdf' AND r.job_card_number= v_child->'extraction'->'email_vehicle'->>'job_card_number' AND r.operation_count=jsonb_array_length(v_child->'extraction'->'operation_lines') AND r.canonical_import_receipt_id IS NOT NULL AND r.vehicle_id IS NOT NULL;
         IF v_receipt_count<>1 THEN RAISE EXCEPTION 'PDC_782_1740_CHILD_RECEIPT_READBACK_FAILED' USING errcode='55000'; END IF;
         v_vehicle_id:=NULLIF((SELECT r->>'authoritative_vehicle_id' FROM jsonb_array_elements(v_result->'data'->'attachment_receipts') r WHERE r->>'attachment_hash'=v_child->>'attachment_hash' LIMIT 1),'')::uuid;
         v_required:=coalesce(v_child->'extraction'->'required_work','[]'::jsonb);
         IF v_vehicle_id IS NULL OR EXISTS(SELECT 1 FROM jsonb_array_elements_text(v_required) k WHERE NOT EXISTS(SELECT 1 FROM public.vehicle_work_items wi WHERE wi.vehicle_id=v_vehicle_id AND wi.work_key=k AND wi.required)) THEN RAISE EXCEPTION 'PDC_782_1740_AUTHORITATIVE_WORK_FAILED' USING errcode='55000'; END IF;
       END IF;
     END LOOP;
   END IF;
 END IF;
 RETURN v_result;
EXCEPTION WHEN OTHERS THEN
 RETURN jsonb_build_object('ok',false,'code','historical_reconciliation_782_atomic_rollback');
END
$wrapper$;
REVOKE ALL ON FUNCTION public.submit_pdc_historical_reconciliation_778(jsonb) FROM public,anon,authenticated,service_role,pdc_email_monitor;
GRANT EXECUTE ON FUNCTION public.submit_pdc_historical_reconciliation_778(jsonb) TO authenticated;

DO $verify$
DECLARE d text; o text; c text; s boolean; a text;
BEGIN
 SELECT pg_get_functiondef('public.submit_pdc_historical_reconciliation_778(jsonb)'::regprocedure),pg_get_userbyid(p.proowner),coalesce(array_to_string(p.proconfig,','),''),p.prosecdef,coalesce((SELECT string_agg(coalesce(pg_get_userbyid(x.grantee),'PUBLIC')||':'||x.privilege_type||':'||x.is_grantable,'|' ORDER BY coalesce(pg_get_userbyid(x.grantee),'PUBLIC'),x.privilege_type,x.is_grantable) FROM aclexplode(coalesce(p.proacl,acldefault('f',p.proowner))) x),'') INTO d,o,c,s,a FROM pg_proc p WHERE p.oid='public.submit_pdc_historical_reconciliation_778(jsonb)'::regprocedure;
 IF o IS DISTINCT FROM 'postgres' OR c IS DISTINCT FROM 'search_path=pg_catalog, public, auth, extensions,statement_timeout=300s' OR s IS DISTINCT FROM true OR a IS DISTINCT FROM 'authenticated:EXECUTE:false|postgres:EXECUTE:false' OR position('PDC_782_1740_PROTECTED_BOUNDARY_DRIFT' in d)=0 OR position('PDC_782_1740_FLAG_READBACK_FAILED' in d)=0 OR position('PDC_782_1740_AUTHORITATIVE_STATE_MISSING' in d)=0 OR position('pdc_historical_782_boundary_snapshot' in d)=0 OR position('submit_pdc_historical_reconciliation_782_base' in d)=0 OR position('booking_created' in d)=0 OR position('completion_created' in d)=0 OR position('location_scheduled' in d)=0 OR position('parts_changed' in d)=0 OR NOT has_function_privilege('authenticated','public.submit_pdc_historical_reconciliation_778(jsonb)','execute') OR has_function_privilege('anon','public.submit_pdc_historical_reconciliation_778(jsonb)','execute') OR has_function_privilege('service_role','public.submit_pdc_historical_reconciliation_778(jsonb)','execute') OR to_regclass('public.pdc_production_environment_sentinel') IS NOT NULL THEN RAISE EXCEPTION 'PDC_782_1740_POSTCONDITION_FAILED' USING errcode='55000'; END IF;
 IF NOT EXISTS(SELECT 1 FROM pg_class WHERE oid='public.pdc_historical_job_card_attachments_782'::regclass AND relrowsecurity AND relforcerowsecurity) OR NOT EXISTS(SELECT 1 FROM pg_class WHERE oid='public.pdc_historical_provider_observations_778'::regclass AND relrowsecurity AND relforcerowsecurity) OR NOT EXISTS(SELECT 1 FROM pg_class WHERE oid='public.pdc_historical_reconciliation_778_receipts'::regclass AND relrowsecurity AND relforcerowsecurity) OR (SELECT count(*) FROM public.pdc_historical_job_card_attachments_782)<>3 OR has_table_privilege('anon','public.pdc_historical_job_card_attachments_782','select') OR has_table_privilege('anon','public.pdc_historical_provider_observations_778','select') OR has_table_privilege('anon','public.pdc_historical_reconciliation_778_receipts','select') THEN RAISE EXCEPTION 'PDC_782_1740_BINDING_POSTCONDITION_FAILED' USING errcode='55000'; END IF;
END
$verify$;
INSERT INTO supabase_migrations.schema_migrations(version,name,statements) VALUES('20260830174000','782_historical_reconciliation_atomic_wrapper_successor',ARRAY[
 'Privatize the already-applied 1730 historical body behind a PostgreSQL SECURITY DEFINER base and preserve its exact child/callee/trigger contract',
 'Compute booking/completion/location/Parts flags from authoritative before/after protected-state snapshots and reject any protected drift atomically',
 'Require authoritative vehicle readback on successful child receipts while preserving exact frozen manifest, sender, Stock, UID, expiry, replay, old-mail, RLS and authenticated-only boundaries',
 'Keep Production, outbound email, mailbox flags, task enablement and ordinary monitor behavior untouched'
]);
NOTIFY pgrst,'reload schema';
COMMIT;
