-- STAGING ONLY 430: exact-admin synthetic acceptance path for the sealed email interceptor.
BEGIN; SET LOCAL lock_timeout='10s'; SET LOCAL statement_timeout='120s';
SELECT pg_advisory_xact_lock(hashtextextended('pdc-staging-430-admin-email-intercept-acceptance',0));
DO $pre$ BEGIN
 IF current_user<>'postgres' OR session_user<>'postgres'
  OR (SELECT count(*) FROM public.pdc_staging_environment_sentinel WHERE singleton AND project_ref='cdsmnqxtyyoeoznmbidd')<>1
  OR to_regclass('public.pdc_production_environment_sentinel') IS NOT NULL OR NOT public.pdc_monitor_staging_guard()
  OR NOT EXISTS(SELECT 1 FROM supabase_migrations.schema_migrations WHERE version='20260826204000' AND name='429_rft_email_intercept_receipts')
  OR EXISTS(SELECT 1 FROM supabase_migrations.schema_migrations WHERE version~'^[0-9]{14}$' AND version>'20260826204000') THEN RAISE EXCEPTION 'PDC_430_STAGING_HEAD_MISMATCH' USING errcode='55000'; END IF;
END $pre$;
CREATE OR REPLACE FUNCTION public.claim_pdc_rft_transport_email_intercept_acceptance_430()
RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path=pg_catalog,public,extensions AS $claim$
DECLARE uid uuid:=auth.uid(); actor_email text:=lower(btrim(coalesce(auth.jwt()->>'email',''))); o public.pdc_rft_transport_salesperson_outbox_412%rowtype; v public.vehicles%rowtype; token uuid; payload_sha text; now_at timestamptz:=clock_timestamp();
BEGIN
 IF uid<>'557dba7f-fd70-4b9e-aa7b-b83b717682a7'::uuid OR actor_email<>'administrator2@staging.pdc-workshop.example.com' OR NOT EXISTS(SELECT 1 FROM public.pdc_user_roles r WHERE r.auth_user_id=uid AND lower(r.email)=actor_email AND r.role='administrator' AND r.active AND r.account_status='approved') OR NOT public.pdc_monitor_staging_guard() THEN RETURN jsonb_build_object('ok',false,'code','acceptance_intercept_unauthorized'); END IF;
 PERFORM pg_advisory_xact_lock(hashtextextended('pdc-429-email-intercept-claim',0));
 SELECT x.* INTO o FROM public.pdc_rft_transport_salesperson_outbox_412 x JOIN public.vehicles vehicle ON vehicle.id=x.vehicle_id WHERE x.delivery_status='pending' AND x.sent_at IS NULL AND x.delivered_at IS NULL AND NOT coalesce((x.payload->>'delivery_enabled')::boolean,false) AND vehicle.stock_number LIKE 'HERMES-TEST-%' AND NOT EXISTS(SELECT 1 FROM public.pdc_rft_transport_email_intercept_receipts_429 r WHERE r.notification_id=x.notification_id) ORDER BY x.created_at,x.notification_id LIMIT 1 FOR UPDATE OF x SKIP LOCKED;
 IF NOT FOUND THEN RETURN jsonb_build_object('ok',true,'code','no_pending_synthetic_intercept'); END IF;
 SELECT * INTO v FROM public.vehicles WHERE id=o.vehicle_id; payload_sha:=encode(extensions.digest(convert_to(o.payload::text,'UTF8'),'sha256'),'hex'); token:=extensions.uuid_generate_v5('43000000-0000-5000-8000-000000000430'::uuid,o.notification_id::text||':'||payload_sha);
 INSERT INTO public.pdc_rft_transport_email_intercept_claims_429 VALUES(o.notification_id,token,uid,now_at,now_at+interval '10 minutes',payload_sha) ON CONFLICT(notification_id) DO UPDATE SET claim_token=excluded.claim_token,claimed_by=excluded.claimed_by,claimed_at=excluded.claimed_at,expires_at=excluded.expires_at,payload_sha256=excluded.payload_sha256;
 RETURN jsonb_build_object('ok',true,'code','synthetic_email_intercept_claimed','notification_id',o.notification_id,'transport_receipt_id',o.transport_receipt_id,'vehicle_id',o.vehicle_id,'stock_number',v.stock_number,'claim_token',token,'expires_at',now_at+interval '10 minutes','payload_sha256',payload_sha,'recipient_email',o.recipient_email,'payload',o.payload);
END $claim$;
CREATE OR REPLACE FUNCTION public.ack_pdc_rft_transport_email_intercept_acceptance_430(p_notification_id uuid,p_claim_token uuid,p_payload_sha256 text,p_mime_sha256 text,p_attachment_sha256 text,p_artifact_sha256 text,p_artifact_bytes bigint)
RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path=pg_catalog,public,extensions AS $ack$
DECLARE uid uuid:=auth.uid(); actor_email text:=lower(btrim(coalesce(auth.jwt()->>'email',''))); c public.pdc_rft_transport_email_intercept_claims_429%rowtype; o public.pdc_rft_transport_salesperson_outbox_412%rowtype; old public.pdc_rft_transport_email_intercept_receipts_429%rowtype; payload_sha text; receipt uuid;
BEGIN
 IF uid<>'557dba7f-fd70-4b9e-aa7b-b83b717682a7'::uuid OR actor_email<>'administrator2@staging.pdc-workshop.example.com' OR p_notification_id IS NULL OR p_claim_token IS NULL OR p_payload_sha256!~'^[a-f0-9]{64}$' OR p_mime_sha256!~'^[a-f0-9]{64}$' OR p_attachment_sha256!~'^[a-f0-9]{64}$' OR p_artifact_sha256!~'^[a-f0-9]{64}$' OR p_artifact_bytes<1 OR NOT public.pdc_monitor_staging_guard() THEN RETURN jsonb_build_object('ok',false,'code','acceptance_intercept_ack_invalid'); END IF;
 PERFORM pg_advisory_xact_lock(hashtextextended('pdc-429-email-intercept-ack:'||p_notification_id::text,0)); SELECT * INTO old FROM public.pdc_rft_transport_email_intercept_receipts_429 WHERE notification_id=p_notification_id;
 IF FOUND THEN IF old.claim_token<>p_claim_token OR old.payload_sha256<>p_payload_sha256 OR old.mime_sha256<>p_mime_sha256 OR old.attachment_sha256<>p_attachment_sha256 OR old.artifact_sha256<>p_artifact_sha256 OR old.artifact_bytes<>p_artifact_bytes THEN RAISE EXCEPTION 'PDC_430_INTERCEPT_REPLAY_MISMATCH' USING errcode='22023'; END IF; RETURN jsonb_build_object('ok',true,'code','synthetic_email_intercepted','replay',true,'receipt_id',old.receipt_id,'notification_id',old.notification_id,'outcome',old.outcome); END IF;
 SELECT * INTO c FROM public.pdc_rft_transport_email_intercept_claims_429 WHERE notification_id=p_notification_id AND claim_token=p_claim_token AND claimed_by=uid AND expires_at>=clock_timestamp() FOR UPDATE; IF NOT FOUND THEN RETURN jsonb_build_object('ok',false,'code','intercept_claim_missing_or_expired'); END IF;
 SELECT * INTO o FROM public.pdc_rft_transport_salesperson_outbox_412 WHERE notification_id=p_notification_id FOR SHARE; payload_sha:=encode(extensions.digest(convert_to(o.payload::text,'UTF8'),'sha256'),'hex');
 IF payload_sha<>c.payload_sha256 OR payload_sha<>p_payload_sha256 OR lower(o.payload#>>'{photo_attachment,sha256}')<>p_attachment_sha256 OR o.delivery_status<>'pending' OR o.sent_at IS NOT NULL OR o.delivered_at IS NOT NULL OR coalesce((o.payload->>'delivery_enabled')::boolean,false) THEN RAISE EXCEPTION 'PDC_430_INTERCEPT_EVIDENCE_MISMATCH' USING errcode='55000'; END IF;
 receipt:=extensions.uuid_generate_v5('42900000-0000-5000-8000-000000000429'::uuid,o.notification_id::text||':'||payload_sha||':'||p_mime_sha256); INSERT INTO public.pdc_rft_transport_email_intercept_receipts_429 VALUES(receipt,o.notification_id,o.transport_receipt_id,o.vehicle_id,uid,actor_email,p_claim_token,p_payload_sha256,p_mime_sha256,p_attachment_sha256,p_artifact_sha256,p_artifact_bytes,'intercepted',clock_timestamp());
 RETURN jsonb_build_object('ok',true,'code','synthetic_email_intercepted','replay',false,'receipt_id',receipt,'notification_id',o.notification_id,'outcome','intercepted','outbox_status',o.delivery_status,'sent_at',o.sent_at,'delivered_at',o.delivered_at);
END $ack$;
REVOKE ALL ON FUNCTION public.claim_pdc_rft_transport_email_intercept_acceptance_430() FROM public,anon,authenticated,service_role; REVOKE ALL ON FUNCTION public.ack_pdc_rft_transport_email_intercept_acceptance_430(uuid,uuid,text,text,text,text,bigint) FROM public,anon,authenticated,service_role;
GRANT EXECUTE ON FUNCTION public.claim_pdc_rft_transport_email_intercept_acceptance_430() TO authenticated; GRANT EXECUTE ON FUNCTION public.ack_pdc_rft_transport_email_intercept_acceptance_430(uuid,uuid,text,text,text,text,bigint) TO authenticated;
CREATE POLICY pdc_rft_transport_interceptor_admin_read_430 ON storage.objects FOR SELECT TO authenticated USING(bucket_id='pdc-qc-evidence-staging' AND auth.uid()='557dba7f-fd70-4b9e-aa7b-b83b717682a7'::uuid AND EXISTS(SELECT 1 FROM public.pdc_rft_transport_salesperson_outbox_412 o JOIN public.vehicles v ON v.id=o.vehicle_id WHERE o.delivery_status='pending' AND o.sent_at IS NULL AND o.delivered_at IS NULL AND v.stock_number LIKE 'HERMES-TEST-%' AND o.payload#>>'{photo_attachment,bucket_id}'=storage.objects.bucket_id AND o.payload#>>'{photo_attachment,storage_path}'=storage.objects.name));
INSERT INTO supabase_migrations.schema_migrations(version,name,statements) VALUES('20260826205000','430_admin_email_intercept_acceptance',ARRAY['Exact staging Admin2-only synthetic claim/ack and narrow QC object policy permit end-to-end interception acceptance while the isolated pmbcontroller credential is repaired separately','No real recipient, outbound provider, real vehicle, Production target or outbox sent/delivered field is touched']);
NOTIFY pgrst,'reload schema'; COMMIT;
