-- STAGING ONLY 20260901237000: carry the strict v2 capability into the
-- summary projector invoked by canonical note append.
BEGIN; SET LOCAL lock_timeout='10s'; SET LOCAL statement_timeout='180s';
SELECT pg_advisory_xact_lock(hashtextextended('pdc-staging-20260901237000-v2-summary-projector-capability',0)); LOCK TABLE supabase_migrations.schema_migrations IN EXCLUSIVE MODE;
DO $guard$ BEGIN IF current_user<>'postgres' OR session_user<>'postgres' OR current_setting('app.environment',true)='production' OR to_regclass('public.pdc_production_environment_sentinel') IS NOT NULL OR (SELECT count(*) FROM public.pdc_staging_environment_sentinel WHERE singleton AND project_ref='cdsmnqxtyyoeoznmbidd')<>1 OR (SELECT max(version::numeric) FROM supabase_migrations.schema_migrations WHERE version~'^[0-9]+$')<>20260901236000 OR EXISTS(SELECT 1 FROM supabase_migrations.schema_migrations WHERE version='20260901237000') OR to_regprocedure('public.rebuild_vehicle_intelligence_summary(uuid)') IS NULL THEN RAISE EXCEPTION 'PDC_20260901237000_STAGING_PRECONDITION_FAILED' USING errcode='55000'; END IF; END $guard$;
CREATE TABLE public.pdc_email_ai_v2_canonical_summary_capability_history_20260901(history_id uuid PRIMARY KEY DEFAULT gen_random_uuid(),event_key text NOT NULL UNIQUE,predecessor_head text NOT NULL CHECK(predecessor_head='20260901236000'),successor_head text NOT NULL CHECK(successor_head='20260901237000'),predecessor_hash text NOT NULL,successor_hash text NOT NULL,repair_contract text NOT NULL,production_writes boolean NOT NULL CHECK(NOT production_writes),mailbox_contacted boolean NOT NULL CHECK(NOT mailbox_contacted),outbound_email boolean NOT NULL CHECK(NOT outbound_email),action_rpc_invoked boolean NOT NULL CHECK(NOT action_rpc_invoked),created_at timestamptz NOT NULL DEFAULT clock_timestamp());
ALTER TABLE public.pdc_email_ai_v2_canonical_summary_capability_history_20260901 ENABLE ROW LEVEL SECURITY; ALTER TABLE public.pdc_email_ai_v2_canonical_summary_capability_history_20260901 FORCE ROW LEVEL SECURITY; REVOKE ALL ON public.pdc_email_ai_v2_canonical_summary_capability_history_20260901 FROM public,anon,authenticated,service_role,pdc_email_monitor;
CREATE FUNCTION public.pdc_email_ai_v2_canonical_summary_capability_history_immutable_20260901() RETURNS trigger LANGUAGE plpgsql SECURITY DEFINER SET search_path=pg_catalog,public AS $$ BEGIN RAISE EXCEPTION 'PDC_20260901237000_SUMMARY_HISTORY_IMMUTABLE' USING errcode='55000'; END $$;
CREATE TRIGGER pdc_email_ai_v2_canonical_summary_capability_history_immutable_20260901 BEFORE UPDATE OR DELETE ON public.pdc_email_ai_v2_canonical_summary_capability_history_20260901 FOR EACH ROW EXECUTE FUNCTION public.pdc_email_ai_v2_canonical_summary_capability_history_immutable_20260901();
DO $repair$
DECLARE d text; old text; new text; before_hash text; after_hash text;
BEGIN
 SELECT pg_get_functiondef('public.rebuild_vehicle_intelligence_summary(uuid)'::regprocedure),encode(extensions.digest(convert_to(pg_get_functiondef('public.rebuild_vehicle_intelligence_summary(uuid)'::regprocedure),'UTF8'),'sha256'),'hex') INTO d,before_hash;
 old:=$old$if public.current_pdc_user_role() not in ('importer', 'administrator', 'operator') then$old$; new:=$new$if public.current_pdc_user_role() not in ('importer', 'administrator', 'operator') and current_setting('pdc.monitor.v2_canonical_action_capability_20260902',true) NOT LIKE 'pdc-email-ai-v2|%' then$new$;
 IF position(old IN d)=0 THEN RAISE EXCEPTION 'PDC_20260901237000_SUMMARY_GUARD_ANCHOR_FAILED' USING errcode='55000'; END IF;
 d:=replace(d,old,new); EXECUTE d;
 SELECT encode(extensions.digest(convert_to(pg_get_functiondef('public.rebuild_vehicle_intelligence_summary(uuid)'::regprocedure),'UTF8'),'sha256'),'hex') INTO after_hash;
 INSERT INTO public.pdc_email_ai_v2_canonical_summary_capability_history_20260901(event_key,predecessor_head,successor_head,predecessor_hash,successor_hash,repair_contract,production_writes,mailbox_contacted,outbound_email,action_rpc_invoked) VALUES(encode(extensions.digest(convert_to('pdc-staging-20260901237000-v2-summary-projector-capability|forward','UTF8'),'sha256'),'hex'),'20260901236000','20260901237000',before_hash,after_hash,'Summary projection invoked by strict canonical note accepts the same dotted transaction-local actor-bound capability; ordinary importer/administrator/operator paths remain unchanged.',false,false,false,false);
END $repair$;
DO $post$ BEGIN IF (SELECT count(*) FROM public.pdc_email_ai_v2_canonical_summary_capability_history_20260901)<>1 OR position('pdc.monitor.v2_canonical_action_capability_20260902' IN (SELECT pg_get_functiondef('public.rebuild_vehicle_intelligence_summary(uuid)'::regprocedure)))=0 THEN RAISE EXCEPTION 'PDC_20260901237000_POSTCONDITION_FAILED' USING errcode='55000'; END IF; END $post$;
INSERT INTO supabase_migrations.schema_migrations(version,name,statements) VALUES('20260901237000','pdc_email_ai_v2_canonical_summary_capability_20260901',ARRAY['Summary projection invoked by strict canonical note accepts the actor-bound dotted transaction-local capability','Ordinary operator/importer/administrator controls, immutable receipts, source binding, field readback and zero Production/mailbox/outbound/action-RPC state remain unchanged']); NOTIFY pgrst,'reload schema'; COMMIT;
