-- STAGING ONLY 710: make every JSONB-minus-key-array expression in the
-- existing strict 502 execute function explicitly grouped. This closes the
-- remaining precedence path revealed after the synthetic authoritative pre-read.
BEGIN;
SET LOCAL lock_timeout='10s'; SET LOCAL statement_timeout='90s';
SELECT pg_advisory_xact_lock(hashtextextended('pdc-staging-710-agentic-execute-explicit-subtraction',0));
LOCK TABLE supabase_migrations.schema_migrations IN EXCLUSIVE MODE;
DO $guard$
DECLARE h text;
BEGIN SELECT encode(extensions.digest(convert_to(p.prosrc,'UTF8'),'sha256'),'hex') INTO h FROM pg_proc p WHERE p.oid='public.execute_pdc_agentic_email_action_502(jsonb)'::regprocedure;
 IF current_user<>'postgres' OR session_user<>'postgres' OR (SELECT count(*) FROM public.pdc_staging_environment_sentinel WHERE singleton AND project_ref='cdsmnqxtyyoeoznmbidd')<>1 OR to_regclass('public.pdc_production_environment_sentinel') IS NOT NULL OR lower(coalesce(current_setting('app.environment',true),''))='production' OR (SELECT max(version) FROM supabase_migrations.schema_migrations WHERE version~'^[0-9]{14}$')<>'20260828310000' OR h<>'80a5ae67bd7f50b6ad9c938095a6d94be3e6f3f9c3267a7dc25c8a06e2add0c2' OR to_regclass('public.pdc_authenticated_agentic_execute_explicit_history_710') IS NOT NULL THEN RAISE EXCEPTION 'PDC_710_EXACT_709_EXECUTE_PREDECESSOR_MISMATCH' USING errcode='55000'; END IF; END $guard$;
CREATE TABLE public.pdc_authenticated_agentic_execute_explicit_history_710(history_id uuid PRIMARY KEY DEFAULT gen_random_uuid(),event_key text NOT NULL UNIQUE,event_kind text NOT NULL CHECK(event_kind='agentic_execute_explicit_jsonb_subtraction'),predecessor_head text NOT NULL CHECK(predecessor_head='20260828310000'),successor_head text NOT NULL CHECK(successor_head='20260828320000'),predecessor_function_sha256 text NOT NULL CHECK(predecessor_function_sha256='80a5ae67bd7f50b6ad9c938095a6d94be3e6f3f9c3267a7dc25c8a06e2add0c2'),successor_function_sha256 text NOT NULL,repair_contract text NOT NULL,production_writes boolean NOT NULL CHECK(NOT production_writes),task_enabled boolean NOT NULL CHECK(NOT task_enabled),mailbox_contacted boolean NOT NULL CHECK(NOT mailbox_contacted),uid514_processed boolean NOT NULL CHECK(NOT uid514_processed),created_at timestamptz NOT NULL DEFAULT clock_timestamp());
ALTER TABLE public.pdc_authenticated_agentic_execute_explicit_history_710 ENABLE ROW LEVEL SECURITY; ALTER TABLE public.pdc_authenticated_agentic_execute_explicit_history_710 FORCE ROW LEVEL SECURITY; REVOKE ALL ON public.pdc_authenticated_agentic_execute_explicit_history_710 FROM public,anon,authenticated,service_role,pdc_email_monitor;
CREATE FUNCTION public.pdc_authenticated_agentic_execute_explicit_history_immutable_710() RETURNS trigger LANGUAGE plpgsql SECURITY DEFINER SET search_path=pg_catalog,public AS $$ BEGIN RAISE EXCEPTION 'PDC_710_EXECUTE_EXPLICIT_HISTORY_IMMUTABLE' USING errcode='55000'; END $$;
REVOKE ALL ON FUNCTION public.pdc_authenticated_agentic_execute_explicit_history_immutable_710() FROM public,anon,authenticated,service_role,pdc_email_monitor;
CREATE TRIGGER pdc_authenticated_agentic_execute_explicit_history_immutable_710 BEFORE UPDATE OR DELETE ON public.pdc_authenticated_agentic_execute_explicit_history_710 FOR EACH ROW EXECUTE FUNCTION public.pdc_authenticated_agentic_execute_explicit_history_immutable_710();
DO $repair$
DECLARE d text;before_sha text;after_sha text;old text;new text;
BEGIN
 SELECT pg_get_functiondef('public.execute_pdc_agentic_email_action_502(jsonb)'::regprocedure),encode(extensions.digest(convert_to(p.prosrc,'UTF8'),'sha256'),'hex') INTO d,before_sha FROM pg_proc p WHERE p.oid='public.execute_pdc_agentic_email_action_502(jsonb)'::regprocedure;
 old:=$old$p_action-array['plan_hash','evidence_hash','source_binding','planned_vehicle_id','current_state','context','terminal_only']::text[]$old$; new:=$new$(p_action-array['plan_hash','evidence_hash','source_binding','planned_vehicle_id','current_state','context','terminal_only']::text[])$new$;
 IF before_sha<>'80a5ae67bd7f50b6ad9c938095a6d94be3e6f3f9c3267a7dc25c8a06e2add0c2' OR position(old IN d)=0 THEN RAISE EXCEPTION 'PDC_710_ACTION_SUBTRACTION_ANCHOR_MISMATCH' USING errcode='55000'; END IF;
 d:=replace(d,old,new); EXECUTE d;
 SELECT encode(extensions.digest(convert_to(p.prosrc,'UTF8'),'sha256'),'hex') INTO after_sha FROM pg_proc p WHERE p.oid='public.execute_pdc_agentic_email_action_502(jsonb)'::regprocedure;
 INSERT INTO public.pdc_authenticated_agentic_execute_explicit_history_710(event_key,event_kind,predecessor_head,successor_head,predecessor_function_sha256,successor_function_sha256,repair_contract,production_writes,task_enabled,mailbox_contacted,uid514_processed) VALUES(encode(extensions.digest(convert_to('pdc-staging-710-agentic-execute-explicit-subtraction|forward','UTF8'),'sha256'),'hex'),'agentic_execute_explicit_jsonb_subtraction','20260828310000','20260828320000',before_sha,after_sha,'Group the p_action key-array subtraction explicitly; the expression remains identical in meaning while avoiding text-to-JSON coercion during authoritative action membership comparison',false,false,false,false);
END $repair$;
DO $post$ BEGIN IF (SELECT count(*) FROM public.pdc_authenticated_agentic_execute_explicit_history_710)<>1 OR position('(p_action-array[' IN (SELECT p.prosrc FROM pg_proc p WHERE p.oid='public.execute_pdc_agentic_email_action_502(jsonb)'::regprocedure))=0 OR to_regclass('public.pdc_production_environment_sentinel') IS NOT NULL THEN RAISE EXCEPTION 'PDC_710_POSTCONDITION_FAILED' USING errcode='55000'; END IF; END $post$;
INSERT INTO supabase_migrations.schema_migrations(version,name,statements) VALUES('20260828320000','710_agentic_execute_explicit_jsonb_subtraction',ARRAY['Exact 709 predecessor and execute-function hash guard','Explicitly group the remaining p_action minus text-array expression','Normal Board/read filters, action semantics, idempotency, UID514/task/mailbox/outbound and Production untouched']);
NOTIFY pgrST,'reload schema'; COMMIT;
