-- STAGING ONLY 724: route canonical apply readback through the exact
-- synthetic context projection for UID>=515 acceptance actions.
BEGIN;
SET LOCAL lock_timeout='10s'; SET LOCAL statement_timeout='90s';
SELECT pg_advisory_xact_lock(hashtextextended('pdc-staging-724-agentic-apply-readback',0));
LOCK TABLE supabase_migrations.schema_migrations IN EXCLUSIVE MODE;
DO $guard$
DECLARE h text;
BEGIN SELECT encode(extensions.digest(convert_to(p.prosrc,'UTF8'),'sha256'),'hex') INTO h FROM pg_proc p WHERE p.oid='public.pdc_agentic_apply_action_502(uuid)'::regprocedure;
 IF current_user<>'postgres' OR session_user<>'postgres' OR (SELECT count(*) FROM public.pdc_staging_environment_sentinel WHERE singleton AND project_ref='cdsmnqxtyyoeoznmbidd')<>1 OR to_regclass('public.pdc_production_environment_sentinel') IS NOT NULL OR lower(coalesce(current_setting('app.environment',true),''))='production' OR (SELECT max(version) FROM supabase_migrations.schema_migrations WHERE version~'^[0-9]{14}$')<>'20260828450000' OR h<>'4b131be7ccd705862971779e93481865908ef6616672bf6667c4d33512418806' OR to_regclass('public.pdc_authenticated_agentic_apply_readback_history_724') IS NOT NULL THEN RAISE EXCEPTION 'PDC_724_EXACT_723_APPLY_PREDECESSOR_MISMATCH' USING errcode='55000'; END IF; END $guard$;
CREATE TABLE public.pdc_authenticated_agentic_apply_readback_history_724(history_id uuid PRIMARY KEY DEFAULT gen_random_uuid(),event_key text NOT NULL UNIQUE,event_kind text NOT NULL CHECK(event_kind='agentic_apply_acceptance_readback'),predecessor_head text NOT NULL CHECK(predecessor_head='20260828450000'),successor_head text NOT NULL CHECK(successor_head='20260828460000'),predecessor_function_sha256 text NOT NULL CHECK(predecessor_function_sha256='4b131be7ccd705862971779e93481865908ef6616672bf6667c4d33512418806'),successor_function_sha256 text NOT NULL,repair_contract text NOT NULL,production_writes boolean NOT NULL CHECK(NOT production_writes),task_enabled boolean NOT NULL CHECK(NOT task_enabled),mailbox_contacted boolean NOT NULL CHECK(NOT mailbox_contacted),uid514_processed boolean NOT NULL CHECK(NOT uid514_processed),created_at timestamptz NOT NULL DEFAULT clock_timestamp());
ALTER TABLE public.pdc_authenticated_agentic_apply_readback_history_724 ENABLE ROW LEVEL SECURITY; ALTER TABLE public.pdc_authenticated_agentic_apply_readback_history_724 FORCE ROW LEVEL SECURITY; REVOKE ALL ON public.pdc_authenticated_agentic_apply_readback_history_724 FROM public,anon,authenticated,service_role,pdc_email_monitor;
CREATE FUNCTION public.pdc_authenticated_agentic_apply_readback_history_immutable_724() RETURNS trigger LANGUAGE plpgsql SECURITY DEFINER SET search_path=pg_catalog,public AS $$ BEGIN RAISE EXCEPTION 'PDC_724_APPLY_READBACK_HISTORY_IMMUTABLE' USING errcode='55000'; END $$;
REVOKE ALL ON FUNCTION public.pdc_authenticated_agentic_apply_readback_history_immutable_724() FROM public,anon,authenticated,service_role,pdc_email_monitor;
CREATE TRIGGER pdc_authenticated_agentic_apply_readback_history_immutable_724 BEFORE UPDATE OR DELETE ON public.pdc_authenticated_agentic_apply_readback_history_724 FOR EACH ROW EXECUTE FUNCTION public.pdc_authenticated_agentic_apply_readback_history_immutable_724();
DO $repair$
DECLARE d text;before_sha text;after_sha text;old text;new text;
BEGIN
 SELECT pg_get_functiondef('public.pdc_agentic_apply_action_502(uuid)'::regprocedure),encode(extensions.digest(convert_to(p.prosrc,'UTF8'),'sha256'),'hex') INTO d,before_sha FROM pg_proc p WHERE p.oid='public.pdc_agentic_apply_action_502(uuid)'::regprocedure;
 old:=$old$v_after:=public.read_pdc_agentic_email_vehicle_502(v_readback_vehicle_id);$old$; new:=$new$v_after:=case when ((a.request->'source_binding')->>'provider_uid'~'^imap_uid:[0-9]+$' and substring((a.request->'source_binding')->>'provider_uid' from 10)::bigint>=515) then public.pdc_monitor_authenticated_acceptance_vehicle_projection_703(v_readback_vehicle_id,p.context_receipt_id) else public.read_pdc_agentic_email_vehicle_502(v_readback_vehicle_id) end;$new$;
 IF before_sha<>'4b131be7ccd705862971779e93481865908ef6616672bf6667c4d33512418806' OR position(old IN d)=0 THEN RAISE EXCEPTION 'PDC_724_READBACK_ANCHOR_MISMATCH' USING errcode='55000'; END IF;
 EXECUTE replace(d,old,new);
 SELECT encode(extensions.digest(convert_to(p.prosrc,'UTF8'),'sha256'),'hex') INTO after_sha FROM pg_proc p WHERE p.oid='public.pdc_agentic_apply_action_502(uuid)'::regprocedure;
 INSERT INTO public.pdc_authenticated_agentic_apply_readback_history_724(event_key,event_kind,predecessor_head,successor_head,predecessor_function_sha256,successor_function_sha256,repair_contract,production_writes,task_enabled,mailbox_contacted,uid514_processed) VALUES(encode(extensions.digest(convert_to('pdc-staging-724-agentic-apply-readback|forward','UTF8'),'sha256'),'hex'),'agentic_apply_acceptance_readback','20260828450000','20260828460000',before_sha,after_sha,'Use the exact server-side acceptance vehicle projection for apply verification only when the action source carries provider UID>=515; normal canonical apply readback remains unchanged',false,false,false,false);
END $repair$;
DO $post$ BEGIN IF (SELECT count(*) FROM public.pdc_authenticated_agentic_apply_readback_history_724)<>1 OR position('pdc_monitor_authenticated_acceptance_vehicle_projection_703' IN (SELECT p.prosrc FROM pg_proc p WHERE p.oid='public.pdc_agentic_apply_action_502(uuid)'::regprocedure))=0 OR to_regclass('public.pdc_production_environment_sentinel') IS NOT NULL THEN RAISE EXCEPTION 'PDC_724_POSTCONDITION_FAILED' USING errcode='55000'; END IF; END $post$;
INSERT INTO supabase_migrations.schema_migrations(version,name,statements) VALUES('20260828460000','724_agentic_apply_acceptance_readback',ARRAY['Exact 723 predecessor and canonical apply hash guard','Acceptance-only apply readback uses exact synthetic context projection; normal readback unchanged','UID514/task/mailbox/outbound/Production untouched']);
NOTIFY pgrST,'reload schema'; COMMIT;
