-- STAGING ONLY 468: bind the reviewed reset scope correction and preservation evidence.
BEGIN;SET LOCAL lock_timeout='10s';SET LOCAL statement_timeout='120s';
SELECT pg_advisory_xact_lock(hashtextextended('pdc-staging-468-reset-review-correction',0));
DO $guard$ BEGIN
 IF current_user<>'postgres' OR session_user<>'postgres'
 OR (SELECT count(*) FROM public.pdc_staging_environment_sentinel WHERE singleton AND project_ref='cdsmnqxtyyoeoznmbidd')<>1
 OR to_regclass('public.pdc_production_environment_sentinel') IS NOT NULL
 OR NOT EXISTS(SELECT 1 FROM supabase_migrations.schema_migrations WHERE version='20260827017000' AND name='467_bind_direct_inbox_reset_cutoff')
 OR EXISTS(SELECT 1 FROM supabase_migrations.schema_migrations WHERE version~'^[0-9]{14}$' AND version>'20260827017000')
 OR (SELECT count(*) FROM public.pdc_auditor_telegram_deliveries_230)<>0 OR (SELECT count(*) FROM public.pdc_auditor_telegram_instructions_225)<>0
 OR (SELECT count(*) FROM public.pdc_email_source_claims)<>0 OR (SELECT count(*) FROM public.pdc_jobcard_attachment_rule_receipts_279)<>0
 OR (SELECT count(*) FROM public.pdc_monitor_runtime_binding_rotations_270)<>0 OR (SELECT count(*) FROM public.pdc_supervised_rule_events)<>0 OR (SELECT count(*) FROM public.pdc_supervised_telegram_commands)<>0
 THEN RAISE EXCEPTION 'PDC_468_TARGET_HEAD_OR_SCOPE_RESULT_MISMATCH' USING errcode='55000';END IF;
END $guard$;
DO $rules$ BEGIN
 IF (SELECT count(*) FROM public.pdc_supervised_rule_families)<>29 OR (SELECT count(*) FROM public.pdc_supervised_rule_versions)<>29 OR (SELECT count(*) FROM public.pdc_supervised_rule_aliases)<>39 OR (SELECT count(*) FROM public.pdc_supervised_rule_examples)<>30
 OR (SELECT count(*) FROM public.pdc_auditor_rule_families_227)<>1 OR (SELECT count(*) FROM public.pdc_auditor_rule_versions_227)<>1 OR (SELECT count(*) FROM public.pdc_auditor_rule_config)<>4 OR (SELECT count(*) FROM public.pdc_auditor_rule_examples_227)<>2
 OR (SELECT count(*) FROM public.pdc_email_monitor_activation_receipts_454)<>1 OR (SELECT count(*) FROM public.pdc_email_monitor_runtime_receipts_455)<>1
 THEN RAISE EXCEPTION 'PDC_468_CANONICAL_RULE_OR_RUNTIME_CONFIG_DRIFT' USING errcode='55000';END IF;
END $rules$;
CREATE TABLE public.pdc_staging_reset_review_corrections_468(receipt_id uuid PRIMARY KEY DEFAULT gen_random_uuid(),project_ref text NOT NULL CHECK(project_ref='cdsmnqxtyyoeoznmbidd'),reset_version text NOT NULL CHECK(reset_version='20260827016000'),scope_sha256 text NOT NULL CHECK(scope_sha256='b6156455a4cc0ceda441a5d525fd50bc00cc9868f7063707b71fcba9c58cf574'),backup_manifest_sha256 text NOT NULL CHECK(backup_manifest_sha256='055acf91eac9c45847e0140bae515a4c4dcc0a9a9fd637d5b81f78b5ad6b77d5'),reclassified_operational_history jsonb NOT NULL,canonical_preservation jsonb NOT NULL,backup_evidence_boundary text NOT NULL CHECK(backup_evidence_boundary='encrypted snapshot has exact per-table hashes; reset preflight bound live table counts after all automatic writers were stopped'),fk_execution_note text NOT NULL CHECK(fk_execution_note='existing FK ON DELETE actions participated; no constraint was dropped or disabled and final authoritative zero readback covered every purge relation'),created_at timestamptz NOT NULL DEFAULT clock_timestamp());
ALTER TABLE public.pdc_staging_reset_review_corrections_468 ENABLE ROW LEVEL SECURITY;REVOKE ALL ON public.pdc_staging_reset_review_corrections_468 FROM public,anon,authenticated,service_role;
CREATE FUNCTION public.pdc_staging_reset_review_correction_immutable_468() RETURNS trigger LANGUAGE plpgsql SECURITY DEFINER SET search_path=pg_catalog,public AS $$BEGIN RAISE EXCEPTION 'PDC_468_REVIEW_CORRECTION_IMMUTABLE' USING errcode='55000';END$$;REVOKE ALL ON FUNCTION public.pdc_staging_reset_review_correction_immutable_468() FROM public,anon,authenticated,service_role;CREATE TRIGGER pdc_staging_reset_review_correction_immutable_468 BEFORE UPDATE OR DELETE ON public.pdc_staging_reset_review_corrections_468 FOR EACH ROW EXECUTE FUNCTION public.pdc_staging_reset_review_correction_immutable_468();
INSERT INTO public.pdc_staging_reset_review_corrections_468(project_ref,reset_version,scope_sha256,backup_manifest_sha256,reclassified_operational_history,canonical_preservation,backup_evidence_boundary,fk_execution_note) VALUES('cdsmnqxtyyoeoznmbidd','20260827016000','b6156455a4cc0ceda441a5d525fd50bc00cc9868f7063707b71fcba9c58cf574','055acf91eac9c45847e0140bae515a4c4dcc0a9a9fd637d5b81f78b5ad6b77d5','["pdc_auditor_telegram_deliveries_230","pdc_auditor_telegram_instructions_225","pdc_email_source_claims","pdc_jobcard_attachment_rule_receipts_279","pdc_monitor_runtime_binding_rotations_270","pdc_supervised_rule_events","pdc_supervised_telegram_commands"]'::jsonb,jsonb_build_object('supervised_rule_families',29,'supervised_rule_versions',29,'supervised_rule_aliases',39,'supervised_rule_examples',30,'auditor_rule_families',1,'auditor_rule_versions',1,'auditor_rule_config',4,'auditor_rule_examples',2,'monitor_activation_receipts',1,'monitor_runtime_receipts',1),'encrypted snapshot has exact per-table hashes; reset preflight bound live table counts after all automatic writers were stopped','existing FK ON DELETE actions participated; no constraint was dropped or disabled and final authoritative zero readback covered every purge relation');
INSERT INTO supabase_migrations.schema_migrations(version,name,statements) VALUES('20260827018000','468_bind_reset_scope_review_correction',ARRAY['Reclassify seven transport event receipt and claim tables as operational history under Craig full-backend reset intent','Prove canonical durable rule definitions aliases examples auth-adjacent runtime configuration remain preserved','Record exact backup evidence boundary and existing FK execution behavior without weakening constraints; Production untouched']);NOTIFY pgrst,'reload schema';COMMIT;
