-- STAGING ONLY 478: retain every genuine Job Card OP; unknown station/hours remain reviewable, never omitted or zeroed.
BEGIN;SET LOCAL statement_timeout='180s';SELECT pg_advisory_xact_lock(hashtextextended('pdc-staging-478-complete-jobcard-operation-contract',0));DO $g$ BEGIN IF current_user<>'postgres' OR (SELECT count(*) FROM public.pdc_staging_environment_sentinel WHERE singleton AND project_ref='cdsmnqxtyyoeoznmbidd')<>1 OR to_regclass('public.pdc_production_environment_sentinel') IS NOT NULL OR NOT EXISTS(SELECT 1 FROM supabase_migrations.schema_migrations WHERE version='20260827027000') OR EXISTS(SELECT 1 FROM supabase_migrations.schema_migrations WHERE version~'^[0-9]{14}$' AND version>'20260827027000') OR encode(extensions.digest(convert_to(pg_get_functiondef('public.import_pdc_jobcard_attachment_canonical(uuid,uuid,text,text,jsonb,jsonb,jsonb,jsonb)'::regprocedure),'UTF8'),'sha256'),'hex')<>'c4cd98fd67714465b5fd664917cda7e762f3e7abf7d24b2add36e9c6328f2cfe' OR encode(extensions.digest(convert_to(pg_get_functiondef('public.import_pdc_authenticated_email_operations_with_hours(text,text,jsonb)'::regprocedure),'UTF8'),'sha256'),'hex')<>'b3772c47de1a387ed6dec1e83b60d34d0fad517814a0b8f257693047d1f4b9ee' THEN RAISE EXCEPTION 'PDC_478_TARGET_OR_FUNCTION_MISMATCH';END IF;END $g$;
CREATE TABLE public.pdc_email_operation_mapping_reviews_478(mapping_review_id uuid PRIMARY KEY DEFAULT gen_random_uuid(),receipt_id uuid NOT NULL REFERENCES public.pdc_jobcard_attachment_import_receipts(receipt_id) ON DELETE RESTRICT,operation_line_id uuid NOT NULL UNIQUE REFERENCES public.pdc_authenticated_email_operation_lines(operation_line_id) ON DELETE RESTRICT,operation_no text NOT NULL CHECK(operation_no~'^OP([1-9]|[1-9][0-9]{1,2})$'),status text NOT NULL DEFAULT 'pending' CHECK(status IN('pending','resolved','dismissed')),reason text NOT NULL CHECK(reason='station mapping is not established by an existing Craig-approved durable rule'),created_at timestamptz NOT NULL DEFAULT clock_timestamp());ALTER TABLE public.pdc_email_operation_mapping_reviews_478 ENABLE ROW LEVEL SECURITY;REVOKE ALL ON public.pdc_email_operation_mapping_reviews_478 FROM public,anon,authenticated,service_role;
DO $canonical$ DECLARE d text;n text;BEGIN d:=pg_get_functiondef('public.import_pdc_jobcard_attachment_canonical(uuid,uuid,text,text,jsonb,jsonb,jsonb,jsonb)'::regprocedure);n:=d;
n:=replace(n,$old$or line->>'work_key' not in ('bus4x4','tint','hoist','fitting','fabrication','electrical','tyre','pitInspection','PARTS','sublet')$old$,$new$or line->>'work_key' not in ('bus4x4','tint','hoist','fitting','fabrication','electrical','tyre','pitInspection','PARTS','sublet','owner_supplied_document')$new$);
n:=replace(n,$old$or jsonb_typeof(line->'estimated_hours')<>'number'
       or (line->>'estimated_hours')::numeric<0 or (line->>'estimated_hours')::numeric>999.99
       or mod((line->>'estimated_hours')::numeric,0.01)<>0$old$,$new$or jsonb_typeof(line->'estimated_hours') not in ('number','null')
       or (jsonb_typeof(line->'estimated_hours')='number' and ((line->>'estimated_hours')::numeric<0 or (line->>'estimated_hours')::numeric>999.99 or mod((line->>'estimated_hours')::numeric,0.01)<>0))$new$);
n:=replace(n,$old$(select array_agg(distinct x->>'work_key' order by x->>'work_key') from jsonb_array_elements(v_input_lines) x)$old$,$new$(select array_agg(distinct x->>'work_key' order by x->>'work_key') from jsonb_array_elements(v_input_lines) x where x->>'work_key'<>'owner_supplied_document')$new$);
n:=replace(n,$old$'estimated_hours',(line->>'estimated_hours')::numeric,'estimated_hours_source','job_card'$old$,$new$'estimated_hours',case when jsonb_typeof(line->'estimated_hours')='number' then (line->>'estimated_hours')::numeric else null end,'estimated_hours_source',case when jsonb_typeof(line->'estimated_hours')='number' then 'job_card' else 'owner_supplied_document_unknown' end$new$);
n:=replace(n,$old$and ol.description=x.line->>'description' and ol.estimated_hours=(x.line->>'estimated_hours')::numeric
     and ol.estimated_hours_source='job_card';$old$,$new$and ol.description=x.line->>'description' and ol.estimated_hours is not distinct from case when jsonb_typeof(x.line->'estimated_hours')='number' then (x.line->>'estimated_hours')::numeric else null end
     and ol.estimated_hours_source=case when jsonb_typeof(x.line->'estimated_hours')='number' then 'job_card' else 'owner_supplied_document_unknown' end;$new$);
n:=replace(n,$old$v_operation_count,v_hours_sum,v_line_ids,v_response);
    for v_item in select value from jsonb_array_elements(v_input_lines) loop$old$,$new$v_operation_count,v_hours_sum,v_line_ids,v_response);
    insert into public.pdc_email_operation_mapping_reviews_478(receipt_id,operation_line_id,operation_no,reason) select v_receipt_id,ol.operation_line_id,ol.operation_no,'station mapping is not established by an existing Craig-approved durable rule' from public.pdc_authenticated_email_operation_lines ol where ol.source_hash=v_canonical_source_hash and ol.work_key='owner_supplied_document' on conflict(operation_line_id) do nothing;
    for v_item in select value from jsonb_array_elements(v_input_lines) loop$new$);
IF n=d OR n NOT LIKE '%pdc_email_operation_mapping_reviews_478%' OR n NOT LIKE '%owner_supplied_document_unknown%' THEN RAISE EXCEPTION 'PDC_478_CANONICAL_PATCH_ANCHOR_MISSING';END IF;EXECUTE n;END $canonical$;
DO $ops$ DECLARE d text;n text;BEGIN d:=pg_get_functiondef('public.import_pdc_authenticated_email_operations_with_hours(text,text,jsonb)'::regprocedure);n:=d;
n:=replace(n,$old$not in ('bus4x4','tint','hoist','fitting','fabrication','electrical','tyre','pitInspection','PARTS','sublet')$old$,$new$not in ('bus4x4','tint','hoist','fitting','fabrication','electrical','tyre','pitInspection','PARTS','sublet','owner_supplied_document')$new$);
n:=replace(n,$old$or (jsonb_typeof(x->'estimated_hours')='null' and x->>'estimated_hours_source' is not null)$old$,$new$or (jsonb_typeof(x->'estimated_hours')='null' and x->>'estimated_hours_source' is distinct from 'owner_supplied_document_unknown')$new$);
n:=replace(n,$old$select 1 from (select distinct x->>'work_key' as work_key from jsonb_array_elements(v_operations) x) requested$old$,$new$select 1 from (select distinct x->>'work_key' as work_key from jsonb_array_elements(v_operations) x where x->>'work_key'<>'owner_supplied_document') requested$new$);
n:=replace(n,$old$    v_work_before:=null; v_work_after:=null;$old$,$new$    if v_work_key<>'owner_supplied_document' then
    v_work_before:=null; v_work_after:=null;$new$);
n:=replace(n,$old$    end if;
  end loop;

  select revision into v_resulting_revision$old$,$new$    end if;
    end if;
  end loop;

  select revision into v_resulting_revision$new$);
IF n=d OR n NOT LIKE '%v_work_key<>''owner_supplied_document''%' OR n NOT LIKE '%owner_supplied_document_unknown%' THEN RAISE EXCEPTION 'PDC_478_OPS_PATCH_ANCHOR_MISSING';END IF;EXECUTE n;END $ops$;
INSERT INTO supabase_migrations.schema_migrations(version,name,statements) VALUES('20260827028000','478_complete_jobcard_operation_contract',ARRAY['Retain every genuine numbered Job Card operation including explicit zero-hour lines','Represent missing hours as NULL with owner_supplied_document_unknown, never zero','Represent unknown station as owner_supplied_document and create a pending mapping review instead of omitting the line','Exclude unknown station placeholders from required Workshop work while preserving known mapped requirements','Production untouched']);NOTIFY pgrst,'reload schema';COMMIT;
