-- Staging-only migration 215: Telegram teaching command completeness.
begin;
set local lock_timeout='10s';set local statement_timeout='180s';
select pg_advisory_xact_lock(hashtextextended('pdc-staging-migration-215-telegram-command-completeness',0));select public.pdc_monitor_staging_guard();
do $guard$ begin if not public.pdc_monitor_staging_guard() or not exists(select 1 from public.pdc_staging_environment_sentinel where singleton and project_ref='cdsmnqxtyyoeoznmbidd') or to_regclass('public.pdc_production_environment_sentinel') is not null or not exists(select 1 from supabase_migrations.schema_migrations where version='214' and name='supervised_learning_review_undo_hardening') or exists(select 1 from supabase_migrations.schema_migrations where version~'^[0-9]+$' and version::integer>214) or exists(select 1 from supabase_migrations.schema_migrations where version='215') then raise exception 'PDC_215_STAGING_OR_LEDGER_MISMATCH' using errcode='55000';end if;end $guard$;

create or replace function public.execute_pdc_supervised_learning_command(p_action text,p_parameters jsonb,p_telegram_evidence jsonb) returns jsonb language plpgsql security definer set search_path=pg_catalog,public as $$declare s jsonb:=public.pdc_supervised_admin_scope_213();a uuid;e text;sender bigint;result jsonb;f uuid;v uuid;scope jsonb;pricing jsonb;desc_norm text;prev public.pdc_supervised_rule_versions%rowtype;begin if not coalesce((s->>'ok')::boolean,false) then return public.navision_backend_response(false,'unauthorized');end if;a=(s->'data'->>'actor_id')::uuid;e=s->'data'->>'actor_email';sender=(p_telegram_evidence->>'telegram_sender_id')::bigint;if not exists(select 1 from public.pdc_supervised_telegram_identities i where i.telegram_sender_id=sender and i.auth_user_id=a and lower(i.actor_email)=e and i.active) then return public.navision_backend_response(false,'unauthorized');end if;
 if p_action='list_active' then result:=public.navision_backend_response(true,'active_lessons',jsonb_build_object('rules',(select coalesce(jsonb_agg(to_jsonb(x)),'[]'::jsonb) from public.list_pdc_supervised_rules_213(false)x)));
 elsif p_action='review_uncertain' then result:=public.navision_backend_response(true,'uncertain_lessons',jsonb_build_object('items',(select coalesce(jsonb_agg(to_jsonb(q)),'[]'::jsonb) from (select review_id,operation_code,source_description,current_mapping,reason,created_at from public.pdc_supervised_review_queue where resolved_at is null order by created_at desc limit 100)q)));
 elsif p_action='propose_lesson' then scope=p_parameters->'scope';pricing=p_parameters->'pricing';desc_norm=btrim(lower(regexp_replace(scope->>'operation_description','[^a-zA-Z0-9]+',' ','g')));if upper(coalesce(scope->>'operation_code','')) in('ALL','ANY','*') or desc_norm in('all','all accessories','accessories','all operations','everything','tint') or length(desc_norm)<4 then result:=public.navision_backend_response(true,'clarification_required',jsonb_build_object('question','This may match too broadly. Provide an exact operation code or exact description.','candidate_scope',scope));else result:=public.create_pdc_supervised_rule_family_213('telegram_'||substr(replace(gen_random_uuid()::text,'-',''),1,24),left(p_parameters->>'reason',160),p_telegram_evidence->>'original_instruction',case when nullif(scope->>'operation_code','') is not null then 'operation_code' else 'exact_description' end,scope->>'operation_code',desc_norm,null,p_parameters->>'target_mapping',1000,1,clock_timestamp(),case when p_parameters->>'estimated_hours' is null then null else (p_parameters->>'estimated_hours')::numeric end,case when pricing is null then null else (pricing->>'cost_ex_gst')::numeric end,case when pricing is null then null else (pricing->>'sell_ex_gst')::numeric end,case when pricing is null then null else (pricing->>'gst_percent')::numeric end,case when pricing is null then null else pricing->>'currency' end);result:=public.navision_backend_response(coalesce((result->>'ok')::boolean,false),'lesson_proposed',result->'data');end if;
 elsif p_action='create_corrected_version' then select * into prev from public.pdc_supervised_rule_versions where version_id=(p_parameters->>'lesson_id')::uuid;scope=p_parameters->'replacement'->'scope';pricing=p_parameters->'replacement'->'pricing';if not found then result:=public.navision_backend_response(false,'not_found');else result:=public.propose_pdc_supervised_rule_version_213(prev.family_id,prev.version_id,p_telegram_evidence->>'original_instruction',case when nullif(scope->>'operation_code','') is not null then 'operation_code' else 'exact_description' end,scope->>'operation_code',btrim(lower(regexp_replace(scope->>'operation_description','[^a-zA-Z0-9]+',' ','g'))),null,p_parameters->'replacement'->>'target_mapping',prev.priority,1,clock_timestamp(),case when p_parameters->'replacement'->>'estimated_hours' is null then null else (p_parameters->'replacement'->>'estimated_hours')::numeric end,case when pricing is null then null else (pricing->>'cost_ex_gst')::numeric end,case when pricing is null then null else (pricing->>'sell_ex_gst')::numeric end,case when pricing is null then null else (pricing->>'gst_percent')::numeric end,case when pricing is null then null else pricing->>'currency' end);v=(result->'data'->>'version_id')::uuid;perform public.activate_pdc_supervised_rule_version_213(v,'Telegram corrected rule version');result:=public.navision_backend_response(true,'corrected_version_created',jsonb_build_object('version_id',v,'predecessor_version_id',prev.version_id));end if;
 elsif p_action='activate_future' then result:=public.activate_pdc_supervised_rule_version_213((p_parameters->>'lesson_id')::uuid,'Telegram activation');result:=public.navision_backend_response(coalesce((result->>'ok')::boolean,false),'lesson_activated',coalesce(result->'data','{}'::jsonb));
 elsif p_action='disable' then select family_id into f from public.pdc_supervised_rule_versions where version_id=(p_parameters->>'lesson_id')::uuid;result:=public.disable_pdc_supervised_rule_213(f,'Telegram disable');result:=public.navision_backend_response(coalesce((result->>'ok')::boolean,false),'lesson_disabled',coalesce(result->'data','{}'::jsonb));
 elsif p_action='undo_last_lesson' then select family_id into f from public.pdc_supervised_rule_events where actor_id=a and event_kind in('proposed','activated','superseded','disabled') order by created_at desc,event_id desc limit 1;if f is null then result:=public.navision_backend_response(false,'no_lesson_to_undo');else result:=public.undo_pdc_supervised_rule_213(f,'Telegram undo last lesson');result:=public.navision_backend_response(true,'last_lesson_undone',jsonb_build_object('family_id',f,'undo',result->'data'));end if;
 elsif p_action='review_apply_existing_scope' then result:=public.navision_backend_response(true,'existing_scope_reviewed',jsonb_build_object('clarification_required',true,'message','Use exact operation-line scope preview before batch apply.'));
 elsif p_action='explain_why' then select family_id into f from public.pdc_supervised_rule_versions where version_id=(p_parameters->>'lesson_id')::uuid;result:=public.navision_backend_response(true,'lesson_explained',jsonb_build_object('lesson_id',p_parameters->>'lesson_id','family_id',f,'events',(select coalesce(jsonb_agg(to_jsonb(x)),'[]'::jsonb) from (select event_kind,reason,actor_email,created_at from public.pdc_supervised_rule_events where family_id=f order by created_at)x)));
 else result:=public.navision_backend_response(false,'invalid_request');end if;
 insert into public.pdc_supervised_telegram_commands(action,original_instruction,telegram_sender_id,telegram_chat_id,telegram_message_id,actor_id,actor_email,request,result_code) values(p_action,p_telegram_evidence->>'original_instruction',sender,(p_telegram_evidence->>'telegram_chat_id')::bigint,(p_telegram_evidence->>'telegram_message_id')::bigint,a,e,jsonb_build_object('parameters',p_parameters,'telegram_evidence',p_telegram_evidence),result->>'code') on conflict(telegram_chat_id,telegram_message_id) do nothing;return result;
exception when others then insert into public.pdc_supervised_failures(rpc_name,error_code,error_detail,actor_id,actor_email,request_context) values('execute_pdc_supervised_learning_command',sqlstate,sqlerrm,a,e,jsonb_build_object('action',p_action));return public.navision_backend_response(false,'rpc_error');end$$;
revoke all on function public.execute_pdc_supervised_learning_command(text,jsonb,jsonb) from public,anon,authenticated,service_role;grant execute on function public.execute_pdc_supervised_learning_command(text,jsonb,jsonb) to authenticated;
insert into supabase_migrations.schema_migrations(version,name,statements) values('215','telegram_supervised_command_completeness',array['dangerously broad lessons require clarification','corrected versions supersede previous versions','uncertain review reads durable queue','why includes rule event evidence','all Telegram commands append immutable evidence']);notify pgrst,'reload schema';commit;
