-- Staging-only migration 217: complete correction evidence and Administrator Telegram enrollment.
begin;set local lock_timeout='10s';set local statement_timeout='180s';select pg_advisory_xact_lock(hashtextextended('pdc-staging-migration-217-supervised-evidence-enrollment',0));select public.pdc_monitor_staging_guard();do $guard$ begin if not public.pdc_monitor_staging_guard() or not exists(select 1 from public.pdc_staging_environment_sentinel where singleton and project_ref='cdsmnqxtyyoeoznmbidd') or to_regclass('public.pdc_production_environment_sentinel') is not null or not exists(select 1 from supabase_migrations.schema_migrations where version='216' and name='supervised_rule_list_column_qualification') or exists(select 1 from supabase_migrations.schema_migrations where version~'^[0-9]+$' and version::integer>216) or exists(select 1 from supabase_migrations.schema_migrations where version='217') then raise exception 'PDC_217_STAGING_OR_LEDGER_MISMATCH' using errcode='55000';end if;end $guard$;
create table public.pdc_supervised_correction_evidence(
 evidence_id uuid primary key default gen_random_uuid(),item_id uuid not null unique references public.pdc_supervised_correction_items(item_id) on delete restrict,
 original_telegram_instruction text not null check(length(btrim(original_telegram_instruction)) between 3 and 4000),
 authorizing_user_id uuid not null references auth.users(id) on delete restrict,authorizing_email text not null,
 bot_identity text not null check(length(btrim(bot_identity)) between 3 and 160),source_telegram_sender_id bigint not null,
 recorded_at timestamptz not null default clock_timestamp()
);
alter table public.pdc_supervised_correction_evidence enable row level security;revoke all on table public.pdc_supervised_correction_evidence from public,anon,authenticated,service_role;create trigger pdc_supervised_correction_evidence_immutable before update or delete on public.pdc_supervised_correction_evidence for each row execute function public.pdc_supervised_immutable_213();
do $seed$ declare a uuid;e text;begin select auth_user_id,lower(email) into a,e from public.pdc_user_roles where role='administrator' and active and account_status='approved' and lower(email)='craig.watson@broometoyota.com.au' limit 1;if a is null then raise exception 'PDC_217_CRAIG_AUTHORIZER_MISSING';end if;insert into public.pdc_supervised_correction_evidence(item_id,original_telegram_instruction,authorizing_user_id,authorizing_email,bot_identity,source_telegram_sender_id)
select i.item_id,case
 when i.expected_normalized_description like '%safety triangle%' then 'Loose safety/accessory items belong to Fitting, not Parts, including safety triangle kits and similar items left loose in the vehicle.'
 when i.expected_normalized_description like '%bonnet protector%' then 'Bonnet protectors belong to Fitting; the word Tint in their finish must not send them to the Tint bay.'
 when i.expected_normalized_description like '%seat cover%' then 'Front, rear and other seat-cover operations, including canvas seat covers, belong to Fitting.'
 when i.expected_normalized_description like '%recovery point%' then 'Front, rear and other recovery points, including pairs and Broome to supply descriptions, belong to Fitting.'
 when i.expected_normalized_description like '%long range%' then 'ARB Frontier Long Range Tanks and all other long-range fuel tanks belong to Hoist/GVM.'
 when i.expected_normalized_description like '%pre-delivery inspection%' then 'Pre-Delivery Inspection and Complete Pre-Delivery Inspection always belong to Fitting.'
 else 'Craig authorised this exact operation-line department correction in Telegram.' end,a,e,'Hermes Agent — PDC development profile',7828138290
from public.pdc_supervised_correction_items i join public.pdc_supervised_correction_batches b using(batch_id) where b.idempotency_key='migration-213-authorised-exact-active-lines';if not found then raise exception 'PDC_217_CORRECTION_BATCH_MISSING';end if;end $seed$;
create function public.authorize_pdc_supervised_telegram_identity_217(p_telegram_sender_id bigint,p_auth_user_id uuid,p_reason text) returns jsonb language plpgsql security definer set search_path=pg_catalog,public as $$declare s jsonb:=public.pdc_supervised_admin_scope_213();a uuid;e text;target_email text;i uuid;begin if not coalesce((s->>'ok')::boolean,false) then return s;end if;a=(s->'data'->>'actor_id')::uuid;e=s->'data'->>'actor_email';if p_telegram_sender_id=0 or length(btrim(coalesce(p_reason,'')))<3 then return public.navision_backend_response(false,'invalid_request');end if;select lower(email) into target_email from public.pdc_user_roles where auth_user_id=p_auth_user_id and role='administrator' and active and account_status='approved';if target_email is null then return public.navision_backend_response(false,'administrator_required');end if;insert into public.pdc_supervised_telegram_identities(telegram_sender_id,auth_user_id,actor_email,authorized_by) values(p_telegram_sender_id,p_auth_user_id,target_email,a) returning identity_id into i;insert into public.pdc_supervised_telegram_commands(action,original_instruction,telegram_sender_id,telegram_chat_id,telegram_message_id,actor_id,actor_email,request,result_code) values('authorize_administrator_telegram_identity',btrim(p_reason),p_telegram_sender_id,p_telegram_sender_id,(extract(epoch from clock_timestamp())*1000000)::bigint,a,e,jsonb_build_object('target_auth_user_id',p_auth_user_id,'target_email',target_email),'administrator_telegram_identity_authorized');return public.navision_backend_response(true,'administrator_telegram_identity_authorized',jsonb_build_object('identity_id',i,'auth_user_id',p_auth_user_id,'actor_email',target_email));exception when unique_violation then return public.navision_backend_response(false,'conflict');when others then insert into public.pdc_supervised_failures(rpc_name,error_code,error_detail,actor_id,actor_email,request_context) values('authorize_pdc_supervised_telegram_identity_217',sqlstate,sqlerrm,a,e,jsonb_build_object('telegram_sender_id',p_telegram_sender_id,'auth_user_id',p_auth_user_id));return public.navision_backend_response(false,'rpc_error');end$$;
revoke all on function public.authorize_pdc_supervised_telegram_identity_217(bigint,uuid,text) from public,anon,authenticated,service_role;grant execute on function public.authorize_pdc_supervised_telegram_identity_217(bigint,uuid,text) to authenticated;
insert into supabase_migrations.schema_migrations(version,name,statements) values('217','supervised_correction_evidence_and_admin_telegram_enrollment',array['append immutable Craig instruction and Hermes bot identity to every exact correction item','Administrator-only Telegram identity enrollment for approved active Administrators','no direct table grants and no Monitor mutation authority']);notify pgrst,'reload schema';commit;
