[CmdletBinding()]
param([string]$InstallRoot="$env:ProgramData\PDCMonitor\Staging",[Parameter(Mandatory=$true)][string]$BundleRoot,[Parameter(Mandatory=$true)][string]$ExpectedManifestSha256,[Parameter(Mandatory=$true)][string]$ExpectedParentManifestSha256,[Parameter(Mandatory=$true)][string]$ExpectedBridgeSha256,[Parameter(Mandatory=$true)][string]$MachineStoreSource,[string]$SourceRoot=(Split-Path -Parent $PSScriptRoot))
$ErrorActionPreference='Stop';$v='2026.08.66';$old='2026.08.65';$taskName='PDC-PMB-Email-Monitor-Staging';$mutex=New-Object System.Threading.Mutex($false,'Global\PDCMonitorStagingSuccessorInstall');$held=$false
function Fail([string]$x){throw $x};function Hash([string]$p){if(-not(Test-Path -LiteralPath $p -PathType Leaf)){Fail 'PDC_MONITOR_SUCCESSOR_INSTALL_MISSING_FILE'};(Get-FileHash -LiteralPath $p -Algorithm SHA256).Hash.ToLowerInvariant()};function Protect([string]$p){& icacls.exe $p '/inheritance:r' '/grant:r' '*S-1-5-18:(F)' '*S-1-5-32-544:(F)' '*S-1-5-19:(RX)'|Out-Null;if($LASTEXITCODE){Fail 'PDC_MONITOR_SUCCESSOR_INSTALL_ACL_FAILED'}};function ProtectTree([string]$p){& icacls.exe $p '/inheritance:r' '/grant:r' '*S-1-5-18:(F)' '*S-1-5-32-544:(F)' '*S-1-5-19:(RX)' '/T' '/C'|Out-Null;if($LASTEXITCODE){Fail 'PDC_MONITOR_SUCCESSOR_INSTALL_TREE_ACL_FAILED'};& icacls.exe $p '/grant' '*S-1-5-18:(OI)(CI)(F)' '*S-1-5-32-544:(OI)(CI)(F)' '*S-1-5-19:(OI)(CI)(RX)'|Out-Null;if($LASTEXITCODE){Fail 'PDC_MONITOR_SUCCESSOR_INSTALL_TREE_INHERITANCE_ACL_FAILED'}};function Source([string]$n){Join-Path $SourceRoot $n}
try{
 $held=$mutex.WaitOne(0);if(-not$held){Fail 'PDC_MONITOR_SUCCESSOR_INSTALL_OVERLAP'};$install=[IO.Path]::GetFullPath($InstallRoot);if(-not$install.EndsWith('\PDCMonitor\Staging',[StringComparison]::OrdinalIgnoreCase)){Fail 'PDC_MONITOR_SUCCESSOR_INSTALL_EXACT_ROOT_REQUIRED'};$bundle=[IO.Path]::GetFullPath($BundleRoot);if($bundle.StartsWith($install+'\',[StringComparison]::OrdinalIgnoreCase)){Fail 'PDC_MONITOR_SUCCESSOR_INSTALL_BUNDLE_MUST_BE_EXTERNAL'};if((Hash (Join-Path $bundle 'release-manifest.json')) -ne $ExpectedManifestSha256.ToLower()){Fail 'PDC_MONITOR_SUCCESSOR_INSTALL_MANIFEST_HASH_MISMATCH'}
 $task=Get-ScheduledTask -TaskName $taskName -ErrorAction Stop;if($task.State -ne 'Disabled'){Fail 'PDC_MONITOR_SUCCESSOR_INSTALL_TASK_MUST_REMAIN_DISABLED'};if($task.Principal.UserId -ne 'LOCAL SERVICE' -or $task.Principal.RunLevel -ne 'Limited' -or $task.Principal.LogonType -ne 'ServiceAccount'){Fail 'PDC_MONITOR_SUCCESSOR_INSTALL_TASK_IDENTITY_MISMATCH'};if(@($task.Triggers|Where-Object{$_.Repetition.Interval -eq 'PT5M'}).Count -eq 0){Fail 'PDC_MONITOR_SUCCESSOR_INSTALL_TASK_TRIGGER_MISMATCH'}
 $current=Join-Path $install 'CURRENT';$currentValue=(Get-Content $current -Raw).Trim();if($currentValue -ne $old -and $currentValue -ne $v){Fail 'PDC_MONITOR_SUCCESSOR_INSTALL_CURRENT_NOT_065_OR_066'};$parent=Join-Path $install "releases\$old";if((Hash (Join-Path $parent 'release-manifest.json')) -ne $ExpectedParentManifestSha256.ToLower()){Fail 'PDC_MONITOR_SUCCESSOR_INSTALL_PARENT_MANIFEST_CHANGED'}
 $target=Join-Path $install "releases\$v";if(Test-Path $target){if((Hash (Join-Path $target 'release-manifest.json')) -ne $ExpectedManifestSha256.ToLower()){Fail 'PDC_MONITOR_SUCCESSOR_INSTALL_EXISTING_SUCCESSOR_MISMATCH'}}else{Copy-Item $bundle $target -Recurse -Force};$targetManifest=Get-Content (Join-Path $target 'release-manifest.json') -Raw|ConvertFrom-Json;foreach($member in $targetManifest.files.psobject.Properties.Name){$relative=$member.Replace('/','\');$targetMember=Join-Path $target $relative;if(-not(Test-Path -LiteralPath $targetMember -PathType Leaf)){New-Item (Split-Path -Parent $targetMember) -ItemType Directory -Force|Out-Null;Copy-Item (Join-Path $bundle $relative) $targetMember -Force}};ProtectTree $target
 $oldVenv=Join-Path $install "venvs\$old";$venv=Join-Path $install "venvs\$v";if(-not(Test-Path (Join-Path $venv 'Scripts\python.exe'))){New-Item $venv -ItemType Directory -Force|Out-Null;Copy-Item (Join-Path $oldVenv '*') $venv -Recurse -Force};$venvCfg=Join-Path $venv 'pyvenv.cfg';Set-Content $venvCfg @("home = $install\releases\$v\python-runtime",'include-system-site-packages = false','version = 3.11.15',"executable = $install\releases\$v\python-runtime\python.exe",("command = $install\releases\$v\python-runtime\python.exe -m venv $venv")) -Encoding ascii;ProtectTree $venv
 $oldCfg=Join-Path $install "config\$old";$cfg=Join-Path $install "config\$v";New-Item $cfg -ItemType Directory -Force|Out-Null;if(-not(Test-Path (Join-Path $cfg 'runtime.env'))){Copy-Item (Join-Path $oldCfg 'runtime.env') (Join-Path $cfg 'runtime.env') -Force};$cfgPath=Join-Path $cfg 'runtime.env';$cfgText=Get-Content $cfgPath -Raw;$cfgText=[regex]::Replace($cfgText,'(?m)^PDC_AGENTIC_EMAIL_ENABLED=.*$','PDC_AGENTIC_EMAIL_ENABLED=true');Set-Content $cfgPath $cfgText -Encoding ascii;Protect $cfgPath
 $control=Join-Path $install "control\$v";$trust=Join-Path $install "trust\$v";New-Item $control,$trust -ItemType Directory -Force|Out-Null;$controlFiles=[ordered]@{'pdc_monitor_refresh_20260866.py'='pdc_monitor_refresh_20260866.py';'pdc_monitor_active_dispatch_20260866.ps1'='run-current-active.ps1';'pdc_monitor_verifyonly_runner_20260866.ps1'='run-current-verifyonly.ps1';'pdc_monitor_verifyonly_bootstrap_20260866.ps1'='bootstrap-verifyonly.ps1';'verify_pdc_monitor_successor_20260866.py'='verify-successor.py'};foreach($sourceName in $controlFiles.Keys){$destinationName=$controlFiles[$sourceName];Copy-Item (Source "scripts\$sourceName") (Join-Path $control $destinationName) -Force;Protect (Join-Path $control $destinationName)}
 $rootBootstrap=Join-Path $install 'control\bootstrap.ps1';Copy-Item (Source 'scripts\pdc_monitor_active_bootstrap_20260866.ps1') $rootBootstrap -Force;Protect $rootBootstrap
 $secretDir=Join-Path $install "secrets\$v";New-Item $secretDir -ItemType Directory -Force|Out-Null;$secretTarget=Join-Path $secretDir 'monitor-refresh.dpapi';if(-not(Test-Path -LiteralPath $MachineStoreSource -PathType Leaf)){Fail 'PDC_MONITOR_SUCCESSOR_INSTALL_MACHINE_STORE_MISSING'};Copy-Item $MachineStoreSource $secretTarget -Force;Protect $secretTarget
 $anchors=@{'SUCCESSOR_MANIFEST_SHA256'=$ExpectedManifestSha256.ToLower();'PARENT_MANIFEST_SHA256'=$ExpectedParentManifestSha256.ToLower();'SUCCESSOR_BRIDGE_SHA256'=$ExpectedBridgeSha256.ToLower();'SUCCESSOR_VERIFIER_SHA256'=(Hash (Join-Path $control 'verify-successor.py'));'ACTIVE_DISPATCH_SHA256'=(Hash (Join-Path $control 'run-current-active.ps1'));'VERIFYONLY_BOOTSTRAP_SHA256'=(Hash (Join-Path $control 'bootstrap-verifyonly.ps1'));'VERIFYONLY_RUNNER_SHA256'=(Hash (Join-Path $control 'run-current-verifyonly.ps1'));'ACTIVE_BOOTSTRAP_SHA256'=(Hash $rootBootstrap);'MACHINE_REFRESH_SHA256'=(Hash (Join-Path $control 'pdc_monitor_refresh_20260866.py'));'MACHINE_STORE_SHA256'=(Hash $secretTarget);'GRANDPARENT_MANIFEST_SHA256'='d48b49f6598a99fbef99fc4f0d0ab36b8b47576b8ff7cd8ecd2cb64d6cfed58d'};foreach($n in $anchors.Keys){$p=Join-Path $trust $n;Set-Content $p $anchors[$n] -Encoding ascii -NoNewline;Protect $p}
 Set-Content $current $v -Encoding ascii -NoNewline;ProtectTree $target;ProtectTree $venv;ProtectTree $control;ProtectTree $secretDir
 [ordered]@{ok=$true;successor=$v;manifest_sha256=$ExpectedManifestSha256.ToLower();parent_manifest_sha256=$ExpectedParentManifestSha256.ToLower();current=$v;task_enabled=$false;mailbox_contacted=$false;uid514_processed=$false;production_contacted=$false;parent_release_unchanged=$true}|ConvertTo-Json -Compress;exit 0
}catch{throw ('PDC_MONITOR_SUCCESSOR_INSTALL_DENIED:' + $_.Exception.Message)}finally{if($held){$mutex.ReleaseMutex()|Out-Null};$mutex.Dispose()}
