[CmdletBinding()]
param([string]$InstallRoot="$env:ProgramData\PDCMonitor\Staging",[Parameter(Mandatory=$true)][string]$BundleRoot,[Parameter(Mandatory=$true)][string]$ExpectedManifestSha256,[Parameter(Mandatory=$true)][string]$ExpectedParentManifestSha256)
$ErrorActionPreference='Stop';$Version='2026.08.69';$Parent='2026.08.68';$Task='PDC-PMB-Email-Monitor-Staging';$mutex=New-Object System.Threading.Mutex($false,'Global\PDCMonitorStagingNoSuchKeySuccessorInstall');$held=$false
function Fail([string]$x){throw $x};function Hash([string]$p){if(-not(Test-Path -LiteralPath $p -PathType Leaf)){Fail 'PDC_MONITOR_NOSUCHKEY_INSTALL_MISSING_FILE'};(Get-FileHash -LiteralPath $p -Algorithm SHA256).Hash.ToLowerInvariant()};function ProtectTree([string]$p){& icacls.exe $p '/inheritance:r' '/grant:r' '*S-1-5-18:(OI)(CI)(F)' '*S-1-5-32-544:(OI)(CI)(F)' '*S-1-5-19:(OI)(CI)(RX)' '/T' '/C'|Out-Null;if($LASTEXITCODE){Fail 'PDC_MONITOR_NOSUCHKEY_INSTALL_ACL_FAILED'}}
try{
 $held=$mutex.WaitOne(0);if(-not$held){Fail 'PDC_MONITOR_NOSUCHKEY_INSTALL_OVERLAP'};$root=[IO.Path]::GetFullPath($InstallRoot);if(-not$root.EndsWith('\PDCMonitor\Staging',[StringComparison]::OrdinalIgnoreCase)){Fail 'PDC_MONITOR_NOSUCHKEY_INSTALL_EXACT_ROOT_REQUIRED'};$bundle=[IO.Path]::GetFullPath($BundleRoot);if($bundle.StartsWith($root+'\',[StringComparison]::OrdinalIgnoreCase)){Fail 'PDC_MONITOR_NOSUCHKEY_INSTALL_BUNDLE_MUST_BE_EXTERNAL'}
 if((Hash (Join-Path $bundle 'release-manifest.json')) -ne $ExpectedManifestSha256.ToLowerInvariant()){Fail 'PDC_MONITOR_NOSUCHKEY_INSTALL_MANIFEST_HASH_MISMATCH'}
 $task=Get-ScheduledTask -TaskName $Task -ErrorAction Stop;if($task.State -ne 'Disabled'){Fail 'PDC_MONITOR_NOSUCHKEY_INSTALL_TASK_MUST_REMAIN_DISABLED'};if($task.Principal.UserId -ne 'LOCAL SERVICE' -or $task.Principal.RunLevel -ne 'Limited' -or $task.Principal.LogonType -ne 'ServiceAccount'){Fail 'PDC_MONITOR_NOSUCHKEY_INSTALL_TASK_IDENTITY_MISMATCH'}
 $current=Join-Path $root 'CURRENT';$cur=(Get-Content -LiteralPath $current -Raw).Trim();if($cur -ne $Parent -and $cur -ne $Version){Fail 'PDC_MONITOR_NOSUCHKEY_INSTALL_CURRENT_NOT_068_OR_069'};$parent=Join-Path $root "releases\$Parent";if((Hash (Join-Path $parent 'release-manifest.json')) -ne $ExpectedParentManifestSha256.ToLowerInvariant()){Fail 'PDC_MONITOR_NOSUCHKEY_INSTALL_PARENT_CHANGED'}
 $target=Join-Path $root "releases\$Version";if(Test-Path -LiteralPath $target){if((Hash (Join-Path $target 'release-manifest.json')) -ne $ExpectedManifestSha256.ToLowerInvariant()){Fail 'PDC_MONITOR_NOSUCHKEY_INSTALL_EXISTING_TARGET_MISMATCH'}}else{Copy-Item -LiteralPath $bundle -Destination $target -Recurse -Force};ProtectTree $target
 Set-Content -LiteralPath $current -Value $Version -Encoding ascii -NoNewline
 [ordered]@{ok=$true;successor=$Version;parent=$Parent;current=$Version;task_enabled=$false;task_started=$false;mailbox_contacted=$false;uid514_processed=$false;production_contacted=$false}|ConvertTo-Json -Compress;exit 0
}catch{throw ('PDC_MONITOR_NOSUCHKEY_INSTALL_DENIED:'+$_.Exception.Message)}finally{if($held){$mutex.ReleaseMutex()|Out-Null};$mutex.Dispose()}
