[CmdletBinding()]
param(
 [string]$InstallRoot="$env:ProgramData\PDCMonitor\Staging",
 [Parameter(Mandatory=$true)][string]$BundleRoot,
 [Parameter(Mandatory=$true)][string]$ExpectedManifestSha256,
 [Parameter(Mandatory=$true)][string]$ExpectedParentManifestSha256,
 [Parameter(Mandatory=$true)][string]$ExpectedProcessorSha256,
 [Parameter(Mandatory=$true)][string]$MachineStoreSource
)
$ErrorActionPreference='Stop';$Version='2026.08.68';$Parent='2026.08.66';$TaskName='PDC-PMB-Email-Monitor-Staging';$mutex=New-Object System.Threading.Mutex($false,'Global\PDCMonitorStagingCurrentHead766Install');$held=$false
function Fail([string]$Code){throw $Code}
function Hash([string]$Path){if(-not(Test-Path -LiteralPath $Path -PathType Leaf)){Fail 'PDC_MONITOR_766_INSTALL_MISSING_FILE'};(Get-FileHash -LiteralPath $Path -Algorithm SHA256).Hash.ToLowerInvariant()}
function Protect([string]$Path){& icacls.exe $Path '/inheritance:r' '/grant:r' '*S-1-5-18:(F)' '*S-1-5-32-544:(F)' '*S-1-5-19:(RX)'|Out-Null;if($LASTEXITCODE-ne 0){Fail 'PDC_MONITOR_766_INSTALL_ACL_FAILED'}}
function ProtectTree([string]$Path){& icacls.exe $Path '/inheritance:r' '/grant:r' '*S-1-5-18:(OI)(CI)(F)' '*S-1-5-32-544:(OI)(CI)(F)' '*S-1-5-19:(OI)(CI)(RX)' '/T' '/C'|Out-Null;if($LASTEXITCODE-ne 0){Fail 'PDC_MONITOR_766_INSTALL_TREE_ACL_FAILED'}}
function ProtectDirectory([string]$Path){New-Item -LiteralPath $Path -ItemType Directory -Force|Out-Null;& icacls.exe $Path '/inheritance:r' '/grant:r' '*S-1-5-18:(OI)(CI)(F)' '*S-1-5-32-544:(OI)(CI)(F)' '*S-1-5-19:(OI)(CI)(RX)'|Out-Null;if($LASTEXITCODE-ne 0){Fail 'PDC_MONITOR_766_INSTALL_PARENT_ACL_FAILED'}}
function ProtectWritableDirectory([string]$Path){ProtectDirectory $Path;& icacls.exe $Path '/grant:r' '*S-1-5-19:(OI)(CI)(M)'|Out-Null;if($LASTEXITCODE-ne 0){Fail 'PDC_MONITOR_766_INSTALL_WRITABLE_PARENT_ACL_FAILED'}}
function CopyChecked([string]$Source,[string]$Destination){if(-not(Test-Path -LiteralPath $Source -PathType Leaf)){Fail 'PDC_MONITOR_766_INSTALL_SOURCE_MISSING'};New-Item (Split-Path -Parent $Destination) -ItemType Directory -Force|Out-Null;Copy-Item -LiteralPath $Source -Destination $Destination -Force;Protect $Destination}
function Set-Key([string]$Path,[string]$Key,[string]$Value){$lines=@(Get-Content -LiteralPath $Path);$found=@($lines|Where-Object{$_ -match ('^'+[regex]::Escape($Key)+'=')});if($found.Count -gt 1){Fail "PDC_MONITOR_766_INSTALL_DUPLICATE_CONFIG_$Key"};if($found.Count -eq 1){$lines=@($lines|ForEach-Object{if($_ -match ('^'+[regex]::Escape($Key)+'=')){$Key+'='+$Value}else{$_}})}else{$lines+=($Key+'='+$Value)};Set-Content -LiteralPath $Path -Value $lines -Encoding ascii;Protect $Path}
try{
 $id=[Security.Principal.WindowsIdentity]::GetCurrent();$principal=New-Object Security.Principal.WindowsPrincipal($id);if(-not$principal.IsInRole([Security.Principal.WindowsBuiltInRole]::Administrator)){Fail 'PDC_MONITOR_766_INSTALL_ELEVATION_REQUIRED'}
 $held=$mutex.WaitOne(0);if(-not$held){Fail 'PDC_MONITOR_766_INSTALL_OVERLAP'};$install=[IO.Path]::GetFullPath($InstallRoot);if(-not$install.EndsWith('\PDCMonitor\Staging',[StringComparison]::OrdinalIgnoreCase)){Fail 'PDC_MONITOR_766_INSTALL_EXACT_ROOT_REQUIRED'};$bundle=[IO.Path]::GetFullPath($BundleRoot);if($bundle.StartsWith($install+'\',[StringComparison]::OrdinalIgnoreCase)){Fail 'PDC_MONITOR_766_INSTALL_BUNDLE_MUST_BE_EXTERNAL'};if((Hash (Join-Path $bundle 'release-manifest.json')) -ne $ExpectedManifestSha256.ToLowerInvariant()){Fail 'PDC_MONITOR_766_INSTALL_MANIFEST_HASH_MISMATCH'}
 ProtectDirectory (Join-Path $install 'releases');ProtectDirectory (Join-Path $install 'venvs');ProtectDirectory (Join-Path $install 'control');ProtectDirectory (Join-Path $install 'trust');ProtectDirectory (Join-Path $install 'secrets');ProtectDirectory (Join-Path $install 'config');ProtectWritableDirectory (Join-Path $install 'state');ProtectWritableDirectory (Join-Path $install 'logs')
 $task=Get-ScheduledTask -TaskName $TaskName -ErrorAction Stop;if($task.State -ne 'Disabled'){Fail 'PDC_MONITOR_766_INSTALL_TASK_MUST_REMAIN_DISABLED'};if($task.Principal.UserId -ne 'LOCAL SERVICE' -or $task.Principal.RunLevel -ne 'Limited' -or $task.Principal.LogonType -ne 'ServiceAccount'){Fail 'PDC_MONITOR_766_INSTALL_TASK_IDENTITY_MISMATCH'};if(@($task.Triggers|Where-Object{$_.Repetition.Interval -eq 'PT5M'}).Count -eq 0){Fail 'PDC_MONITOR_766_INSTALL_TASK_TRIGGER_MISMATCH'}
 $current=Join-Path $install 'CURRENT';$currentValue=(Get-Content -LiteralPath $current -Raw).Trim();if($currentValue -ne $Parent -and $currentValue -ne $Version){Fail 'PDC_MONITOR_766_INSTALL_CURRENT_NOT_066_OR_068'}
 $parentManifest=Join-Path $install "releases\$Parent\release-manifest.json";if((Hash $parentManifest) -ne $ExpectedParentManifestSha256.ToLowerInvariant()){Fail 'PDC_MONITOR_766_INSTALL_PARENT_MANIFEST_CHANGED'}
 $target=Join-Path $install "releases\$Version";if(Test-Path -LiteralPath $target){if((Hash (Join-Path $target 'release-manifest.json')) -ne $ExpectedManifestSha256.ToLowerInvariant()){Fail 'PDC_MONITOR_766_INSTALL_EXISTING_TARGET_MISMATCH'}}else{Copy-Item -LiteralPath $bundle -Destination $target -Recurse -Force};ProtectTree $target
 $oldVenv=Join-Path $install "venvs\$Parent";$newVenv=Join-Path $install "venvs\$Version";if(-not(Test-Path -LiteralPath (Join-Path $newVenv 'Scripts\python.exe') -PathType Leaf)){if(-not(Test-Path -LiteralPath $oldVenv -PathType Container)){Fail 'PDC_MONITOR_766_INSTALL_PARENT_VENV_MISSING'};Copy-Item -LiteralPath $oldVenv -Destination $newVenv -Recurse -Force};Set-Content -LiteralPath (Join-Path $newVenv 'pyvenv.cfg') -Value @("home = $install\releases\$Version\python-runtime",'include-system-site-packages = false','version = 3.11.15',"executable = $install\releases\$Version\python-runtime\python.exe",("command = $install\releases\$Version\python-runtime\python.exe -m venv $newVenv")) -Encoding ascii;ProtectTree $newVenv
 $oldConfig=Join-Path $install "config\$Parent\runtime.env";$newConfig=Join-Path $install "config\$Version\runtime.env";if(-not(Test-Path -LiteralPath $newConfig -PathType Leaf)){CopyChecked $oldConfig $newConfig};Set-Key $newConfig 'PDC_AGENTIC_EMAIL_ENABLED' 'true';Set-Key $newConfig 'PDC_AGENTIC_PLANNER_COMMAND' ('["'+($newVenv.Replace('\','\\'))+'\\Scripts\\python.exe","'+(Join-Path $install "trust\$Version\pdc_active_semantic_planner.py").Replace('\','\\')+'"]');Set-Key $newConfig 'PDC_AGENTIC_PLANNER_SHA256' '7e08a00bc099610aa919bb7c3089ef84b91a74bafd69f95fab06bfccfdf67348';Set-Key $newConfig 'PDC_AGENTIC_PLANNER_TRUST_RECEIPT' ((Join-Path $install "trust\$Version\pdc-active-semantic-planner-trust-receipt.json"));Set-Key $newConfig 'PDC_AGENTIC_PLANNER_TRUST_RECEIPT_SHA256' 'e3e30ace04e676e34f271b161283b9e4764d462f76428d63826fa3cb153d7227'
 $control=Join-Path $install "control\$Version";$trust=Join-Path $install "trust\$Version";New-Item $control,$trust -ItemType Directory -Force|Out-Null;CopyChecked (Join-Path $bundle 'scripts\pdc_monitor_active_dispatch_20260868.ps1') (Join-Path $control 'run-current-active.ps1');CopyChecked (Join-Path $bundle 'scripts\pdc_monitor_verifyonly_runner_20260868.ps1') (Join-Path $control 'run-current-verifyonly.ps1');CopyChecked (Join-Path $bundle 'scripts\pdc_monitor_verifyonly_bootstrap_20260868.ps1') (Join-Path $control 'bootstrap-verifyonly.ps1');CopyChecked (Join-Path $bundle 'scripts\verify_pdc_monitor_successor_20260868.py') (Join-Path $control 'verify-successor.py');CopyChecked (Join-Path $bundle 'scripts\pdc_monitor_current_head_preflight_20260868.py') (Join-Path $control 'current-head-preflight.py');CopyChecked (Join-Path $bundle 'scripts\pdc_monitor_refresh_20260868.py') (Join-Path $control 'pdc_monitor_refresh_20260868.py');CopyChecked (Join-Path $bundle 'trusted-control\pdc_active_semantic_planner.py') (Join-Path $trust 'pdc_active_semantic_planner.py');CopyChecked (Join-Path $bundle 'trusted-control\pdc-active-semantic-planner-trust-receipt.json') (Join-Path $trust 'pdc-active-semantic-planner-trust-receipt.json');$machineTarget=Join-Path $install "secrets\$Version\monitor-refresh.dpapi";CopyChecked ([IO.Path]::GetFullPath($MachineStoreSource)) $machineTarget
 $rootBootstrap=Join-Path $install 'control\bootstrap.ps1';$rootBootstrapLines=@('[CmdletBinding()]','param([string]$InstallRoot="$env:ProgramData\PDCMonitor\Staging",[switch]$DryRun)','$ErrorActionPreference=''Stop''','$v=''2026.08.68''','$runner=Join-Path (Join-Path (Join-Path $InstallRoot ''control'') $v) ''run-current-active.ps1''','if((Get-Content (Join-Path $InstallRoot ''CURRENT'') -Raw).Trim()-ne$v){throw ''PDC_MONITOR_766_BOOTSTRAP_CURRENT_MISMATCH''}','& $runner -InstallRoot $InstallRoot -Mode OneCycle -DryRun:$DryRun','exit $LASTEXITCODE');Set-Content -LiteralPath $rootBootstrap -Value $rootBootstrapLines -Encoding ascii;Protect $rootBootstrap
 $anchors=@{'SUCCESSOR_MANIFEST_SHA256'=$ExpectedManifestSha256.ToLowerInvariant();'PARENT_MANIFEST_SHA256'=$ExpectedParentManifestSha256.ToLowerInvariant();'FROZEN_066_MANIFEST_SHA256'=$ExpectedParentManifestSha256.ToLowerInvariant();'SUCCESSOR_PROCESSOR_SHA256'=$ExpectedProcessorSha256.ToLowerInvariant();'ACTIVE_DISPATCH_SHA256'=(Hash (Join-Path $control 'run-current-active.ps1'));'VERIFYONLY_RUNNER_SHA256'=(Hash (Join-Path $control 'run-current-verifyonly.ps1'));'VERIFYONLY_BOOTSTRAP_SHA256'=(Hash (Join-Path $control 'bootstrap-verifyonly.ps1'));'CURRENT_HEAD_PREFLIGHT_SHA256'=(Hash (Join-Path $control 'current-head-preflight.py'));'REFRESH_SHA256'=(Hash (Join-Path $control 'pdc_monitor_refresh_20260868.py'));'ROOT_BOOTSTRAP_SHA256'=(Hash $rootBootstrap)};foreach($name in $anchors.Keys){$path=Join-Path $trust $name;Set-Content -LiteralPath $path -Value $anchors[$name] -Encoding ascii -NoNewline;Protect $path}
 Set-Content -LiteralPath $current -Value $Version -Encoding ascii -NoNewline;Protect $current;ProtectTree $target;ProtectTree $control;ProtectTree $trust;ProtectTree (Join-Path $install "secrets\$Version");[ordered]@{ok=$true;successor=$Version;parent=$Parent;manifest_sha256=$ExpectedManifestSha256.ToLowerInvariant();parent_manifest_sha256=$ExpectedParentManifestSha256.ToLowerInvariant();current=$Version;task_enabled=$false;task_started=$false;mailbox_contacted=$false;uid514_processed=$false;production_contacted=$false}|ConvertTo-Json -Compress;exit 0
}catch{throw ('PDC_MONITOR_766_INSTALL_DENIED:'+$_.Exception.Message)}finally{if($held){$mutex.ReleaseMutex()|Out-Null};$mutex.Dispose()}
