[CmdletBinding()]
param(
 [string]$InstallRoot="$env:ProgramData\PDCMonitor\Staging",
 [Parameter(Mandatory=$true)][string]$BundleRoot,
 [Parameter(Mandatory=$true)][string]$ExpectedManifestSha256,
 [Parameter(Mandatory=$true)][string]$ExpectedParentManifestSha256,
 [Parameter(Mandatory=$true)][string]$ExpectedBridgeSha256,
 [string]$SourceRoot=''
)
$ErrorActionPreference='Stop';$ExpectedVersion='2026.08.48';$ParentVersion='2026.08.44';$ExpectedEnvironment='pdc-monitor-staging';$TaskName='PDC-PMB-Email-Monitor-Staging';$mutex=New-Object System.Threading.Mutex($false,'Global\PDCMonitorStagingSuccessorInstall');$held=$false
$SourceRoot=if($SourceRoot){$SourceRoot}else{Split-Path -Parent $PSScriptRoot}
function Fail([string]$Code){throw $Code}
function Hash([string]$Path){if(-not(Test-Path -LiteralPath $Path -PathType Leaf)){Fail 'PDC_MONITOR_SUCCESSOR_INSTALL_MISSING_FILE'};return (Get-FileHash -LiteralPath $Path -Algorithm SHA256).Hash.ToLowerInvariant()}
function No-Reparse([string]$Path,[string]$Label){$probe=[IO.Path]::GetFullPath($Path);while($probe){if(Test-Path -LiteralPath $probe){$item=Get-Item -LiteralPath $probe -Force;if(($item.Attributes-band[IO.FileAttributes]::ReparsePoint)-ne 0){Fail "PDC_MONITOR_SUCCESSOR_INSTALL_REPARSE_$Label"}};$parent=[IO.Path]::GetDirectoryName($probe);if(-not$parent-or$parent-eq$probe){break};$probe=$parent}}
function Protect([string]$Path){& 'C:\Windows\System32\icacls.exe' $Path '/inheritance:r' '/grant:r' '*S-1-5-18:(F)' '*S-1-5-32-544:(F)' '*S-1-5-19:(RX)'|Out-Null;if($LASTEXITCODE-ne 0){Fail 'PDC_MONITOR_SUCCESSOR_INSTALL_ACL_FAILED'}}
function Source([string]$Name){$p=[IO.Path]::GetFullPath((Join-Path $SourceRoot $Name));No-Reparse $p 'SOURCE';return $p}
try{
 $held=$mutex.WaitOne(0);if(-not$held){Fail 'PDC_MONITOR_SUCCESSOR_INSTALL_OVERLAP'}
 $install=[IO.Path]::GetFullPath($InstallRoot);if(-not$install.EndsWith('\PDCMonitor\Staging',[StringComparison]::OrdinalIgnoreCase)){Fail 'PDC_MONITOR_SUCCESSOR_INSTALL_EXACT_ROOT_REQUIRED'};No-Reparse $install 'INSTALL_ROOT'
 $bundle=[IO.Path]::GetFullPath($BundleRoot);if($bundle.StartsWith($install+'\',[StringComparison]::OrdinalIgnoreCase)){Fail 'PDC_MONITOR_SUCCESSOR_INSTALL_BUNDLE_MUST_BE_EXTERNAL'};No-Reparse $bundle 'BUNDLE';$manifest=Join-Path $bundle 'release-manifest.json';if((Hash $manifest)-ne$ExpectedManifestSha256.ToLowerInvariant()){Fail 'PDC_MONITOR_SUCCESSOR_INSTALL_MANIFEST_HASH_MISMATCH'}
 $task=Get-ScheduledTask -TaskName $TaskName -ErrorAction Stop;if($task.State-ne'Disabled'){Fail 'PDC_MONITOR_SUCCESSOR_INSTALL_TASK_MUST_REMAIN_DISABLED'};if($task.Principal.UserId-ne'LOCAL SERVICE'-or$task.Principal.RunLevel-ne'Limited'-or$task.Principal.LogonType-ne'ServiceAccount'){Fail 'PDC_MONITOR_SUCCESSOR_INSTALL_TASK_IDENTITY_MISMATCH'};if(@($task.Actions).Count-ne 1-or$task.Actions[0].Arguments-notmatch '(?i)control[\\/]bootstrap\.ps1'){Fail 'PDC_MONITOR_SUCCESSOR_INSTALL_TASK_ACTION_MISMATCH'};if(@($task.Triggers|Where-Object{$_.Repetition.Interval-eq'PT5M'}).Count-eq0){Fail 'PDC_MONITOR_SUCCESSOR_INSTALL_TASK_TRIGGER_MISMATCH'}
 $parentRoot=Join-Path $install ("releases\"+$ParentVersion);$parentManifest=Join-Path $parentRoot 'release-manifest.json';if((Hash $parentManifest)-ne$ExpectedParentManifestSha256.ToLowerInvariant()){Fail 'PDC_MONITOR_SUCCESSOR_INSTALL_PARENT_MANIFEST_CHANGED'};if((Hash (Join-Path $parentRoot 'backend\imap_bridge.py'))-ne'80d45bb7bde5e0b00fe73e5a54386ede07f7c44fbafcb9e3cc990cc501979248'){Fail 'PDC_MONITOR_SUCCESSOR_INSTALL_PARENT_BRIDGE_CHANGED'}
 $backup=Join-Path $install ("backups\20260848\"+(Get-Date).ToUniversalTime().ToString('yyyyMMddTHHmmssfffZ'));New-Item $backup -ItemType Directory -Force|Out-Null;Copy-Item (Join-Path $install 'CURRENT') (Join-Path $backup 'CURRENT') -Force;Copy-Item (Join-Path $install 'control\bootstrap.ps1') (Join-Path $backup 'bootstrap.ps1') -Force;Export-ScheduledTask -TaskName $TaskName|Out-File (Join-Path $backup 'task.xml') -Encoding utf8;Set-Content (Join-Path $backup 'parent-manifest.sha256') $ExpectedParentManifestSha256 -Encoding ascii
 $verify=Source 'scripts\verify_pdc_monitor_successor_20260848.py';$bridge=Source 'backend\imap_bridge_successor_20260848.py';if((Hash $bridge)-ne$ExpectedBridgeSha256.ToLowerInvariant()){Fail 'PDC_MONITOR_SUCCESSOR_INSTALL_SOURCE_BRIDGE_HASH_MISMATCH'};$python=(Get-Command python.exe -ErrorAction Stop).Source;& $python -B $verify --bundle $bundle --expected-manifest-sha256 $ExpectedManifestSha256 --expected-parent-manifest-sha256 $ExpectedParentManifestSha256 --expected-bridge-sha256 $ExpectedBridgeSha256|Out-Null;if($LASTEXITCODE-ne 0){Fail 'PDC_MONITOR_SUCCESSOR_INSTALL_BUNDLE_VERIFY_FAILED'}
 $target=Join-Path $install ("releases\"+$ExpectedVersion);if(Test-Path -LiteralPath $target){if((Hash (Join-Path $target 'release-manifest.json'))-ne$ExpectedManifestSha256.ToLowerInvariant()){Fail 'PDC_MONITOR_SUCCESSOR_INSTALL_EXISTING_SUCCESSOR_MISMATCH'}}else{New-Item (Split-Path -Parent $target) -ItemType Directory -Force|Out-Null;Copy-Item -LiteralPath $bundle -Destination $target -Recurse -Force}
 $parentVenv=Join-Path $install ("venvs\"+$ParentVersion);$venv=Join-Path $install ("venvs\"+$ExpectedVersion);if(Test-Path -LiteralPath $venv){if(-not(Test-Path -LiteralPath (Join-Path $venv 'Scripts\python.exe') -PathType Leaf)){Fail 'PDC_MONITOR_SUCCESSOR_INSTALL_EXISTING_VENV_INVALID'}}else{Copy-Item -LiteralPath $parentVenv -Destination $venv -Recurse -Force};$venvConfig=Join-Path $venv 'pyvenv.cfg';$venvText=Get-Content -LiteralPath $venvConfig -Raw;if($venvText-notmatch '(?m)^home\s*='){Fail 'PDC_MONITOR_SUCCESSOR_INSTALL_VENV_CONFIG_INVALID'};$venvText=[regex]::Replace($venvText,'(?m)^home\s*=.*$','home = '+(Join-Path $target 'python-runtime'));Set-Content -LiteralPath $venvConfig -Value $venvText -Encoding ascii -NoNewline
 $config=Join-Path $install ("config\"+$ExpectedVersion);if(-not(Test-Path -LiteralPath $config)){New-Item $config -ItemType Directory -Force|Out-Null;Copy-Item (Join-Path $install ("config\"+$ParentVersion+'\runtime.env')) (Join-Path $config 'runtime.env') -Force};Protect (Join-Path $config 'runtime.env')
 $control=Join-Path $install ("control\"+$ExpectedVersion);$trust=Join-Path $install ("trust\"+$ExpectedVersion);New-Item $control,$trust -ItemType Directory -Force|Out-Null
 $files=@{'run-current-active.ps1'='scripts\pdc_monitor_active_dispatch_20260848.ps1';'bootstrap-verifyonly.ps1'='scripts\pdc_monitor_verifyonly_bootstrap_20260848.ps1';'run-current-verifyonly.ps1'='scripts\pdc_monitor_verifyonly_runner_20260848.ps1';'rollback-successor.ps1'='scripts\rollback_pdc_monitor_successor_20260848.ps1';'verify-successor.py'='scripts\verify_pdc_monitor_successor_20260848.py'};foreach($name in $files.Keys){Copy-Item -LiteralPath (Source $files[$name]) -Destination (Join-Path $control $name) -Force;Protect (Join-Path $control $name)}
 $rootBootstrap=Join-Path $install 'control\bootstrap.ps1';Copy-Item -LiteralPath (Source 'scripts\pdc_monitor_active_bootstrap_20260848.ps1') -Destination $rootBootstrap -Force;Protect $rootBootstrap
 $anchors=@{'SUCCESSOR_MANIFEST_SHA256'=$ExpectedManifestSha256.ToLowerInvariant();'PARENT_MANIFEST_SHA256'=$ExpectedParentManifestSha256.ToLowerInvariant();'SUCCESSOR_BRIDGE_SHA256'=$ExpectedBridgeSha256.ToLowerInvariant();'SUCCESSOR_VERIFIER_SHA256'=(Hash (Join-Path $control 'verify-successor.py'));'ACTIVE_DISPATCH_SHA256'=(Hash (Join-Path $control 'run-current-active.ps1'));'VERIFYONLY_BOOTSTRAP_SHA256'=(Hash (Join-Path $control 'bootstrap-verifyonly.ps1'));'VERIFYONLY_RUNNER_SHA256'=(Hash (Join-Path $control 'run-current-verifyonly.ps1'));'ACTIVE_BOOTSTRAP_SHA256'=(Hash $rootBootstrap)};foreach($name in $anchors.Keys){$path=Join-Path $trust $name;Set-Content -LiteralPath $path -Value $anchors[$name] -Encoding ascii -NoNewline;Protect $path}
 $current=Join-Path $install 'CURRENT';Set-Content -LiteralPath $current -Value $ExpectedVersion -Encoding ascii -NoNewline
 # Re-check the immutable parent after all successor writes.
 if((Hash $parentManifest)-ne$ExpectedParentManifestSha256.ToLowerInvariant() -or (Hash (Join-Path $parentRoot 'backend\imap_bridge.py'))-ne'80d45bb7bde5e0b00fe73e5a54386ede07f7c44fbafcb9e3cc990cc501979248'){Fail 'PDC_MONITOR_SUCCESSOR_INSTALL_PARENT_POSTCHECK_FAILED'}
 [pscustomobject]@{ok=$true;successor=$ExpectedVersion;manifest_sha256=$ExpectedManifestSha256.ToLowerInvariant();bridge_sha256=$ExpectedBridgeSha256.ToLowerInvariant();backup=$backup;current=$ExpectedVersion;task_enabled=$false;task_started=$false;mailbox_contacted=$false;uid514_processed=$false;production_contacted=$false;parent_release_unchanged=$true}|ConvertTo-Json -Compress;exit 0
}catch{[Console]::Error.WriteLine('PDC_MONITOR_SUCCESSOR_INSTALL_DENIED');exit 1}finally{if($held){$mutex.ReleaseMutex()|Out-Null};$mutex.Dispose()}
