[CmdletBinding()]
param(
 [string]$InstallRoot="$env:ProgramData\PDCMonitor\Staging",
 [ValidateSet('OneCycle','Continuous')][string]$Mode='OneCycle',
 [switch]$DryRun
)
$ErrorActionPreference='Stop'
$ExpectedVersion='2026.08.61';$ParentVersion='2026.08.44'
$ExpectedRelease='pdc-monitor-staging-m502-2026.08.61';$ParentRelease='pdc-monitor-staging-m502-2026.08.44'
$ExpectedProject='cdsmnqxtyyoeoznmbidd';$ExpectedActorId='df7c55d9-6ba0-47f6-ba16-44d6ae2c2a4b';$ExpectedActorEmail='sales@broometoyota.com.au';$ExpectedGateway='pdc-monitor-staging-sales-uid509-v1';$ExpectedHead=503
$mutex=New-Object System.Threading.Mutex($false,'Global\PDCMonitorStagingSuccessorActiveDispatch');$held=$false;$phase='startup';$statusPath=$null
function Fail([string]$Code){throw $Code}
function Hash([string]$Path){if(-not(Test-Path -LiteralPath $Path -PathType Leaf)){Fail 'PDC_MONITOR_SUCCESSOR_ACTIVE_MISSING_FILE'};return (Get-FileHash -LiteralPath $Path -Algorithm SHA256).Hash.ToLowerInvariant()}
function No-Reparse([string]$Path,[string]$Label){$probe=[IO.Path]::GetFullPath($Path);while($probe){if(Test-Path -LiteralPath $probe){$item=Get-Item -LiteralPath $probe -Force;if(($item.Attributes-band[IO.FileAttributes]::ReparsePoint)-ne 0){Fail "PDC_MONITOR_SUCCESSOR_ACTIVE_REPARSE_$Label"}};$parent=[IO.Path]::GetDirectoryName($probe);if(-not$parent-or$parent-eq$probe){break};$probe=$parent}}
function Trust([string]$Name){$p=Join-Path $trust $Name;if(-not(Test-Path -LiteralPath $p -PathType Leaf)){Fail "PDC_MONITOR_SUCCESSOR_ACTIVE_TRUST_MISSING_$Name"};return (Get-Content -LiteralPath $p -Raw).Trim().ToLowerInvariant()}
function Assert-Hash([string]$Path,[string]$Expected,[string]$Code){if((Hash $Path)-ne$Expected.ToLowerInvariant()){Fail $Code}}
function Status([string]$State,[string]$Code,[bool]$Reached,[bool]$Contacted,[bool]$Blocked){
 if(-not$statusPath){return};$payload=[ordered]@{ok=($State-eq'ok');status=$State;code=$Code;release_version=$ExpectedVersion;mode=$Mode;dry_run=[bool]$DryRun;phase=$phase;monitor_entrypoint_reached=$Reached;active_dispatch_blocked=$Blocked;mailbox_contacted=$Contacted;uid514_processed=$false;production_contacted=$false;task_enabled=$false;sealed_parent_unchanged=$true;last_cycle=([DateTime]::UtcNow.ToString('o'))};$json=$payload|ConvertTo-Json -Compress;if($json.Length-gt 4096){Fail 'PDC_MONITOR_SUCCESSOR_ACTIVE_STATUS_BOUNDED_WRITE_FAILED'};$tmp=$statusPath+'.tmp';Set-Content -LiteralPath $tmp -Value $json -Encoding ascii -NoNewline;Move-Item -LiteralPath $tmp -Destination $statusPath -Force
}
function Invoke-Captured([string[]]$Arguments){$out=& $venvPython -B -I -S @Arguments 2>&1|Out-String;if($LASTEXITCODE-ne 0){Fail 'PDC_MONITOR_SUCCESSOR_ACTIVE_CHILD_FAILED'};return $out}
try{
 $held=$mutex.WaitOne(0);$statusPath=Join-Path $InstallRoot 'state\monitor\active-dispatch-status.json';New-Item (Split-Path -Parent $statusPath) -ItemType Directory -Force|Out-Null
 if(-not$held){Status 'ok' 'PDC_MONITOR_SUCCESSOR_ACTIVE_OVERLAP_SKIPPED' $false $false $true;exit 0}
 $env:PYTHONDONTWRITEBYTECODE='1';$env:PYTHONNOUSERSITE='1';$env:PATH='';Remove-Item Env:PYTHONHOME,Env:PYTHONPATH,Env:PYTHONSTARTUP,Env:PYTHONUSERBASE -ErrorAction SilentlyContinue;Remove-Item Env:PYTHONPATH -ErrorAction SilentlyContinue
 $current=Join-Path $InstallRoot 'CURRENT';$phase='static_current';if((Get-Content -LiteralPath $current -Raw).Trim()-ne$ExpectedVersion){Fail 'PDC_MONITOR_SUCCESSOR_ACTIVE_CURRENT_MISMATCH'}
 $root=Join-Path $InstallRoot ("releases\"+$ExpectedVersion);$parent=Join-Path $InstallRoot ("releases\"+$ParentVersion);$trust=Join-Path $InstallRoot ("trust\"+$ExpectedVersion);$parentTrust=Join-Path $InstallRoot ("trust\"+$ParentVersion);$control=Join-Path $InstallRoot ("control\"+$ExpectedVersion);$venv=Join-Path $InstallRoot ("venvs\"+$ExpectedVersion);$config=Join-Path $InstallRoot ("config\"+$ExpectedVersion+'\runtime.env');$venvPython=Join-Path $venv 'Scripts\python.exe';foreach($p in @($root,$parent,$trust,$parentTrust,$control)){No-Reparse $p 'ROOT'}
 $manifest=Join-Path $root 'release-manifest.json';$successorVerifier=Join-Path $control 'verify-successor.py';$phase='successor_inventory';Assert-Hash $successorVerifier (Trust 'SUCCESSOR_VERIFIER_SHA256') 'PDC_MONITOR_SUCCESSOR_ACTIVE_VERIFIER_HASH_MISMATCH';& $venvPython -B -I -S $successorVerifier --bundle $root --expected-manifest-sha256 (Trust 'SUCCESSOR_MANIFEST_SHA256') --expected-parent-manifest-sha256 (Trust 'PARENT_MANIFEST_SHA256') --expected-bridge-sha256 (Trust 'SUCCESSOR_BRIDGE_SHA256') --expected-processor-sha256 (Trust 'SUCCESSOR_PROCESSOR_SHA256') --expected-jobcard-sha256 (Trust 'SUCCESSOR_JOBCARD_SHA256') 2>&1|Out-String;if($LASTEXITCODE-ne 0){Fail 'PDC_MONITOR_SUCCESSOR_ACTIVE_INVENTORY_FAILED'}
 $phase='parent_static';$parentManifest=Join-Path $parent 'release-manifest.json';Assert-Hash $parentManifest (Trust 'PARENT_MANIFEST_SHA256') 'PDC_MONITOR_SUCCESSOR_ACTIVE_PARENT_MANIFEST_HASH_MISMATCH';Assert-Hash (Join-Path $parent 'backend\\imap_bridge.py') '80d45bb7bde5e0b00fe73e5a54386ede07f7c44fbafcb9e3cc990cc501979248' 'PDC_MONITOR_SUCCESSOR_ACTIVE_PARENT_BRIDGE_HASH_MISMATCH';Assert-Hash (Join-Path (Join-Path $InstallRoot ("control\\"+$ParentVersion)) 'run-current-sealed.ps1') (Get-Content (Join-Path $parentTrust 'SEALED_RUN_CURRENT_SHA256') -Raw).Trim() 'PDC_MONITOR_SUCCESSOR_ACTIVE_PARENT_SEALED_RUNNER_HASH_MISMATCH'
 $phase='authenticated_parent_preflight';$preflight=Join-Path (Join-Path $InstallRoot ("control\"+$ParentVersion)) 'active-preflight-authenticated-mailbox-compatibility.py';Assert-Hash $preflight (Get-Content (Join-Path $parentTrust 'AUTHENTICATED_MAILBOX_PREFLIGHT_SHA256') -Raw).Trim() 'PDC_MONITOR_SUCCESSOR_ACTIVE_PREFLIGHT_HASH_MISMATCH';$parentConfig=Join-Path $InstallRoot ("config\"+$ParentVersion+'\runtime.env');$preflightArgs=@($preflight,'--release-root',$parent,'--trust-root',$parentTrust,'--env-file',$parentConfig,'--compatibility-path',$preflight,'--live','--require-terminal-uid514');Invoke-Captured $preflightArgs|Out-Null
 if($DryRun){$phase='active_dispatch_boundary';Status 'ok' 'PDC_MONITOR_SUCCESSOR_ACTIVE_DRY_RUN_NO_MAILBOX' $false $false $true;[Console]::WriteLine('{"ok":true,"successor":"2026.08.61","active_dispatch_blocked":true,"mailbox_contacted":false,"production_contacted":false}');exit 0}
 $phase='monitor_entrypoint';$launcher=Join-Path $root 'runtime_launcher.py';$meta=Get-Content $manifest -Raw|ConvertFrom-Json;Assert-Hash $launcher ([string]$meta.files.'runtime_launcher.py'.sha256) 'PDC_MONITOR_SUCCESSOR_ACTIVE_LAUNCHER_HASH_MISMATCH';$env:PDC_MONITOR_RELEASE_VERSION=$ExpectedVersion;$env:PDC_MONITOR_LOCAL_STATE_DIR=Join-Path $InstallRoot 'state\monitor';$env:IMAP_BRIDGE_STATE=Join-Path $InstallRoot 'state\imap.json';$env:IMAP_BRIDGE_ATTACHMENT_DIR=Join-Path $InstallRoot 'state\attachments';$env:IMAP_BRIDGE_EVIDENCE_DIR=Join-Path $InstallRoot 'state\evidence';$log=Join-Path $InstallRoot ("logs\cycle-"+(Get-Date -Format 'yyyyMMdd')+'.log');New-Item (Split-Path -Parent $log) -ItemType Directory -Force|Out-Null;Status 'running' 'PDC_MONITOR_SUCCESSOR_ACTIVE_REACHED_MONITOR' $true $true $false
 do{& $venvPython -B -I -S $launcher --release-root $root --venv-root $venv --mode monitor --env-file $config *>> $log;if($LASTEXITCODE-ne 0){Fail 'PDC_MONITOR_SUCCESSOR_ACTIVE_MONITOR_FAILED'};Status 'ok' 'PDC_MONITOR_SUCCESSOR_ACTIVE_CYCLE_COMPLETE' $true $true $false;if($Mode-eq'Continuous'){Start-Sleep -Seconds 300}}while($Mode-eq'Continuous')
 [Console]::WriteLine('{"ok":true,"successor":"2026.08.61","active_dispatch":"monitor","mailbox_contacted":true,"production_contacted":false}');exit 0
}catch{$code='PDC_MONITOR_SUCCESSOR_ACTIVE_DENIED';switch($phase){'static_current'{$code='PDC_MONITOR_SUCCESSOR_ACTIVE_CURRENT_DENIED'}'successor_inventory'{$code='PDC_MONITOR_SUCCESSOR_ACTIVE_INVENTORY_DENIED'}'parent_static'{$code='PDC_MONITOR_SUCCESSOR_ACTIVE_PARENT_STATIC_DENIED'}'authenticated_parent_preflight'{$code='PDC_MONITOR_SUCCESSOR_ACTIVE_PREFLIGHT_DENIED'}'monitor_entrypoint'{$code='PDC_MONITOR_SUCCESSOR_ACTIVE_MONITOR_DENIED'}};try{Status 'failed' $code $false $false $true}catch{};[Console]::Error.WriteLine('PDC_MONITOR_SUCCESSOR_ACTIVE_DENIED');exit 1}finally{if($held){$mutex.ReleaseMutex()|Out-Null};$mutex.Dispose()}
