[CmdletBinding()]
param([string]$InstallRoot="$env:ProgramData\PDCMonitor\Staging",[ValidateSet('OneCycle','Continuous')][string]$Mode='OneCycle',[switch]$DryRun)
$ErrorActionPreference='Stop'
$Version='2026.08.68';$Parent='2026.08.66';$TaskName='PDC-PMB-Email-Monitor-Staging'
$mutex=New-Object System.Threading.Mutex($false,'Global\PDCMonitorStagingCurrentHead766');$held=$false;$phase='startup';$statusPath=$null;$handoff=$null
function Fail([string]$Code){throw $Code}
function Hash([string]$Path){if(-not(Test-Path -LiteralPath $Path -PathType Leaf)){Fail 'PDC_MONITOR_766_MISSING_FILE'};(Get-FileHash -LiteralPath $Path -Algorithm SHA256).Hash.ToLowerInvariant()}
function Trust([string]$Name){$p=Join-Path $trust $Name;if(-not(Test-Path -LiteralPath $p -PathType Leaf)){Fail "PDC_MONITOR_766_TRUST_MISSING_$Name"};(Get-Content -LiteralPath $p -Raw).Trim().ToLowerInvariant()}
function No-Reparse([string]$Path){$probe=[IO.Path]::GetFullPath($Path);while($probe){if(Test-Path -LiteralPath $probe){$item=Get-Item -LiteralPath $probe -Force;if(($item.Attributes-band[IO.FileAttributes]::ReparsePoint)-ne 0){Fail 'PDC_MONITOR_766_REPARSE_POINT'}};$next=[IO.Path]::GetDirectoryName($probe);if(-not$next-or$next-eq$probe){break};$probe=$next}}
function Status([string]$State,[string]$Code,[bool]$Reached,[bool]$Contacted,[bool]$Blocked){if(-not$statusPath){return};$payload=[ordered]@{ok=($State-eq'ok');status=$State;code=$Code;release_version=$Version;mode=$Mode;dry_run=[bool]$DryRun;phase=$phase;monitor_entrypoint_reached=$Reached;active_dispatch_blocked=$Blocked;mailbox_contacted=$Contacted;uid514_processed=$false;production_contacted=$false;task_enabled=$false;current_staging_migration_head=766;sealed_parent_unchanged=$true;last_cycle=([DateTime]::UtcNow.ToString('o'))};$tmp=$statusPath+'.tmp';$json=$payload|ConvertTo-Json -Compress;if($json.Length-gt 4096){Fail 'PDC_MONITOR_766_STATUS_BOUNDED_WRITE_FAILED'};Set-Content -LiteralPath $tmp -Value $json -Encoding ascii -NoNewline;Move-Item -LiteralPath $tmp -Destination $statusPath -Force}
function Invoke-Captured([string[]]$Arguments){$out=& $venvPython -B -I -S @Arguments 2>&1|Out-String;if($LASTEXITCODE-ne 0){Fail 'PDC_MONITOR_766_CHILD_FAILED'};return $out}
try{
 $held=$mutex.WaitOne(0);$statusPath=Join-Path $InstallRoot 'state\monitor\active-dispatch-status.json';New-Item (Split-Path -Parent $statusPath) -ItemType Directory -Force|Out-Null;if(-not$held){Status 'ok' 'PDC_MONITOR_766_OVERLAP_SKIPPED' $false $false $true;exit 0}
 $env:PYTHONDONTWRITEBYTECODE='1';$env:PYTHONNOUSERSITE='1';$env:PATH='';Remove-Item Env:PYTHONHOME,Env:PYTHONPATH,Env:PYTHONSTARTUP,Env:PYTHONUSERBASE -ErrorAction SilentlyContinue
 $current=Join-Path $InstallRoot 'CURRENT';$phase='static_current';if((Get-Content -LiteralPath $current -Raw).Trim()-ne$Version){Fail 'PDC_MONITOR_766_CURRENT_MISMATCH'}
 $root=Join-Path $InstallRoot "releases\$Version";$parent=Join-Path $InstallRoot "releases\$Parent";$trust=Join-Path $InstallRoot "trust\$Version";$control=Join-Path $InstallRoot "control\$Version";$venv=Join-Path $InstallRoot "venvs\$Version";$config=Join-Path $InstallRoot "config\$Version\runtime.env";$venvPython=Join-Path $venv 'Scripts\python.exe';foreach($path in @($root,$parent,$trust,$control,$venv,$config)){No-Reparse $path}
 $phase='successor_inventory';$verifier=Join-Path $control 'verify-successor.py';& $venvPython -B -I -S $verifier --bundle $root --expected-manifest-sha256 (Trust 'SUCCESSOR_MANIFEST_SHA256') --expected-parent-manifest-sha256 (Trust 'PARENT_MANIFEST_SHA256') --expected-processor-sha256 (Trust 'SUCCESSOR_PROCESSOR_SHA256') 2>&1|Out-String;if($LASTEXITCODE-ne 0){Fail 'PDC_MONITOR_766_INVENTORY_FAILED'}
 $phase='frozen_parent';if((Hash (Join-Path $parent 'release-manifest.json')) -ne (Trust 'FROZEN_066_MANIFEST_SHA256')){Fail 'PDC_MONITOR_766_FROZEN_066_CHANGED'}
 $phase='token_refresh';$refresh=Join-Path $control 'pdc_monitor_refresh_20260868.py';$refreshOut=Invoke-Captured @($refresh,'--machine-store',(Join-Path $InstallRoot "secrets\$Version\monitor-refresh.dpapi"),'--base-config',$config,'--state-dir',(Join-Path $InstallRoot 'state\monitor'));try{$refreshResult=$refreshOut|ConvertFrom-Json}catch{Fail 'PDC_MONITOR_766_REFRESH_DENIED'};$handoff=[IO.Path]::GetFullPath([string]$refreshResult.handoff);if($refreshResult.ok-ne$true-or-not(Test-Path -LiteralPath $handoff -PathType Leaf)-or-not$handoff.StartsWith(([IO.Path]::GetFullPath((Join-Path $InstallRoot 'state\monitor'))+'\'),[StringComparison]::OrdinalIgnoreCase)){Fail 'PDC_MONITOR_766_REFRESH_DENIED'};No-Reparse $handoff
 $phase='current_head_preflight';$preflight=Join-Path $control 'current-head-preflight.py';$args=@($preflight,'--bundle-root',$root,'--trust-root',$trust,'--env-file',$handoff,'--compatibility-path',$preflight,'--live','--require-terminal-uid514');Invoke-Captured $args|Out-Null
 if($DryRun){$phase='dispatch_boundary';Status 'ok' 'PDC_MONITOR_766_DRY_RUN_NO_MAILBOX' $false $false $true;[Console]::WriteLine('{"ok":true,"successor":"2026.08.68","current_staging_migration_head":766,"active_dispatch_blocked":true,"mailbox_contacted":false,"uid514_processed":false,"production_contacted":false}');exit 0}
 $phase='monitor_import_preflight';$probe=& $venvPython -B -I -S (Join-Path $root 'backend\imap_bridge.py') --help 2>&1|Out-String;if($LASTEXITCODE-ne 0-or$probe-match'ModuleNotFoundError'){Fail 'PDC_MONITOR_766_IMPORT_DENIED'}
 $phase='monitor_entrypoint';$env:PDC_MONITOR_RELEASE_VERSION=$Version;$env:PDC_MONITOR_LOCAL_STATE_DIR=Join-Path $InstallRoot 'state\monitor';$env:IMAP_BRIDGE_STATE=Join-Path $InstallRoot 'state\imap.json';$env:IMAP_BRIDGE_ATTACHMENT_DIR=Join-Path $InstallRoot 'state\attachments';$env:IMAP_BRIDGE_EVIDENCE_DIR=Join-Path $InstallRoot 'state\evidence';$log=Join-Path $InstallRoot ("logs\cycle-"+(Get-Date -Format 'yyyyMMdd')+'.log');New-Item (Split-Path -Parent $log) -ItemType Directory -Force|Out-Null;Status 'running' 'PDC_MONITOR_766_REACHED_MONITOR' $true $true $false
 do{& $venvPython -B -I -S (Join-Path $root 'runtime_launcher.py') --release-root $root --venv-root $venv --mode monitor --env-file $handoff *>> $log;if($LASTEXITCODE-ne 0){Fail 'PDC_MONITOR_766_MONITOR_FAILED'};Status 'ok' 'PDC_MONITOR_766_CYCLE_COMPLETE' $true $true $false;if($Mode-eq'Continuous'){Start-Sleep -Seconds 300}}while($Mode-eq'Continuous')
 [Console]::WriteLine('{"ok":true,"successor":"2026.08.68","current_staging_migration_head":766,"active_dispatch":"monitor","mailbox_contacted":true,"uid514_processed":false,"production_contacted":false}');exit 0
}catch{$code='PDC_MONITOR_766_DENIED';switch($phase){'static_current'{$code='PDC_MONITOR_766_CURRENT_DENIED'}'successor_inventory'{$code='PDC_MONITOR_766_INVENTORY_DENIED'}'frozen_parent'{$code='PDC_MONITOR_766_PARENT_DENIED'}'current_head_preflight'{$code='PDC_MONITOR_766_PREFLIGHT_DENIED'}'monitor_import_preflight'{$code='PDC_MONITOR_766_IMPORT_DENIED'}'monitor_entrypoint'{$code='PDC_MONITOR_766_MONITOR_DENIED'}};try{Status 'failed' $code $false $false $true}catch{};[Console]::Error.WriteLine('PDC_MONITOR_766_DENIED');exit 1}finally{if($handoff){Remove-Item -LiteralPath $handoff -Force -ErrorAction SilentlyContinue};if($held){$mutex.ReleaseMutex()|Out-Null};$mutex.Dispose()}
