[CmdletBinding()]
param([string]$InstallRoot="$env:ProgramData\PDCMonitor\Staging")
$ErrorActionPreference='Stop'
$ExpectedVersion='2026.08.47';$ParentVersion='2026.08.44';$ExpectedRelease='pdc-monitor-staging-m502-2026.08.47';$ParentRelease='pdc-monitor-staging-m502-2026.08.44';$ExpectedProject='cdsmnqxtyyoeoznmbidd';$ExpectedActorId='df7c55d9-6ba0-47f6-ba16-44d6ae2c2a4b';$ExpectedActorEmail='sales@broometoyota.com.au';$ExpectedHead=503
function Fail([string]$Code){throw $Code}
function Hash([string]$Path){if(-not(Test-Path -LiteralPath $Path -PathType Leaf)){Fail 'PDC_MONITOR_SUCCESSOR_VERIFYONLY_MISSING_FILE'};return (Get-FileHash -LiteralPath $Path -Algorithm SHA256).Hash.ToLowerInvariant()}
function Trust([string]$Name){$p=Join-Path $trust $Name;if(-not(Test-Path -LiteralPath $p -PathType Leaf)){Fail "PDC_MONITOR_SUCCESSOR_VERIFYONLY_TRUST_MISSING_$Name"};return (Get-Content -LiteralPath $p -Raw).Trim().ToLowerInvariant()}
function Assert-Hash([string]$Path,[string]$Expected,[string]$Code){if((Hash $Path)-ne$Expected.ToLowerInvariant()){Fail $Code}}
function No-Reparse([string]$Path,[string]$Label){$probe=[IO.Path]::GetFullPath($Path);while($probe){if(Test-Path -LiteralPath $probe){$item=Get-Item -LiteralPath $probe -Force;if(($item.Attributes-band[IO.FileAttributes]::ReparsePoint)-ne 0){Fail "PDC_MONITOR_SUCCESSOR_VERIFYONLY_REPARSE_$Label"}};$parent=[IO.Path]::GetDirectoryName($probe);if(-not$parent-or$parent-eq$probe){break};$probe=$parent}}
try{
 $env:PYTHONDONTWRITEBYTECODE='1';$env:PYTHONNOUSERSITE='1';$env:PATH='';Remove-Item Env:PYTHONHOME,Env:PYTHONPATH,Env:PYTHONSTARTUP,Env:PYTHONUSERBASE -ErrorAction SilentlyContinue
 $current=Join-Path $InstallRoot 'CURRENT';if((Get-Content -LiteralPath $current -Raw).Trim()-ne$ExpectedVersion){Fail 'PDC_MONITOR_SUCCESSOR_VERIFYONLY_CURRENT_MISMATCH'}
 $root=Join-Path $InstallRoot ("releases\"+$ExpectedVersion);$parent=Join-Path $InstallRoot ("releases\"+$ParentVersion);$trust=Join-Path $InstallRoot ("trust\"+$ExpectedVersion);$parentTrust=Join-Path $InstallRoot ("trust\"+$ParentVersion);$control=Join-Path $InstallRoot ("control\"+$ExpectedVersion);$parentControl=Join-Path $InstallRoot ("control\"+$ParentVersion);$venv=Join-Path $InstallRoot ("venvs\"+$ExpectedVersion);$venvPython=Join-Path $venv 'Scripts\python.exe';foreach($p in @($root,$parent,$trust,$parentTrust,$control)){No-Reparse $p 'ROOT'}
 $self=Join-Path $control 'run-current-verifyonly.ps1';$bootstrap=Join-Path $control 'bootstrap-verifyonly.ps1';Assert-Hash $self (Trust 'VERIFYONLY_RUNNER_SHA256') 'PDC_MONITOR_SUCCESSOR_VERIFYONLY_RUNNER_HASH_MISMATCH';Assert-Hash $bootstrap (Trust 'VERIFYONLY_BOOTSTRAP_SHA256') 'PDC_MONITOR_SUCCESSOR_VERIFYONLY_BOOTSTRAP_HASH_MISMATCH'
 $verifier=Join-Path $control 'verify-successor.py';& $venvPython -B -I -S $verifier --bundle $root --expected-manifest-sha256 (Trust 'SUCCESSOR_MANIFEST_SHA256') --expected-parent-manifest-sha256 (Trust 'PARENT_MANIFEST_SHA256') --expected-bridge-sha256 (Trust 'SUCCESSOR_BRIDGE_SHA256') 2>&1|Out-String;if($LASTEXITCODE-ne 0){Fail 'PDC_MONITOR_SUCCESSOR_VERIFYONLY_INVENTORY_FAILED'}
 $parentManifest=Join-Path $parent 'release-manifest.json';Assert-Hash $parentManifest (Trust 'PARENT_MANIFEST_SHA256') 'PDC_MONITOR_SUCCESSOR_VERIFYONLY_PARENT_MANIFEST_HASH_MISMATCH';Assert-Hash (Join-Path $parent 'backend\\imap_bridge.py') '80d45bb7bde5e0b00fe73e5a54386ede07f7c44fbafcb9e3cc990cc501979248' 'PDC_MONITOR_SUCCESSOR_VERIFYONLY_PARENT_BRIDGE_HASH_MISMATCH';Assert-Hash (Join-Path $parentControl 'run-current-sealed.ps1') (Get-Content (Join-Path $parentTrust 'SEALED_RUN_CURRENT_SHA256') -Raw).Trim() 'PDC_MONITOR_SUCCESSOR_VERIFYONLY_PARENT_SEALED_RUNNER_HASH_MISMATCH'
 $preflight=Join-Path $parentControl 'active-preflight-authenticated-mailbox-compatibility.py';$preflightExpected=Get-Content (Join-Path $parentTrust 'AUTHENTICATED_MAILBOX_PREFLIGHT_SHA256') -Raw;Assert-Hash $preflight $preflightExpected 'PDC_MONITOR_SUCCESSOR_VERIFYONLY_PREFLIGHT_HASH_MISMATCH';$parentConfig=Join-Path $InstallRoot ("config\"+$ParentVersion+'\runtime.env');$args=@($preflight,'--release-root',$parent,'--trust-root',$parentTrust,'--env-file',$parentConfig,'--compatibility-path',$preflight,'--live','--require-terminal-uid514');$null=& $venvPython -B -I -S @args 2>&1|Out-String;if($LASTEXITCODE-ne 0){Fail 'PDC_MONITOR_SUCCESSOR_VERIFYONLY_PREFLIGHT_DENIED'}
 $launcher=Join-Path $root 'runtime_launcher.py';& $venvPython -B -I -S $launcher --release-root $root --venv-root $venv --mode smoke 2>&1|Out-String;if($LASTEXITCODE-ne 0){Fail 'PDC_MONITOR_SUCCESSOR_VERIFYONLY_LAUNCHER_SMOKE_FAILED'}
 [Console]::WriteLine('{"ok":true,"verified":true,"verifyonly":true,"successor":"2026.08.47","task_enabled":false,"task_started":false,"mailbox_contacted":false,"uid514_processed":false,"production_contacted":false}');exit 0
}catch{[Console]::Error.WriteLine('PDC_MONITOR_SUCCESSOR_VERIFYONLY_DENIED');exit 1}
