[CmdletBinding()]
param([string]$InstallRoot="$env:ProgramData\PDCMonitor\Staging",[ValidateSet('OneCycle','Continuous')][string]$Mode='OneCycle',[switch]$DryRun)
$ErrorActionPreference='Stop';$ExpectedVersion='2026.08.66';$ParentVersion='2026.08.44';$ExpectedActorId='df7c55d9-6ba0-47f6-ba16-44d6ae2c2a4b';$ExpectedActorEmail='sales@broometoyota.com.au';$ExpectedGateway='pdc-monitor-staging-sales-uid509-v1';$mutex=New-Object System.Threading.Mutex($false,'Global\PDCMonitorStagingSuccessorActiveDispatch');$held=$false;$phase='startup';$statusPath=$null;$runtimeEnv=$null
function Fail([string]$Code){throw $Code}
function Hash([string]$Path){if(-not(Test-Path -LiteralPath $Path -PathType Leaf)){Fail 'PDC_MONITOR_SUCCESSOR_ACTIVE_MISSING_FILE'};return (Get-FileHash -LiteralPath $Path -Algorithm SHA256).Hash.ToLowerInvariant()}
function No-Reparse([string]$Path,[string]$Label){$probe=[IO.Path]::GetFullPath($Path);while($probe){if(Test-Path -LiteralPath $probe){$item=Get-Item -LiteralPath $probe -Force;if(($item.Attributes-band[IO.FileAttributes]::ReparsePoint)-ne 0){Fail "PDC_MONITOR_SUCCESSOR_ACTIVE_REPARSE_$Label"}};$parent=[IO.Path]::GetDirectoryName($probe);if(-not$parent-or$parent-eq$probe){break};$probe=$parent}}
function Trust([string]$Name){$p=Join-Path $trust $Name;if(-not(Test-Path -LiteralPath $p -PathType Leaf)){Fail "PDC_MONITOR_SUCCESSOR_ACTIVE_TRUST_MISSING_$Name"};return (Get-Content -LiteralPath $p -Raw).Trim().ToLowerInvariant()}
function Assert-Hash([string]$Path,[string]$Expected,[string]$Code){if((Hash $Path)-ne$Expected.ToLowerInvariant()){Fail $Code}}
function Status([string]$State,[string]$Code,[bool]$Reached,[bool]$Contacted,[bool]$Blocked){if(-not$statusPath){return};$payload=[ordered]@{ok=($State-eq'ok');status=$State;code=$Code;release_version='2026.08.66';mode=$Mode;dry_run=[bool]$DryRun;phase=$phase;monitor_entrypoint_reached=$Reached;active_dispatch_blocked=$Blocked;mailbox_contacted=$Contacted;uid514_processed=$false;production_contacted=$false;task_enabled=$false;sealed_parent_unchanged=$true;last_cycle=([DateTime]::UtcNow.ToString('o'))};$json=$payload|ConvertTo-Json -Compress;if($json.Length-gt 4096){Fail 'PDC_MONITOR_SUCCESSOR_ACTIVE_STATUS_BOUNDED_WRITE_FAILED'};$tmp=$statusPath+'.tmp';Set-Content -LiteralPath $tmp -Value $json -Encoding ascii -NoNewline;Move-Item -LiteralPath $tmp -Destination $statusPath -Force}
function Invoke-Captured([string[]]$Arguments){$out=& $venvPython -B -I -S @Arguments 2>&1|Out-String;if($LASTEXITCODE-ne 0){Fail 'PDC_MONITOR_SUCCESSOR_ACTIVE_CHILD_FAILED'};return $out}
try{
 $held=$mutex.WaitOne(0);$statusPath=Join-Path $InstallRoot 'state\monitor\active-dispatch-status.json';New-Item (Split-Path -Parent $statusPath) -ItemType Directory -Force|Out-Null;if(-not$held){Status 'ok' 'PDC_MONITOR_SUCCESSOR_ACTIVE_OVERLAP_SKIPPED' $false $false $true;exit 0}
 $env:PYTHONDONTWRITEBYTECODE='1';$env:PYTHONNOUSERSITE='1';$env:PATH='';Remove-Item Env:PYTHONHOME,Env:PYTHONPATH,Env:PYTHONSTARTUP,Env:PYTHONUSERBASE -ErrorAction SilentlyContinue
 $current=Join-Path $InstallRoot 'CURRENT';$phase='static_current';if((Get-Content $current -Raw).Trim() -ne '2026.08.66'){Fail 'PDC_MONITOR_SUCCESSOR_ACTIVE_CURRENT_MISMATCH'}
 $root=Join-Path $InstallRoot 'releases\2026.08.66';$parent=Join-Path $InstallRoot 'releases\2026.08.44';$trust=Join-Path $InstallRoot 'trust\2026.08.66';$parentTrust=Join-Path $InstallRoot 'trust\2026.08.44';$control=Join-Path $InstallRoot 'control\2026.08.66';$venv=Join-Path $InstallRoot 'venvs\2026.08.66';$config=Join-Path $InstallRoot 'config\2026.08.66\runtime.env';$stateDir=Join-Path $InstallRoot 'state\monitor';$machineStore=Join-Path $InstallRoot 'secrets\2026.08.66\monitor-refresh.dpapi';$venvPython=Join-Path $venv 'Scripts\python.exe';foreach($p in @($root,$parent,$trust,$parentTrust,$control,$stateDir,$machineStore)){No-Reparse $p 'ROOT'}
 $manifest=Join-Path $root 'release-manifest.json';$successorVerifier=Join-Path $control 'verify-successor.py';$phase='successor_inventory';Assert-Hash $successorVerifier (Trust 'SUCCESSOR_VERIFIER_SHA256') 'PDC_MONITOR_SUCCESSOR_ACTIVE_VERIFIER_HASH_MISMATCH';& $venvPython -B -I -S $successorVerifier --bundle $root --expected-manifest-sha256 (Trust 'SUCCESSOR_MANIFEST_SHA256') --expected-parent-manifest-sha256 (Trust 'PARENT_MANIFEST_SHA256') --expected-bridge-sha256 (Trust 'SUCCESSOR_BRIDGE_SHA256') 2>&1|Out-String;if($LASTEXITCODE-ne 0){Fail 'PDC_MONITOR_SUCCESSOR_ACTIVE_INVENTORY_FAILED'}
 $phase='parent_static';Assert-Hash (Join-Path $parent 'release-manifest.json') (Trust 'GRANDPARENT_MANIFEST_SHA256') 'PDC_MONITOR_SUCCESSOR_ACTIVE_PARENT_MANIFEST_HASH_MISMATCH';Assert-Hash (Join-Path $parent 'backend\imap_bridge.py') '80d45bb7bde5e0b00fe73e5a54386ede07f7c44fbafcb9e3cc990cc501979248' 'PDC_MONITOR_SUCCESSOR_ACTIVE_PARENT_BRIDGE_HASH_MISMATCH';Assert-Hash (Join-Path (Join-Path $InstallRoot 'control\2026.08.44') 'run-current-sealed.ps1') (Get-Content (Join-Path $parentTrust 'SEALED_RUN_CURRENT_SHA256') -Raw).Trim() 'PDC_MONITOR_SUCCESSOR_ACTIVE_PARENT_SEALED_RUNNER_HASH_MISMATCH'
 $phase='token_refresh';$refresh=Join-Path $control 'pdc_monitor_refresh_20260866.py';$refreshOut=Invoke-Captured @($refresh,'--machine-store',$machineStore,'--base-config',$config,'--state-dir',$stateDir);try{$refreshResult=$refreshOut|ConvertFrom-Json}catch{Fail 'PDC_MONITOR_SUCCESSOR_ACTIVE_REFRESH_DENIED'};$runtimeEnv=[IO.Path]::GetFullPath([string]$refreshResult.handoff);if($refreshResult.ok -ne $true -or -not(Test-Path -LiteralPath $runtimeEnv -PathType Leaf) -or -not$runtimeEnv.StartsWith(([IO.Path]::GetFullPath($stateDir)+'\'),[StringComparison]::OrdinalIgnoreCase)){Fail 'PDC_MONITOR_SUCCESSOR_ACTIVE_REFRESH_DENIED'};No-Reparse $runtimeEnv 'HANDOFF'
 $phase='authenticated_parent_preflight';$preflight=Join-Path $InstallRoot 'control\2026.08.44\active-preflight-authenticated-mailbox-compatibility.py';$preflightRoot=Join-Path $InstallRoot 'releases\2026.08.44';$preflightTrust=Join-Path $InstallRoot 'trust\2026.08.44';$preflightArgs=@($preflight,'--release-root',$preflightRoot,'--trust-root',$preflightTrust,'--env-file',$runtimeEnv,'--compatibility-path',$preflight,'--live','--require-terminal-uid514');Invoke-Captured $preflightArgs|Out-Null
 if($DryRun){$phase='active_dispatch_boundary';Status 'ok' 'PDC_MONITOR_SUCCESSOR_ACTIVE_DRY_RUN_NO_MAILBOX' $false $false $true;[Console]::WriteLine('{"ok":true,"successor":"2026.08.66","active_dispatch_blocked":true,"mailbox_contacted":false,"production_contacted":false}');exit 0}
 $phase='monitor_import_preflight';$importProbe=& $venvPython -B -I -S (Join-Path $root 'backend\imap_bridge.py') --help 2>&1|Out-String;if($LASTEXITCODE-ne 0 -or $importProbe -match 'ModuleNotFoundError'){Fail 'PDC_MONITOR_SUCCESSOR_ACTIVE_IMPORT_DENIED'}
 $phase='monitor_entrypoint';$launcher=Join-Path $root 'runtime_launcher.py';$meta=Get-Content $manifest -Raw|ConvertFrom-Json;Assert-Hash $launcher ([string]$meta.files.'runtime_launcher.py'.sha256) 'PDC_MONITOR_SUCCESSOR_ACTIVE_LAUNCHER_HASH_MISMATCH';$env:PDC_MONITOR_RELEASE_VERSION='2026.08.66';$env:PDC_MONITOR_LOCAL_STATE_DIR=$stateDir;$env:IMAP_BRIDGE_STATE=Join-Path $InstallRoot 'state\imap.json';$env:IMAP_BRIDGE_ATTACHMENT_DIR=Join-Path $InstallRoot 'state\attachments';$env:IMAP_BRIDGE_EVIDENCE_DIR=Join-Path $InstallRoot 'state\evidence';$log=Join-Path $InstallRoot ("logs\cycle-"+(Get-Date -Format 'yyyyMMdd')+'.log');New-Item (Split-Path -Parent $log) -ItemType Directory -Force|Out-Null;Status 'running' 'PDC_MONITOR_SUCCESSOR_ACTIVE_REACHED_MONITOR' $true $false $false;& $venvPython -B -I -S $launcher --release-root $root --venv-root $venv --mode monitor --env-file $runtimeEnv *>> $log;if($LASTEXITCODE-ne 0){Fail 'PDC_MONITOR_SUCCESSOR_ACTIVE_MONITOR_FAILED'};Status 'ok' 'PDC_MONITOR_SUCCESSOR_ACTIVE_CYCLE_COMPLETE' $true $true $false
 [Console]::WriteLine('{"ok":true,"successor":"2026.08.66","active_dispatch":"monitor","mailbox_contacted":true,"production_contacted":false}');exit 0
}catch{$code='PDC_MONITOR_SUCCESSOR_ACTIVE_DENIED';switch($phase){'static_current'{$code='PDC_MONITOR_SUCCESSOR_ACTIVE_CURRENT_DENIED'}'successor_inventory'{$code='PDC_MONITOR_SUCCESSOR_ACTIVE_INVENTORY_DENIED'}'parent_static'{$code='PDC_MONITOR_SUCCESSOR_ACTIVE_PARENT_STATIC_DENIED'}'token_refresh'{$code='PDC_MONITOR_SUCCESSOR_ACTIVE_REFRESH_DENIED'}'authenticated_parent_preflight'{$code='PDC_MONITOR_SUCCESSOR_ACTIVE_PREFLIGHT_DENIED'}'monitor_import_preflight'{$code='PDC_MONITOR_SUCCESSOR_ACTIVE_IMPORT_DENIED'}'monitor_entrypoint'{$code='PDC_MONITOR_SUCCESSOR_ACTIVE_MONITOR_DENIED'}};try{Status 'failed' $code $false $false $true}catch{};[Console]::Error.WriteLine('PDC_MONITOR_SUCCESSOR_ACTIVE_DENIED');exit 1}finally{if($runtimeEnv){Remove-Item -LiteralPath $runtimeEnv -Force -ErrorAction SilentlyContinue};if($held){$mutex.ReleaseMutex()|Out-Null};$mutex.Dispose()}
