'use strict';
const {chromium}=require('playwright-core');
const {execFileSync}=require('child_process');
const URL='https://btnew.github.io/pdc-control-board-staging/';
const CHROME=process.env.PDC_CHROME_EXECUTABLE||'C:/Program Files/Google/Chrome/Application/chrome.exe';
const users=[{email:process.env.PDC_STAGING_ADMIN2_EMAIL,password:process.env.PDC_STAGING_ADMIN2_PASSWORD,role:'administrator'},{email:process.env.PDC_STAGING_CONTROLLER_B_EMAIL,password:process.env.PDC_STAGING_CONTROLLER_B_PASSWORD,role:'operator'}];
async function login(page,u){await page.goto(URL+'?learning216='+Date.now(),{waitUntil:'networkidle',timeout:60000});await page.waitForFunction(()=>document.body.dataset.authState==='signed-out'||!document.getElementById('pdc-password-form')?.hidden,null,{timeout:60000});await page.locator('#pdc-login-email').fill(u.email);await page.locator('#pdc-login-password').fill(u.password);await page.locator('#pdc-password-login').click();await page.waitForFunction(role=>window.PDC_AUTH_CONTEXT?.role===role&&document.body.dataset.authState==='approved',u.role,{timeout:60000});}
(async()=>{if(users.some(u=>!u.email||!u.password))throw Error('missing staging credentials');const b=await chromium.launch({executablePath:CHROME,headless:true});const contexts=await Promise.all(users.map(()=>b.newContext()));const pages=await Promise.all(contexts.map(c=>c.newPage()));await Promise.all(pages.map((p,i)=>login(p,users[i])));const refs=await Promise.all(pages.map(p=>p.evaluate(()=>window.PDC_SUPABASE_CONFIG?.projectRef)));if(refs.some(x=>x!=='cdsmnqxtyyoeoznmbidd'))throw Error('wrong project');const channelNames=[];for(let i=0;i<pages.length;i++){const result=await pages[i].evaluate(async i=>{const token=window.__pdcCachedAccessToken,cfg=window.PDC_SUPABASE_CONFIG;if(!token||!cfg?.url||!cfg?.publishableKey||!window.supabase?.createClient)throw Error('authenticated realtime prerequisites unavailable');window.__learningSupabase=window.supabase.createClient(cfg.url,cfg.publishableKey,{global:{headers:{Authorization:`Bearer ${token}`}},auth:{persistSession:false,autoRefreshToken:false}});const c=window.__learningSupabase;window.__learningEvents=[];const name=`learning-216-${i}-${Date.now()}`;window.__learningChannel=c.channel(name).on('postgres_changes',{event:'UPDATE',schema:'public',table:'pdc_supervised_revision'},payload=>window.__learningEvents.push(payload)).subscribe();await new Promise((resolve,reject)=>{let n=0;const t=setInterval(()=>{n++;const st=window.__learningChannel?.state;if(st==='joined'){clearInterval(t);resolve()}else if(n>100){clearInterval(t);reject(Error('channel not joined '+st))}},100)});return name},i);channelNames.push(result)}
const before=await Promise.all(pages.map(p=>p.evaluate(()=>window.__learningEvents.length)));execFileSync('python',['-c',"import os,psycopg2;u=os.environ.get('PDC_STAGING_DIRECT_DATABASE_URL') or os.environ['PDC_STAGING_DATABASE_URL'];c=psycopg2.connect(u);q=c.cursor();q.execute(\"update public.pdc_supervised_revision set revision=revision+1,updated_at=clock_timestamp() where singleton\");c.commit();c.close()"],{stdio:'inherit'});await Promise.all(pages.map(p=>p.waitForFunction(()=>window.__learningEvents.length===1,null,{timeout:30000})));const after=await Promise.all(pages.map(p=>p.evaluate(()=>window.__learningEvents.map(e=>({eventType:e.eventType,newRevision:e.new.revision,oldRevision:e.old.revision})))));if(!after.every(x=>x.length===1&&x[0].eventType==='UPDATE'))throw Error('event-bound realtime failed '+JSON.stringify(after));console.log(JSON.stringify({schema:'pdc.supervised-learning-two-user-realtime/v1',project:'cdsmnqxtyyoeoznmbidd',twoAuthenticatedUsers:true,distinctContexts:contexts[0]!==contexts[1],channelNames,before,after,passed:true},null,2));await Promise.all(contexts.map(c=>c.close()));await b.close()})().catch(e=>{console.error(e);process.exit(1)});
