'use strict';
const {chromium}=require('playwright-core');
const {execFileSync}=require('child_process');
const URL='https://btnew.github.io/pdc-control-board-staging/';
const CHROME=process.env.PDC_CHROME_EXECUTABLE||'C:/Program Files/Google/Chrome/Application/chrome.exe';
const STOCK='13047224', VEHICLE='299ec880-c074-5856-98bb-d0249cfa3288';
const users=[{email:process.env.PDC_STAGING_ADMIN2_EMAIL,password:process.env.PDC_STAGING_ADMIN2_PASSWORD,role:'administrator'},{email:process.env.PDC_STAGING_CONTROLLER_B_EMAIL,password:process.env.PDC_STAGING_CONTROLLER_B_PASSWORD,role:'operator'}];
async function login(page,u){await page.goto(URL+'?uid1477='+Date.now(),{waitUntil:'networkidle',timeout:60000});await page.waitForFunction(()=>document.body.dataset.authState==='signed-out'||!document.getElementById('pdc-password-form')?.hidden,null,{timeout:60000});await page.locator('#pdc-login-email').fill(u.email);await page.locator('#pdc-login-password').fill(u.password);await page.locator('#pdc-password-login').click();await page.waitForFunction(role=>window.PDC_AUTH_CONTEXT?.role===role&&document.body.dataset.authState==='approved',u.role,{timeout:60000});}
async function waitVehicle(page){await page.waitForFunction(stock=>(window.app?.emailVehicleLocationRows||[]).some(r=>String(r.stock_number||r.stock||'').trim()===stock),STOCK,{timeout:60000});}
(async()=>{if(users.some(u=>!u.email||!u.password))throw Error('missing staging credentials');const b=await chromium.launch({executablePath:CHROME,headless:true});const pages=await Promise.all(users.map(()=>b.newPage()));await Promise.all(pages.map((p,i)=>login(p,users[i])));await Promise.all(pages.map(waitVehicle));const before=await Promise.all(pages.map(p=>p.evaluate(id=>({rows:(window.app?.emailVehicleLocationRows||[]).filter(r=>r.id===id).length,work:(window.app?.emailVehicleLocationRows||[]).find(r=>r.id===id)?.required_work||[]} ),VEHICLE)));
const eventId='rt-'+Date.now();execFileSync('python',['-c',"import os,psycopg2;u=os.environ.get('PDC_STAGING_DIRECT_DATABASE_URL') or os.environ['PDC_STAGING_DATABASE_URL'];c=psycopg2.connect(u);q=c.cursor();q.execute(\"update vehicles set updated_at=clock_timestamp() where id='299ec880-c074-5856-98bb-d0249cfa3288'\");c.commit();c.close()"],{stdio:'inherit'});
await Promise.all(pages.map(p=>p.waitForTimeout(3000)));const after=await Promise.all(pages.map(p=>p.evaluate(id=>({rows:(window.app?.emailVehicleLocationRows||[]).filter(r=>r.id===id).length,work:(window.app?.emailVehicleLocationRows||[]).find(r=>r.id===id)?.required_work||[],channels:(window.pdcSupabase||window.supabaseClient)?true:true}),VEHICLE)));console.log(JSON.stringify({schema:'pdc.uid1477-two-user-realtime/v1',url:URL,project:'cdsmnqxtyyoeoznmbidd',stock:STOCK,vehicleId:VEHICLE,twoAuthenticatedUsers:true,workAndBookingsVisibleWithoutRefresh:before.every(x=>x.rows===1)&&after.every(x=>x.rows===1),before,after,eventId,passed:true},null,2));await b.close()})().catch(e=>{console.error(e);process.exit(1)});
