[CmdletBinding()] param(
 [string]$InstallRoot="$env:ProgramData\PDCMonitor\Staging",
 [string]$ReleaseVersion,
 [long]$RecoveryEventId=0,
 [switch]$StaticOnly,
 [switch]$VerifyOnly,
 [ValidateSet('contained','active')][string]$AgenticMode='contained'
)
$ErrorActionPreference='Stop';$env:PYTHONDONTWRITEBYTECODE='1';$env:PYTHONNOUSERSITE='1';$env:PATH=''
Remove-Item Env:PYTHONHOME,Env:PYTHONPATH,Env:PYTHONSTARTUP,Env:PYTHONUSERBASE -ErrorAction SilentlyContinue
function Read-Trust([string]$Root,[string]$Name){$path=Join-Path $Root $Name;if(-not(Test-Path -LiteralPath $path -PathType Leaf)){throw "Trust anchor $Name is missing."};return (Get-Content -LiteralPath $path -Raw).Trim()}
function Assert-FileHash([string]$Path,[string]$Expected,[string]$Label){if(-not(Test-Path -LiteralPath $Path -PathType Leaf)){throw "$Label is missing."};$actual=(Get-FileHash -LiteralPath $Path -Algorithm SHA256).Hash.ToLowerInvariant();if($actual -ne $Expected.ToLowerInvariant()){throw "$Label hash mismatch."}}
function Assert-ReadExecuteAcl([string]$Path){$acl=Get-Acl -LiteralPath $Path;if(-not $acl.AreAccessRulesProtected){throw 'Sealed runtime ACL inheritance is not protected.'};$writers=@('S-1-5-18','S-1-5-32-544');$rx=$false;$mask=[System.Security.AccessControl.FileSystemRights]::WriteData -bor [System.Security.AccessControl.FileSystemRights]::CreateFiles -bor [System.Security.AccessControl.FileSystemRights]::AppendData -bor [System.Security.AccessControl.FileSystemRights]::CreateDirectories -bor [System.Security.AccessControl.FileSystemRights]::WriteExtendedAttributes -bor [System.Security.AccessControl.FileSystemRights]::WriteAttributes -bor [System.Security.AccessControl.FileSystemRights]::Delete -bor [System.Security.AccessControl.FileSystemRights]::DeleteSubdirectoriesAndFiles -bor [System.Security.AccessControl.FileSystemRights]::ChangePermissions -bor [System.Security.AccessControl.FileSystemRights]::TakeOwnership;foreach($rule in $acl.Access){$sid=$rule.IdentityReference.Translate([System.Security.Principal.SecurityIdentifier]).Value;if($rule.AccessControlType -eq 'Allow' -and (($rule.FileSystemRights -band $mask) -ne 0) -and $sid -notin $writers){throw 'Sealed runtime ACL grants broad write authority.'};if($sid -eq 'S-1-5-19' -and $rule.AccessControlType -eq 'Allow' -and (($rule.FileSystemRights -band [System.Security.AccessControl.FileSystemRights]::ReadAndExecute) -eq [System.Security.AccessControl.FileSystemRights]::ReadAndExecute) -and (($rule.FileSystemRights -band $mask) -eq 0)){$rx=$true}};if(-not $rx){throw 'Sealed runtime ACL lacks LOCAL SERVICE read and execute only.'}}
function Assert-NoReparse([string]$Path,[string]$Label){$probe=[System.IO.Path]::GetFullPath($Path);while(-not[string]::IsNullOrWhiteSpace($probe)){if(Test-Path -LiteralPath $probe){$item=Get-Item -LiteralPath $probe -Force;if(($item.Attributes -band [System.IO.FileAttributes]::ReparsePoint) -ne 0){throw "$Label contains a reparse point."}};$parent=[System.IO.Path]::GetDirectoryName($probe);if([string]::IsNullOrWhiteSpace($parent)-or$parent -eq $probe){break};$probe=$parent}}
function Assert-SealedRuntime([string]$Release,[string]$ExpectedManifest){
 $manifestPath=Join-Path $Release 'release-manifest.json';Assert-FileHash $manifestPath $ExpectedManifest 'Release manifest';$manifest=Get-Content -LiteralPath $manifestPath -Raw|ConvertFrom-Json
 $runtime=$manifest.python_runtime;if($runtime.root -ne 'python-runtime' -or $runtime.executable -ne 'python-runtime/python.exe' -or $runtime.version -ne '3.11.15' -or $runtime.architecture -ne 'AMD64' -or $runtime.inventory_sha256 -ne $manifest.python_runtime_inventory_sha256){throw 'Sealed Python runtime identity mismatch.'}
 $runtimeRoot=[System.IO.Path]::GetFullPath((Join-Path $Release 'python-runtime')).TrimEnd('\');Assert-NoReparse $runtimeRoot 'Sealed Python runtime';Assert-ReadExecuteAcl $runtimeRoot;$count=0
 foreach($property in $runtime.files.PSObject.Properties){$relative=[string]$property.Name;$meta=$property.Value;if([string]::IsNullOrWhiteSpace($relative)-or$relative.Contains('\')-or[System.IO.Path]::IsPathRooted($relative)-or$relative -match '(^|/)\.\.(/|$)'-or$meta.sha256 -notmatch '^[0-9a-f]{64}$'-or[int64]$meta.bytes -lt 0){throw 'Sealed Python runtime inventory is invalid.'};$item=[System.IO.Path]::GetFullPath((Join-Path $runtimeRoot $relative.Replace('/','\')));if(-not$item.StartsWith($runtimeRoot+'\',[System.StringComparison]::OrdinalIgnoreCase)){throw 'Sealed runtime path escaped its root.'};Assert-NoReparse $item 'Sealed runtime member';if(-not(Test-Path -LiteralPath $item -PathType Leaf)-or(Get-Item -LiteralPath $item -Force).Length -ne [int64]$meta.bytes){throw 'Sealed runtime member size mismatch.'};Assert-FileHash $item ([string]$meta.sha256) 'Sealed runtime member';$count++}
 if(@(Get-ChildItem -LiteralPath $runtimeRoot -Recurse -File -Force).Count -ne $count){throw 'Sealed runtime membership mismatch.'};return Join-Path $runtimeRoot 'python.exe'
}
$current=Join-Path $InstallRoot 'CURRENT';if($ReleaseVersion){$version=$ReleaseVersion}else{if(-not(Test-Path -LiteralPath $current -PathType Leaf)){throw 'CURRENT pointer is missing.'};$version=(Get-Content -LiteralPath $current -Raw).Trim()}
if($version -notmatch '^[A-Za-z0-9][A-Za-z0-9._-]{0,79}$'){throw 'Release pointer is invalid.'}
$root=Join-Path $InstallRoot ("releases\"+$version);$venv=Join-Path $InstallRoot ("venvs\"+$version);$trust=Join-Path $InstallRoot ("trust\"+$version);$control=Join-Path $InstallRoot ("control\"+$version);$config=Join-Path $InstallRoot ("config\"+$version+'\runtime.env')
$python=Assert-SealedRuntime $root (Read-Trust $trust 'MANIFEST_SHA256')
$verifier=Join-Path $control 'verify_release.py';Assert-FileHash $verifier (Read-Trust $trust 'TRUSTED_VERIFIER_SHA256') 'Trusted verifier'
$verifyArgs=@($verifier,'--bundle',$root,'--expected-manifest-sha256',(Read-Trust $trust 'MANIFEST_SHA256'),'--expected-source-sha',(Read-Trust $trust 'EXPECTED_SOURCE_SHA'),'--expected-source-tree',(Read-Trust $trust 'EXPECTED_SOURCE_TREE'),'--expected-staging-sha',(Read-Trust $trust 'EXPECTED_STAGING_SHA'),'--expected-gateway-instance-id',(Read-Trust $trust 'EXPECTED_GATEWAY_INSTANCE_ID'),'--expected-release-name',(Read-Trust $trust 'EXPECTED_RELEASE_NAME'),'--expected-release-version',(Read-Trust $trust 'EXPECTED_RELEASE_VERSION'),'--expected-built-at-utc',(Read-Trust $trust 'EXPECTED_BUILT_AT_UTC'),'--expected-bundle-hash-definition',(Read-Trust $trust 'EXPECTED_BUNDLE_HASH_DEFINITION'))
& $python -B -I -S @verifyArgs;if($LASTEXITCODE -ne 0){throw 'Installed release verification failed.'}
$inventory=Join-Path $trust 'VENV_SHA256.tsv';if(-not(Test-Path -LiteralPath $inventory -PathType Leaf)){throw 'Venv inventory is missing.'};$expectedCount=0
foreach($line in Get-Content -LiteralPath $inventory){if([string]::IsNullOrWhiteSpace($line)){continue};$fields=$line.Split("`t",3);if($fields.Count -ne 3-or$fields[0] -notmatch '^[0-9a-f]{64}$'-or$fields[1] -notmatch '^[0-9]+$'){throw 'Venv inventory is invalid.'};$relative=$fields[2];if([System.IO.Path]::IsPathRooted($relative)-or$relative -match '(^|[\\/])\.\.([\\/]|$)'){throw 'Venv inventory path is invalid.'};$item=Join-Path $venv $relative;Assert-NoReparse $item 'Venv member';if(-not(Test-Path -LiteralPath $item -PathType Leaf)-or(Get-Item -LiteralPath $item).Length -ne [int64]$fields[1]){throw 'Venv inventory member is missing or changed.'};Assert-FileHash $item $fields[0] 'Venv inventory member';$expectedCount++}
if(@(Get-ChildItem -LiteralPath $venv -Recurse -File -Force).Count -ne $expectedCount){throw 'Venv inventory membership mismatch.'}
$venvPython=Join-Path $venv 'Scripts\python.exe';$launcher=Join-Path $root 'runtime_launcher.py'
& $venvPython -B -I -S $launcher --release-root $root --venv-root $venv --mode smoke;if($LASTEXITCODE -ne 0){throw 'Sealed release dependency smoke test failed.'}
if($StaticOnly){[pscustomobject]@{ok=$true;static_verified=$true;sealed_python_runtime=$true;release=$version;network_contacted=$false;intake_started=$false}|ConvertTo-Json -Compress;exit 0}
if(-not(Test-Path -LiteralPath $config -PathType Leaf)){throw 'Versioned runtime environment is missing.'}
$preflightArgs=@($launcher,'--release-root',$root,'--venv-root',$venv,'--mode','preflight','--env-file',$config,'--agentic-mode',$AgenticMode)
if($VerifyOnly -or $RecoveryEventId -eq 0){$preflightArgs+='--require-terminal-uid514'}
& $venvPython -B -I -S @preflightArgs;if($LASTEXITCODE -ne 0){throw 'Live identity, gateway, migration-head or UID-514 recovery gate failed.'}
if($VerifyOnly){[pscustomobject]@{ok=$true;verified=$true;sealed_python_runtime=$true;release=$version;intake_started=$false}|ConvertTo-Json -Compress;exit 0}
$env:PDC_MONITOR_RELEASE_VERSION=$version;$env:PDC_MONITOR_LOCAL_STATE_DIR=Join-Path $InstallRoot 'state\monitor';$env:IMAP_BRIDGE_STATE=Join-Path $InstallRoot 'state\imap.json';$env:IMAP_BRIDGE_ATTACHMENT_DIR=Join-Path $InstallRoot 'state\attachments';$env:IMAP_BRIDGE_EVIDENCE_DIR=Join-Path $InstallRoot 'state\evidence';$log=Join-Path $InstallRoot ("logs\cycle-"+(Get-Date -Format 'yyyyMMdd')+'.log')
if($RecoveryEventId -eq 0){& $venvPython -B -I -S $launcher --release-root $root --venv-root $venv --mode monitor --env-file $config *>> $log}elseif($RecoveryEventId -eq 25751401){& $venvPython -B -I -S $launcher --release-root $root --venv-root $venv --mode recovery --env-file $config *>> $log}else{throw 'Only active recovery event 25751401 is supported by this candidate.'}
exit $LASTEXITCODE
