-- Six independent typed operation Review/Apply/replay/Undo round trips.
\set ON_ERROR_STOP on
select set_config('request.jwt.claim.sub','10000000-0000-4000-8000-000000000002',false);
select set_config('request.jwt.claims','{"sub":"10000000-0000-4000-8000-000000000002","email":"auditor@example.test","role":"authenticated"}',false);

create function pg_temp.envelope5(p_instruction text,p_scope jsonb,p_delivery uuid,p_nonce text) returns jsonb
language plpgsql as $$declare issued text;expires text;evidence jsonb;env jsonb;digest text;begin
 issued:=to_char(clock_timestamp() at time zone 'UTC','YYYY-MM-DD"T"HH24:MI:SS.US"Z"');expires:=to_char((clock_timestamp()+interval '2 minutes') at time zone 'UTC','YYYY-MM-DD"T"HH24:MI:SS.US"Z"');digest:=encode(extensions.digest(convert_to(p_instruction,'UTF8'),'sha256'),'hex');evidence:=jsonb_build_object('bot_identity','pdc-auditor-staging','instruction_sha256',digest,'original_instruction',p_instruction,'telegram_chat_id',7828138290,'telegram_message_id',abs(hashtextextended(p_delivery::text,0))%2147483646+1,'telegram_sender_id',7828138290,'telegram_update_id',abs(hashtextextended(p_delivery::text,1))%2147483647);env:=jsonb_build_object('gateway_instance_id','fixture-gateway','delivery_uuid',p_delivery,'key_id','fixture-key','nonce',p_nonce,'issued_at',issued,'expires_at',expires,'instruction_sha256',digest,'selected_scope',p_scope,'telegram_evidence',evidence,'signature',repeat('0',64));return jsonb_set(env,'{signature}',to_jsonb(encode(extensions.hmac(public.pdc_auditor_signing_bytes_253(env),decode(repeat('42',32),'hex'),'sha256'),'hex')));end$$;

create function pg_temp.scope5(p_vehicle uuid,p_card text) returns jsonb language sql stable as $$select public.pdc_auditor_typed_snapshot_253(p_vehicle,p_card)$$;

insert into public.vehicle_work_items(vehicle_id,work_key,required,completed,completed_by,completed_at,notes)
select '20000000-0000-4000-8000-000000000010','tint',true,true,'10000000-0000-4000-8000-000000000003',clock_timestamp(),'protected completed fixture'
where not exists(select 1 from public.vehicle_work_items where notes='protected completed fixture');
insert into public.vehicle_workshop_line_adjustments(vehicle_id,line_key,source_kind,stage_code,description,estimated_hours,active,version,created_by,updated_by,operation_code,display_order,manual_assignment_locked,correction_origin,job_card_number)
select '20000000-0000-4000-8000-000000000010','manual:protected','manual','FAB','Protected manual fixture',3,true,7,'10000000-0000-4000-8000-000000000003','10000000-0000-4000-8000-000000000003','MANUAL',99,true,'manual_operator','J10'
where not exists(select 1 from public.vehicle_workshop_line_adjustments where line_key='manual:protected');

do $$declare
 actions text[]:=array['add','edit','split','combine','reorder','remove_duplicate'];scopes jsonb[];i int;scope jsonb;env jsonb;result jsonb;d jsonb;apply_scope jsonb;apply_env jsonb;applied jsonb;replayed jsonb;runid uuid;rev text;undo_scope jsonb;undone jsonb;vehicle uuid;card text;before_review jsonb;before_apply jsonb;after_apply jsonb;protected_work jsonb;protected_manual jsonb;revision_before bigint;receipt_count bigint;changed_env jsonb;
begin
 scopes:=array[
 jsonb_build_object('contract','pdc-auditor-bounded-intent-253-v1','action','add','apply_unambiguous',true,'selector',jsonb_build_object('vehicle_id','20000000-0000-4000-8000-000000000010'),'desire',jsonb_build_object('new_value',jsonb_build_object('description','Individual Added','estimated_hours',1.5,'operation_code','INDA','ordered_position',2,'work_key','hoist'))),
 jsonb_build_object('contract','pdc-auditor-bounded-intent-253-v1','action','edit','apply_unambiguous',true,'selector',jsonb_build_object('operation_ref','source:30000000-0000-4000-8000-000000000011'),'desire',jsonb_build_object('new_value',jsonb_build_object('description','Individual Edited','estimated_hours',2.75,'operation_code','INDE','ordered_position',3,'work_key','electrical'))),
 jsonb_build_object('contract','pdc-auditor-bounded-intent-253-v1','action','split','apply_unambiguous',true,'selector',jsonb_build_object('operation_ref','source:30000000-0000-4000-8000-000000000012'),'desire',jsonb_build_object('children',jsonb_build_array(jsonb_build_object('description','Individual Split A','estimated_hours',0.5,'operation_code','INDS1','work_key','fitting'),jsonb_build_object('description','Individual Split B','estimated_hours',1.5,'operation_code','INDS2','work_key','hoist')))),
 jsonb_build_object('contract','pdc-auditor-bounded-intent-253-v1','action','combine','apply_unambiguous',true,'selector',jsonb_build_object('operation_refs',jsonb_build_array('source:30000000-0000-4000-8000-000000000013','source:30000000-0000-4000-8000-000000000014')),'desire',jsonb_build_object('survivor_operation_ref','source:30000000-0000-4000-8000-000000000013','new_value',jsonb_build_object('description','Individual Combined','estimated_hours',2,'operation_code','INDC','work_key','fabrication'))),
 jsonb_build_object('contract','pdc-auditor-bounded-intent-253-v1','action','reorder','apply_unambiguous',true,'selector',jsonb_build_object('operation_refs',jsonb_build_array('source:30000000-0000-4000-8000-000000000016','source:30000000-0000-4000-8000-000000000015')),'desire',jsonb_build_object('complete_effective_set',true)),
 jsonb_build_object('contract','pdc-auditor-bounded-intent-253-v1','action','remove_duplicate','apply_unambiguous',true,'selector',jsonb_build_object('operation_refs',jsonb_build_array('source:30000000-0000-4000-8000-000000000017','source:30000000-0000-4000-8000-000000000018')),'desire',jsonb_build_object('duplicate_proof','database_exact','survivor_operation_ref','source:30000000-0000-4000-8000-000000000017'))];
 select to_jsonb(w) into protected_work from public.vehicle_work_items w where notes='protected completed fixture';select to_jsonb(a) into protected_manual from public.vehicle_workshop_line_adjustments a where line_key='manual:protected';
 for i in 1..6 loop
  scope:=scopes[i];vehicle:=('20000000-0000-4000-8000-'||lpad((9+i)::text,12,'0'))::uuid;card:='J'||(9+i)::text;before_review:=pg_temp.scope5(vehicle,card);
  env:=pg_temp.envelope5('Individual Review '||actions[i],scope,('71000000-0000-4000-8000-'||lpad(i::text,12,'0'))::uuid,'individual-review-'||actions[i]);begin result:=public.plan_pdc_auditor_typed_instruction_253(actions[i],'review',scope,env);exception when others then raise exception 'individual % Review error: %',actions[i],sqlerrm using errcode=sqlstate;end;d:=result->'data';
  if result->>'code'<>'typed_review_proposal_created' or (d->>'proposed_count')::int<1 or (d->>'ambiguous_count')::int<>0 or pg_temp.scope5(vehicle,card)<>before_review then raise exception '% Review invalid or mutating',actions[i];end if;
  -- Apply the exact immutable Review proposal under a new signed confirmation;
  -- no replanning or caller-authored typed state is accepted here.
  before_apply:=pg_temp.scope5(vehicle,card);apply_scope:=jsonb_build_object('contract','pdc-auditor-apply-selection-253-v1','proposal_id',d->>'proposal_id','proposal_version',(d->>'proposal_version')::int,'proposal_hash',d->>'proposal_hash','typed_item_set_hash',d->>'typed_item_set_hash','final_scope_hash',d->>'final_scope_hash','expected_row_versions_hash',d->>'expected_row_versions_hash');apply_env:=pg_temp.envelope5('Apply these corrections',apply_scope,('72000000-0000-4000-8000-'||lpad(i::text,12,'0'))::uuid,'individual-apply-'||actions[i]);select count(*) into revision_before from public.pdc_auditor_workshop_revisions;
  applied:=public.apply_pdc_auditor_typed_plan_253((d->>'proposal_id')::uuid,(d->>'proposal_version')::int,d->>'proposal_hash',d->>'typed_item_set_hash',d->>'final_scope_hash',d->>'expected_row_versions_hash',apply_env);runid:=(applied->'data'->>'run_id')::uuid;after_apply:=pg_temp.scope5(vehicle,card);
  if applied->>'code'<>'typed_plan_applied_253' or after_apply=before_apply or (select count(*) from public.pdc_auditor_workshop_revisions)<>revision_before+1 then raise exception '% Apply/revision invalid',actions[i];end if;
  if (after_apply->>'aggregate_total_hours')::numeric<>(select coalesce(sum(estimated_hours),0) from public.pdc_effective_operation_lines where vehicle_id=vehicle and coalesce(job_card_number,'')=card and active) then raise exception '% aggregate total wrong',actions[i];end if;
  if after_apply->'per_department_hours'<>(select coalesce(jsonb_object_agg(x.work_key,x.hours),'{}'::jsonb) from(select work_key,sum(estimated_hours)hours from public.pdc_effective_operation_lines where vehicle_id=vehicle and coalesce(job_card_number,'')=card and active group by work_key order by work_key)x) then raise exception '% department totals wrong',actions[i];end if;
  if after_apply->'required_work_identifiers'<>(select coalesce(jsonb_agg(jsonb_build_object('id',id,'work_key',work_key,'required',required,'completed',completed) order by work_key,id),'[]'::jsonb) from public.vehicle_work_items where vehicle_id=vehicle and (required or completed)) then raise exception '% required identifiers wrong',actions[i];end if;
  if actions[i]='add' and not exists(select 1 from public.pdc_effective_operation_lines where vehicle_id=vehicle and active and description='Individual Added' and operation_code='INDA' and work_key='hoist' and estimated_hours=1.5 and display_order=2) then raise exception 'individual Add fields wrong';
  elsif actions[i]='edit' and not exists(select 1 from public.pdc_effective_operation_lines where vehicle_id=vehicle and active and description='Individual Edited' and operation_code='INDE' and work_key='electrical' and estimated_hours=2.75 and display_order=3) then raise exception 'individual Edit fields wrong';
  elsif actions[i]='split' and ((select count(*) from public.pdc_effective_operation_lines where vehicle_id=vehicle and active and description like 'Individual Split %')<>2 or (select sum(estimated_hours) from public.pdc_effective_operation_lines where vehicle_id=vehicle and active)<>2) then raise exception 'individual Split fields wrong';
  elsif actions[i]='combine' and ((select count(*) from public.pdc_effective_operation_lines where vehicle_id=vehicle and active)<>1 or not exists(select 1 from public.pdc_effective_operation_lines where vehicle_id=vehicle and active and description='Individual Combined' and operation_code='INDC' and work_key='fabrication' and estimated_hours=2)) then raise exception 'individual Combine fields wrong';
  elsif actions[i]='reorder' and (select array_agg(operation_code order by display_order,operation_line_identifier) from public.pdc_effective_operation_lines where vehicle_id=vehicle and active)<>array['R2','R1']::text[] then raise exception 'individual Reorder wrong';
  elsif actions[i]='remove_duplicate' and (select count(*) from public.pdc_effective_operation_lines where vehicle_id=vehicle and active)<>1 then raise exception 'individual Remove Duplicate wrong';end if;
  select count(*) into receipt_count from public.pdc_auditor_typed_scope_receipts_253 where run_id=runid and before_snapshot=before_apply and after_snapshot=after_apply;if receipt_count<>1 or exists(select 1 from public.pdc_auditor_typed_change_receipts_253 where run_id=runid and (overlay_after is null or reason='' or server_rule_evidence is null)) then raise exception '% receipts incomplete',actions[i];end if;
  replayed:=public.apply_pdc_auditor_typed_plan_253((d->>'proposal_id')::uuid,(d->>'proposal_version')::int,d->>'proposal_hash',d->>'typed_item_set_hash',d->>'final_scope_hash',d->>'expected_row_versions_hash',apply_env);if replayed<>applied or pg_temp.scope5(vehicle,card)<>after_apply then raise exception '% replay not idempotent',actions[i];end if;
  changed_env:=pg_temp.envelope5('Apply these corrections',jsonb_set(apply_scope,'{proposal_version}','2'::jsonb),('72000000-0000-4000-8000-'||lpad(i::text,12,'0'))::uuid,'individual-changed-'||actions[i]);begin perform public.apply_pdc_auditor_typed_plan_253((d->>'proposal_id')::uuid,(d->>'proposal_version')::int,d->>'proposal_hash',d->>'typed_item_set_hash',d->>'final_scope_hash',d->>'expected_row_versions_hash',changed_env);raise exception '% changed-intent replay succeeded',actions[i];exception when unique_violation then null;end;
  select run_revision_after into rev from public.pdc_auditor_typed_runs_253 where run_id=runid;undo_scope:=jsonb_build_object('contract','pdc-auditor-undo-selection-253-v1','run_id',runid,'run_revision_after',rev);env:=pg_temp.envelope5('Undo the selected Auditor run',undo_scope,('73000000-0000-4000-8000-'||lpad(i::text,12,'0'))::uuid,'individual-undo-'||actions[i]);undone:=public.undo_last_pdc_auditor_typed_run_253(env);
  if undone->>'code'<>'typed_run_undone_253' or pg_temp.scope5(vehicle,card)<>before_apply then raise exception '% exact logical Undo failed',actions[i];end if;
  begin perform public.undo_last_pdc_auditor_typed_run_253(pg_temp.envelope5('Undo the selected Auditor run',undo_scope,('74000000-0000-4000-8000-'||lpad(i::text,12,'0'))::uuid,'individual-second-undo-'||actions[i]));raise exception '% second Undo succeeded',actions[i];exception when no_data_found then null;end;
  if protected_work<>(select to_jsonb(w) from public.vehicle_work_items w where notes='protected completed fixture') or protected_manual<>(select to_jsonb(a) from public.vehicle_workshop_line_adjustments a where line_key='manual:protected') then raise exception '% changed protected values',actions[i];end if;
 end loop;
end$$;
select 'AI_AUDITOR_253_SIX_INDIVIDUAL_PATHS_PASS' result;
