(function(root,factory){'use strict';const api=factory(root);if(typeof module==='object'&&module.exports)module.exports=api;else root.KARRATHA_API=api;})(typeof window==='object'?window:globalThis,function(root){
 'use strict';
 const PROJECT='cdsmnqxtyyoeoznmbidd',CENTRE='KARRATHA';
 const RPCS=Object.freeze({context:'get_karratha_pdc_context',snapshot:'get_karratha_pdc_snapshot',preview:'preview_karratha_nuvu_import',apply:'apply_karratha_nuvu_import',save:'save_karratha_pdc'});
 const ACTIONS=new Set(['job_selection','operation','parts','vehicle_location','booking','start','stop','resume','complete','cancel','external_complete','qc','technician','bay','setting','membership']);
 class StaleResponse extends Error {constructor(){super('The account or page changed.');this.name='StaleResponse';}}
 let client=null,getOwner=()=>'',getContext=()=>null,getUserId=()=>null;const attempts=new Map();
 function validConfig(config){return Boolean(config&&config.projectRef===PROJECT&&config.url==='https://'+PROJECT+'.supabase.co'&&config.centreCode===CENTRE&&config.authStorageKey==='karratha-pdc-auth-v1'&&typeof config.publishableKey==='string'&&config.publishableKey.startsWith('sb_publishable_'));}
 function message(error){const code=String(error?.code||'');if(['42501','PGRST301','401','403'].includes(code))return 'Your Karratha access could not be confirmed. Sign in again or ask an administrator.';if(['40001','23505','409'].includes(code)||/version|stale|conflict|changed since/i.test(error?.message||''))return 'This record changed. Refresh and review the current details before saving again.';const text=String(error?.message||'').slice(0,240);return text&&/^(?:Karratha|Booking|Bay|Operation|Job|Technician|Parts|QC|Selected|Provide|Invalid|Expected|No |Cannot |Work |Source |Current |NuVu|Mapping|Calendar|Start |End |Duration|File |Import|Preview|Membership|Role |Centre)/i.test(text)&&!/(?:SQL|schema|function|SELECT|pdc_|\{)/i.test(text)?text:'The request could not be confirmed. Refresh to check the current records before trying again.';}
 function init(options){if(!validConfig(options.config))throw new Error('Karratha configuration is missing or does not match this deployment.');client=options.client;getOwner=options.getOwner;getContext=options.getContext;getUserId=options.getUserId;return api;}
 async function call(method,params={}){const name=RPCS[method];if(!name||!client)throw new Error('Karratha request is unavailable.');const owner=getOwner();if(!owner)throw new Error('Sign in to Karratha first.');if(method!=='context'&&getContext()?.centre!==CENTRE)throw new Error('Karratha access has not been confirmed.');let result;try{result=await client.rpc(name,params);}catch(error){if(owner!==getOwner())throw new StaleResponse();throw new Error(message(error));}if(owner!==getOwner())throw new StaleResponse();if(result?.error){const failure=new Error(message(result.error));failure.code=result.error.code;throw failure;}if(!result?.data||typeof result.data!=='object'||Array.isArray(result.data))throw new Error('The server returned incomplete Karratha information. Refresh before continuing.');return result.data;}
 async function context(){const result=await call('context');if(result.centre!==CENTRE||!['administrator','operator','viewer'].includes(result.role)||result.user_id!==getUserId()||!Number.isInteger(result.membership_version)||result.membership_version<1)throw new Error('Your approved Karratha membership could not be confirmed.');return result;}
 async function snapshot(from,to){const result=await call('snapshot',{p_date_from:from,p_date_to:to});if(result.context?.centre!==CENTRE||result.context.user_id!==getUserId()||!Number.isInteger(result.context.membership_version)||result.context.membership_version<1)throw new Error('The snapshot does not match your Karratha access.');for(const key of ['vehicles','jobs','operations','bookings','bays','technicians','settings','history'])if(!Array.isArray(result[key]))throw new Error('The Karratha snapshot is incomplete. Refresh before continuing.');return result;}
 async function preview(fileName,fileHash,rows){if(!getContext()?.can_import)throw new Error('Karratha import access is required.');return call('preview',{p_file_name:fileName,p_file_sha256:fileHash,p_rows:rows});}
 async function apply(id,version){if(!getContext()?.can_import)throw new Error('Karratha import access is required.');return call('apply',{p_preview_id:id,p_expected_version:version});}
 async function save(action,id,version,data){if(!ACTIONS.has(action))throw new Error('This Karratha action is unavailable.');const admin=['membership','setting','technician','bay'].includes(action);if(!getContext()?.can_edit&&!admin)throw new Error('Your Karratha access is read-only.');if(admin&&!getContext()?.can_admin)throw new Error('Karratha administrator access is required.');if(!Number.isInteger(version)||version<0)throw new Error('The current record version is required.');const attemptKey=JSON.stringify([getOwner(),action,id||null,version,data]);if(!attempts.has(attemptKey))attempts.set(attemptKey,root.crypto.randomUUID());const requestId=attempts.get(attemptKey),result=await call('save',{p_action:action,p_id:id||null,p_expected_version:version,p_data:{...data,request_id:requestId}});if(!result.record?.id||(id&&result.record.id!==id)||!Number.isInteger(result.record.version)||result.record.version<1)throw new Error('The saved record could not be confirmed. Refresh before continuing.');attempts.delete(attemptKey);return result;}
 const api={init,validConfig,message,context,snapshot,preview,apply,save,clear(){attempts.clear();},StaleResponse,RPCS};return api;
});
