(function(root){
 'use strict';
 const $=id=>document.getElementById(id),state={client:null,user:null,context:null,generation:0,checking:false,blocked:false},listeners=new Set();
 const owner=()=>state.user?.id&&!state.blocked?JSON.stringify([state.user.id,state.generation,state.context?.membership_version||null,state.context?.role||null,state.context?.can_edit||false,state.context?.can_admin||false,state.context?.can_import||false]):'';
 const notify=()=>{for(const fn of listeners)fn({user:state.user,context:state.context,generation:state.generation});};
 function status(text,error=false){$('auth-message').textContent=text;$('auth-message').classList.toggle('error',error);}
 function locked(message='Sign in with approved Karratha access.'){state.generation++;state.context=null;state.user=null;$('app-shell').hidden=true;$('app-shell').setAttribute('inert','');$('auth-screen').hidden=false;status(message);notify();}
 async function accept(session){const generation=++state.generation;state.context=null;state.user=null;$('app-shell').hidden=true;$('app-shell').setAttribute('inert','');$('auth-screen').hidden=false;notify();if(!session||state.blocked){status('Sign in with approved Karratha access.');return;}status('Checking your Karratha access…');try{const {data,error}=await state.client.auth.getUser();if(generation!==state.generation)return;if(error||data?.user?.id!==session.user.id)throw new Error('Your account could not be confirmed. Sign in again.');state.user=data.user;const context=await root.KARRATHA_API.context();if(generation!==state.generation)return;if(context.user_id!==state.user.id)throw new Error('The Karratha membership does not match your account.');state.context=Object.freeze(context);$('auth-signout').hidden=false;status('');$('signin-form').hidden=false;if(/(?:^|[?#&])type=(?:recovery|invite)(?:[&#]|$)/.test(location.hash)){ $('password-form').hidden=false;$('signin-form').hidden=true;status('Set your password before opening Karratha.');return;}$('auth-screen').hidden=true;$('app-shell').hidden=false;$('app-shell').removeAttribute('inert');notify();}catch(error){if(generation!==state.generation)return;state.context=null;$('auth-signout').hidden=!state.user;status(error.message,true);notify();}}
 async function signOut(){state.blocked=true;locked('Signed out of Karratha.');try{await state.client.auth.signOut({scope:'local'});}catch(error){status('Signed out here. The remote sign-out could not be confirmed.');}}
 function adoptContext(context){if(!state.user||context?.centre!=='KARRATHA'||context.user_id!==state.user.id)throw new Error('Karratha access changed. Sign in again.');const changed=state.context?.membership_version!==context.membership_version||state.context?.role!==context.role||state.context?.can_edit!==context.can_edit||state.context?.can_admin!==context.can_admin||state.context?.can_import!==context.can_import;state.context=Object.freeze(context);if(changed)notify();}
 async function init(){try{const config=root.KARRATHA_CONFIG;if(!root.KARRATHA_API.validConfig(config)||!root.supabase?.createClient)throw new Error('Karratha sign-in configuration is unavailable.');state.client=root.supabase.createClient(config.url,config.publishableKey,{auth:{storageKey:config.authStorageKey,persistSession:true,autoRefreshToken:true,detectSessionInUrl:true}});root.KARRATHA_API.init({client:state.client,config,getOwner:owner,getContext:()=>state.context,getUserId:()=>state.user?.id});state.client.auth.onAuthStateChange((event,session)=>{if(event==='PASSWORD_RECOVERY')state.blocked=false;if(event==='SIGNED_OUT'){locked('Signed out of Karratha.');return;}if(state.checking)return;if(session&&state.user?.id===session.user.id&&state.context&&['TOKEN_REFRESHED','SIGNED_IN','INITIAL_SESSION'].includes(event))return;root.setTimeout(()=>void accept(session),0);});const {data,error}=await state.client.auth.getSession();if(error)throw error;await accept(data.session);}catch(error){locked(error.message);status(error.message,true);}}
 $('signin-form').addEventListener('submit',async event=>{event.preventDefault();const form=event.currentTarget,values=new FormData(form),button=form.querySelector('button');state.blocked=false;state.checking=true;button.disabled=true;status('Signing in…');try{const {data,error}=await state.client.auth.signInWithPassword({email:String(values.get('email')).trim(),password:String(values.get('password'))});if(error)throw new Error('The email or password could not be confirmed.');form.elements.password.value='';await accept(data.session);}catch(error){status(error.message,true);}finally{state.checking=false;button.disabled=false;}});
 $('forgot-password').addEventListener('click',async()=>{const email=$('signin-form').elements.email.value.trim();if(!email){status('Enter your email address first.');return;}status('Requesting a password reset…');try{const {error}=await state.client.auth.resetPasswordForEmail(email,{redirectTo:location.origin+location.pathname});if(error)throw error;status('If that account exists, a password reset link will be sent.');}catch(error){status('The password reset request could not be confirmed. Try again later.',true);}});
 $('password-form').addEventListener('submit',async event=>{event.preventDefault();const form=event.currentTarget,password=form.elements.password.value;if(password.length<12){status('Use at least 12 characters for your password.',true);return;}try{const {error}=await state.client.auth.updateUser({password});if(error)throw error;form.reset();$('password-form').hidden=true;history.replaceState({},document.title,location.pathname);state.blocked=false;const {data}=await state.client.auth.getSession();await accept(data.session);}catch(error){status('The password change could not be confirmed.',true);}});
 $('auth-signout').addEventListener('click',signOut);$('signout-button').addEventListener('click',signOut);
 root.KARRATHA_AUTH={getContext:()=>state.context,getUser:()=>state.user,getOwner:owner,adoptContext,lock:locked,signOut,onChanged(fn){listeners.add(fn);return()=>listeners.delete(fn);}};
 root.KARRATHA_AUTH_READY=init();
})(window);
