(function(root,factory){'use strict';const api=factory();if(typeof module==='object'&&module.exports)module.exports=api;else root.KARRATHA_CALENDAR=api;})(typeof window==='object'?window:globalThis,function(){
 'use strict';const STAGES=new Set(['TINT','HOIST','FITTING','FABRICATION','ELECTRICAL','TYRE']);let options;
 const e=value=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 const add=(date,offset)=>new Date(Date.parse(date+'T12:00:00Z')+offset*86400000).toISOString().slice(0,10);
 const format=(date,settings)=>new Intl.DateTimeFormat('en-AU',{timeZone:'UTC',...settings}).format(new Date(date+'T12:00:00Z'));
 const clock=value=>new Intl.DateTimeFormat('en-AU',{timeZone:'Australia/Perth',hour:'numeric',minute:'2-digit'}).format(new Date(value));
 const minute=value=>/^\d{2}:\d{2}$/.test(value||'')&&Number(value.slice(0,2))<24&&Number(value.slice(3))<60?Number(value.slice(0,2))*60+Number(value.slice(3)):NaN;
 function days(scope){if(scope.mode==='day')return [scope.date];const start=add(scope.date,-((new Date(scope.date+'T12:00:00Z').getUTCDay()+6)%7));return Array.from({length:7},(_,index)=>add(start,index));}
 function closedPeriods(date,calendar){const start=minute(calendar.day_start),end=minute(calendar.day_end);if(!Number.isFinite(start)||!Number.isFinite(end)||end<=start)return [];const weekday=new Date(date+'T12:00:00Z').getUTCDay()||7;if(!(calendar.working_week||[]).includes(weekday)||(calendar.closures||[]).includes(date))return [{start,end,label:(calendar.closures||[]).includes(date)?'Closed':'Non-working day'}];return (calendar.break_windows||[]).map(item=>({start:Math.max(start,minute(item.start)),end:Math.min(end,minute(item.end)),label:'Break'})).filter(item=>Number.isFinite(item.start)&&Number.isFinite(item.end)&&item.end>item.start);}
 function segmentsForDate(booking,date,calendar){const start=Date.parse(date+'T'+calendar.day_start+':00+08:00'),end=Date.parse(date+'T'+calendar.day_end+':00+08:00');if(!Array.isArray(booking.segments)||!Number.isFinite(start)||!Number.isFinite(end)||end<=start)return [];return booking.segments.map(segment=>({start:Date.parse(segment.start_at),end:Date.parse(segment.end_at)})).filter(segment=>Number.isFinite(segment.start)&&Number.isFinite(segment.end)&&segment.end>segment.start&&segment.start<end&&segment.end>start).map(segment=>({...segment,from:Math.max(start,segment.start),to:Math.min(end,segment.end),left:Math.max(0,(segment.start-start)/(end-start)*100),width:(Math.min(end,segment.end)-Math.max(start,segment.start))/(end-start)*100}));}
 function ruler(calendar){const start=minute(calendar.day_start),end=minute(calendar.day_end),labels=[];for(let tick=start;tick<=end;tick=tick===start?Math.ceil((start+1)/60)*60:tick+60)labels.push('<span class="hour-label" style="left:'+((tick-start)/(end-start)*100).toFixed(4)+'%">'+e(String(Math.floor(tick/60)).padStart(2,'0')+':'+String(tick%60).padStart(2,'0'))+'</span>');if(end%60!==0)labels.push('<span class="hour-label final-hour" style="left:100%">'+e(calendar.day_end)+'</span>');return '<div class="hour-ruler">'+labels.join('')+'</div>';}
 function markup(data,scope,context){
  if(!STAGES.has(scope.stage))return '<div class="empty-state">Choose a Karratha workshop station.</div>';
  const dateList=days(scope),calendar=(data.settings||[]).find(row=>row.key==='calendar')?.value||{},start=minute(calendar.day_start),end=minute(calendar.day_end);
  if(!Number.isFinite(start)||!Number.isFinite(end)||end<=start||!Array.isArray(calendar.working_week))return '<div class="empty-state">The Karratha working calendar could not be confirmed. Refresh before booking.</div>';
  const bays=(data.bays||[]).filter(bay=>bay.stage_code===scope.stage&&bay.active===true).sort((a,b)=>a.bay_number-b.bay_number),jobs=new Map((data.jobs||[]).filter(job=>job.selected===true).map(job=>[job.id,job])),vehicles=new Map((data.vehicles||[]).map(vehicle=>[vehicle.id,vehicle])),techs=new Map((data.technicians||[]).map(tech=>[tech.id,tech])),operations=new Map((data.operations||[]).map(operation=>[operation.id,operation]));
  const bookings=(data.bookings||[]).filter(booking=>booking.stage_code===scope.stage&&jobs.has(booking.job_id)),headers=scope.mode==='week'?dateList.map(date=>'<th scope="col">'+e(format(date,{weekday:'short',day:'numeric',month:'short'}))+'</th>').join(''):'<th scope="col">'+ruler(calendar)+'</th>',dateLabel=scope.mode==='week'?format(dateList[0],{day:'numeric',month:'short'})+' – '+format(dateList[6],{day:'numeric',month:'short',year:'numeric'}):format(scope.date,{weekday:'long',day:'numeric',month:'short',year:'numeric'});
  let rows='',visibleSegments=0;
  for(const bay of bays){let cells='';for(const date of dateList){const closed=closedPeriods(date,calendar),fullClosed=closed.some(item=>item.start===start&&item.end===end);let tiles='',index=0;
    for(const booking of bookings.filter(item=>item.bay_id===bay.id).sort((a,b)=>String(a.start_at).localeCompare(String(b.start_at)))){const vehicle=vehicles.get(booking.vehicle_id),job=jobs.get(booking.job_id),tech=techs.get(booking.technician_id),operation=operations.get(booking.operation_id);for(const segment of segmentsForDate(booking,date,calendar)){visibleSegments++;const title=[vehicle?.stock_number||job.job_card_number,'Job '+job.job_card_number,operation?.description,tech?.name,booking.status,clock(booking.start_at)+' – '+clock(booking.end_at),'This working period '+clock(segment.from)+' – '+clock(segment.to)].filter(Boolean).join(' · '),position=scope.mode==='week'?'top:'+(index++*64+8)+'px;':'left:'+segment.left.toFixed(4)+'%;width:'+Math.max(segment.width,1).toFixed(4)+'%;';tiles+='<button type="button" class="calendar-booking '+e(['planned','started','stopped','completed','cancelled'].includes(booking.status)?booking.status:'planned')+'" data-calendar-booking="'+e(booking.id)+'" style="'+position+'" title="'+e(title)+'" aria-label="'+e(title)+'"><strong>'+e(vehicle?.stock_number||job.job_card_number)+'</strong><small>'+e(clock(segment.from)+'–'+clock(segment.to))+' · '+e(booking.status)+'</small><small>'+e(tech?.name||'Technician not recorded')+'</small></button>';}}
    const shading=scope.mode==='week'?(fullClosed?'<div class="calendar-closed full-closed"><span>'+e(closed[0].label)+'</span></div>':'') : closed.map(item=>'<div class="calendar-closed" style="left:'+((item.start-start)/(end-start)*100).toFixed(4)+'%;width:'+((item.end-item.start)/(end-start)*100).toFixed(4)+'%" title="'+e(item.label)+'"><span>'+e(item.label)+'</span></div>').join('');
    const grid=scope.mode==='day'?Array.from({length:Math.max(0,Math.ceil(end/60)-Math.ceil(start/60))},(_,offset)=>Math.ceil(start/60)*60+offset*60).filter(tick=>tick>start&&tick<end).map(tick=>'<span class="calendar-gridline" style="left:'+((tick-start)/(end-start)*100).toFixed(4)+'%"></span>').join(''):'';
    const addButton=context.can_edit===true&&!fullClosed?'<button type="button" class="calendar-add" data-calendar-bay="'+e(bay.id)+'" data-calendar-date="'+e(date)+'" aria-label="Book '+e(bay.display_name)+' on '+e(date)+'">+ Book</button>':'';
    cells+='<td class="'+(scope.mode==='week'?'week-day ':'')+(fullClosed?'closed-day':'')+'"><div class="calendar-lane"'+(scope.mode==='week'?' style="height:'+Math.max(102,index*64+34)+'px"':'')+'>'+shading+grid+tiles+addButton+'</div></td>';}
   rows+='<tr><th scope="row" class="bay-label">'+e(bay.display_name||'Bay '+bay.bay_number)+'<small>'+e(techs.get(bay.default_technician_id)?.name||'No default technician')+'</small></th>'+cells+'</tr>';}
  return '<div class="calendar-toolbar"><div class="date-nav"><button type="button" data-calendar-shift="-1">‹ Previous</button><span class="calendar-date">'+e(dateLabel)+'</span><button type="button" data-calendar-shift="1">Next ›</button><button type="button" data-calendar-today>Today</button></div><div class="calendar-toggle"><button type="button" data-calendar-mode="day" aria-pressed="'+(scope.mode==='day')+'">Day</button><button type="button" data-calendar-mode="week" aria-pressed="'+(scope.mode==='week')+'">Week</button></div></div>'+(bays.length?'<div class="calendar-scroll" tabindex="0" aria-label="Karratha bay calendar"><table class="calendar-table"><thead><tr><th scope="col">Bay</th>'+headers+'</tr></thead><tbody>'+rows+'</tbody></table></div>':'<div class="empty-state"><h3>No active bays</h3><p>Ask a Karratha administrator to review this station.</p></div>')+'<div class="calendar-empty-note">'+(visibleSegments?'Showing confirmed working periods.':'No working periods booked for these dates.')+' · '+e(calendar.day_start)+'–'+e(calendar.day_end)+' · Perth time. Striped areas are closed.'+(bookings.some(booking=>!Array.isArray(booking.segments))?' Some booking periods could not be confirmed; refresh before scheduling.':'')+'</div>';
 }
 function init(settings){options=settings;options.container.addEventListener('click',event=>{const target=event.target.closest('button');if(!target)return;const scope=options.getScope();if(target.dataset.calendarBooking)options.onOpenBooking(target.dataset.calendarBooking);else if(target.dataset.calendarBay)options.onCreateBooking({bay_id:target.dataset.calendarBay,date:target.dataset.calendarDate});else if(target.dataset.calendarShift)options.onScopeChange({...scope,date:add(scope.date,Number(target.dataset.calendarShift)*(scope.mode==='week'?7:1))});else if(target.hasAttribute('data-calendar-today'))options.onScopeChange({...scope,date:options.today()});else if(target.dataset.calendarMode)options.onScopeChange({...scope,mode:target.dataset.calendarMode});});return api;}
 function render(){if(options)options.container.innerHTML=markup(options.getData(),options.getScope(),options.getContext()||{});}
 const api={init,render,clear(){if(options)options.container.replaceChildren();},markup,days,add,closedPeriods,segmentsForDate};return api;
});
