window.K135_API_MAP = Object.freeze({
  "centre": "135",
  "project_ref": "cdsmnqxtyyoeoznmbidd",
  "url": "https://cdsmnqxtyyoeoznmbidd.supabase.co",
  "context_rpc": "k135_get_native_engine_context",
  "ready": true,
  "rpc": {
    "add_salesperson": "k135_add_salesperson",
    "add_sublet_provider": "k135_add_sublet_provider",
    "add_technician": "k135_add_technician",
    "admin_approve_user": "k135_admin_approve_user",
    "admin_change_role": "k135_admin_change_role",
    "admin_disable_user": "k135_admin_disable_user",
    "admin_reject_registration": "k135_admin_reject_registration",
    "admin_restore_user": "k135_admin_restore_user",
    "administrator_move_workshop_booking": "k135_administrator_move_workshop_booking",
    "administrator_schedule_workshop_vehicle": "k135_administrator_schedule_workshop_vehicle",
    "apply_pdc_email_ai_typed_action_surface_20260901": "k135_apply_pdc_email_ai_typed_action_surface_20260901",
    "approve_pdc_new_vehicle_review": "k135_approve_pdc_new_vehicle_review",
    "approve_pdc_tune_operation_change_with_schedule": "k135_approve_pdc_tune_operation_change_with_schedule",
    "assign_booking_technician": "k135_assign_booking_technician",
    "assign_pdc_vehicle_salesperson_386": "k135_assign_pdc_vehicle_salesperson_386",
    "book_all_vehicle_stations": "k135_book_all_vehicle_stations",
    "book_rft_transport_412": "k135_book_rft_transport_412",
    "book_rft_transport_700": "k135_book_rft_transport_700",
    "book_rft_transport_734": "k135_book_rft_transport_734",
    "book_rft_transport_email_draft_739": "k135_book_rft_transport_email_draft_739",
    "cancel_workshop_booking": "k135_cancel_workshop_booking",
    "cascade_workshop_booking_move": "k135_cascade_workshop_booking_move",
    "cascade_workshop_schedule": "k135_cascade_workshop_schedule",
    "change_booking_bay": "k135_change_booking_bay",
    "clear_vehicle_stoppage_422": "k135_clear_vehicle_stoppage_422",
    "collect_rft_transport_412": "k135_collect_rft_transport_412",
    "collect_rft_transport_700": "k135_collect_rft_transport_700",
    "collect_rft_transport_734": "k135_collect_rft_transport_734",
    "complete_pdc_vehicle_department_772": "k135_complete_pdc_vehicle_department_772",
    "complete_workshop_work": "k135_complete_workshop_work",
    "create_pdc_acceptance_vehicle_375": "k135_create_pdc_acceptance_vehicle_375",
    "create_pdc_sublet_booking": "k135_create_pdc_sublet_booking",
    "create_pdc_sublet_operation_booking": "k135_create_pdc_sublet_operation_booking",
    "create_workshop_admin_block": "k135_create_workshop_admin_block",
    "decide_pdc_ai_intake_proposal": "k135_decide_pdc_ai_intake_proposal",
    "delete_pdc_authenticated_operation_line_772": "k135_delete_pdc_authenticated_operation_line_772",
    "delete_vehicle_workshop_line_adjustment": "k135_delete_vehicle_workshop_line_adjustment",
    "delete_workshop_admin_block": "k135_delete_workshop_admin_block",
    "edit_salesperson": "k135_edit_salesperson",
    "edit_sublet_provider": "k135_edit_sublet_provider",
    "edit_technician": "k135_edit_technician",
    "export_navision_backend_records": "k135_export_navision_backend_records",
    "finalize_pdc_qc_retest_to_rft_747": "k135_finalize_pdc_qc_retest_to_rft_747",
    "finalize_pdc_qc_to_rft_399": "k135_finalize_pdc_qc_to_rft_399",
    "finalize_pdc_qc_to_rft_700": "k135_finalize_pdc_qc_to_rft_700",
    "fitter_job_command": "k135_fitter_job_command",
    "get_fitter_job": "k135_get_fitter_job",
    "get_fitter_jobs": "k135_get_fitter_jobs",
    "get_fitter_refresh": "k135_get_fitter_refresh",
    "get_fitter_roster": "k135_get_fitter_roster",
    "get_navision_backend_snapshot": "k135_get_navision_backend_snapshot",
    "get_navision_reconciliation_report": "k135_get_navision_reconciliation_report",
    "get_navision_visible_snapshot": "k135_get_navision_visible_snapshot",
    "get_pdc_ai_intake_snapshot": "k135_get_pdc_ai_intake_snapshot",
    "get_pdc_auditor_review_queue": "k135_get_pdc_auditor_review_queue",
    "get_pdc_auditor_snapshot": "k135_get_pdc_auditor_snapshot",
    "get_pdc_bus_workflow": "k135_get_pdc_bus_workflow",
    "get_pdc_email_ai_successor_action_contract_20260901": "k135_get_pdc_email_ai_successor_action_contract_20260901",
    "get_pdc_email_ai_transaction_successor_inbox_v2": "k135_get_pdc_email_ai_transaction_successor_inbox_v2",
    "get_pdc_email_monitor_status": "k135_get_pdc_email_monitor_status",
    "get_pdc_email_vehicle_board_snapshot": "k135_get_pdc_email_vehicle_board_snapshot",
    "get_pdc_email_vehicle_location_snapshot": "k135_get_pdc_email_vehicle_location_snapshot",
    "get_pdc_review_counts": "k135_get_pdc_review_counts",
    "get_pdc_review_counts_by_department": "k135_get_pdc_review_counts_by_department",
    "get_pdc_sublet_audit_ledgers": "k135_get_pdc_sublet_audit_ledgers",
    "get_pdc_update_history": "k135_get_pdc_update_history",
    "get_pdc_usage_report_20260914": "k135_get_pdc_usage_report_20260914",
    "get_pdc_vehicle_planning_windows": "k135_get_pdc_vehicle_planning_windows",
    "get_pdc_vehicle_provenance_history": "k135_get_pdc_vehicle_provenance_history",
    "get_station_workshop_snapshot": "k135_get_station_workshop_snapshot",
    "get_vehicle_workshop_detail_scoped": "k135_get_vehicle_workshop_detail_scoped",
    "get_workshop_admin_block_audit_771_successor": "k135_get_workshop_admin_block_audit_771_successor",
    "get_workshop_booking_search_scoped": "k135_get_workshop_booking_search_scoped",
    "get_workshop_capacity_configuration": "k135_get_workshop_capacity_configuration",
    "get_workshop_configuration": "k135_get_workshop_configuration",
    "get_workshop_eligibility_snapshot": "k135_get_workshop_eligibility_snapshot",
    "get_workshop_hours_for_setup": "k135_get_workshop_hours_for_setup",
    "get_workshop_overview_revisions": "k135_get_workshop_overview_revisions",
    "get_workshop_snapshot": "k135_get_workshop_snapshot",
    "list_pdc_new_vehicle_reviews": "k135_list_pdc_new_vehicle_reviews",
    "list_pdc_new_vehicle_reviews_by_department": "k135_list_pdc_new_vehicle_reviews_by_department",
    "list_pdc_tune_operation_changes": "k135_list_pdc_tune_operation_changes",
    "list_pdc_tune_operation_changes_by_department": "k135_list_pdc_tune_operation_changes_by_department",
    "list_pdc_unidentified_tune_reviews": "k135_list_pdc_unidentified_tune_reviews",
    "list_pdc_unidentified_tune_reviews_by_department": "k135_list_pdc_unidentified_tune_reviews_by_department",
    "list_salespeople": "k135_list_salespeople",
    "list_sublet_providers": "k135_list_sublet_providers",
    "list_technicians": "k135_list_technicians",
    "list_workshop_bays": "k135_list_workshop_bays",
    "mark_pdc_parts_ordered_377": "k135_mark_pdc_parts_ordered_377",
    "mark_pdc_parts_received_authenticated_751": "k135_mark_pdc_parts_received_authenticated_751",
    "mark_vehicle_ready_for_qc": "k135_mark_vehicle_ready_for_qc",
    "move_vehicle_workshop_source_line_stage": "k135_move_vehicle_workshop_source_line_stage",
    "move_workshop_admin_block": "k135_move_workshop_admin_block",
    "move_workshop_booking": "k135_move_workshop_booking",
    "pdc_acceptance_lifecycle_375": "k135_pdc_acceptance_lifecycle_375",
    "pdc_admin_allow_vehicle_recreation_once": "k135_pdc_admin_allow_vehicle_recreation_once",
    "pdc_admin_archive_vehicle": "k135_pdc_admin_archive_vehicle",
    "pdc_admin_archived_vehicle_snapshot": "k135_pdc_admin_archived_vehicle_snapshot",
    "pdc_admin_reset_staging_test_vehicle": "k135_pdc_admin_reset_staging_test_vehicle",
    "pdc_admin_restore_vehicle": "k135_pdc_admin_restore_vehicle",
    "pdc_pilbara_service_apply_v1": "k135_pdc_pilbara_service_apply_v1",
    "pdc_pilbara_service_classification_apply_v2": "k135_pdc_pilbara_service_classification_apply_v2",
    "pdc_pilbara_service_classification_preview_v2": "k135_pdc_pilbara_service_classification_preview_v2",
    "pdc_pilbara_service_preview_v1": "k135_pdc_pilbara_service_preview_v1",
    "pdc_pilbara_service_reconcile_work_controls_v1": "k135_pdc_pilbara_service_reconcile_work_controls_v1",
    "pit_transfer_vehicle": "k135_pit_transfer_vehicle",
    "pmb_transfer_vehicle": "k135_pmb_transfer_vehicle",
    "prioritise_workshop_vehicle": "k135_prioritise_workshop_vehicle",
    "qc_complete_vehicle": "k135_qc_complete_vehicle",
    "qc_signoff_to_rft": "k135_qc_signoff_to_rft",
    "read_pdc_rft_transport_evidence_734": "k135_read_pdc_rft_transport_evidence_734",
    "read_rft_transport_booking_context_739": "k135_read_rft_transport_booking_context_739",
    "read_rft_transport_draft_739": "k135_read_rft_transport_draft_739",
    "record_pdc_auditor_decision": "k135_record_pdc_auditor_decision",
    "record_pdc_bus_helper_labour": "k135_record_pdc_bus_helper_labour",
    "record_pdc_login": "k135_record_pdc_login",
    "record_pdc_qc_photo_evidence_399": "k135_record_pdc_qc_photo_evidence_399",
    "record_pdc_qc_retest_photo_747": "k135_record_pdc_qc_retest_photo_747",
    "record_pdc_usage_20260914": "k135_record_pdc_usage_20260914",
    "reject_pdc_qc_vehicle_to_pmb_stoppage_767": "k135_reject_pdc_qc_vehicle_to_pmb_stoppage_767",
    "rename_workshop_admin_block_20260904": "k135_rename_workshop_admin_block_20260904",
    "replan_workshop_capacity": "k135_replan_workshop_capacity",
    "resize_workshop_admin_block": "k135_resize_workshop_admin_block",
    "resize_workshop_booking": "k135_resize_workshop_booking",
    "resolve_vehicle_lifecycle_identity": "k135_resolve_vehicle_lifecycle_identity",
    "restore_workshop_booking": "k135_restore_workshop_booking",
    "resume_workshop_work": "k135_resume_workshop_work",
    "retry_vehicle_notification": "k135_retry_vehicle_notification",
    "return_completed_work": "k135_return_completed_work",
    "return_pdc_sublet_booking": "k135_return_pdc_sublet_booking",
    "return_work_to_queue": "k135_return_work_to_queue",
    "rft_collect_vehicle": "k135_rft_collect_vehicle",
    "rft_transfer_vehicle": "k135_rft_transfer_vehicle",
    "save_pdc_bus_workflow": "k135_save_pdc_bus_workflow",
    "save_vehicle_workshop_line_hours_batch_768": "k135_save_vehicle_workshop_line_hours_batch_768",
    "schedule_vehicle_work": "k135_schedule_vehicle_work",
    "set_bay_default_technician": "k135_set_bay_default_technician",
    "set_pdc_bus_booking_team": "k135_set_pdc_bus_booking_team",
    "set_pdc_bus_supplier_status": "k135_set_pdc_bus_supplier_status",
    "set_pdc_parts_stoppage_376": "k135_set_pdc_parts_stoppage_376",
    "set_pdc_qc_operation_completion_379": "k135_set_pdc_qc_operation_completion_379",
    "set_pdc_vehicle_location_1500": "k135_set_pdc_vehicle_location_1500",
    "set_pdc_vehicle_location_override": "k135_set_pdc_vehicle_location_override",
    "set_pdc_vehicle_work_states": "k135_set_pdc_vehicle_work_states",
    "set_pmb_stoppage_422": "k135_set_pmb_stoppage_422",
    "set_rft_confirmation_736": "k135_set_rft_confirmation_736",
    "set_salesperson_active": "k135_set_salesperson_active",
    "set_sublet_provider_active": "k135_set_sublet_provider_active",
    "set_technician_active": "k135_set_technician_active",
    "set_workshop_bay_active": "k135_set_workshop_bay_active",
    "set_workshop_hours_0600_1630": "k135_set_workshop_hours_0600_1630",
    "set_workshop_stage_estimated_minutes_407": "k135_set_workshop_stage_estimated_minutes_407",
    "start_workshop_work": "k135_start_workshop_work",
    "stop_workshop_work": "k135_stop_workshop_work",
    "undo_administrator_workshop_booking_move": "k135_undo_administrator_workshop_booking_move",
    "undo_pdc_authenticated_operation_line_772": "k135_undo_pdc_authenticated_operation_line_772",
    "update_pdc_parts_eta": "k135_update_pdc_parts_eta",
    "update_pdc_sublet_booking": "k135_update_pdc_sublet_booking",
    "update_pdc_sublet_booking_field": "k135_update_pdc_sublet_booking_field",
    "update_pdc_sublet_booking_provider_399": "k135_update_pdc_sublet_booking_provider_399",
    "update_pdc_vehicle_detail_fields_388": "k135_update_pdc_vehicle_detail_fields_388",
    "update_pdc_vehicle_sales_preparation": "k135_update_pdc_vehicle_sales_preparation",
    "update_workshop_configuration": "k135_update_workshop_configuration",
    "upsert_vehicle_workshop_line_adjustment": "k135_upsert_vehicle_workshop_line_adjustment",
    "request_department_access_135": "k135_request_department_access_135"
  },
  "tables": {
    "backup_runs": "k135_backup_runs",
    "navision_backend_revision": "k135_navision_backend_revision",
    "pdc_ai_intake_revision": "k135_pdc_ai_intake_revision",
    "pdc_auditor_revision": "k135_pdc_auditor_revision",
    "pdc_email_ai_successor_ui_revision": "k135_pdc_email_ai_successor_ui_revision",
    "pdc_email_vehicle_revision": "k135_pdc_email_vehicle_revision",
    "pdc_user_roles": "k135_pdc_user_roles",
    "restore_test_runs": "k135_restore_test_runs",
    "salespeople": "k135_salespeople",
    "sublet_providers": "k135_sublet_providers",
    "vehicle_parts_updates": "k135_vehicle_parts_updates",
    "vehicle_work_items": "k135_vehicle_work_items",
    "vehicles": "k135_vehicles",
    "workshop_bays": "k135_workshop_bays",
    "workshop_revision": "k135_workshop_revision",
    "workshop_technicians": "k135_workshop_technicians",
    "workshop_station_revision": "k135_workshop_station_revision",
    "workshop_settings": "k135_workshop_settings"
  },
  "realtime": {
    "navision_backend_revision": {
      "schema": "karratha135_pdc",
      "table": "navision_backend_revision"
    },
    "pdc_ai_intake_revision": {
      "schema": "karratha135_pdc",
      "table": "pdc_ai_intake_revision"
    },
    "pdc_auditor_revision": {
      "schema": "karratha135_pdc",
      "table": "pdc_auditor_revision"
    },
    "pdc_email_ai_successor_ui_revision": {
      "schema": "karratha135_pdc",
      "table": "pdc_email_ai_successor_ui_revision"
    },
    "pdc_email_vehicle_revision": {
      "schema": "karratha135_pdc",
      "table": "pdc_email_vehicle_revision"
    },
    "pdc_user_roles": {
      "schema": "karratha135_pdc",
      "table": "pdc_user_roles"
    },
    "salespeople": {
      "schema": "karratha135_pdc",
      "table": "salespeople"
    },
    "sublet_providers": {
      "schema": "karratha135_pdc",
      "table": "sublet_providers"
    },
    "vehicle_lifecycle_resolver_revision": {
      "schema": "karratha135_pdc",
      "table": "vehicle_lifecycle_resolver_revision"
    },
    "workshop_bays": {
      "schema": "karratha135_pdc",
      "table": "workshop_bays"
    },
    "workshop_revision": {
      "schema": "karratha135_pdc",
      "table": "workshop_revision"
    },
    "workshop_settings": {
      "schema": "karratha135_pdc",
      "table": "workshop_settings"
    },
    "workshop_station_revision": {
      "schema": "karratha135_pdc",
      "table": "workshop_station_revision"
    },
    "workshop_technicians": {
      "schema": "karratha135_pdc",
      "table": "workshop_technicians"
    }
  },
  "buckets": {
    "pdc-qc-evidence-staging": "karratha135-qc-evidence-staging"
  },
  "engine_version": "pmb-native135-candidate-v1"
});
window.K135_RUNTIME_ASSETS = Object.freeze([
  "ai-auditor.css",
  "ai-board-advisor.js",
  "app.js",
  "arb-labor-catalog.js",
  "assets/brand-logo.svg",
  "assets/pmb-logo.png",
  "broome-navision-import.js",
  "canonical-entry.js",
  "control-board-overview.js",
  "data-staging-empty.js",
  "deployment-manifest.json",
  "desktop-operations.css",
  "email-board-data.js",
  "favicon.svg",
  "index.html",
  "navision-backend-service.js",
  "navision-vin.js",
  "pdc-ai-auditor-stage-a.js",
  "pdc-ai-intake-review.css",
  "pdc-ai-intake-review.js",
  "pdc-ai-intake-service.js",
  "pdc-auth-registration.js",
  "pdc-auth.js",
  "pdc-book-all-stations.js",
  "pdc-bus-workflow.css",
  "pdc-bus-workflow.js",
  "pdc-completed-history.css",
  "pdc-conversions.js",
  "pdc-department-filter.js",
  "pdc-email-ai-successor-inbox.css",
  "pdc-email-ai-successor-inbox.js",
  "pdc-email-ai-v2-actions.js",
  "pdc-email-vehicle-location-service.js",
  "pdc-emergency-priority.css",
  "pdc-emergency-priority.js",
  "pdc-estimated-hours.css",
  "pdc-estimated-hours.js",
  "pdc-fitters.css",
  "pdc-fitters.js",
  "pdc-location-override.js",
  "pdc-new-vehicles.css",
  "pdc-new-vehicles.js",
  "pdc-parts-confirmation.js",
  "pdc-planner-capacity.css",
  "pdc-planner-capacity.js",
  "pdc-planner-slim.css",
  "pdc-planner-slim.js",
  "pdc-professional-polish.css",
  "pdc-qc-mobile.css",
  "pdc-qc-mobile.js",
  "pdc-qc-rework.js",
  "pdc-review-stations.css",
  "pdc-review-stations.js",
  "pdc-rft-actions.css",
  "pdc-rft-actions.js",
  "pdc-service-locations.js",
  "pdc-stacked-jobcards.css",
  "pdc-stacked-jobcards.js",
  "pdc-staff-usage.css",
  "pdc-staff-usage.js",
  "pdc-sublet-intake.js",
  "pdc-supabase-config.staging.js",
  "pdc-update-history.css",
  "pdc-update-history.js",
  "pdc-vehicle-handover.js",
  "pdc-workshop-hours.js",
  "pdc-workshop-tile-cleanup.js",
  "pdc-workshop-usability.js",
  "sales/navision-orders.js",
  "scripts/stage2b_c4_browser_export.js",
  "site-switcher.css",
  "site-switcher.js",
  "staging-browser-assessment.js",
  "styles.css",
  "vehicle-lifecycle-actions.js",
  "vehicle-location-lifecycle.js",
  "vehicle-locations-refresh-ui.js",
  "vehicle-locations-refresh.js",
  "vehicle-modal-identity.js",
  "vehicle-requirements-guard.js",
  "vendor/pdfjs/LICENSE",
  "vendor/pdfjs/pdf.min.js",
  "vendor/pdfjs/pdf.worker.min.js",
  "vendor/qz/qz-tray.js",
  "vendor/supabase/supabase-2.110.5.js",
  "workshop-booking-timing.js",
  "workshop-data-service.js",
  "workshop-display-identity.js",
  "workshop-eligibility.js",
  "workshop-navigation.js",
  "workshop-planner.css",
  "workshop-planner.js",
  "workshop-realtime.js",
  "workshop-reference-data-service.js",
  "workshop-shared-actions.js",
  "pd135-api-map.js",
  "pd135-transport.js",
  "pd135-navigation.js",
  "pd135-nuvu-parser.js",
  "pd135-nuvu-intake.js",
  "pd135-nuvu-intake.css",
  "vendor/xlsx/xlsx.full.min.js",
  "vendor/xlsx/LICENSE"
]);
